USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_SEL_PREVENTIVOS_MIGRA]

/*=======================================================================================================
	Nombre:				Fecha:				Descripcion:
	Diego Bazalar		28.11.24			Realiza el select de los mantenimientos preventivos migrados.
	EXEC [USP_PREV_SEL_PREVENTIVOS_MIGRA] @IsId_Equipo=0,@IsNumSerie='', @IsNumProc='AMC Nº 0406M14891',@IsEmpresa='0',@IsPeriodoInicio=NULL,@IsPeriodoFinal=NULL,@IsNomEquipo = '', @IsMarca='', @IsModelo='',@IsNomEmpresa='',@IsDestino='',@IndCronograma = 'N',@NUMPAGINAS=-1,@PAGINA=1
=======================================================================================================*/

	@IsId_Equipo		BIGINT
	,@IsNumSerie		VARCHAR(100)
	,@IsNumProc			VARCHAR(15)
	,@IsEmpresa			NVARCHAR(20)
	,@IsPeriodoInicio	VARCHAR(7)
	,@IsPeriodoFinal	VARCHAR(7)
	,@IsNomEmpresa		VARCHAR(12)
	,@IsNomEquipo		VARCHAR(100)
	,@IsMarca			VARCHAR(60)
	,@IsDestino			VARCHAR(40)
	,@IsModelo			VARCHAR(60)
	,@IndCronograma		CHAR(1)
	,@NUMPAGINAS		INT
	,@PAGINA			INT

AS
BEGIN
SET NOCOUNT ON	
	
	IF OBJECT_ID('tempdb..#tmpSinCronograma') IS NOT NULL 
		DROP TABLE #tmpSinCronograma
	IF OBJECT_ID('tempdb..#tmpPreventivosMig') IS NOT NULL 
		DROP TABLE #tmpPreventivosMig
	IF OBJECT_ID('tempdb..#tmpPreventivos') IS NOT NULL 
		DROP TABLE #tmpPreventivos
	IF OBJECT_ID('tempdb..#tmpMantPrev') IS NOT NULL 
		DROP TABLE #tmpMantPrev


	DECLARE @INI INT,@FIN INT
	DECLARE @SQL NVARCHAR(MAX);


/******Obtener los mantenimientos según su estado********/
	CREATE TABLE #tmpMantPrev
	(
		ID_MANT BIGINT
		,TOTALPREVE INT
		,PENDIENTES INT
		,COMPLETADOS INT
	)

	;WITH CTE_1 As (
		SELECT
			COUNT(MANTDET.ID_MANT) TOTALPREVE
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT
		GROUP BY MANTDET.ID_MANT
		),
	CTE_2 AS (
		SELECT
			COUNT(MANTDET.ID_MANT) PENDIENTES
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND MANTDET.ESTADO != 'COM'
		GROUP BY MANTDET.ID_MANT
	),
	CTE_3 AS (																						----------------------------------
		SELECT
			COUNT(MANTDET.ID_MANT) COMPLETADOS
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT 
		WHERE MANTDET.ESTADO = 'COM'
		GROUP BY MANTDET.ID_MANT
	)
	INSERT INTO #tmpMantPrev(ID_MANT, TOTALPREVE, PENDIENTES, COMPLETADOS)
	SELECT
		MANT.ID_MANT
		,ISNULL(TOTALPREVE,0)  TOTALPREVE
		,ISNULL(PENDIENTES,0)  PENDIENTES
		,ISNULL(COMPLETADOS,0) COMPLETADOS
	FROM [dbo].[TBM_MANT_PREV] MANT
	LEFT JOIN CTE_1 cte1 ON cte1.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_2 cte2 ON cte2.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_3 cte3 ON cte3.ID_MANT = MANT.ID_MANT


/******Obtener los mantenimientos que aún no han generado cronograma   ********/
	SELECT 
		MANT.ID_MANT
	INTO #tmpSinCronograma
	FROM TBM_MANT_PREV MANT
	LEFT JOIN TBD_MANT_PREV MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT
	WHERE MANTDET.ID IS NULL

/******  Obtenemos la próxima fecha de mantenimiento   ********************************************************/
	SELECT
		ROW_NUMBER() OVER(ORDER BY MANT.ID_MANT) AS CONTADOR
		,MANT.ID_MANT
		,MANT.FECHAINSTALACION
		,ISNULL(CONVERT(VARCHAR(10),MIN(FECHAMANTENIMIENTO),102),'') PROXFECHAMANT
	INTO #tmpProxavencer
	FROM TBM_MANT_PREV MANT
	LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND ESTADO != 'COM'
	WHERE MANT.ID_MANT IS NOT NULL
	GROUP BY MANT.ID_MANT,FECHAINSTALACION
/***************************************************************************************************************/

	SELECT @INI= (@NUMPAGINAS*(@PAGINA-1)+1),@FIN=@NUMPAGINAS*@PAGINA

	CREATE TABLE #tmpPreventivosMig(
		MIG_ID			BIGINT
		,ID_EQUIPO		BIGINT	
		,NUMSERIE		VARCHAR(200)
		,NOMEQUIPO		VARCHAR(200)
		,MARCA			VARCHAR(60)
		,MODELO			VARCHAR(60)
		,NOMEMPRESA		VARCHAR(200)
		,TIPOPROCESO	VARCHAR(200)
		,FECHAINSTAL	DATETIME
		,TOTALPREV		INT
		,REALPREV		INT
		,PENDPREV		INT
		,NOM_DESTINO	VARCHAR(200)
		,RAZON_SOCIAL	NVARCHAR(200)
	)

	
	SET @SQL = '
				SELECT
					MIGRA.ID								AS MIG_ID
					,MIGRA.MIG_ID_EQUIPO					AS ID_EQUIPO
					,MIGRA.MIG_SERIE						AS NUMSERIE
					,ISNULL(MIGRA.MIG_DESC_EQUIPO,'''')		AS NOMEQUIPO
					,ISNULL(MIGRA.MIG_MARCA,'''')			AS MARCA
					,ISNULL(MIGRA.MIG_MODELO,'''')			AS MODELO
					,ISNULL(MIGRA.MIG_NOMEMPRESA,'''')		AS NOMEMPRESA
					,ISNULL(MIGRA.MIG_PROCESO,'''') 		AS TIPOPROCESO
					,MIGRA.MIG_FECHA_INSTAL					AS FECHAINSTAL
					,ISNULL(MIGRA.MIG_TOTAL_PREV,0)			AS TOTALPREV
					,ISNULL(MIGRA.MIG_EJEC_PREV,0)			AS REALPREV
					,ISNULL(MIGRA.MIG_PEND_PREV,0)			AS PENDPREV
					,ISNULL(MIG_NOM_DESTINO,'''')			AS NOM_DESTINO
					,DATOS.VALOR1							AS RAZON_SOCIAL
				FROM [dbo].[TBM_MIGRACION_PREV] MIGRA WITH(NOLOCK)
				LEFT JOIN [dbo].[TBD_DATOS_GENERALES] DATOS ON DATOS.DOMINIO = ''RAZSOCIAL'' AND DATOS.ESTADO = 1 AND DATOS.HABILITADO = 1 AND MIGRA.MIG_RAZON_SOCIAL = DATOS.PARAMETRO
				WHERE 1 = 1 
				'
	IF(@IsId_Equipo != 0)
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_ID_EQUIPO = '+CAST(@IsId_Equipo AS VARCHAR)
	END

	IF (@IsNumSerie != '')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_SERIE = '''+CAST(@IsNumSerie AS VARCHAR)+''' '
	END

	IF (@IsNumProc != '')
	BEGIN
		SET @SQL = @SQL + 'AND TRIM(REPLACE(MIGRA.MIG_PROCESO,'' '','''')) = '''+CAST(TRIM(REPLACE(@IsNumProc,' ','')) AS VARCHAR) +''' '
	END

	IF (@IsEmpresa != '0')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_RAZON_SOCIAL = '''+CAST(@IsEmpresa AS VARCHAR)  +''' '
	END

	IF(@IsNomEmpresa != '')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_NOMEMPRESA LIKE '''+'%'+''+CAST(@IsNomEmpresa AS VARCHAR)+''+'%' + ''' '
	END

	IF(@IsNomEquipo != '')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_DESC_EQUIPO LIKE '''+'%'+''+CAST(@IsNomEquipo AS VARCHAR)+''+'%' + ''' '
	END

	IF(@IsMarca != '')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_MARCA LIKE '''+'%'+''+CAST(@IsMarca AS VARCHAR)+''+'%' + ''' '
	END
		
	IF(@IsDestino != '')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_NOM_DESTINO LIKE '''+'%'+''+CAST(@IsDestino AS VARCHAR)+''+'%' + ''' '
	END

	IF(@IsModelo != '')
	BEGIN
		SET @SQL = @SQL + 'AND MIGRA.MIG_MODELO LIKE '''+'%'+''+CAST(@IsModelo AS VARCHAR)+''+'%' + ''' '
	END

	PRINT(@SQL)
	INSERT INTO #tmpPreventivosMig
	EXEC sp_executesql @SQL

/***Se determinar el ID_MANT de los migrados buscados**/
	
;WITH CTE_1 AS (
	SELECT
		ID_MANT
		,MIGRA.ID_EQUIPO
		,MIGRA.NUMSERIE
		,MIGRA.NOMEQUIPO
		,MIGRA.MARCA
		,MIGRA.MODELO
		,MIGRA.NOMEMPRESA
		,MIGRA.TIPOPROCESO
		,MIGRA.FECHAINSTAL
		,MIGRA.TOTALPREV
		,MIGRA.REALPREV
		,MIGRA.PENDPREV
		,MIGRA.NOM_DESTINO
		,MIGRA.RAZON_SOCIAL
	FROM #tmpPreventivosMig AS MIGRA
	LEFT JOIN [dbo].[TBM_MANT_PREV] AS MANT WITH(NOLOCK) ON MIGRA.ID_EQUIPO = MANT.MIG_ID_EQUIPO 
	WHERE MANT.MIGRADO = 'S' AND MIGRA.ID_EQUIPO IS NOT NULL
), 
	CTE_2 AS (
		SELECT
			MANT.ID_MANT
			,MIGRA.ID_EQUIPO
			,MIGRA.NUMSERIE
			,MIGRA.NOMEQUIPO
			,MIGRA.MARCA
			,MIGRA.MODELO
			,MIGRA.NOMEMPRESA
			,MIGRA.TIPOPROCESO
			,MIGRA.FECHAINSTAL
			,MIGRA.TOTALPREV
			,MIGRA.REALPREV
			,MIGRA.PENDPREV
			,MIGRA.NOM_DESTINO
			,MIGRA.RAZON_SOCIAL
		FROM #tmpPreventivosMig AS MIGRA
		LEFT JOIN [dbo].[TBM_MANT_PREV] AS MANT WITH(NOLOCK) ON MIGRA.NUMSERIE = MANT.SERIE
		LEFT JOIN CTE_1 AS CTE ON CTE.ID_MANT = MANT.ID_MANT
		WHERE CTE.ID_MANT IS NULL AND MANT.SERIE IS NOT NULL
	),
		CTE_3 AS (
			SELECT 
				*
			FROM CTE_1
			UNION
			SELECT
				*
			FROM CTE_2
		)
		SELECT 
			CTE.*
			,CASE WHEN SC.ID_MANT IS NULL
			THEN 'S'
			ELSE 'N' END  AS INDCRONOGRAMA
		INTO #tmpPreventivos
		FROM CTE_3 CTE
		LEFT JOIN #tmpSinCronograma AS SC ON SC.ID_MANT = CTE.ID_MANT
	
	SELECT 
		tmp.ID_MANT
		,ID_EQUIPO
		,ISNULL(NUMSERIE,'') NUMSERIE
		,NOMEQUIPO
		,MARCA
		,MODELO
		,NOMEMPRESA
		,TIPOPROCESO
		,CONVERT(VARCHAR(10),FECHAINSTAL,103) FECHAINSTAL
		,ISNULL(calc.TOTALPREVE,TOTALPREV) TOTALPREV
		,ISNULL(calc.COMPLETADOS,REALPREV) REALPREV
		,ISNULL(calc.PENDIENTES,PENDPREV) PENDPREV
		,NOM_DESTINO
		,RAZON_SOCIAL
		,INDCRONOGRAMA
		,PROXFECHAMANT
	INTO #tmpTotal
	FROM #tmpPreventivos tmp
	LEFT JOIN #tmpProxavencer prox ON prox.ID_MANT = tmp.ID_MANT
	LEFT JOIN #tmpMantPrev calc ON calc.ID_MANT = tmp.ID_MANT
	WHERE CAST(prox.PROXFECHAMANT AS VARCHAR(7)) BETWEEN IIF(@IsPeriodoInicio IS NULL,CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102),CONVERT(VARCHAR(7),@IsPeriodoInicio,102)) AND IIF(@IsPeriodoFinal IS NULL, CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102),CONVERT(VARCHAR(7),@IsPeriodoFinal,102))
	AND tmp.INDCRONOGRAMA = IIF(@IndCronograma IS NULL, tmp.INDCRONOGRAMA, @IndCronograma)



	DECLARE @TOTAL INT

	SELECT @TOTAL=COUNT(1) FROM #tmpTotal

	IF(@TOTAL > 500)
	BEGIN
		IF(@NUMPAGINAS > 0)
		BEGIN
			SELECT 
				ID_MANT
				,ID_EQUIPO
				,NUMSERIE
				,NOMEQUIPO
				,MARCA
				,MODELO
				,NOMEMPRESA
				,TIPOPROCESO
				,FECHAINSTAL
				,TOTALPREV
				,REALPREV
				,PENDPREV
				,NOM_DESTINO
				,RAZON_SOCIAL
				,CASE WHEN INDCRONOGRAMA = 'S'
				THEN 'SI'
				ELSE 'NO' END INDCRONOGRAMA
				,PROXFECHAMANT
			FROM #tmpTotal
			ORDER BY  ID_MANT 
			OFFSET @INI ROWS FETCH NEXT @NUMPAGINAS ROWS ONLY;
		END 
		ELSE 
		BEGIN
			SELECT 
				ID_MANT
				,ID_EQUIPO
				,NUMSERIE
				,NOMEQUIPO
				,MARCA
				,MODELO
				,NOMEMPRESA
				,TIPOPROCESO
				,FECHAINSTAL
				,TOTALPREV
				,REALPREV
				,PENDPREV
				,NOM_DESTINO
				,RAZON_SOCIAL
				,CASE WHEN INDCRONOGRAMA = 'S'
				THEN 'SI'
				ELSE 'NO' END INDCRONOGRAMA
				,PROXFECHAMANT		
			FROM #tmpTotal
			ORDER BY  ID_MANT
		END
	END
	ELSE
	BEGIN
		SELECT 
			ID_MANT
			,ID_EQUIPO
			,NUMSERIE
			,NOMEQUIPO
			,MARCA
			,MODELO
			,NOMEMPRESA
			,TIPOPROCESO
			,FECHAINSTAL
			,TOTALPREV
			,REALPREV
			,PENDPREV
			,NOM_DESTINO
			,RAZON_SOCIAL
			,CASE WHEN INDCRONOGRAMA = 'S'
			THEN 'SI'
			ELSE 'NO' END INDCRONOGRAMA
			,PROXFECHAMANT
		FROM #tmpTotal
		ORDER BY  ID_MANT 
	END
SET NOCOUNT OFF
END