USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_CONTACTOS_X_RUC]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		16.01.25		Realiza el select de contactos activos por numero de requerimiento
	[USP_SEL_CONTACTOS_X_RUC] '20100013747','K',''
  =======================================================================================================*/
	@IsRUC VARCHAR(12)
	,@IsNomContacto VARCHAR(150)
	,@IsEstablecimiento VARCHAR(100)
)
AS
BEGIN
SET NOCOUNT ON
	DECLARE @IsID_CLIENTE BIGINT 

	SELECT @IsID_CLIENTE = ID FROM [dbo].[TBM_CLIENTES] WHERE RUCEMPRESA = @IsRUC

	SELECT
		IDCONTACTO
		,ISNULL(DATOS.DESCRIPCION,'') DESCRIPCION
		,ISNULL(NUMDOCCONTACTO,'') NUMDOCCONTACTO
		,ISNULL([NOMBRE CONTACTO],'') AS [NOMBRE CONTACTO]
		,ISNULL(ESTABLECIMIENTO,'') AS ESTABLECIMIENTO
		,ISNULL(AREACONTACTO,'') AS AREA
		,ISNULL(TELEFONOCONTACTO,'') AS TELEFONOCONTACTO
		,ISNULL(TELEFONO2CONTACTO,'') AS TELEFONO2CONTACTO
		,ISNULL(CARGOCONTACTO,'') AS CARGOCONTACTO
		,ISNULL(CORREOCONTACTO,'') AS CORREOCONTACTO
		,ISNULL(ESTADOS.VALOR1,'') AS ESTADO
	INTO #contactos
	FROM [dbo].[TBM_CONTACTOS] CONTACTO
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS DATOS WITH(NOLOCK) ON DATOS.PARAMETRO = CONTACTO.TIPDOCCONTACTO AND DOMINIO = 'GENTDOC' AND DATOS.ESTADO = 1
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS ESTADOS WITH(NOLOCK) ON ESTADOS.COD_VALOR1 = CONTACTO.ESTADO AND ESTADOS.DOMINIO = 'ESTADOS' AND ESTADOS.ESTADO = 1
	WHERE CONTACTO.ESTADO = 1 AND CONTACTO.ID_CLIENTE = @IsID_CLIENTE

	SELECT 
		* 
	FROM #contactos
	WHERE [NOMBRE CONTACTO] LIKE IIF(@IsNomContacto != '','%'+@IsNomContacto+'%' ,'%%')
	AND [ESTABLECIMIENTO] LIKE IIF(@IsEstablecimiento != '', '%'+@IsEstablecimiento+'%','%%')


SET NOCOUNT OFF
END

