USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_SEL_MAIN_PREVENTIVOS_MIGRA]

/*=======================================================================================================
	Nombre:				Fecha:				Descripcion:
	Diego Bazalar		28.11.24		Realiza el select de los mantenimientod preventivos.
	EXEC [USP_PREV_SEL_MAIN_PREVENTIVOS_MIGRA] @IsNumMant = 7
=======================================================================================================*/
	@IsNumMant		BIGINT
AS
BEGIN
SET NOCOUNT ON	
			SELECT 
				ISNULL(MIGRA.MIG_NOMEMPRESA, '')  NOMEMPRESA
				,ISNULL(MIGRA.MIG_PROCESO, '') PROCESO
				,ISNULL(MIGRA.RUC_NUEVO,'') RUC
			FROM [dbo].[TBM_MANT_PREV] MANT WITH(NOLOCK)
			LEFT JOIN [dbo].[TBM_MIGRACION_PREV] MIGRA WITH(NOLOCK) ON MIGRA.MIG_ID_EQUIPO = MANT.MIG_ID_EQUIPO OR MIGRA.MIG_SERIE = MANT.SERIE
			WHERE MANT.ID_MANT = @IsNumMant

			SELECT
				CODEQUIPO_NUEVO  CODITEM
				,ISNULL(MIGRA.MIG_DESC_EQUIPO, '')	AS DESC_EQUIPO
				,ISNULL(MIGRA.MIG_MARCA, '')		AS MARCA
				,CONVERT(VARCHAR(10),MIGRA.MIG_FECHA_INSTAL,103)	AS FECHA_INSTAL
				,ISNULL(MIGRA.MIG_MODELO, '')		AS MODELO
				,ISNULL(MIGRA.MIG_SERIE, '')		AS SERIE
				,ISNULL(MIGRA.MIG_NOM_DESTINO, '')	AS DESTINO
				,MIGRA.MIG_TOTAL_PREV				AS TOTAL_PREV
				,MIGRA.MIG_PEND_PREV				AS PEND_PREV
				,MIGRA.MIG_EJEC_PREV				AS EJEC_PREV
				,CONVERT(VARCHAR(10),MIGRA.MIG_FECHA_FIN_GAR,103)			AS FECHA_FIN_GAR
				,MIGRA.CODGARANTIA_NUEVO			AS CODGARANTIA
				,MIGRA.MIG_CODPERIODO				AS CODPERIODO
				,MIGRA.MIG_OBS						AS OBSERVACION
				,DATEDIFF(DAY,GETDATE(), MIGRA.MIG_FECHA_FIN_GAR)	DIFDIAS
				,DATEDIFF(DAY, MIGRA.MIG_FECHA_INSTAL, GETDATE())	DIASTRANCURRIDOS
			FROM [dbo].[TBM_MANT_PREV] MANT WITH(NOLOCK)
			LEFT JOIN [dbo].[TBM_MIGRACION_PREV] MIGRA WITH(NOLOCK) ON MIGRA.MIG_ID_EQUIPO = MANT.MIG_ID_EQUIPO OR MIGRA.MIG_SERIE = MANT.SERIE
			WHERE MANT.ID_MANT = @IsNumMant

			SELECT
				MANTDET.ID
				,ID_WORKFLOW
				,FECHAMANTENIMIENTO
				,ESTADO					AS CODESTADO
				,ESTADO.NOM_ESTADO		AS ESTADO
			FROM [dbo].[TBD_MANT_PREV] MANTDET WITH(NOLOCK)
			LEFT JOIN [dbo].[TBM_MANT_PREV] MANT WITH(NOLOCK) ON MANT.ID_MANT = MANTDET.ID_MANT
			LEFT JOIN [dbo].[TBM_PROCESOESTADOS] ESTADO WITH(NOLOCK) ON ESTADO.COD_ESTADO = MANTDET.ESTADO AND ESTADO.ID_PROCESO = 6 
			WHERE MANTDET.ID_MANT = @IsNumMant

SET NOCOUNT OFF
END