USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_PREV_PROX_VENCER_MIG]
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		04.02.25		Selecciona los mantenimientos preventivos migrados que se deben ejecutar en el rango de fecha parametrizado
	EXEC [USP_SEL_PREV_PROX_VENCER_MIG]
=======================================================================================================*/

AS
BEGIN
SET NOCOUNT ON
	DECLARE @IsNumDias INT
	DECLARE @FecHoy DATETIME 
	DECLARE @FecFinal DATETIME
	DECLARE @SQL NVARCHAR(MAX)

	SET @IsNumDias = (SELECT TOP 1 CAST(VALOR1 AS INT) FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'DIASGAR') --Obtenemos el número de días. 

/************************************************************/
	IF OBJECT_ID('tempdb..#tmpDetalleParcial') IS NOT NULL
		DROP TABLE #tmpDetalleParcial
	IF OBJECT_ID('tempdb..#tmpDetalle') IS NOT NULL
		DROP TABLE #tmpDetalle
	IF OBJECT_ID('tempdb..#tmpParcial') IS NOT NULL 
		DROP TABLE #tmpParcial
	IF OBJECT_ID('tempdb..#tmpMantPrev') IS NOT NULL 
		DROP TABLE #tmpMantPrev
	IF OBJECT_ID('tempdb..#tmpPreventivosMig') IS NOT NULL 
		DROP TABLE #tmpPreventivosMig
	IF OBJECT_ID('tempdb..#tmpProxavencer') IS NOT NULL 
		DROP TABLE #tmpProxavencer

		
/************************************************************/

----Se Establece los rangos de Fecha------------------------------------------------------------------------------------------------------------------------------------------------
	SET @FecHoy = GETDATE()
	SET @FecFinal = DATEADD(DAY,@IsNumDias,@FecHoy)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	CREATE TABLE #tmpMantPrev
	(
		ID_MANT BIGINT
		,TOTALPREVE INT
		,PENDIENTES INT
		,COMPLETADOS INT
	)

	CREATE TABLE #tmpPreventivosMig(
		MIG_ID			BIGINT
		,ID_EQUIPO		BIGINT	
		,NUMSERIE		VARCHAR(200)
		,NOMEQUIPO		VARCHAR(200)
		,MARCA			VARCHAR(60)
		,MODELO			VARCHAR(60)
		,NOMEMPRESA		VARCHAR(200)
		,TIPOPROCESO	VARCHAR(200)
		,FECHAINSTAL	DATETIME
		,TOTALPREV		INT
		,REALPREV		INT
		,PENDPREV		INT
		,NOM_DESTINO	VARCHAR(200)
		,RAZON_SOCIAL	NVARCHAR(200)
	)


	;WITH CTE_1 As (
		SELECT
			COUNT(MANTDET.ID_MANT) TOTALPREVE
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT
		GROUP BY MANTDET.ID_MANT
		),
	CTE_2 AS (
		SELECT
			COUNT(MANTDET.ID_MANT) PENDIENTES
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND MANTDET.ESTADO != 'COM'
		GROUP BY MANTDET.ID_MANT
	),
	CTE_3 AS (																						----------------------------------
		SELECT
			COUNT(MANTDET.ID_MANT) COMPLETADOS
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT 
		WHERE MANTDET.ESTADO = 'COM'
		GROUP BY MANTDET.ID_MANT
	)
	INSERT INTO #tmpMantPrev(ID_MANT, TOTALPREVE, PENDIENTES, COMPLETADOS)
	SELECT
		MANT.ID_MANT
		,ISNULL(TOTALPREVE,0)  TOTALPREVE
		,ISNULL(PENDIENTES,0)  PENDIENTES
		,ISNULL(COMPLETADOS,0) COMPLETADOS
	FROM [dbo].[TBM_MANT_PREV] MANT
	LEFT JOIN CTE_1 cte1 ON cte1.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_2 cte2 ON cte2.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_3 cte3 ON cte3.ID_MANT = MANT.ID_MANT

	SELECT
		ROW_NUMBER() OVER(ORDER BY MANT.ID_MANT) AS CONTADOR
		,MANT.ID_MANT
		,MANT.FECHAINSTALACION
		,MIN(FECHAMANTENIMIENTO) PROXFECHAMANT
	INTO #tmpProxavencer
	FROM TBM_MANT_PREV MANT
	LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND ESTADO != 'COM'
	WHERE MANT.ID_MANT IS NOT NULL
	GROUP BY MANT.ID_MANT,FECHAINSTALACION

	

	SET @SQL = '
				SELECT
					MIGRA.ID								AS MIG_ID
					,MIGRA.MIG_ID_EQUIPO					AS ID_EQUIPO
					,MIGRA.MIG_SERIE						AS NUMSERIE
					,ISNULL(MIGRA.MIG_DESC_EQUIPO,'''')		AS NOMEQUIPO
					,ISNULL(MIGRA.MIG_MARCA,'''')			AS MARCA
					,ISNULL(MIGRA.MIG_MODELO,'''')			AS MODELO
					,ISNULL(MIGRA.MIG_NOMEMPRESA,'''')		AS NOMEMPRESA
					,ISNULL(MIGRA.MIG_PROCESO,'''') 		AS TIPOPROCESO
					,MIGRA.MIG_FECHA_INSTAL					AS FECHAINSTAL
					,ISNULL(MIGRA.MIG_TOTAL_PREV,0)			AS TOTALPREV
					,ISNULL(MIGRA.MIG_EJEC_PREV,0)			AS REALPREV
					,ISNULL(MIGRA.MIG_PEND_PREV,0)			AS PENDPREV
					,ISNULL(MIG_NOM_DESTINO,'''')			AS NOM_DESTINO
					,DATOS.VALOR1							AS RAZON_SOCIAL
				FROM [dbo].[TBM_MIGRACION_PREV] MIGRA WITH(NOLOCK)
				LEFT JOIN [dbo].[TBD_DATOS_GENERALES] DATOS ON DATOS.DOMINIO = ''RAZSOCIAL'' AND DATOS.ESTADO = 1 AND DATOS.HABILITADO = 1 AND MIGRA.MIG_RAZON_SOCIAL = DATOS.PARAMETRO
				WHERE 1 = 1 
				'

	INSERT INTO #tmpPreventivosMig
	EXEC sp_executesql @SQL


	;WITH CTE_1 AS (
	SELECT
		MANT.ID_MANT
			,MIGRA.ID_EQUIPO
			,MIGRA.NUMSERIE
			,MIGRA.NOMEQUIPO
			,MIGRA.TIPOPROCESO
			,MIGRA.FECHAINSTAL
			,MIGRA.TOTALPREV
			,MIGRA.REALPREV
			,MIGRA.PENDPREV
			,MIGRA.NOM_DESTINO
	FROM #tmpPreventivosMig AS MIGRA
	LEFT JOIN [dbo].[TBM_MANT_PREV] AS MANT WITH(NOLOCK) ON MIGRA.ID_EQUIPO = MANT.MIG_ID_EQUIPO 
	WHERE MANT.MIGRADO = 'S' AND MIGRA.ID_EQUIPO IS NOT NULL
	), 
	CTE_2 AS (
		SELECT
			MANT.ID_MANT
			,MIGRA.ID_EQUIPO
			,MIGRA.NUMSERIE
			,MIGRA.NOMEQUIPO
			,MIGRA.TIPOPROCESO
			,MIGRA.FECHAINSTAL
			,MIGRA.TOTALPREV
			,MIGRA.REALPREV
			,MIGRA.PENDPREV
			,MIGRA.NOM_DESTINO
		FROM #tmpPreventivosMig AS MIGRA
		LEFT JOIN [dbo].[TBM_MANT_PREV] AS MANT WITH(NOLOCK) ON MIGRA.NUMSERIE = MANT.SERIE
		LEFT JOIN CTE_1 AS CTE ON CTE.ID_MANT = MANT.ID_MANT
		WHERE CTE.ID_MANT IS NULL AND MANT.SERIE IS NOT NULL
	),CTE_3 AS (
			SELECT 
				*
			FROM CTE_1
			UNION
			SELECT
				*
			FROM CTE_2
		)
		SELECT
			MANT.ID_MANT
			,ISNULL(NUMSERIE,'')									AS SERIE
			,ISNULL(NOMEQUIPO,'')									AS DESCRIPCION
			,ISNULL(CONVERT(VARCHAR(10),FECHAINSTAL,103),'')		AS FECHAINSTALACION
			,ISNULL(CONVERT(VARCHAR(10),prox.PROXFECHAMANT,103),'') PROXFECHAMANT
			,ISNULL(calc.TOTALPREVE,TOTALPREV)						AS TOTALPREVE
			,ISNULL(calc.COMPLETADOS,REALPREV)						AS COMPLETADOS
			,ISNULL(calc.PENDIENTES,PENDPREV)						AS PENDIENTES
			,NOM_DESTINO											AS UBIGEODEST
		FROM CTE_3 AS MANT WITH(NOLOCK)
		LEFT JOIN #tmpMantPrev calc ON calc.ID_MANT = MANT.ID_MANT
		LEFT JOIN #tmpProxavencer prox ON prox.ID_MANT = MANT.ID_MANT
		WHERE prox.PROXFECHAMANT BETWEEN @FecHoy AND @FecFinal
		ORDER BY MANT.ID_MANT ASC


SET NOCOUNT OFF
END