USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_FILTRAR_COSTEOMULTIPLE
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:		
	José A. Peralta		09.02.25		Carga de combos múltiples de costeo y detalle de costeo por id cotizacion detalle
	EXEC USP_FILTRAR_COSTEOMULTIPLE 38
  ==================================================================================================*/
@IDCOTIZACIONDETALLE BIGINT
AS
BEGIN
	SET NOCOUNT ON;

	--TIPO DE GARANTIA ADICIONAL
	SELECT PARAMETRO AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='GARANTIAS' AND ESTADO=1 AND HABILITADO=1 AND PARAMETRO NOT IN('GARN0001')

    --CICLO DE COSTOS
	SELECT PARAMETRO AS CODIGO, 
					  ISNULL(DESCRIPCION,'') DESCRIPCION 
					  FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					  WHERE DOMINIO='COSTOXCD' AND ESTADO=1 AND HABILITADO=1
					  ORDER BY 2

	--TIPO DE CICLO PREVENTIVOS:
	SELECT PARAMETRO AS CODIGO, 
					  ISNULL(DESCRIPCION,'') DESCRIPCION 
					  FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					  WHERE DOMINIO='CICLOPREV' AND ESTADO=1 AND HABILITADO=1

	--DETALLE DE COTIZACION:

	SELECT A.ID_COTIZACION,A.TIPOITEM,
	RTRIM(A.CODITEM) CODITEM,
	RTRIM(A.DESCRIPCION) DESCRIPCION,
	ISNULL(A.UNDMED,'') UNDMED,
	A.CANTIDAD,
	ISNULL(A.INDSTOCK,'N') INDSTOCK,
	ISNULL(B.INDCOMPRALOCAL,'N') INDCOMPRALOCAL,
	ISNULL(B.DIMENSIONES,'') DIMENSIONES,
	ISNULL(A.DESCRIPADIC,'') DESCRIPADIC,
	ISNULL(B.OBSCLIENTE,'') OBSCLIENTE,
	ISNULL(B.OBSDESPACHO,'') OBSDESPACHO,
	ISNULL(B.INDREQPLACA,'N') INDREQPLACA,
	ISNULL(A.COSTOFOB,'') EXWORK,
	ISNULL(A.PORCGANANCIA,0.00) MARGENADICIONAL,
	ISNULL(A.VVENTAUNI,0.00) VVENTAUNI,
	ISNULL(B.CODGARANADIC,'') CODGARANADIC,
	RTRIM(ISNULL(D.VALOR1,'')) DESCRIPCIONMONEDA,
	ISNULL(A.MARGENUTILIDAD,'') MARGENUTILIDAD,
	ISNULL(A.CODTRANSPORTE,'') CODTRANSPORTE,
	ISNULL(E.VALOR1,'') NOMTRANSPORTE,
	ISNULL(C.INDCOSTEADO,'') INDCOSTEADO,
	ISNULL(C.INDVALORIZADO,'') INDVALORIZADO 
	FROM TBD_COTIZACIONVENTA A WITH(NOLOCK) 
	INNER JOIN TBM_COTDET_DESPACHO B WITH(NOLOCK) ON A.ID=B.ID_COTDETALLE
	INNER JOIN TBM_COTIZACIONVENTA C WITH(NOLOCK) ON A.ID_COTIZACION=C.ID_COTIZACION
	LEFT JOIN TBD_DATOS_GENERALES D WITH(NOLOCK) ON D.DOMINIO='TIPMONEDA' AND  C.MONEDA=D.COD_VALOR1
		LEFT JOIN TBD_DATOS_GENERALES E WITH(NOLOCK) ON E.DOMINIO='TIPTRAN'  AND A.CODTRANSPORTE=E.COD_VALOR1
	WHERE A.ID=@IDCOTIZACIONDETALLE AND ISNULL(A.ELIMINADO,'N') != 'S'

	--LISTA DE COSTOS DE COTIZACION:

	SELECT A.ID,A.CODCOSTO,
	ISNULL(C.DESCRIPCION,'') DESCOSTO,
	A.CANTCOSTO,
	 CONVERT(VARCHAR,CAST(ISNULL(A.MONTOUNICOSTO ,0) AS MONEY) ,1) MONTOUNICOSTO,
	  CONVERT(VARCHAR,CAST(ISNULL(A.MONTOTOTCOSTO ,0) AS MONEY) ,1) MONTOTOTCOSTO,
	ISNULL(A.CODUBIGEODEST,'') CODUBIGEO ,
	CASE WHEN LEN(ISNULL(A.CODUBIGEODEST,''))>0 THEN 
		RTRIM(ISNULL(B.NOMDEPARTAMENTO,''))+'/'+RTRIM(ISNULL(B.NOMPROVINCIA,''))+'/'+RTRIM(ISNULL(B.NOMDISTRITO,''))
		ELSE '' END DESUBIGEO
	FROM TBD_COTIZACIONCOSTOS A WITH(NOLOCK)
	LEFT JOIN TBM_UBIGEO B WITH(NOLOCK) ON A. CODUBIGEODEST=B.CODUBIGEO
	LEFT JOIN TBD_DATOS_GENERALES C WITH(NOLOCK) ON ISNULL(A.CODCOSTO,'')=ISNULL(C.PARAMETRO,'') AND  C.DOMINIO='COSTOXCD' 
	WHERE A.ID_COTDETALLE=@IDCOTIZACIONDETALLE AND A.ELIMINADO = 0
	ORDER BY 3,8






	SET NOCOUNT OFF;
END





































