USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_COSTEOITEM
/*-----------------------------------------------------------------------------------------------------------------------------------------------------
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Jose A. Peralta		09.02.25		Mantenimiento de costeo item.
  ------------------------------------------------------------------------------------------------------------------------------------------------------*/
 @TIPO VARCHAR(1),
 @IDCOTDETALLE BIGINT,
 @CODCOSTO VARCHAR(8),
 @CANTCOSTO INT,
 @CANTPREVENTIVO INT,
 @CODCICLOPREVENTIVO VARCHAR(20),
 @CODUBIGEO VARCHAR(6),
 @DIRECCION VARCHAR(150),
 @AMBIENTEDESTINO VARCHAR(200),
 @NROPISO INT,
 @MONTOUNITARIO DECIMAL(18,9),
 @IDCOSTO BIGINT,
 @USRREG VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @NUMSEC INT
	DECLARE @CODIGO BIGINT,@MSG VARCHAR(250),@CODCOTCOSTO BIGINT,@CODCOSTOITEM VARCHAR(10)
	DECLARE @INDINFO CHAR(1),@SQL VARCHAR(MAX),@MONTOTOTAL DECIMAL(18,9)

		DECLARE @NUM INT
		DECLARE @INDINFOVIDEO CHAR(1)
		DECLARE @INDINFOMANUAL CHAR(1)
		DECLARE @INDINSTALACION CHAR(1)
		DECLARE @INDCAPACITACION CHAR(1)
		DECLARE @INDGARANADIC CHAR(1)
		DECLARE @INDMANTPREVENT CHAR(1)
		DECLARE @INDCALIB CHAR(1)
		DECLARE @INDFLETE CHAR(1)
		DECLARE @INDCOSTEADO CHAR(1)
		DECLARE @TOTALCANTCOSTO INT
		DECLARE @IDCOTIZACION INT
		DECLARE @CANTCOTIZADO INT
		DECLARE @FLAG_LLAVEMANO INT
		DECLARE @FLAG_MANUALES INT
		DECLARE @FLAG_VIDEOS INT
		DECLARE @FLAG_INSTALACION INT
		DECLARE @FLAG_CAPACITACION INT
		DECLARE @FLAG_GARANTADIC INT
		DECLARE @FLAG_MANTPREV INT
		DECLARE @FLAG_CALIB INT
		DECLARE @FLAG_FLETE INT

	SELECT @NUMSEC = COUNT(1)+1 FROM TBD_COTIZACIONCOSTOS WHERE ID_COTDETALLE=@IDCOTDETALLE

	SELECT @CODIGO=0,@MSG='No se pudo realizar ninguna accion'

	IF(@TIPO = 'I')
	BEGIN


			SET @MONTOTOTAL = @CANTCOSTO*@MONTOUNITARIO

		
		INSERT INTO TBD_COTIZACIONCOSTOS(ID_COTDETALLE,NUMSEC,CODCOSTO,CANTCOSTO,CANTPREVENTIVO,CODCICLOPREVENT,CODUBIGEODEST,DIRECCION,AMBIENTEDEST,NROPISO,MONTOUNICOSTO,MONTOTOTCOSTO,USR_REG,FEC_REG,ELIMINADO)
			VALUES(@IDCOTDETALLE,@NUMSEC,@CODCOSTO,@CANTCOSTO,@CANTPREVENTIVO,@CODCICLOPREVENTIVO,@CODUBIGEO,@DIRECCION,@AMBIENTEDESTINO,@NROPISO,@MONTOUNITARIO,@MONTOTOTAL,@USRREG,GETDATE(),0)

			SET @CODCOTCOSTO = @@IDENTITY;

		UPDATE TBM_COTDET_DESPACHO
			SET INDINFOVIDEO = CASE WHEN @CODCOSTO='CXCD0005' THEN 'S' ELSE 'N' END,
					INDINFOMANUAL = CASE WHEN @CODCOSTO='CXCD0004' THEN 'S' ELSE 'N' END,
					INDINSTALACION = CASE WHEN @CODCOSTO='CXCD0002' THEN 'S' ELSE 'N' END,
					INDCAPACITACION = CASE WHEN @CODCOSTO='CXCD0003' THEN 'S' ELSE 'N' END,
					INDMANTPREVENT = CASE WHEN @CODCOSTO='CXCD0006' THEN 'S' ELSE 'N' END,
					INDCALIB =  CASE WHEN @CODCOSTO='CXCD0007' THEN 'S' ELSE 'N' END,
					INDFLETE =  CASE WHEN @CODCOSTO='CXCD0008' THEN 'S' ELSE 'N' END,
					USR_MOD= @USRREG,
					FEC_MOD = GETDATE()
				--	INDREQPLACA= CASE WHEN @CODCOSTO='CXCD0007' THEN 'S' ELSE 'N' END,
			WHERE ID_COTDETALLE=@IDCOTDETALLE

			SET  @CODIGO = @CODCOTCOSTO
		    SET @MSG ='Se realizó el registro de costeo con éxito'

	END
	IF(@TIPO = 'U')
	BEGIN
		SET @MONTOTOTAL = @CANTCOSTO*@MONTOUNITARIO

				UPDATE TBD_COTIZACIONCOSTOS
				SET CANTCOSTO = @CANTCOSTO,
						CANTPREVENTIVO = @CANTPREVENTIVO,
						CODCICLOPREVENT = @CODCICLOPREVENTIVO,
						CODUBIGEODEST=@CODUBIGEO,
						DIRECCION=@DIRECCION,
						AMBIENTEDEST = @AMBIENTEDESTINO,
						NROPISO = @NROPISO,
						MONTOUNICOSTO  =  @MONTOUNITARIO ,
						MONTOTOTCOSTO = @MONTOTOTAL,
						USR_MOD = @USRREG,
						FEC_MOD = GETDATE()
				WHERE ID_COTDETALLE=@IDCOTDETALLE AND ID=@IDCOSTO;



		  --------------------------------------------------------


		  -- 0: Sin Costear
		-- 1: Costeo Parcial
		-- 2: Costeo Completo
		SET @FLAG_LLAVEMANO = 0;
		SET @FLAG_INSTALACION = 0;
		SET @FLAG_CAPACITACION = 0;
		SET @FLAG_MANUALES = 0;
		SET @FLAG_VIDEOS = 0;
		SET @FLAG_MANTPREV = 0;
		SET @FLAG_GARANTADIC = 0;
		SET @FLAG_CALIB = 0;
		SET @FLAG_FLETE = 0;

		SELECT TOP 1 @IDCOTIZACION = C.ID_COTIZACION, @CANTCOTIZADO = ISNULL(CD.CANTIDAD,0) 
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTIZACIONVENTA] C ON CD.ID_COTIZACION = C.ID_COTIZACION
		WHERE CD.ID = @IDCOTDETALLE;

		SELECT TOP 1 @INDINFOVIDEO = CDD.INDINFOVIDEO, @INDINFOMANUAL = CDD.INDINFOMANUAL,
		@INDINSTALACION = CDD.INDINSTALACION, @INDCAPACITACION = CDD.INDCAPACITACION, @INDGARANADIC = CDD.INDGARANADIC,
		@INDMANTPREVENT = CDD.INDMANTPREVENT, @INDCALIB = CDD.INDCALIB
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTDET_DESPACHO] CDD ON CD.ID = CDD.ID_COTDETALLE
		WHERE CD.ID = @IDCOTDETALLE;

		--
		-- LLAVE EN MANO
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0001' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_LLAVEMANO = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_LLAVEMANO = 1;
			END
		END
		
		--
		-- INSTALACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0002' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_INSTALACION = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_INSTALACION = 1;
			END
		END
		
		--
		-- CAPACITACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0003' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_CAPACITACION = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_CAPACITACION = 1;
			END
		END
		
		--
		-- MANUALES
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0004' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_MANUALES = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_MANUALES = 1;
			END
		END
		
		--
		-- VIDEOS
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0005' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_VIDEOS = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_VIDEOS = 1;
			END
		END
		
		--
		-- MANTENIMIENTO PREVENTIVO
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0006' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_MANTPREV = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_MANTPREV = 1;
			END
		END
		
		--
		-- GARANTIA ADICIONAL
		--
		--SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		--WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0007' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		--IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
		--	SET @FLAG_GARANTADIC = 2;
		--END
		--ELSE BEGIN
		--	IF @TOTALCANTCOSTO > 0 BEGIN
		--		SET @FLAG_GARANTADIC = 1;
		--	END
		--END
		
		--
		-- CALIBRACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0007' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_CALIB = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_CALIB = 1;
			END
		END
		
		--
		-- FLETE
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0008' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_FLETE = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_FLETE = 1;
			END
		END

		SET @INDCOSTEADO = 'S';

		--
		-- VALIDA que los INDICADORES tengan sus registros de COSTOS respectivos
		--
		IF @INDINFOVIDEO IS NOT NULL BEGIN
			IF ISNULL(@INDINFOVIDEO,'') = 'S' AND ISNULL(@FLAG_VIDEOS,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDINFOMANUAL IS NOT NULL BEGIN
			IF ISNULL(@INDINFOMANUAL,'') = 'S' AND ISNULL(@FLAG_MANUALES,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDINSTALACION IS NOT NULL BEGIN
			IF ISNULL(@INDINSTALACION,'') = 'S' AND ISNULL(@FLAG_INSTALACION,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDCAPACITACION IS NOT NULL BEGIN
			IF ISNULL(@INDCAPACITACION,'') = 'S' AND ISNULL(@FLAG_CAPACITACION,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		--IF @INDGARANADIC IS NOT NULL BEGIN
		--	IF ISNULL(@INDGARANADIC,'') = 'S' AND ISNULL(@FLAG_GARANTADIC,0) = 0 BEGIN
		--		SET @INDCOSTEADO = 'N'
		--	END
		--END

		IF @INDMANTPREVENT IS NOT NULL BEGIN
			IF ISNULL(@INDMANTPREVENT,'') = 'S' AND ISNULL(@FLAG_MANTPREV,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDCALIB IS NOT NULL BEGIN
			IF ISNULL(@INDCALIB,'') = 'S' AND ISNULL(@FLAG_CALIB,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END
		
		IF @INDFLETE IS NOT NULL BEGIN
			IF ISNULL(@INDFLETE,'') = 'S' AND ISNULL(@FLAG_FLETE,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END
		
		--
		-- VALIDA que los registros de costos hayan sido VALORIZADOS con sus montos respectivos
		--
		IF @INDCOSTEADO = 'S' BEGIN
			SELECT @NUM = COUNT(1) FROM TBD_COTIZACIONCOSTOS TX WHERE TX.ID_COTDETALLE IN (SELECT T1.ID FROM TBD_COTIZACIONVENTA T1 WHERE T1.ID_COTIZACION = @IDCOTIZACION) 
			AND (ISNULL(MONTOUNICOSTO,0) <= 0 AND ISNULL(MONTOTOTCOSTO,0) <= 0);
			IF @NUM > 0 BEGIN
				SET @INDCOSTEADO = 'N';
			END
		END

		UPDATE TBM_COTIZACIONVENTA SET INDCOSTEADO = @INDCOSTEADO WHERE ID_COTIZACION = @IDCOTIZACION;
		
		EXEC USP_UPD_TOTALIZAR_COTDET @IDCOTDETALLE

	


			SET  @CODIGO = 1
		    SET @MSG ='Se realizó la actualización de costeo con éxito'

	END
	IF(@TIPO= 'D')
	BEGIN


			UPDATE TBD_COTIZACIONCOSTOS
				SET ELIMINADO=1,
						USR_MOD = @USRREG,
						FEC_MOD=GETDATE()
				WHERE ID_COTDETALLE=@IDCOTDETALLE AND ID=@IDCOSTO

				SELECT @CODCOSTOITEM=CODCOSTO 
				FROM TBD_COTIZACIONCOSTOS WITH(NOLOCK) 
				WHERE  ID_COTDETALLE=@IDCOTDETALLE AND ID=@IDCOSTO;

				SELECT @INDINFO='N'


				IF EXISTS(SELECT 1 FROM TBD_COTIZACIONCOSTOS WITH(NOLOCK) 
				WHERE ID_COTDETALLE=@IDCOTDETALLE AND CODCOSTO=@CODCOSTOITEM
				 AND ELIMINADO=0)
				 BEGIN

						SET @INDINFO = 'S'

				 END

				 SET @SQL='UPDATE TBM_COTDET_DESPACHO SET '
				 IF(@CODCOSTOITEM = 'CXCD0005')
						BEGIN
								SET @SQL=@SQL+'INDINFOVIDEO='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0004')
						BEGIN
								SET @SQL=@SQL+'INDINFOMANUAL='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0002')
						BEGIN
								SET @SQL=@SQL+'INDINSTALACION='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0003')
						BEGIN
								SET @SQL=@SQL+'INDCAPACITACION='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0006')
						BEGIN
								SET @SQL=@SQL+'INDMANTPREVENT='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0007')
						BEGIN
								SET @SQL=@SQL+'INDCALIB='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0008')
						BEGIN
								SET @SQL=@SQL+'INDFLETE='''+@INDINFO+''''
						END
			    SET @SQL=@SQL+' WHERE ID_COTDETALLE='+CAST(@IDCOTDETALLE AS VARCHAR)

			EXEC(@SQL)


			SET  @CODIGO = 1
		    SET @MSG ='Se realizó la eliminación de costeo con éxito'

	END

	IF(@TIPO = 'X')
	BEGIN


			UPDATE TBD_COTIZACIONVENTA
				SET INDSTOCK = RTRIM(@CODUBIGEO),
				CANTIDAD=@CANTCOSTO,
				VVENTAUNI = @MONTOUNITARIO,
				USR_MOD=@USRREG,
				FEC_MOD=GETDATE()
				WHERE ID=@IDCOTDETALLE


		 UPDATE TBM_COTDET_DESPACHO
		 SET INDCOMPRALOCAL = RTRIM(@CODCICLOPREVENTIVO),
				USR_MOD=@USRREG,
				FEC_MOD=GETDATE()
				WHERE ID_COTDETALLE=@IDCOTDETALLE
				

	
		  -- 0: Sin Costear
		-- 1: Costeo Parcial
		-- 2: Costeo Completo
		SET @FLAG_LLAVEMANO = 0;
		SET @FLAG_INSTALACION = 0;
		SET @FLAG_CAPACITACION = 0;
		SET @FLAG_MANUALES = 0;
		SET @FLAG_VIDEOS = 0;
		SET @FLAG_MANTPREV = 0;
		SET @FLAG_GARANTADIC = 0;
		SET @FLAG_CALIB = 0;
		SET @FLAG_FLETE = 0;

		SELECT TOP 1 @IDCOTIZACION = C.ID_COTIZACION, @CANTCOTIZADO = ISNULL(CD.CANTIDAD,0) 
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTIZACIONVENTA] C ON CD.ID_COTIZACION = C.ID_COTIZACION
		WHERE CD.ID = @IDCOTDETALLE;

		SELECT TOP 1 @INDINFOVIDEO = CDD.INDINFOVIDEO, @INDINFOMANUAL = CDD.INDINFOMANUAL,
		@INDINSTALACION = CDD.INDINSTALACION, @INDCAPACITACION = CDD.INDCAPACITACION, @INDGARANADIC = CDD.INDGARANADIC,
		@INDMANTPREVENT = CDD.INDMANTPREVENT, @INDCALIB = CDD.INDCALIB
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTDET_DESPACHO] CDD ON CD.ID = CDD.ID_COTDETALLE
		WHERE CD.ID = @IDCOTDETALLE;

		--
		-- LLAVE EN MANO
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0001' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_LLAVEMANO = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_LLAVEMANO = 1;
			END
		END
		
		--
		-- INSTALACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0002' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_INSTALACION = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_INSTALACION = 1;
			END
		END
		
		--
		-- CAPACITACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0003' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_CAPACITACION = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_CAPACITACION = 1;
			END
		END
		
		--
		-- MANUALES
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0004' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_MANUALES = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_MANUALES = 1;
			END
		END
		
		--
		-- VIDEOS
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0005' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_VIDEOS = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_VIDEOS = 1;
			END
		END
		
		--
		-- MANTENIMIENTO PREVENTIVO
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0006' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_MANTPREV = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_MANTPREV = 1;
			END
		END
		
		--
		-- GARANTIA ADICIONAL
		--
		--SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		--WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0007' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		--IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
		--	SET @FLAG_GARANTADIC = 2;
		--END
		--ELSE BEGIN
		--	IF @TOTALCANTCOSTO > 0 BEGIN
		--		SET @FLAG_GARANTADIC = 1;
		--	END
		--END
		
		--
		-- CALIBRACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0007' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_CALIB = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_CALIB = 1;
			END
		END
		
		--
		-- FLETE
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @IDCOTDETALLE AND CODCOSTO = 'CXCD0008' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_FLETE = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_FLETE = 1;
			END
		END

		SET @INDCOSTEADO = 'S';

		--
		-- VALIDA que los INDICADORES tengan sus registros de COSTOS respectivos
		--
		IF @INDINFOVIDEO IS NOT NULL BEGIN
			IF ISNULL(@INDINFOVIDEO,'') = 'S' AND ISNULL(@FLAG_VIDEOS,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDINFOMANUAL IS NOT NULL BEGIN
			IF ISNULL(@INDINFOMANUAL,'') = 'S' AND ISNULL(@FLAG_MANUALES,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDINSTALACION IS NOT NULL BEGIN
			IF ISNULL(@INDINSTALACION,'') = 'S' AND ISNULL(@FLAG_INSTALACION,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDCAPACITACION IS NOT NULL BEGIN
			IF ISNULL(@INDCAPACITACION,'') = 'S' AND ISNULL(@FLAG_CAPACITACION,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		--IF @INDGARANADIC IS NOT NULL BEGIN
		--	IF ISNULL(@INDGARANADIC,'') = 'S' AND ISNULL(@FLAG_GARANTADIC,0) = 0 BEGIN
		--		SET @INDCOSTEADO = 'N'
		--	END
		--END

		IF @INDMANTPREVENT IS NOT NULL BEGIN
			IF ISNULL(@INDMANTPREVENT,'') = 'S' AND ISNULL(@FLAG_MANTPREV,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDCALIB IS NOT NULL BEGIN
			IF ISNULL(@INDCALIB,'') = 'S' AND ISNULL(@FLAG_CALIB,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END
		
		IF @INDFLETE IS NOT NULL BEGIN
			IF ISNULL(@INDFLETE,'') = 'S' AND ISNULL(@FLAG_FLETE,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END
		
		--
		-- VALIDA que los registros de costos hayan sido VALORIZADOS con sus montos respectivos
		--
		IF @INDCOSTEADO = 'S' BEGIN
			SELECT @NUM = COUNT(1) FROM TBD_COTIZACIONCOSTOS TX WHERE TX.ID_COTDETALLE IN (SELECT T1.ID FROM TBD_COTIZACIONVENTA T1 WHERE T1.ID_COTIZACION = @IDCOTIZACION) 
			AND (ISNULL(MONTOUNICOSTO,0) <= 0 AND ISNULL(MONTOTOTCOSTO,0) <= 0);
			IF @NUM > 0 BEGIN
				SET @INDCOSTEADO = 'N';
			END
		END

		UPDATE TBM_COTIZACIONVENTA SET INDCOSTEADO = @INDCOSTEADO WHERE ID_COTIZACION = @IDCOTIZACION;
		
		EXEC USP_UPD_TOTALIZAR_COTDET @IDCOTDETALLE

		
			SET  @CODIGO = 1
		    SET @MSG ='Se realizó la actualización de costeo con éxito'


	END

	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;
END