USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_COSTEOITEM
/*-----------------------------------------------------------------------------------------------------------------------------------------------------
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Jose A. Peralta		09.02.25		Mantenimiento de costeo item.
  ------------------------------------------------------------------------------------------------------------------------------------------------------*/
 @TIPO VARCHAR(1),
 @IDCOTDETALLE BIGINT,
 @CODCOSTO VARCHAR(8),
 @CANTCOSTO INT,
 @CANTPREVENTIVO INT,
 @CODCICLOPREVENTIVO VARCHAR(20),
 @CODUBIGEO VARCHAR(6),
 @DIRECCION VARCHAR(150),
 @AMBIENTEDESTINO VARCHAR(200),
 @NROPISO INT,
 @MONTOUNITARIO DECIMAL(18,9),
 @IDCOSTO BIGINT,
 @USRREG VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @NUMSEC INT
	DECLARE @CODIGO BIGINT,@MSG VARCHAR(250),@CODCOTCOSTO BIGINT,@CODCOSTOITEM VARCHAR(10)
	DECLARE @INDINFO CHAR(1),@SQL VARCHAR(MAX)

	SELECT @NUMSEC = COUNT(1)+1 FROM TBD_COTIZACIONCOSTOS WHERE ID_COTDETALLE=@IDCOTDETALLE

	SELECT @CODIGO=0,@MSG='No se pudo realizar ninguna accion'

	IF(@TIPO = 'I')
	BEGIN
		
		INSERT INTO TBD_COTIZACIONCOSTOS(ID_COTDETALLE,NUMSEC,CODCOSTO,CANTCOSTO,CANTPREVENTIVO,CODCICLOPREVENT,CODUBIGEODEST,DIRECCION,AMBIENTEDEST,NROPISO,MONTOUNICOSTO,MONTOTOTCOSTO,USR_REG,FEC_REG,ELIMINADO)
			VALUES(@IDCOTDETALLE,@NUMSEC,@CODCOSTO,@CANTCOSTO,@CANTPREVENTIVO,@CODCICLOPREVENTIVO,@CODUBIGEO,@DIRECCION,@AMBIENTEDESTINO,@NROPISO,@MONTOUNITARIO,0.00,@USRREG,GETDATE(),0)

			SET @CODCOTCOSTO = @@IDENTITY;

		UPDATE TBM_COTDET_DESPACHO
			SET INDINFOVIDEO = CASE WHEN @CODCOSTO='CXCD0005' THEN 'S' ELSE 'N' END,
					INDINFOMANUAL = CASE WHEN @CODCOSTO='CXCD0004' THEN 'S' ELSE 'N' END,
					INDINSTALACION = CASE WHEN @CODCOSTO='CXCD0002' THEN 'S' ELSE 'N' END,
					INDCAPACITACION = CASE WHEN @CODCOSTO='CXCD0003' THEN 'S' ELSE 'N' END,
					INDMANTPREVENT = CASE WHEN @CODCOSTO='CXCD0006' THEN 'S' ELSE 'N' END,
					INDCALIB =  CASE WHEN @CODCOSTO='CXCD0007' THEN 'S' ELSE 'N' END,
					INDFLETE =  CASE WHEN @CODCOSTO='CXCD0008' THEN 'S' ELSE 'N' END,
					USR_MOD= @USRREG,
					FEC_MOD = GETDATE()
				--	INDREQPLACA= CASE WHEN @CODCOSTO='CXCD0007' THEN 'S' ELSE 'N' END,
			WHERE ID_COTDETALLE=@IDCOTDETALLE

			SET  @CODIGO = @CODCOTCOSTO
		    SET @MSG ='Se realizó el registro de costeo con éxito'

	END
	IF(@TIPO = 'U')
	BEGIN
				UPDATE TBD_COTIZACIONCOSTOS
				SET CANTCOSTO = @CANTCOSTO,
						CANTPREVENTIVO = @CANTPREVENTIVO,
						CODCICLOPREVENT = @CODCICLOPREVENTIVO,
						CODUBIGEODEST=@CODUBIGEO,
						DIRECCION=@DIRECCION,
						AMBIENTEDEST = @AMBIENTEDESTINO,
						NROPISO = @NROPISO,
						MONTOUNICOSTO  = (CASE WHEN @CODCOSTO='CXCD0007' THEN @MONTOUNITARIO ELSE MONTOUNICOSTO END ),
						USR_MOD = @USRREG,
						FEC_MOD = GETDATE()
				WHERE ID_COTDETALLE=@IDCOTDETALLE AND ID=@IDCOSTO;

			SET  @CODIGO = 1
		    SET @MSG ='Se realizó la actualización de costeo con éxito'

	END
	IF(@TIPO= 'D')
	BEGIN


			UPDATE TBD_COTIZACIONCOSTOS
				SET ELIMINADO=1,
						USR_MOD = @USRREG,
						FEC_MOD=GETDATE()
				WHERE ID_COTDETALLE=@IDCOTDETALLE AND ID=@IDCOSTO

				SELECT @CODCOSTOITEM=CODCOSTO 
				FROM TBD_COTIZACIONCOSTOS WITH(NOLOCK) 
				WHERE  ID_COTDETALLE=@IDCOTDETALLE AND ID=@IDCOSTO;

				SELECT @INDINFO='N'


				IF EXISTS(SELECT 1 FROM TBD_COTIZACIONCOSTOS WITH(NOLOCK) 
				WHERE ID_COTDETALLE=@IDCOTDETALLE AND CODCOSTO=@CODCOSTOITEM
				 AND ELIMINADO=0)
				 BEGIN

						SET @INDINFO = 'S'

				 END

				 SET @SQL='UPDATE TBM_COTDET_DESPACHO SET '
				 IF(@CODCOSTOITEM = 'CXCD0005')
						BEGIN
								SET @SQL='INDINFOVIDEO='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0004')
						BEGIN
								SET @SQL='INDINFOMANUAL='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0002')
						BEGIN
								SET @SQL='INDINSTALACION='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0003')
						BEGIN
								SET @SQL='INDCAPACITACION='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0006')
						BEGIN
								SET @SQL='INDMANTPREVENT='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0007')
						BEGIN
								SET @SQL='INDCALIB='''+@INDINFO+''''
						END
				 IF(@CODCOSTOITEM = 'CXCD0008')
						BEGIN
								SET @SQL='INDFLETE='''+@INDINFO+''''
						END
			    SET @SQL=' WHERE ID_COTDETALLE='+CAST(@IDCOTDETALLE AS VARCHAR)

			EXEC(@SQL)


			SET  @CODIGO = 1
		    SET @MSG ='Se realizó la eliminación de costeo con éxito'

	END

	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;
END