USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_COSTEOCOTIZACION
/*================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Jose A. Peralta		10.02.25		Mantenimiento de costeo de cotización
  ================================================================================================*/
@TIPO VARCHAR(1),
@IDCOTIZACIONDETALLE BIGINT,
@CANTIDAD INT,
@INDSTOCK VARCHAR(1),
@DIMENSIONES  VARCHAR(50),
@OBSCLIENTE VARCHAR(2000),
@OBSDESPACHO VARCHAR(2000),
@DESCRIPADIC VARCHAR(1000),
@VVENTAUNI DECIMAL(18,9),
@INDCOMPRALOCAL VARCHAR(1),
@INDREQPLACA VARCHAR(1),
@CODGARANADIC VARCHAR(20),
@PORCGANANCIA DECIMAL(18,9),
@USRREG VARCHAR(50)
AS
BEGIN
SET NOCOUNT ON;

DECLARE @IND_GARANTIAADICIONAL VARCHAR(1)
DECLARE @CODIGO BIGINT,@MSG VARCHAR(250)

SELECT @CODIGO=0,@MSG='No se pudo realizar ninguna accion'

IF(@TIPO = 'I')
BEGIN
			UPDATE TBD_COTIZACIONVENTA
				SET CANTIDAD=@CANTIDAD,
					   INDSTOCK=@INDSTOCK,
					   DESCRIPADIC=@DESCRIPADIC,
					   PORCGANANCIA=@PORCGANANCIA,
					   VVENTAUNI=@VVENTAUNI
				WHERE ID=@IDCOTIZACIONDETALLE AND ISNULL(ELIMINADO,'N') != 'S';

				SET @IND_GARANTIAADICIONAL=ISNULL(@CODGARANADIC,'N');

				IF(@IND_GARANTIAADICIONAL = '')
				BEGIN
					SET @IND_GARANTIAADICIONAL='N'
				END

				INSERT INTO TBM_COTDET_DESPACHO(ID_COTDETALLE,INDINFOVIDEO,INDINFOMANUAL,INDINSTALACION,
				INDCAPACITACION,INDGARANADIC,CODGARANADIC,INDMANTPREVENT,INDCALIB,DIMENSIONES,INDCOMPRALOCAL,
				INDREQPLACA,INDFLETE,OBSCLIENTE,OBSDESPACHO,USR_REG,FEC_REG)
				VALUES(@IDCOTIZACIONDETALLE,
							  'N','N','N','N',@IND_GARANTIAADICIONAL,@CODGARANADIC,'N','N',@DIMENSIONES,@INDCOMPRALOCAL,
							  @INDREQPLACA,'N',@OBSCLIENTE,@OBSDESPACHO,@USRREG,GETDATE());


			SET  @CODIGO = @@IDENTITY;
		    SET @MSG ='Se realizó el registro del detalle del costeo del producto'

END

IF(@TIPO = 'U')
BEGIN
				SET @IND_GARANTIAADICIONAL=ISNULL(@CODGARANADIC,'N');

				IF(@IND_GARANTIAADICIONAL = '')
				BEGIN
					SET @IND_GARANTIAADICIONAL='N'
				END


		UPDATE TBM_COTDET_DESPACHO
			SET INDGARANADIC=@IND_GARANTIAADICIONAL,
					CODGARANADIC=@CODGARANADIC,
					DIMENSIONES=@DIMENSIONES,
					INDCOMPRALOCAL=@INDCOMPRALOCAL,
					INDREQPLACA=@INDREQPLACA,
					OBSCLIENTE=@OBSCLIENTE,
					OBSDESPACHO=@OBSDESPACHO,
					USR_MOD=@USRREG,
					FEC_MOD=GETDATE()
		WHERE ID_COTDETALLE=@IDCOTIZACIONDETALLE;

		UPDATE TBD_COTIZACIONVENTA
				SET CANTIDAD=@CANTIDAD,
					   INDSTOCK=@INDSTOCK,
					   DESCRIPADIC=@DESCRIPADIC,
					   VVENTAUNI=@VVENTAUNI,
					   PORCGANANCIA = @PORCGANANCIA
				WHERE ID=@IDCOTIZACIONDETALLE AND ISNULL(ELIMINADO,'N') != 'S';

		EXEC [USP_UPD_TOTALIZAR_COTDET] @IDCOTIZACIONDETALLE


		SET  @CODIGO = 1;
		SET @MSG ='Se realizó la actualización del detalle del costeo del producto'

END

IF(@TIPO = 'C')
BEGIN

	DECLARE @VENTA_TOTAL DECIMAL(18,9)

	SET  @VENTA_TOTAL=(@CANTIDAD*@VVENTAUNI)


	UPDATE TBD_COTIZACIONVENTA
				SET VVENTAUNI=@VVENTAUNI,
					VVTOTALSIGV = @VENTA_TOTAL,
						USR_MOD = @USRREG,
						FEC_MOD = GETDATE()
				WHERE ID=@IDCOTIZACIONDETALLE;

						--ACTUALIZA INDICADOR DE VALORIZADO:
		DECLARE @CANT_COSTOS INT,@CANT_VAL INT,@INDVALORIZADO VARCHAR(1),@IDCOTIZACION BIGINT,@CANTCOSTOS INT 

		SELECT TOP 1 @IDCOTIZACION = C.ID_COTIZACION
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTIZACIONVENTA] C ON CD.ID_COTIZACION = C.ID_COTIZACION
		WHERE CD.ID = @IDCOTIZACIONDETALLE;

		SELECT @CANT_COSTOS=COUNT(1) FROM TBD_COTIZACIONVENTA WHERE ELIMINADO='N' AND ID_COTIZACION=@IDCOTIZACION
		SELECT @CANT_VAL=COUNT(1) FROM TBD_COTIZACIONVENTA WHERE ELIMINADO='N' AND ID_COTIZACION=@IDCOTIZACION AND  ISNULL(VVENTAUNI,0) != 0
		SELECT @CANTCOSTOS= COUNT(1) FROM TBD_COTIZACIONCOSTOS 
							WHERE ID_COTDETALLE IN(SELECT ID FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION=@IDCOTIZACION) AND ELIMINADO=0

		SET  @INDVALORIZADO='N'
		IF(@CANT_COSTOS = @CANT_VAL)
		BEGIN
			SET @INDVALORIZADO='S'

		END
		
			UPDATE TBM_COTIZACIONVENTA
				SET INDVALORIZADO=@INDVALORIZADO
					WHERE ID_COTIZACION=@IDCOTIZACION


		IF(@CANTCOSTOS = 0)
		BEGIN
		
			UPDATE TBM_COTIZACIONVENTA
				SET INDCOSTEADO='S'
					WHERE ID_COTIZACION=@IDCOTIZACION

		END




		SET  @CODIGO = 1;
		SET @MSG ='Se realizó la actualización del valor venta unitario producto'
END


	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;
END

