USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_CONSULTA_COSTEOITEM
/*================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Jose A. Peralta		10.02.25		Consulta del detalle por item del costeo
	EXEC USP_CONSULTA_COSTEOITEM 166,55
  ================================================================================================*/
  @CODDETALLECOTIZACION BIGINT,
  @CODCOSTEO BIGINT
  AS
  BEGIN
  SET NOCOUNT ON;

  DECLARE @CODMONEDA VARCHAR(10),@DESMONEDA VARCHAR(15),@SIMBOLO VARCHAR(5)


   SELECT @CODMONEDA=RTRIM(ISNULL(C.COD_VALOR1,'')),
				@DESMONEDA=RTRIM(ISNULL(C.VALOR1,'')),
				@SIMBOLO=RTRIM(ISNULL(C.COD_VALOR3,'')) 
				FROM TBM_COTIZACIONVENTA A WITH(NOLOCK)
   INNER JOIN TBD_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION AND ID=@CODDETALLECOTIZACION AND ISNULL(B.ELIMINADO,'N') != 'S'
   LEFT JOIN TBD_DATOS_GENERALES C WITH(NOLOCK) ON C.DOMINIO='TIPMONEDA' AND  A.MONEDA=C.COD_VALOR1


	SELECT 
	ISNULL(A.CODITEM,'') CODITEM,
	ISNULL(A.DESCRIPCION,'') DESCRIPCION ,
	ISNULL(A.CANTIDAD,0) CANTIDAD,
	ISNULL(A.UNDMED,'') UNDMED,
	ISNULL(A.DESCRIPADIC,'') DESCRIPADIC,
	ISNULL(C.MONTOUNICOSTO,0.00) VVENTAUNI,
	ISNULL(C.MONTOTOTCOSTO,0.00) VVTOTALSIGV,
	ISNULL(B.DIMENSIONES,'') DIMENSIONES,
	ISNULL(C.CODUBIGEODEST,'') CODUBIGEO,
	CASE WHEN ISNULL(C.CODUBIGEODEST,'') = '' THEN ''
	ELSE  RTRIM(ISNULL(E.NOMDEPARTAMENTO,'')) +'/'+RTRIM(ISNULL(E.NOMPROVINCIA,''))+'/'+RTRIM(ISNULL(E.NOMDISTRITO,'')) 
	END DESUBIGEO,
	ISNULL(C.DIRECCION,'') DIRECCION,
	ISNULL(C.AMBIENTEDEST,'') AMBIENTEDESTINO,
	ISNULL(C.NROPISO,'') NROPISO,
	ISNULL(C.CANTCOSTO,0) CANTCOSTO,
	ISNULL(C.CANTPREVENTIVO,0) CANTPREVENTIVO,
	ISNULL(C.CODCICLOPREVENT,'') CODCICLOPREVENT,
	ISNULL(D.DESCRIPCION,'') DESCICLOPREVENT,
	ISNULL(C.CODCOSTO,'') CODCOSTO,
	ISNULL(F.DESCRIPCION,'') DESCOSTO,
	@CODMONEDA CODMONEDA,
	@DESMONEDA DESMONEDA,
	@SIMBOLO SIMBOLOMONEDA
	FROM TBD_COTIZACIONVENTA A WITH(NOLOCK) 
	INNER JOIN TBM_COTDET_DESPACHO B WITH(NOLOCK) ON A.ID=B.ID_COTDETALLE
	LEFT JOIN TBD_COTIZACIONCOSTOS C WITH(NOLOCK) ON A.ID=C.ID_COTDETALLE
	LEFT JOIN TBD_DATOS_GENERALES D  WITH(NOLOCK) ON  D.DOMINIO='CICLOPREV' AND   C.CODCICLOPREVENT=D.PARAMETRO
	LEFT JOIN TBM_UBIGEO E WITH(NOLOCK) ON ISNULL(C.CODUBIGEODEST,'')=E.CODUBIGEO
	LEFT JOIN TBD_DATOS_GENERALES F  WITH(NOLOCK) ON  F.DOMINIO='COSTOXCD' AND  F.PARAMETRO= C.CODCOSTO
	WHERE A.ID=@CODDETALLECOTIZACION AND C.ID=@CODCOSTEO AND ISNULL(A.ELIMINADO,'N') != 'S' AND ISNULL(C.ELIMINADO,0) != 1


  SET NOCOUNT OFF;
  END




