USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_CONSULTA_BANDEJASOLICITUD
/*================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		13.02.25		Se realiza consulta a bandeja de solicitudes
	EXEC USP_CONSULTA_BANDEJASOLICITUD 0,0,'','','','','','','','','','','','','','','','','','','','','','','','','',''
  ================================================================================================*/
@CODSOL BIGINT,
@COD_FLUJO BIGINT,
@FECINISOL VARCHAR(10),
@FECFINSOL VARCHAR(10),
@TIPOVENTA VARCHAR(6),
@TIPOSOL VARCHAR(6),
@RUCCLIENTE VARCHAR(12),
@NOMCLIENTE VARCHAR(200),
@NOMVENDEDOR VARCHAR(200),
@CODEMPRESA VARCHAR(10),
@ESTADO VARCHAR(5),
@NOMEQUIPO VARCHAR(150),
@FORMAPAGO VARCHAR(10),
@MONEDA VARCHAR(10),
@GARANTIA VARCHAR(10),
@NROORDEN VARCHAR(50),
@NROPROCESO VARCHAR(50),
@NUMCONTRATO VARCHAR(50),
@NUMFIANZAPP VARCHAR(50),
@NUMFIANZAPA VARCHAR(50),
@FLAGGERENCIA VARCHAR(1),
@FLAGLOGISTICA VARCHAR(1),
@FLAGCOSTEO VARCHAR(1),
@FLAGSERVTEC VARCHAR(1),
@FLAGIMPORT VARCHAR(1),
@FLAGFACT VARCHAR(1),
@ROLUSUARIO VARCHAR(35),
@USRREG VARCHAR(50)
AS
BEGIN
SET NOCOUNT ON;

DECLARE @SQL VARCHAR(MAX)


SET @SQL='
SELECT  RIGHT(''000000'' + CAST(A.ID_SOLICITUD AS VARCHAR),6)  NUMSOL,
A.ID_FLUJO,
ISNULL(B.VALOR1,'''') DESFLUJO,
 ISNULL(CONVERT(varchar,A.FECHA_SOL,103),'''') FECHASOL,
 ISNULL(I.VALOR1,'''') TIPOVENTA,
 ISNULL(C.VALOR1,'''') TIPOSOL,
 ISNULL(D.VALOR1,'''') MEDIOCONTACTO,
 ISNULL(A.TIPOPROCESO,'''') TIPOPROCESO,
 ISNULL(A.NROPROCESO,'''') NROPROCESO,
 ISNULL(A.RUC,'''') RUCCLIENTE,
 ISNULL(A.RAZONSOCIAL,'''') RAZONSOCIALCLIENTE,
 ISNULL(A.ASESORVENTA,'''') VENDEDOR,
 ISNULL(E.VALOR1,'''') NOMEMPRESA,
 ISNULL(EST.NOM_ESTADO,'''') NOMESTADO,
 UPPER(A.USR_REG) USR_REG,
 ISNULL(CONVERT(varchar,A.FEC_REG,103) +'' ''+CONVERT(varchar,A.FEC_REG,8),'''')  AS FEC_REG,
 ''PC-''+RIGHT(''000000'' + CAST(COTI.ID_COTIZACION AS VARCHAR),6)  NUMCOTI,
  ISNULL(CONVERT(varchar,COTI.FEC_COTIZACION,103),'''') FECHACOTI,
  ISNULL(COTI.NOMBRECONTACTO,'''') NOMCONTACTO,
  ISNULL(COTI.AREACONTACTO,'''') AREACONTACTO,
  ISNULL(COTI.TELEFONOCONTACTO,'''') TELEFONOCONTACTO,
  ISNULL(COTI.EMAILCONTACTO,'''') EMAILCONTACTO,
  ISNULL(CAST(COTI.PLAZOENTREGA AS VARCHAR),'''') PLAZOENTREGA,
  ISNULL(F.VALOR1,'''') FORMAPAGO,
  ISNULL(G.VALOR1,'''') MONEDA,
  ISNULL(CAST(COTI.VIGENCIA AS varchar),'''') VIGENCIA,
  ISNULL(H.VALOR1,'''') GARANTIA,
  ISNULL(COTI.OBSERVACION,'''') OBSERVACION,
  ISNULL(COTI.PORCDSCTO,0.00) PORCENTAJE_DSC,
  ISNULL(COTI.SUBTOTALVENTA,0.00) SUBTOTAL,
  ISNULL(COTI.MONTOIGV,0.00) MONTOIGV,
  ISNULL(COTI.TOTALVENTA,0.00) TOTALVENTA,
  ISNULL(DESP.NUMORDEN,'''') NUMORDEN,
  ISNULL(CONVERT(varchar,DESP.FECHAORDEN,103),'''') FECHAORDEN,
  ISNULL(CONVERT(varchar,DESP.FECHAMAX,103),'''') FECHAMAX,
  ISNULL(DESP.NUMCONTRATO,'''') NUMCONTRATO,			
  ISNULL(CONVERT(varchar,DESP.FEC_CONTRATO,103),'''') FEC_CONTRATO,
  ISNULL(DESP.PRESTPRIN,'''') PRESTPRIN,
  ISNULL(DESP.PRESTACC,'''') PRESTACC,
  ISNULL(DESP.NUMFIANZAPP,'''') NUMFIANZAPP,
  ISNULL(DESP.NUMFIANZAPA,'''') NUMFIANZAPA,
  ISNULL(DESP.FIANZA,'''') FIANZA,
  ISNULL(A.ID_SOLICITUD,0) IDSOLICITUD,
  ISNULL(A.ID_WORKFLOW,0) IDWORKFLOW,
  ISNULL(A.ESTADO,'''') IDESTADO,
  ISNULL(EST.ABREV_ESTADO,'''') ABREVEST,
  ISNULL(A.TIPO_SOL,'''') CODTIPOSOL,
  ISNULL(A.IDCLIENTE,0) IDCLIENTE,
  ISNULL(A.IDSEDE,0) IDSEDE,
  ISNULL(J.NOMSEDE,'''') NOMSEDE
  FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
  INNER JOIN TBM_PROCESOESTADOS EST WITH(NOLOCK) ON A.ESTADO =EST.COD_ESTADO AND EST.ID_PROCESO=1
  LEFT JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON A.ID_SOLICITUD = COTI.ID_SOLICITUD AND COTI.ESTADO=''A''
  LEFT JOIN ( SELECT ID_SOLICITUD,ID_COTIZACION,NUMORDEN, FECHAORDEN,FECHAMAX,NUMCONTRATO,FEC_CONTRATO,PRESTPRIN,PRESTACC,NUMFIANZAPP,NUMFIANZAPA,FIANZA 
					FROM  TBM_DESPACHO  WITH(NOLOCK)
					GROUP BY ID_SOLICITUD,ID_COTIZACION,NUMORDEN, FECHAORDEN,FECHAMAX,NUMCONTRATO,FEC_CONTRATO,PRESTPRIN,PRESTACC,NUMFIANZAPP,NUMFIANZAPA,FIANZA ) DESP 
					ON A.ID_SOLICITUD=DESP.ID_SOLICITUD '
IF(LEN(RTRIM(@NOMEQUIPO))>0)
BEGIN
	SET @SQL=@SQL+ 'LEFT JOIN (SELECT ID_COTIZACION FROM TBD_COTIZACIONVENTA WITH(NOLOCK) WHERE DESCRIPCION LIKE ''%'+ RTRIM(@NOMEQUIPO)+'%'' AND ELIMINADO=''N'') DET ON COTI.ID_COTIZACION=DET.ID_COTIZACION '
END
	SET @SQL=@SQL+'LEFT JOIN  TBD_DATOS_GENERALES B WITH(NOLOCK)  ON B.DOMINIO=''FLOWSOL'' AND A.ID_FLUJO=CAST(B.COD_VALOR1 AS INT)
LEFT JOIN  TBD_DATOS_GENERALES C WITH(NOLOCK)  ON C.DOMINIO=''TIPOSOLVT'' AND A.TIPO_SOL=C.COD_VALOR1
LEFT JOIN  TBD_DATOS_GENERALES D WITH(NOLOCK)  ON D.DOMINIO=''MEDIOCONT'' AND A.COD_MEDIOCONT=D.COD_VALOR1
LEFT JOIN  TBD_DATOS_GENERALES E WITH(NOLOCK)  ON E.DOMINIO=''RAZSOCIAL'' AND A.COD_EMPRESA=E.PARAMETRO
LEFT JOIN  TBD_DATOS_GENERALES F WITH(NOLOCK)  ON F.DOMINIO=''FORMAPAGO'' AND COTI.FORMAPAGO=F.PARAMETRO
LEFT JOIN  TBD_DATOS_GENERALES G WITH(NOLOCK)  ON G.DOMINIO=''TIPMONEDA'' AND COTI.MONEDA=G.COD_VALOR1
LEFT JOIN  TBD_DATOS_GENERALES H WITH(NOLOCK)  ON H.DOMINIO=''GARANTIAS'' AND COTI.GARANTIA=H.PARAMETRO
LEFT JOIN  TBD_DATOS_GENERALES I WITH(NOLOCK)  ON I.DOMINIO=''TIPOVENTA'' AND A.TIPOVENTA=I.COD_VALOR1 
LEFT JOIN  TBM_SEDES J WITH(NOLOCK) ON ISNULL(A.IDSEDE,0) =J.ID_SEDE AND J.ELIMINADO=0 '
SET @SQL = @SQL+'WHERE 1=1 '
IF(@ROLUSUARIO IN ('SGI_VENTA_ASESOR'))
BEGIN
	SET @SQL= @SQL+' AND UPPER(A.USR_REG)= '''+UPPER(RTRIM(@USRREG))+''' AND A.ID_FLUJO=1'
	SET @SQL=@SQL+' AND A.TIPO_SOL IN(''TSOL04'',''TSOL05'') '
END
IF(@ROLUSUARIO IN ('SGI_VENTA_JEFE','SGI_VENTA_COORDINAVENTA'))
BEGIN
	SET @SQL=@SQL+' AND A.ID_FLUJO=1' --VENTAS
	SET @SQL=@SQL+' AND A.TIPO_SOL IN(''TSOL04'',''TSOL05'') '
END
IF(@ROLUSUARIO IN ('SGI_VENTA_COORDINASERV','SGI_VENTA_COORDINAATC'))
BEGIN
	SET @SQL=@SQL+' AND A.ID_FLUJO=2' --POST VENTA
	SET @SQL=@SQL+' AND A.TIPO_SOL IN(''TSOL01'',''TSOL02'',''TSOL03'') '
END
IF(@CODSOL > 0)
BEGIN
	SET @SQL=@SQL+' AND A.ID_SOLICITUD='+CAST(@CODSOL AS VARCHAR)+' '
END
IF(@COD_FLUJO > 0)
BEGIN
	SET @SQL=@SQL+' AND A.ID_FLUJO='+CAST(@COD_FLUJO AS VARCHAR)+' '
END
IF(LEN(@FECINISOL) > 0 AND LEN(@FECFINSOL) >0 )
BEGIN
	SET @SQL=@SQL+' AND CONVERT(VARCHAR,A.FEC_REG,103) BETWEEN '''+CAST(@FECINISOL AS VARCHAR)+''' AND '''+CAST(@FECFINSOL AS VARCHAR)+''' '
END
IF(LEN(RTRIM(@TIPOVENTA))>0)
BEGIN
	SET @SQL=@SQL+' AND A.TIPOVENTA = '''+RTRIM(@TIPOVENTA)+''' '
END
IF(LEN(RTRIM(@TIPOSOL))>0)
BEGIN
	SET @SQL=@SQL+' AND A.TIPO_SOL = '''+RTRIM(@TIPOSOL)+''' '
END
IF(LEN(RTRIM(@RUCCLIENTE))>0)
BEGIN
	SET @SQL=@SQL+' AND A.RUC = '''+RTRIM(@RUCCLIENTE)+''' '
END
IF(LEN(RTRIM(@NOMCLIENTE))>0)
BEGIN
	SET @SQL=@SQL+' AND A.RAZONSOCIAL LIKE ''%'+RTRIM(@NOMCLIENTE)+'%'' '
END
IF(LEN(RTRIM(@NOMVENDEDOR))>0)
BEGIN
	SET @SQL=@SQL+' AND A.ASESORVENTA LIKE ''%'+RTRIM(@NOMVENDEDOR)+'%'' '
END
IF(LEN(RTRIM(@CODEMPRESA))>0)
BEGIN
		SET @SQL=@SQL+' AND A.COD_EMPRESA = '''+RTRIM(@CODEMPRESA)+''' '
END
IF(LEN(RTRIM(@ESTADO))>0)
BEGIN
		SET @SQL=@SQL+' AND A.ESTADO = '''+RTRIM(@ESTADO)+''' '
END
IF(LEN(RTRIM(@FORMAPAGO))>0)
BEGIN
	SET @SQL=@SQL+' AND COTI.FORMAPAGO = '''+RTRIM(@FORMAPAGO)+''' '
END
IF(LEN(RTRIM(@MONEDA))>0)
BEGIN
	SET @SQL=@SQL+' AND COTI.MONEDA = '''+RTRIM(@MONEDA)+''' '
END
IF(LEN(RTRIM(@GARANTIA))>0)
BEGIN
	SET @SQL=@SQL+' AND COTI.GARANTIA = '''+RTRIM(@GARANTIA)+''' '
END
IF(LEN(RTRIM(@NROORDEN))>0)
BEGIN
	SET @SQL=@SQL+' AND DESP.NUMORDEN LIKE ''%'+RTRIM(@NROORDEN)+'%'' '
END
IF(LEN(RTRIM(@NROPROCESO))>0)
BEGIN
	SET @SQL=@SQL+' AND A.NROPROCESO LIKE ''%'+RTRIM(@NROPROCESO)+'%'' '
END
IF(LEN(RTRIM(@NUMCONTRATO))>0)
BEGIN
	SET @SQL=@SQL+' AND DESP.NUMCONTRATO LIKE ''%'+RTRIM(@NUMCONTRATO)+'%'' '
END
IF(LEN(RTRIM(@NUMFIANZAPP))>0)
BEGIN
	SET @SQL=@SQL+' AND DESP.NUMFIANZAPP LIKE ''%'+RTRIM(@NUMFIANZAPP)+'%'' '
END
IF(LEN(RTRIM(@NUMFIANZAPA))>0)
BEGIN
	SET @SQL=@SQL+' AND DESP.NUMFIANZAPA LIKE ''%'+RTRIM(@NUMFIANZAPA)+'%'' '
END
IF(@FLAGGERENCIA='S')
BEGIN
	SET @SQL=@SQL+' AND A.ID_SOLICITUD IN (SELECT ID_SOLICITUD  
																					FROM TBM_DESPACHO WITH(NOLOCK) WHERE STOCK=''N''
																										AND ESTAPROB=''''
																										UNION
																										SELECT C.ID_SOLICITUD FROM TBD_COTIZACIONVENTA A WITH(NOLOCK) 
																										INNER JOIN TBM_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION AND B.ESTADO=''A''
																										INNER JOIN TBM_SOLICITUDVENTA C WITH(NOLOCK) ON  C.ID_SOLICITUD =B.ID_SOLICITUD
																										WHERE C.ESTADO=''CVAL''
																										AND ISNULL(A.MARGENUTILIDAD,'''')='''' AND ELIMINADO=''N'' 
																										) '
END
IF(@FLAGLOGISTICA='S')
BEGIN
   SET @SQL=@SQL+' AND A.ID_SOLICITUD IN (
																	SELECT DISTINCT SOL.ID_SOLICITUD FROM TBM_SOLICITUDVENTA SOL WITH(NOLOCK) 
																	INNER JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON SOL.ID_SOLICITUD=COTI.ID_SOLICITUD
																	INNER JOIN TBD_COTIZACIONVENTA A WITH(NOLOCK) ON COTI.ID_COTIZACION=A.ID_COTIZACION AND A.ELIMINADO=''N''
																	INNER JOIN TBM_COTDET_DESPACHO B WITH(NOLOCK) ON A.ID=B.ID_COTDETALLE
																	INNER JOIN TBD_COTIZACIONCOSTOS C WITH(NOLOCK) ON A.ID=C.ID_COTDETALLE AND C.CODCOSTO=''CXCD0008'' AND C.ELIMINADO=0
																	WHERE B.INDFLETE=''S'' AND SOL.ESTADO=''CVAL'' AND ISNULL(C.MONTOUNICOSTO,0)=0
																	UNION
																	SELECT DISTINCT C.ID_SOLICITUD FROM TBD_DESPACHO_DIST A WITH(NOLOCK)
																	INNER JOIN TBM_DESPACHO B WITH(NOLOCK) ON A.ID_DESPACHO=B.ID
																	INNER JOIN TBM_SOLICITUDVENTA C WITH(NOLOCK) ON B.ID_SOLICITUD=C.ID_SOLICITUD
																	WHERE C.ESTADO IN (''PRVT'',''VTPG'') AND 
																	C.TIPO_SOL IN (''TSOL02'',''TSOL03'',''TSOL04'',''TSOL05'')
																	AND ISNULL(B.NUMFACTURA,'''')=''''
																	) '
END
IF(@FLAGCOSTEO ='S')
BEGIN
	SET @SQL=@SQL+' AND A.ID_SOLICITUD IN (
																				SELECT DISTINCT C.ID_SOLICITUD FROM TBD_COTIZACIONVENTA A WITH(NOLOCK)
																					INNER JOIN TBM_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION
																					INNER JOIN TBM_SOLICITUDVENTA C WITH(NOLOCK) ON B.ID_SOLICITUD=C.ID_SOLICITUD
																					WHERE 
																					ISNULL(A.VVENTAUNI,0)=0 AND LEN(A.COSTOFOB) >0 AND C.ESTADO=''CVAL''
																					AND A.ELIMINADO=''N''
																		) '
END
IF(@FLAGSERVTEC = 'S')
BEGIN
		SET @SQL=@SQL+' AND A.ID_SOLICITUD IN (
																	SELECT DISTINCT SOL.ID_SOLICITUD FROM TBM_SOLICITUDVENTA SOL WITH(NOLOCK) 
																	INNER JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON SOL.ID_SOLICITUD=COTI.ID_SOLICITUD
																	INNER JOIN TBD_COTIZACIONVENTA A WITH(NOLOCK) ON COTI.ID_COTIZACION=A.ID_COTIZACION AND A.ELIMINADO=''N''
																	INNER JOIN TBM_COTDET_DESPACHO B WITH(NOLOCK) ON A.ID=B.ID_COTDETALLE
																	INNER JOIN TBD_COTIZACIONCOSTOS C WITH(NOLOCK) ON A.ID=C.ID_COTDETALLE AND C.CODCOSTO IN(''CXCD0003'',''CXCD0002'',''CXCD0006'',''CXCD0004'',''CXCD0001'',''CXCD0005'') AND C.ELIMINADO=0
																	WHERE ((B.INDCAPACITACION=''S'' OR B.INDINSTALACION=''S'' OR B.INDMANTPREVENT=''S'' OR B.INDINFOMANUAL=''S'' OR B.INDINFOVIDEO=''S'') AND SOL.ESTADO=''CVAL'' AND ISNULL(C.MONTOUNICOSTO,0)=0)
																	OR (C.CODCOSTO = ''CXCD0001'' AND SOL.ESTADO=''CVAL'' AND ISNULL(C.MONTOUNICOSTO,0)=0 )
					) '
END
IF(@FLAGIMPORT='S')
BEGIN
		SET @SQL=@SQL+' AND A.ID_SOLICITUD IN (SELECT DISTINCT ID_SOLICITUD  
																					FROM TBM_DESPACHO WITH(NOLOCK) WHERE STOCK=''N''
																										AND ESTAPROB=''APR'') '
END
IF(@FLAGFACT='S')
BEGIN
		SET @SQL=@SQL+' AND A.ID_SOLICITUD IN (SELECT DISTINCT ID_SOLICITUD FROM TBM_DESPACHO WITH(NOLOCK) 
																WHERE ENVIOFC=''1'' AND STOCK=''X'' AND ISNULL(NUMFACTSERV,'''')='''') '
END



SET @SQL = @SQL+' ORDER BY A.ID_SOLICITUD DESC'
print @SQL
EXEC(@SQL)

SET NOCOUNT OFF;
END













