








SELECT  RIGHT('000000' + CAST(A.ID_SOLICITUD AS VARCHAR),6)  NUMSOL,
A.ID_FLUJO,
ISNULL(B.VALOR1,'') DESFLUJO,
 ISNULL(CONVERT(varchar,A.FECHA_SOL,103),'') FECHASOL,
 ISNULL(C.VALOR1,'') TIPOSOL,
 ISNULL(D.VALOR1,'') MEDIOCONTACTO,
 ISNULL(A.TIPOPROCESO,'') TIPOPROCESO,
 ISNULL(A.NROPROCESO,'') NROPROCESO,
 ISNULL(A.RUC,'') RUCCLIENTE,
 ISNULL(A.RAZONSOCIAL,'') RAZONSOCIALCLIENTE,
 ISNULL(A.ASESORVENTA,'') VENDEDOR,
 ISNULL(E.VALOR1,'') NOMEMPRESA,
 ISNULL(EST.NOM_ESTADO,'') NOMESTADO,
 UPPER(A.USR_REG) USR_REG,
 ISNULL(CONVERT(varchar,A.FEC_REG,103) +' '+CONVERT(varchar,A.FEC_REG,8),'')  AS FEC_REG,
 'PC-'+RIGHT('000000' + CAST(COTI.ID_COTIZACION AS VARCHAR),6)  NUMCOTI,
  ISNULL(CONVERT(varchar,COTI.FEC_COTIZACION,103),'') FECHACOTI,
  ISNULL(COTI.NOMBRECONTACTO,'') NOMCONTACTO,
  ISNULL(COTI.AREACONTACTO,'') AREACONTACTO,
  ISNULL(COTI.TELEFONOCONTACTO,'') TELEFONOCONTACTO,
  ISNULL(COTI.EMAILCONTACTO,'') EMAILCONTACTO,
  ISNULL(CAST(COTI.PLAZOENTREGA AS VARCHAR),'') PLAZOENTREGA,
  ISNULL(F.VALOR1,'') FORMAPAGO,
  ISNULL(G.VALOR1,'') MONEDA,
  ISNULL(CAST(COTI.VIGENCIA AS varchar),'') VIGENCIA,
  ISNULL(H.VALOR1,'') GARANTIA,
  ISNULL(COTI.OBSERVACION,'') OBSERVACION,
  ISNULL(COTI.PORCDSCTO,0.00) PORCENTAJE_DSC,
  ISNULL(COTI.SUBTOTALVENTA,0.00) SUBTOTAL,
  ISNULL(COTI.MONTOIGV,0.00) MONTOIGV,
  ISNULL(COTI.TOTALVENTA,0.00) TOTALVENTA,
  ISNULL(DESP.NUMORDEN,'') NUMORDEN,
   ISNULL(CONVERT(varchar,DESP.FECHAORDEN,103),'') FECHAORDEN,
  ISNULL(CONVERT(varchar,DESP.FECHAMAX,103),'') FECHAMAX,
ISNULL(DESP.NUMCONTRATO,'') NUMCONTRATO,
 ISNULL(CONVERT(varchar,DESP.FEC_CONTRATO,103),'') FEC_CONTRATO,
 ISNULL(DESP.PRESTPRIN,'') PRESTPRIN,
  ISNULL(DESP.PRESTACC,'') PRESTACC,
   ISNULL(DESP.NUMFIANZAPP,'') NUMFIANZAPP,
  ISNULL(DESP.NUMFIANZAPA,'') NUMFIANZAPA,
  ISNULL(DESP.FIANZA,'') FIANZA
 FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
INNER JOIN TBM_PROCESOESTADOS EST WITH(NOLOCK) ON A.ESTADO =EST.COD_ESTADO AND EST.ID_PROCESO=1
LEFT JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON A.ID_SOLICITUD = COTI.ID_SOLICITUD AND COTI.ESTADO='A'
LEFT JOIN ( SELECT ID_SOLICITUD,ID_COTIZACION,NUMORDEN, FECHAORDEN,FECHAMAX,NUMCONTRATO,FEC_CONTRATO,PRESTPRIN,PRESTACC,NUMFIANZAPP,NUMFIANZAPA,FIANZA 
					FROM  TBM_DESPACHO  WITH(NOLOCK)
					GROUP BY ID_SOLICITUD,ID_COTIZACION,NUMORDEN, FECHAORDEN,FECHAMAX,NUMCONTRATO,FEC_CONTRATO,PRESTPRIN,PRESTACC,NUMFIANZAPP,NUMFIANZAPA,FIANZA ) DESP 
					ON A.ID_SOLICITUD=DESP.ID_SOLICITUD
LEFT JOIN  TBD_DATOS_GENERALES B WITH(NOLOCK)  ON B.DOMINIO='FLOWSOL' AND A.ID_FLUJO=CAST(B.COD_VALOR1 AS INT)
LEFT JOIN  TBD_DATOS_GENERALES C WITH(NOLOCK)  ON C.DOMINIO='TIPOSOLVT' AND A.TIPO_SOL=C.COD_VALOR1
LEFT JOIN  TBD_DATOS_GENERALES D WITH(NOLOCK)  ON D.DOMINIO='MEDIOCONT' AND A.COD_MEDIOCONT=D.COD_VALOR1
LEFT JOIN  TBD_DATOS_GENERALES E WITH(NOLOCK)  ON E.DOMINIO='RAZSOCIAL' AND A.COD_EMPRESA=D.PARAMETRO
LEFT JOIN  TBD_DATOS_GENERALES F WITH(NOLOCK)  ON F.DOMINIO='FORMAPAGO' AND COTI.FORMAPAGO=F.PARAMETRO
LEFT JOIN  TBD_DATOS_GENERALES G WITH(NOLOCK)  ON G.DOMINIO='TIPMONEDA' AND COTI.FORMAPAGO=G.COD_VALOR1
LEFT JOIN  TBD_DATOS_GENERALES H WITH(NOLOCK)  ON H.DOMINIO='GARANTIAS' AND COTI.GARANTIA=H.PARAMETRO



























