USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_FILTRO_BANDEJASOLICITUDES
/*================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		13.02.25		Se realza consulta filtros de solicitudes.
	EXEC USP_FILTRO_BANDEJASOLICITUDES
  ================================================================================================*/

  AS
  BEGIN
  	SET NOCOUNT ON;
	--TIPO VENTA
	SELECT COD_VALOR1 AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='TIPOVENTA' AND ESTADO=1 AND HABILITADO=1


	--TIPO SOLICITUD
	SELECT COD_VALOR1 AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='TIPOSOLVT' AND ESTADO=1 AND HABILITADO=1

	--EMPRESA
	SELECT PARAMETRO AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='RAZSOCIAL' AND ESTADO=1 AND HABILITADO=1

	--FORMA DE PAGO
	SELECT PARAMETRO AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='FORMAPAGO' AND ESTADO=1 AND HABILITADO=1

	--MONEDA
	SELECT COD_VALOR1 AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='TIPMONEDA' AND ESTADO=1 AND HABILITADO=1


	--ESTADOS
	SELECT COD_ESTADO AS CODIGO, 
					  ISNULL(NOM_ESTADO,'') DESCRIPCION
					FROM TBM_PROCESOESTADOS WITH(NOLOCK)
					WHERE ID_PROCESO=1 AND HABILITADO=1
					ORDER BY 2



	--GARANTIAS
	SELECT PARAMETRO AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='GARANTIAS' AND ESTADO=1 AND HABILITADO=1

	--FLUJOS
	SELECT COD_VALOR1 AS CODIGO, 
					  ISNULL(VALOR1,'') DESCRIPCION
					FROM TBD_DATOS_GENERALES WITH(NOLOCK)
					WHERE DOMINIO='FLOWSOL' AND ESTADO=1 AND HABILITADO=1

	SET NOCOUNT OFF;
END