USE [DB_AHSECO]
GO


CREATE OR ALTER PROCEDURE [dbo].[USP_BUSCAR_ASIG_CLIE_MANUAL]
/*=================================================================================================
	José A. Peralta 	16.02.25	 busca clientes asignados en la tabla TBM_ASIG_CLIE_MANUAL
	EXEC [USP_BUSCAR_ASIG_CLIE_MANUAL] @ID_EMPLEADO = 1

  =================================================================================================*/
  @ID_CLIENTE	 INT = 0,
  @ID_EMPLEADO	 INT = NULL,
  @RUC VARCHAR(11),
  @NOMBREEMPRESA VARCHAR(200)
  AS
  BEGIN

  IF OBJECT_ID('tempdb..#TMP_ASIG_CLIENTES') IS NOT NULL DROP TABLE #TMP_ASIG_CLIENTES

  DECLARE @Sql VARCHAR(MAX)
  CREATE TABLE #TMP_ASIG_CLIENTES
   (ID_ASIG INT, 
	ID_CLIENTE INT, 
	ELIMINADO BIT,
	ID_ASESOR INT)

	;WITH CTE_1 as ( SELECT 
					ID_ASIG,
					ID_CLIENTE,
					MAX(FEC_REG) FEC_REG,
					ID_ASESOR
					FROM [TBM_ASIG_CLIE_MANUAL]
					GROUP BY ID_CLIENTE,ID_ASESOR,ID_ASIG),
		CTE_2 AS(SELECT
					ID_ASIG
					,ID_CLIENTE
					,ID_ASESOR
					FROM CTE_1),
				CTE_3 AS (SELECT 
							MAX(ID_ASIG) ID_ASIG
							,ID_CLIENTE
							FROM CTE_2 
							GROUP BY ID_CLIENTE)
					INSERT INTO #TMP_ASIG_CLIENTES(ID_ASIG,ID_CLIENTE, ELIMINADO, ID_ASESOR)
					SELECT
						A.ID_ASIG
						,T.ID_CLIENTE
						,T.ELIMINADO
						,ID_ASESOR
					FROM CTE_3 A
					LEFT JOIN [TBM_ASIG_CLIE_MANUAL] T ON T.ID_ASIG = A.ID_ASIG


	SET @Sql = 	'SELECT
					ID																												AS ID
					,CLI.RUCEMPRESA																									AS RUC
					,CLI.NOMEMPRESA																									AS NOMEMPRESA
					,CASE WHEN temp.ELIMINADO != 1 
						THEN CONCAT(ISNULL(NOMBRES,''''),'' '',ISNULL(APELLIDOPATERNO,''''),'' '',ISNULL(APELLIDOMATERNO,''''))				
						ELSE '''' END																									AS ASESOR
					,CLI.ESTADO
					,temp.ID_ASESOR
					,ISNULL(CLI.CATEGORIA,'''') CATEGORIA
					,ISNULL(UBI.NOMDEPARTAMENTO,'''') NOMDEPARTAMENTO
					,ISNULL(UBI.NOMPROVINCIA,'''') NOMPROVINCIA
					,ISNULL(UBI.NOMDISTRITO,'''') NOMDISTRITO
					,ISNULL(CLI.SECTORCLIENTE,'''') SECTORCLIENTE
					,ISNULL(SEDE.ID_SEDE,0) IDSEDE
					,ISNULL(SEDE.NOMSEDE,'''') NOMSEDE
				--	,EMPLE.ID_EMPLEADO
				--	,temp.ELIMINADO 
				FROM [dbo].[TBM_CLIENTES] CLI WITH(NOLOCK)
				LEFT OUTER JOIN #TMP_ASIG_CLIENTES temp on CLI.ID=temp.ID_CLIENTE
				--LEFT JOIN [TBM_ASIG_CLIE_MANUAL] asig on temp.ID_ASIG = asig.ID_ASIG
				LEFT OUTER JOIN [dbo].[TBM_EMPLEADOS] EMPLE ON EMPLE.ID_EMPLEADO = temp.ID_ASESOR
				LEFT OUTER JOIN [dbo].[TBM_UBIGEO] UBI ON CLI.CODUBIGEO=UBI.CODUBIGEO
				LEFT OUTER JOIN [dbo].[TBM_SEDES] SEDE ON CLI.ID=SEDE.ID_CLIENTE AND SEDE.ESTADO=''A'' 
				WHERE  1= 1'
			IF @ID_CLIENTE > 0
				SET @Sql = @Sql + ' AND CLI.ID = '+CAST(@ID_CLIENTE AS VARCHAR(20))
			IF @ID_EMPLEADO > 0
				SET @Sql = @Sql + ' AND EMPLE.ID_EMPLEADO= '+CAST(@ID_EMPLEADO AS VARCHAR(20))+' AND temp.ELIMINADO != 1'
			IF @ID_EMPLEADO = 0 --sin asignar
			SET @Sql = @Sql + ' AND EMPLE.ID_EMPLEADO IS NULL '
			IF(LEN(RTRIM(ISNULL(@RUC,''))) > 0)
			BEGIN
				SET @Sql = @Sql + ' AND CLI.RUCEMPRESA LIKE ''%'+RTRIM(ISNULL(@RUC,''))+'%'''
			END
			IF(LEN(RTRIM(ISNULL(@NOMBREEMPRESA,'')))>0)
			BEGIN
				SET @Sql = @Sql + ' AND CLI.NOMEMPRESA LIKE ''%'+RTRIM(ISNULL(@NOMBREEMPRESA,''))+'%'''
			END

	EXEC(@Sql)

  END
