USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_DESP_SEL_FILTROS]
/*=================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		21/02/2025	Extrae los filtros para la bandeja de despacho.
	EXEC [USP_DESP_SEL_FILTROS] 1,'SGI_VENTA_ASESOR'
  =================================================================================================*/
@ID_DESPACHO BIGINT,
@RolUsuario VARCHAR(25) = ''
AS
BEGIN
SET NOCOUNT ON
	--ComboBox Tipo Doc
	SELECT COD_VALOR1 COD, DESCRIPCION FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'TIPDESP' AND HABILITADO = '1' AND ESTADO = '1'
	--ComboBox Estados
	SELECT COD_ESTADO COD,
	NOM_ESTADO DESCRIPCION 
	FROM TBM_PROCESOESTADOS WITH(NOLOCK) WHERE ID_PROCESO=8
		--Tipo de Documentos:
	SELECT A.COD_VALOR2 CODIGO,
				  A.VALOR2 VALOR 
				  FROM TBD_DATOS_GENERALES A 
				  INNER JOIN TBD_DATOS_GENERALES B 
				  ON B.DOMINIO='RELDOC' AND B.COD_VALOR1=1 AND B.ESTADO=1 AND B.COD_VALOR2=A.COD_VALOR2 
				  AND B.VALOR1=@RolUsuario
	WHERE A.DOMINIO='TIPODOC' AND A.ESTADO=1 AND A.HABILITADO=1 AND A.COD_VALOR1=1
	ORDER BY 1



	SELECT A.ID,A.ID_COTIZACION,A.ID_SOLICITUD,A.ID_WORKFLOW,A.TIPODESP,A.NUMORDEN,  
	ISNULL(CONVERT(varchar,A.FECHAORDEN,103) ,'') FECHAORDEN,
	ISNULL(CONVERT(varchar,A.FECHAMAX,103) ,'') FECHAMAX,
	ISNULL(A.NUMFACTURA,'') NUMFACTURA,
	ISNULL(CONVERT(varchar,A.FECHAFACTURA,103) ,'') FECHAFACTURA,
	ISNULL(A.NUMCONTRATO,'')NUMCONTRATO,
	ISNULL(CONVERT(varchar,A.FEC_CONTRATO,103) ,'') FECCONTRATO,
	ISNULL(A.CALCULO,'') CALCULO,
	ISNULL(A.FIANZA,'') FIANZA,
	ISNULL(A.PRESTPRIN,'') PRESTPRIN,
	ISNULL(A.NUMFIANZAPP,'') NUMFIANZAPP,
	ISNULL(A.PRESTACC,'') PRESTACC,
	ISNULL(A.NUMFIANZAPA,'') NUMFIANZAPA,
	ISNULL(A.PORCDSCTO,0.00) PORCDSCTO,
	ISNULL(A.SUBTOTALVENTA,0.00) SUBTOTALVENTA,
	ISNULL(A.MONTOIGV,0.00) MONTOIGV,
	ISNULL(A.TOTALVENTA,0.00) TOTALVENTA,
	ISNULL(A.ESTADO,'') CODESTADO,
	ISNULL(C.NOM_ESTADO,'') NOMESTADO,
	ISNULL(SOL.ID_WORKFLOW,0) ID_WORKFLOWSOL,
	ISNULL(SOL.ID_FLUJO,0) ID_FLUJO,
	ISNULL(SOL.TIPOVENTA,'') TIPOVENTA,
	ISNULL(SOL.TIPO_SOL,'') TIPOSOL,
	ISNULL(SOL.ESTADO,'') ESTADOSOL
	FROM TBM_SOLDESPACHO A WITH(NOLOCK)
	INNER JOIN TBM_SOLICITUDVENTA SOL WITH(NOLOCK) ON A.ID_SOLICITUD=SOL.ID_SOLICITUD
	LEFT JOIN TBM_PROCESOESTADOS C WITH(NOLOCK) ON A.ESTADO=C.COD_ESTADO AND C.ID_PROCESO=8
	WHERE A.ID = @ID_DESPACHO

	SELECT A.ID_COTDETALLE,B.CODITEM,B.DESCRIPCION,A.CANTIDAD ,A.VALORUNITARIO,A.VALORTOTAL,A.MARGENADICIONAL,A.VVTOTALSIGVCGAN,
	A.MONTODSCTO,A.VVTOTALSIGVDSCTO
	FROM TBD_DESPACHO_COTIZACION A
	INNER JOIN TBD_COTIZACIONVENTA B ON A.ID_COTDETALLE=B.ID 
	WHERE A.ID_SOLDESPACHO= @ID_DESPACHO

	DECLARE @ID_WORKFLOW BIGINT, @CodSolicitud BIGINT

	SELECT @ID_WORKFLOW=ISNULL(ID_WORKFLOW,0),@CodSolicitud=ISNULL(ID_SOLICITUD,0) FROM TBM_SOLDESPACHO WHERE ID=@ID_DESPACHO

		--Documentos OBSERVACIONES:
	EXEC [USP_SEL_OBSERVACIONES] @ID_WORKFLOW

	
	--Seguimiento de flujo de DESPACHOS:
	EXEC [USP_CONSULTA_WORKFLOWLOG] @ID_WORKFLOW

		--Documentos adjuntos:
	SELECT A.COD_DOCUMENTO,
				 A.ID_WORKFLOW,
				 A.COD_TIPODOC,
				 ISNULL(B.VALOR2,'') NOMTIPODOC,
				 A.NOM_DOCUMENTO,
				 A.VER_DOCUMENTO,
				 A.RUTA_DOCUMENTO,
				 A.NOMBRE_USUARIO,
				 A.PERFIL,
				 A.ELIMINADO,
				 ISNULL(A.USR_REG,'') USR_REG,
				 ISNULL(CONVERT(varchar,A.FEC_REG,103) +' '+CONVERT(varchar,A.FEC_REG,8),'')  AS FEC_REG
				 FROM TBM_DOCUMENTO A
				 INNER JOIN TBD_DATOS_GENERALES B ON A.COD_TIPODOC=B.COD_VALOR2 AND B.DOMINIO='TIPODOC'
				 WHERE ID_WORKFLOW=@ID_WORKFLOW
				 AND ELIMINADO = 0
				 ORDER BY A.FEC_REG DESC

	--DESPACHO:
	EXEC [USP_SEL_DESPACHO]  @CodSolicitud, @ID_DESPACHO

	--TECNICOS DESPACHO:
	SELECT A.ID,A.ID_DESPACHO,A.COD_TECNICO,A.NOMBRES,A.APELLIDOPATERNO,A.APELLIDOMATERNO,
	ISNULL(A.DOCUMENTO,'') DOCUMENTO,
	ISNULL(B.DESCRIPCION,'') NOMTIPODOC,
	ISNULL(A.CORREO,'') CORREO,
	ISNULL(A.TELEFONO,'') TELEFONO,
	ISNULL(A.ZONA,'') ZONA,
	ISNULL(A.EMPRESA,'') EMPRESA,
	A.TIPOTECNICO,
	A.ESTADO
	FROM TBD_TECNICODESPACHO A
	LEFT JOIN TBD_DATOS_GENERALES B WITH(NOLOCK) ON A.TIPO_DOCUMENTO=B.PARAMETRO AND B.DOMINIO='GENTDOC'
	WHERE A.ID_DESPACHO IN (SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CodSolicitud)
	AND A.ESTADO = 1



SET NOCOUNT OFF
END
