USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_BANDEJA_DESPACHOS
/*================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		24.02.25		Bandeja de despachos
	EXEC USP_BANDEJA_DESPACHOS 37,'','','',''
  ================================================================================================*/
@ID_SOLICITUD BIGINT,
@TIPODESP VARCHAR(6),
@NUMORDEN VARCHAR(50),
@NUMCONTRATO VARCHAR(50),
@CODESTADO VARCHAR(6)
AS
BEGIN
	SELECT A. ID,A.TIPODESP,
	ISNULL(B.VALOR1,'') TIPODESP_NOM,
	CASE WHEN(A.TIPODESP ='DESP01') THEN A.NUMORDEN ELSE A.NUMCONTRATO END NUM,
	CASE WHEN(A.TIPODESP ='DESP01') THEN ISNULL(CONVERT(varchar,A.FECHAORDEN,103) ,'') ELSE ISNULL(CONVERT(varchar,A.FEC_CONTRATO,103) ,'') END FEC,
	ISNULL(CONVERT(varchar,A.FECHAMAX,103) ,'') FECHAMAX,
	ISNULL(A.ESTADO,'') CODESTADO,
	ISNULL(C.NOM_ESTADO,'') NOMESTADO,
	ISNULL(C.ABREV_ESTADO,'') ABREVESTADO
	FROM TBM_SOLDESPACHO  A WITH(NOLOCK)
	LEFT JOIN TBD_DATOS_GENERALES B WITH(NOLOCK) ON B.DOMINIO='TIPDESP' AND A.TIPODESP=B.COD_VALOR1
	LEFT JOIN TBM_PROCESOESTADOS C WITH(NOLOCK) ON A.ESTADO=C.COD_ESTADO AND C.ID_PROCESO=8
	WHERE A.ID_SOLICITUD=@ID_SOLICITUD
	AND A.TIPODESP = CASE WHEN LEN(RTRIM(@TIPODESP))>0 THEN @TIPODESP ELSE A.TIPODESP END
	AND ISNULL(A.NUMORDEN,'') LIKE '%'+RTRIM(ISNULL(@NUMORDEN,''))+'%'
	AND ISNULL(A.NUMCONTRATO,'') LIKE '%'+RTRIM(ISNULL(@NUMCONTRATO,''))+'%'
	AND A.ESTADO = CASE WHEN LEN(RTRIM(@CODESTADO))>0 THEN @CODESTADO ELSE A.ESTADO END

END

