USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_TBD_DESPACHO_COTIZACION
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		24.02.25	se realiza el mantenimiento de la tabla TBM_SOLDESPACHO
	EXEC USP_MANT_TBD_DESPACHO_COTIZACION
  ==================================================================================================*/
	@IsTipoProceso			CHAR(1)
	,@IsID					BIGINT
	,@IsID_SOLDEPACHO		BIGINT
	,@IsID_COTDETALLE		BIGINT
	,@IsCANTIDAD			INT
	,@IsVALORUNITARIO		DECIMAL(18,9)
	,@IsVALORTOTAL			DECIMAL(18,9)
	,@IsMARGENADICIONAL		DECIMAL(18,9)
	,@IsVVTOTALSIGVCGAN		DECIMAL(18,9)
	,@IsMONTODSCTO			DECIMAL(18,9)
	,@IsVVTOTALSIGVDSCTO	DECIMAL(18,9)
	,@IsUsrEjecuta			VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CODIGO INT, @MSG VARCHAR(200)

	IF(@IsTipoProceso = 'I')
	BEGIN
		INSERT INTO [dbo].[TBD_DESPACHO_COTIZACION](ID_SOLDEPACHO,ID_COTDETALLE,CANTIDAD,VALORUNITARIO,VALORTOTAL,MARGENADICIONAL,VVTOTALSIGVCGAN,MONTODSCTO,VVTOTALSIGVDSCTO,USR_REG,FEC_REG)
		VALUES (@IsID_SOLDEPACHO,@IsID_COTDETALLE,@IsCANTIDAD,@IsVALORUNITARIO,@IsVALORTOTAL,@IsMARGENADICIONAL,@IsVVTOTALSIGVCGAN,@IsMONTODSCTO,@IsVVTOTALSIGVDSCTO,@IsUsrEjecuta,GETDATE())

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Se produjo un problema al realizar la inserción en la tabla [[TBD_DESPACHO_COTIZACION]]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @@IDENTITY
			SET @MSG = 'Se insertó en la tabla [[TBD_DESPACHO_COTIZACION]]' 
		END
	END
	IF(@IsTipoProceso = 'U')
	BEGIN
		UPDATE [dbo].[TBD_DESPACHO_COTIZACION]
		SET	
		ID_SOLDEPACHO		= @IsID_SOLDEPACHO	
		,ID_COTDETALLE		= @IsID_COTDETALLE	
		,CANTIDAD			= @IsCANTIDAD		
		,VALORUNITARIO		= @IsVALORUNITARIO	
		,VALORTOTAL			= @IsVALORTOTAL		
		,MARGENADICIONAL	= @IsMARGENADICIONAL	
		,VVTOTALSIGVCGAN	= @IsVVTOTALSIGVCGAN	
		,MONTODSCTO			= @IsMONTODSCTO		
		,VVTOTALSIGVDSCTO	= @IsVVTOTALSIGVDSCTO
		,USR_MOD			= @IsUsrEjecuta		
		,FEC_MOD			= GETDATE()
		WHERE ID = @IsID

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Ocurrió un error al actualizar la tabla [[TBD_DESPACHO_COTIZACION]]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @IsID
			SET @MSG = 'Se realizó la actualización de la tabla [[TBD_DESPACHO_COTIZACION]]'
		END
	END

	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;

END