USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_TBD_DESPACHO_COTIZACION
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		24.02.25	se realiza el mantenimiento de la tabla [TBD_DESPACHO_COTIZACION]
	EXEC USP_MANT_TBD_DESPACHO_COTIZACION
  ==================================================================================================*/
	@IsTipoProceso			CHAR(1)
	,@IsID					BIGINT
	,@IsID_SOLDEPACHO		BIGINT
	,@IsID_COTDETALLE		BIGINT
	,@IsCANTIDAD			INT
	,@IsINDSTOCK			CHAR(1)
	,@IsVALORUNITARIO		DECIMAL(18,9)
	,@IsVALORTOTAL			DECIMAL(18,9)
	,@IsMARGENADICIONAL		DECIMAL(18,9)
	,@IsVVTOTALSIGVCGAN		DECIMAL(18,9)
	,@IsMONTODSCTO			DECIMAL(18,9)
	,@IsVVTOTALSIGVDSCTO	DECIMAL(18,9)
	,@IsPorcentajeDscto		DECIMAL(18,9)
	,@IsUsrEjecuta			VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CODIGO INT, @MSG VARCHAR(200)

	IF(@IsTipoProceso = 'I')
	BEGIN
		
		SET @IsVALORTOTAL = @IsCANTIDAD * @IsVALORUNITARIO

		IF(ISNULL(@IsMARGENADICIONAL, 0) > 0)
		BEGIN
			SET @IsVVTOTALSIGVCGAN =  @IsVALORTOTAL + (@IsVALORTOTAL * (@IsMARGENADICIONAL / 100))
		END

		IF(ISNULL(@IsPorcentajeDscto,0) > 0)
		BEGIN
			SET @IsMONTODSCTO = ISNULL(@IsVVTOTALSIGVCGAN, @IsVALORTOTAL) * (@IsPorcentajeDscto / 100 ) --Se calcula el monto de descuento.
			SET @IsVVTOTALSIGVDSCTO = CASE WHEN @IsMARGENADICIONAL > 0 THEN @IsVVTOTALSIGVCGAN - @IsMONTODSCTO
										ELSE @IsVALORTOTAL - @IsMONTODSCTO END
		END

		INSERT INTO [dbo].[TBD_DESPACHO_COTIZACION](ID_SOLDESPACHO,ID_COTDETALLE,CANTIDAD, INDSTOCK, VALORUNITARIO,VALORTOTAL,MARGENADICIONAL,VVTOTALSIGVCGAN,MONTODSCTO,VVTOTALSIGVDSCTO,USR_REG,FEC_REG)
		VALUES (@IsID_SOLDEPACHO,@IsID_COTDETALLE,@IsCANTIDAD, @IsINDSTOCK, @IsVALORUNITARIO,@IsVALORTOTAL,@IsMARGENADICIONAL,@IsVVTOTALSIGVCGAN,@IsMONTODSCTO,@IsVVTOTALSIGVDSCTO,@IsUsrEjecuta,GETDATE())

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Se produjo un problema al realizar la inserción en la tabla [[TBD_DESPACHO_COTIZACION]]'
		END
		ELSE
		BEGIN

			SET @CODIGO = @@IDENTITY
			SET @MSG = 'Se insertó en la tabla [[TBD_DESPACHO_COTIZACION]]' 
		END
	END
	IF(@IsTipoProceso = 'U')
	BEGIN
		UPDATE [dbo].[TBD_DESPACHO_COTIZACION]
		SET	
		ID_SOLDESPACHO		= @IsID_SOLDEPACHO	
		,ID_COTDETALLE		= @IsID_COTDETALLE	
		,CANTIDAD			= @IsCANTIDAD		
		,VALORUNITARIO		= @IsVALORUNITARIO	
		,VALORTOTAL			= @IsVALORTOTAL		
		,MARGENADICIONAL	= @IsMARGENADICIONAL	
		,VVTOTALSIGVCGAN	= @IsVVTOTALSIGVCGAN	
		,MONTODSCTO			= @IsMONTODSCTO		
		,VVTOTALSIGVDSCTO	= @IsVVTOTALSIGVDSCTO
		,USR_MOD			= @IsUsrEjecuta		
		,FEC_MOD			= GETDATE()
		WHERE ID = @IsID

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Ocurrió un error al actualizar la tabla [[TBD_DESPACHO_COTIZACION]]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @IsID
			SET @MSG = 'Se realizó la actualización de la tabla [[TBD_DESPACHO_COTIZACION]]'
		END
	END

	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;

END