USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_TBM_SOLDESPACHO
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		24.02.25	se realiza el mantenimiento de la tabla TBM_SOLDESPACHO
	EXEC USP_MANT_TBM_SOLDESPACHO
  ==================================================================================================*/
	@IsTipoProceso			CHAR(1)
	,@IsID					BIGINT
	,@IsID_SOLICITUD		BIGINT
	,@IsID_COTIZACION		BIGINT
	,@IsID_WORKFLOW			BIGINT
	,@IsTIPODESP			VARCHAR(6)
	,@IsNUMORDEN			VARCHAR(50)
	,@IsFECHAORDEN			DATETIME
	,@IsFECHAMAX			DATETIME
	,@IsNUMFACTURA			VARCHAR(100)
	,@IsFECHAFACTURA		DATETIME
	,@IsNUMCONTRATO			VARCHAR(50)
	,@IsFEC_CONTRATO		DATETIME
	,@IsCALCULO				CHAR(1)
	,@IsFIANZA				CHAR(1)
	,@IsPRESTPRIN			CHAR(1)
	,@IsNUMFIANZAPP			VARCHAR(50)
	,@IsPRESTACC			CHAR(1)
	,@IsNUMFIANZAPA			VARCHAR(50)
	,@IsPORCDSCTO			DECIMAL(18,9)
	,@IsSUBTOTALVENTA		DECIMAL(18,9)
	,@IsMONTOIGV			DECIMAL(18,9)
	,@IsTOTALVENTA			DECIMAL(18,9)
	,@IsESTADO				VARCHAR(50)
	,@IsUsrEjecuta			VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CODIGO INT, @MSG VARCHAR(200)

	IF(@IsTipoProceso = 'I')
	BEGIN
		INSERT INTO [dbo].[TBM_SOLDESPACHO](ID_SOLICITUD,ID_COTIZACION,ID_WORKFLOW,TIPODESP,NUMORDEN,FECHAORDEN,FECHAMAX,NUMFACTURA,FECHAFACTURA,NUMCONTRATO,FEC_CONTRATO
									,CALCULO,FIANZA,PRESTPRIN,NUMFIANZAPP,PRESTACC,NUMFIANZAPA,PORCDSCTO,SUBTOTALVENTA,MONTOIGV,TOTALVENTA, ESTADO, USR_REG, FEC_REG)
		VALUES (@IsID_SOLICITUD,@IsID_COTIZACION,@IsID_WORKFLOW,@IsTIPODESP,@IsNUMORDEN,@IsFECHAORDEN , @IsFECHAMAX,@IsNUMFACTURA,@IsFECHAFACTURA,@IsNUMCONTRATO
				, @IsFEC_CONTRATO ,@IsCALCULO,@IsFIANZA,@IsPRESTPRIN,@IsNUMFIANZAPP,@IsPRESTACC,@IsNUMFIANZAPA,@IsPORCDSCTO,@IsSUBTOTALVENTA,@IsMONTOIGV,@IsTOTALVENTA, @IsESTADO, @IsUsrEjecuta, GETDATE())

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Se produjo un problema al realizar la inserción en la tabla [TBM_SOLDESPACHO]'
		END
		ELSE
		BEGIN
			IF (SELECT COUNT(ID) FROM TBM_SOLDESPACHO WHERE ID_COTIZACION = @IsID_COTIZACION) = 1 --Se cambia a estado en proceso de ventas cuando se crea el primer despacho.
			BEGIN
				DECLARE @idWorkFlowLog bigint, @idWorkFlowSol BIGINT

				SELECT @idWorkFlowSol = ID_WORKFLOW FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD = @IsID_SOLICITUD

				UPDATE [dbo].[TBM_SOLICITUDVENTA]
				SET ESTADO = 'PRVT',
					USR_MOD = @IsUsrEjecuta,
					FEC_MOD = GETDATE()
				WHERE ID_SOLICITUD = @IsID_SOLICITUD

				EXEC [USP_CREAR_WORKFLOWLOG] @IdWorkflow = @idWorkFlowSol, @Usuario = @IsUsrEjecuta, @CodEstado = 'PRVT', @UsrRegistro = @IsUsrEjecuta, @IdWorkflowLog = @idWorkFlowLog

			END 

			SET @CODIGO = @@IDENTITY
			SET @MSG = 'Se insertó en la tabla [TBM_SOLDESPACHO]' 

		END
	END
	IF(@IsTipoProceso = 'U')
	BEGIN
		UPDATE [dbo].[TBM_SOLDESPACHO]
		SET	
		TIPODESP		= @IsTIPODESP
		,NUMORDEN		= @IsNUMORDEN		
		,FECHAORDEN		= @IsFECHAORDEN		
		,FECHAMAX		= @IsFECHAMAX		
		,NUMFACTURA		= @IsNUMFACTURA		
		,FECHAFACTURA	= @IsFECHAFACTURA	
		,NUMCONTRATO	= @IsNUMCONTRATO		
		,FEC_CONTRATO	= @IsFEC_CONTRATO	
		,CALCULO		= @IsCALCULO			
		,FIANZA			= @IsFIANZA			
		,PRESTPRIN		= @IsPRESTPRIN		
		,NUMFIANZAPP	= @IsNUMFIANZAPP		
		,PRESTACC		= @IsPRESTACC		
		,NUMFIANZAPA	= @IsNUMFIANZAPA		
		,PORCDSCTO		= @IsPORCDSCTO		
		,SUBTOTALVENTA	= @IsSUBTOTALVENTA	
		,MONTOIGV		= @IsMONTOIGV		
		,TOTALVENTA		= @IsTOTALVENTA		
		,USR_MOD		= @IsUsrEjecuta		
		,FEC_MOD		= GETDATE()
		WHERE ID = @IsID

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Ocurrió un error al actualizar la tabla [TBM_SOLDESPACHO]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @IsID
			SET @MSG = 'Se realizó la actualización de la tabla [TBM_SOLDESPACHO]'
		END
	END

	IF(@IsTipoProceso = 'F')
	BEGIN
		UPDATE [dbo].[TBM_SOLDESPACHO]
		SET	
		ESTADO			= @IsESTADO 
		,USR_MOD		= @IsUsrEjecuta		
		,FEC_MOD		= GETDATE()
		WHERE ID = @IsID 

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Ocurrió un error al actualizar la tabla [TBM_SOLDESPACHO]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @IsID
			SET @MSG = 'Se realizó la actualización de la tabla [TBM_SOLDESPACHO]'
		END

	END 

	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;

END