USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_TBM_SOLDESPACHO
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		24.02.25	se realiza el mantenimiento de la tabla TBM_SOLDESPACHO
	EXEC USP_MANT_TBM_SOLDESPACHO
  ==================================================================================================*/
	@IsTipoProceso			CHAR(1)
	,@IsID					BIGINT
	,@IsID_SOLICITUD		BIGINT
	,@IsID_COTIZACION		BIGINT
	,@IsID_WORKFLOW			BIGINT
	,@IsTIPODESP			VARCHAR(6)
	,@IsNUMORDEN			VARCHAR(50)
	,@IsFECHAORDEN			DATETIME
	,@IsFECHAMAX			DATETIME
	,@IsNUMFACTURA			VARCHAR(100)
	,@IsFECHAFACTURA		DATETIME
	,@IsNUMCONTRATO			VARCHAR(50)
	,@IsFEC_CONTRATO		DATETIME
	,@IsCALCULO				CHAR(1)
	,@IsFIANZA				CHAR(1)
	,@IsPRESTPRIN			CHAR(1)
	,@IsNUMFIANZAPP			VARCHAR(50)
	,@IsPRESTACC			CHAR(1)
	,@IsNUMFIANZAPA			VARCHAR(50)
	,@IsPORCDSCTO			DECIMAL(18,9)
	,@IsSUBTOTALVENTA		DECIMAL(18,9)
	,@IsMONTOIGV			DECIMAL(18,9)
	,@IsTOTALVENTA			DECIMAL(18,9)
	,@IsESTADO				VARCHAR(50)
	,@IsUsrEjecuta			VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CODIGO INT, @MSG VARCHAR(200)

	IF(@IsTipoProceso = 'I')
	BEGIN
		INSERT INTO [dbo].[TBM_SOLDESPACHO](ID_SOLICITUD,ID_COTIZACION,ID_WORKFLOW,TIPODESP,NUMORDEN,FECHAORDEN,FECHAMAX,NUMFACTURA,FECHAFACTURA,NUMCONTRATO,FEC_CONTRATO
									,CALCULO,FIANZA,PRESTPRIN,NUMFIANZAPP,PRESTACC,NUMFIANZAPA,PORCDSCTO,SUBTOTALVENTA,MONTOIGV,TOTALVENTA, ESTADO, USR_REG, FEC_REG)
		VALUES (@IsID_SOLICITUD,@IsID_COTIZACION,@IsID_WORKFLOW,@IsTIPODESP,@IsNUMORDEN,@IsFECHAORDEN , @IsFECHAMAX,@IsNUMFACTURA,@IsFECHAFACTURA,@IsNUMCONTRATO
				, @IsFEC_CONTRATO ,@IsCALCULO,@IsFIANZA,@IsPRESTPRIN,@IsNUMFIANZAPP,@IsPRESTACC,@IsNUMFIANZAPA,@IsPORCDSCTO,@IsSUBTOTALVENTA,@IsMONTOIGV,@IsTOTALVENTA, @IsESTADO, @IsUsrEjecuta, GETDATE())

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Se produjo un problema al realizar la inserción en la tabla [TBM_SOLDESPACHO]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @@IDENTITY
			SET @MSG = 'Se insertó en la tabla [TBM_SOLDESPACHO]' 


			DECLARE @WORKFLOW_SOL BIGINT 
			SELECT @WORKFLOW_SOL=ID_WORKFLOW FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD=@IsID_SOLICITUD

				IF OBJECT_ID('tempdb..#TMP_DESPACHO') IS NOT NULL
					DROP TABLE #TMP_DESPACHO


					CREATE TABLE #TMP_DESPACHO(COD INT, MENSAJE VARCHAR(250))


			-- SE INSERTA A DESPACHOS:
			INSERT INTO #TMP_DESPACHO
			EXEC USP_MANT_DESPACHOVENTAS @TIPO='I',
						@CODSOLICITUD=@IsID_SOLICITUD,
						@CODCOTIZACION=@IsID_COTIZACION,
						@ID_WORKFLOW=@WORKFLOW_SOL,
						@NOMPERFIL = 'VENDEDOR',
						@NUMRODEN='',
						@FECHAORDEN= NULL,
						@FECHAMAX=NULL,
						@STOCK =NULL,
						@FECHAENTREGA =NULL,
						@NUMFACTURA='',
						@NUMGUIAREM='',
						@NUMPEDIDO ='',
						@FECHAINGRESO =NULL,
						@ESTAPROB ='',
						@OBSERVACION =@CODIGO,
						@NUMCONTRATO ='',
						@FECHACONTRATO =NULL,
						@CALCULO ='',
						@FIANZA ='',
						@PRESTPRIN ='',
						@NUMFIANZAPP ='',
						@PRESTACC ='',
						@NUMFIANZAPA ='',
						@TIPODESP ='',
						@USRREG =@IsUsrEjecuta

						SET @CODIGO =(SELECT DISTINCT COD FROM #TMP_DESPACHO )

		END
	END
	IF(@IsTipoProceso = 'U')
	BEGIN
		UPDATE [dbo].[TBM_SOLDESPACHO]
		SET	
		TIPODESP		= @IsTIPODESP
		,NUMORDEN		= @IsNUMORDEN		
		,FECHAORDEN		= @IsFECHAORDEN		
		,FECHAMAX		= @IsFECHAMAX		
		,NUMFACTURA		= @IsNUMFACTURA		
		,FECHAFACTURA	= @IsFECHAFACTURA	
		,NUMCONTRATO	= @IsNUMCONTRATO		
		,FEC_CONTRATO	= @IsFEC_CONTRATO	
		,CALCULO		= @IsCALCULO			
		,FIANZA			= @IsFIANZA			
		,PRESTPRIN		= @IsPRESTPRIN		
		,NUMFIANZAPP	= @IsNUMFIANZAPP		
		,PRESTACC		= @IsPRESTACC		
		,NUMFIANZAPA	= @IsNUMFIANZAPA		
		,PORCDSCTO		= @IsPORCDSCTO		
		,SUBTOTALVENTA	= @IsSUBTOTALVENTA	
		,MONTOIGV		= @IsMONTOIGV		
		,TOTALVENTA		= @IsTOTALVENTA		
		,USR_MOD		= @IsUsrEjecuta		
		,FEC_MOD		= GETDATE()
		WHERE ID = @IsID

		IF(@@ROWCOUNT = 0)
		BEGIN
			SET @CODIGO = 0
			SET @MSG = 'Ocurrió un error al actualizar la tabla [TBM_SOLDESPACHO]'
		END
		ELSE
		BEGIN
			SET @CODIGO = @IsID
			SET @MSG = 'Se realizó la actualización de la tabla [TBM_SOLDESPACHO]'
		END
	END

	SELECT @CODIGO COD ,@MSG MSG
	SET NOCOUNT OFF;

END