USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_DESP_DATOS]
/*=================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Jose A. Peralta	   21/02/2025	Datos principales del despacho.
	EXEC [USP_DESP_DATOS] 1
  =================================================================================================*/
@ID_DESPACHO BIGINT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT A.ID,A.ID_COTIZACION,A.ID_SOLICITUD,A.ID_WORKFLOW,A.TIPODESP,A.NUMORDEN,  
	ISNULL(CONVERT(varchar,A.FECHAORDEN,103) ,'') FECHAORDEN,
	ISNULL(CONVERT(varchar,A.FECHAMAX,103) ,'') FECHAMAX,
	ISNULL(A.NUMFACTURA,'') NUMFACTURA,
	ISNULL(CONVERT(varchar,A.FECHAFACTURA,103) ,'') FECHAFACTURA,
	ISNULL(A.NUMCONTRATO,'')NUMCONTRATO,
	ISNULL(CONVERT(varchar,A.FEC_CONTRATO,103) ,'') FECCONTRATO,
	ISNULL(A.CALCULO,'') CALCULO,
	ISNULL(A.FIANZA,'') FIANZA,
	ISNULL(A.PRESTPRIN,'') PRESTPRIN,
	ISNULL(A.NUMFIANZAPP,'') NUMFIANZAPP,
	ISNULL(A.PRESTACC,'') PRESTACC,
	ISNULL(A.NUMFIANZAPA,'') NUMFIANZAPA,
	ISNULL(A.PORCDSCTO,0.00) PORCDSCTO,
	ISNULL(A.SUBTOTALVENTA,0.00) SUBTOTALVENTA,
	ISNULL(A.MONTOIGV,0.00) MONTOIGV,
	ISNULL(A.TOTALVENTA,0.00) TOTALVENTA,
	ISNULL(A.ESTADO,'') CODESTADO,
	ISNULL(C.NOM_ESTADO,'') NOMESTADO
	FROM TBM_SOLDESPACHO A WITH(NOLOCK)
	LEFT JOIN TBM_PROCESOESTADOS C WITH(NOLOCK) ON A.ESTADO=C.COD_ESTADO AND C.ID_PROCESO=8
	WHERE A.ID = @ID_DESPACHO

	SET NOCOUNT OFF;
END

