USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_TBD_DESPACHO_COTIZACION]
(
	@IsID_DESPACHO		BIGINT 
	,@IsID_COTIZACION	BIGINT
	,@IsID				BIGINT
	,@IsID_COTDETALLE	BIGINT
)
/************************************************************************************************************************************************************
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		25.02.25	Se realiza consulta a la tabla [TBD_DESPACHO_COTIZACION]
	EXEC [USP_SEL_TBD_DESPACHO_COTIZACION] 
************************************************************************************************************************************************************/
AS
BEGIN
	SELECT 
		DESPDETALLE.ID
		,DESPDETALLE.ID_SOLDESPACHO
		,DESPDETALLE.ID_COTDETALLE
		,DESPDETALLE.CANTIDAD
		,DESPDETALLE.VALORUNITARIO
		,DESPDETALLE.VALORTOTAL
		,DESPDETALLE.MARGENADICIONAL
		,DESPDETALLE.VVTOTALSIGVCGAN
		,DESPDETALLE.MONTODSCTO
		,DESPDETALLE.VVTOTALSIGVDSCTO
	FROM [dbo].[TBD_DESPACHO_COTIZACION] AS DESPDETALLE WITH(NOLOCK)
	LEFT JOIN [dbo].[TBD_COTIZACIONVENTA] AS COTDET WITH(NOLOCK) ON DESPDETALLE.ID_COTDETALLE = COTDET.ID
	WHERE DESPDETALLE.ID_COTDETALLE = IIF(@IsID_COTDETALLE = 0, DESPDETALLE.ID_COTDETALLE,  @IsID_COTDETALLE)
	AND  DESPDETALLE.ID_SOLDESPACHO = IIF(@IsID_DESPACHO = 0, DESPDETALLE.ID_SOLDESPACHO, @IsID_DESPACHO)
	AND	 COTDET.ID_COTIZACION = IIF(@IsID_COTIZACION = 0, COTDET.ID_COTIZACION, @IsID_COTIZACION)
	AND  DESPDETALLE.ID = IIF(@IsID = 0, DESPDETALLE.ID, @IsID)

END