USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_INSTAL_SOLICITUDES] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		25.09.24		Realiza el select de la tabla TBM_SOLICITUDVENTA con parametros de búsqueda.
	Diego Bazalar		23.10.24		Se añade la búsqueda por tipo de solicitud CODTIPOSOL, y por ESTADO. 
	exec [USP_SEL_INSTAL_SOLICITUDES] @isIdCliente = 0, @isIdSolicitud = 0, @isOrdenCompra= NULL, @isContrato= NULL
=======================================================================================================*/
	@isIdCliente BIGINT,
	@isIdSolicitud BIGINT,
	@isOrdenCompra VARCHAR(50),
	@isContrato VARCHAR(50)
)
AS
BEGIN
SET NOCOUNT ON

	SELECT
		DESP.ID								AS ID_SOLDESPACHO
		,ISNULL(DESP.NUMORDEN,'')			AS NUMORDEN
		,ISNULL(DESP.NUMCONTRATO,'')		AS NUMCONTRATO
		,DESP.ID_SOLICITUD					AS ID_SOLICITUD
		,ISNULL(SOL.RAZONSOCIAL,'')			AS RAZONSOCIAL
		,ISNULL(SOL.TIPOVENTA,'')			AS COD_TIPOVENTA
		,ISNULL(DATOS.VALOR1,'')			AS TIPOVENTA
		,CONVERT(VARCHAR(10),FECHA_SOL,103)	AS FECHA_SOL
		,ISNULL(TIPOS.VALOR1,'')			AS TIPOSOL
		,ISNULL(SOL.TIPO_SOL,'')			AS CODTIPOSOL
		,ISNULL(DESP.ESTADO,'')				AS ESTADO
		,ISNULL(ESTADOS.NOM_ESTADO,'')		AS NOM_ESTADO
		,ISNULL(SOL.ASESORVENTA,'')			AS USR_REG
	FROM [dbo].[TBM_SOLDESPACHO] AS DESP WITH(NOLOCK)
	LEFT JOIN [dbo].[TBD_DESPACHO_COTIZACION] AS DESPDET WITH(NOLOCK) ON DESPDET.ID_SOLDESPACHO = DESP.ID
	LEFT JOIN [dbo].[TBM_SOLICITUDVENTA] AS SOL WITH(NOLOCK) ON SOL.ID_SOLICITUD = DESP.ID_SOLICITUD
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS DATOS WITH(NOLOCK) ON DATOS.COD_VALOR1 = SOL.TIPOVENTA AND DATOS.DOMINIO = 'TIPOVENTA' AND DATOS.ESTADO = 1 AND DATOS.HABILITADO = 1
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS TIPOS WITH(NOLOCK) ON TIPOS.COD_VALOR1 = SOL.TIPO_SOL AND TIPOS.DOMINIO = 'TIPOSOLVT' AND TIPOS.ESTADO = 1 AND TIPOS.HABILITADO = 1
	LEFT JOIN [dbo].[TBD_COTIZACIONCOSTOS] AS COSTOS WITH(NOLOCK) ON COSTOS.ID_COTDETALLE = DESPDET.ID_COTDETALLE 
	LEFT JOIN [dbo].[TBM_PROCESOESTADOS] AS ESTADOS WITH(NOLOCK) ON ESTADOS.COD_ESTADO = DESP.ESTADO AND ID_PROCESO = 8
	LEFT JOIN [dbo].[TBM_INSTALACION] INSTALL ON INSTALL.ID_DESPACHO = DESP.ID
	WHERE IDCLIENTE = IIF(@isIdCliente = 0, IDCLIENTE, @isIdCliente)
	AND DESP.ID_SOLICITUD = IIF(@isIdSolicitud = 0, DESP.ID_SOLICITUD, @isIdSolicitud)
	AND ISNULL(DESP.NUMORDEN,'') = IIF(@isOrdenCompra IS NULL, ISNULL(DESP.NUMORDEN,''), @isOrdenCompra)
	AND ISNULL(DESP.NUMCONTRATO,'') = IIF(@isContrato IS NULL, ISNULL(DESP.NUMCONTRATO,''), @isContrato)
	AND SOL.ESTADO IN ('PRVT','VTPG')
	AND SOL.TIPO_SOL = 'TSOL05'
	AND COSTOS.CODCOSTO = 'CXCD0002'
	AND INSTALL.NUMREQ IS NULL
	GROUP BY DESP.ID, DESP.NUMORDEN, DESP.NUMCONTRATO, DESP.ID_SOLICITUD, SOL.RAZONSOCIAL, SOL.TIPOVENTA, DATOS.VALOR1, SOL.FECHA_SOL, TIPOS.VALOR1, SOL.TIPO_SOL,DESP.ESTADO, SOL.ASESORVENTA,NOM_ESTADO

SET NOCOUNT OFF
END