USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_MANT_TBM_COTIZACIONVENTA] 
(
	@IsTipoProceso			CHAR(1)
	,@isIdCotizacion		BIGINT
	,@isID_SOLICITUD		BIGINT
	,@isFEC_COTIZACION		DATETIME
	,@isIDCONTACTO			INT
	,@isNOMBRECONTACTO		VARCHAR(150)
	,@isAREACONTACTO		VARCHAR(100)
	,@isTELEFONOCONTACTO	VARCHAR(50)
	,@isEMAILCONTACTO		VARCHAR(35)
	,@isPLAZOENTREGA		INT
	,@isFORMAPAGO			VARCHAR(10)
	,@isMONEDA				VARCHAR(10)
	,@isVIGENCIA			VARCHAR(50)
	,@isGARANTIA			VARCHAR(10)
	,@isOBSERVACION			VARCHAR(200)
	,@isPORCDSCTO			DECIMAL(18,9)
	,@isINDDSCTOREQAPROB	CHAR(1)
	,@isINDDSCTOAPROB		CHAR(1)
	,@isESTADO				CHAR(1)
	,@isUsrEjecuta			VARCHAR(50)
	,@isFecEjecucion		DATETIME
)
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		25.09.24		Realiza el mantenimiento de la tabla TBM_COTIZACIONVENTA con parametros.
  =======================================================================================================*/
AS
BEGIN
	DECLARE @NUM INT;
	DECLARE @CODIGO BIGINT, @MSG VARCHAR(20), @IdCotDetalle BIGINT, @isPORCDSCTO_ACTUAL DECIMAL(18,9);
	DECLARE CotDet_Cursor CURSOR
	FOR
	SELECT ID FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION = @isIdCotizacion;
	SET NOCOUNT ON;

	SELECT TOP 1 @isPORCDSCTO_ACTUAL = PORCDSCTO FROM TBM_COTIZACIONVENTA WHERE ID_COTIZACION = @isIdCotizacion;

	IF (@IsTipoProceso = 'I')
	BEGIN
		INSERT INTO TBM_COTIZACIONVENTA
		(ID_SOLICITUD,FEC_COTIZACION,IDCONTACTO,NOMBRECONTACTO,AREACONTACTO,TELEFONOCONTACTO,EMAILCONTACTO,PLAZOENTREGA,
		FORMAPAGO,MONEDA,VIGENCIA,GARANTIA,OBSERVACION,PORCDSCTO,INDDSCTOREQAPROB,INDDSCTOAPROB,ESTADO,USR_REG,FEC_REG)
		VALUES
		(@isID_SOLICITUD,ISNULL(@isFEC_COTIZACION,GETDATE()),@isIDCONTACTO,@isNOMBRECONTACTO,@isAREACONTACTO,@isTELEFONOCONTACTO,@isEMAILCONTACTO,@isPLAZOENTREGA,
		@isFORMAPAGO,@isMONEDA,@isVIGENCIA,@isGARANTIA,@isOBSERVACION,@isPORCDSCTO,@isINDDSCTOREQAPROB,@isINDDSCTOAPROB,@isESTADO,@isUsrEjecuta,@isFecEjecucion)

		SET  @CODIGO = @@IDENTITY
		SET @MSG ='Registro Insertado con éxito'
	END

	IF(@IsTipoProceso = 'U')
	BEGIN

		UPDATE TBM_COTIZACIONVENTA
		SET ID_SOLICITUD		 = @isID_SOLICITUD
			,FEC_COTIZACION		 = ISNULL(@isFEC_COTIZACION,GETDATE())
			,IDCONTACTO			 = @isIDCONTACTO
			,NOMBRECONTACTO		 = @isNOMBRECONTACTO
			,AREACONTACTO		 = @isAREACONTACTO
			,TELEFONOCONTACTO	 = @isTELEFONOCONTACTO
			,EMAILCONTACTO		 = @isEMAILCONTACTO
			,PLAZOENTREGA		 = @isPLAZOENTREGA
			,FORMAPAGO			 = @isFORMAPAGO
			,MONEDA				 = @isMONEDA
			,VIGENCIA			 = @isVIGENCIA
			,GARANTIA			 = @isGARANTIA
			,OBSERVACION		 = @isOBSERVACION
			,PORCDSCTO			 = @isPORCDSCTO
			,INDDSCTOREQAPROB	 = @isINDDSCTOREQAPROB
			,INDDSCTOAPROB		 = @isINDDSCTOAPROB
			,ESTADO				 = @isESTADO
			,USR_MOD			 = @isUsrEjecuta
			,FEC_MOD			 = @isFecEjecucion
		WHERE ID_COTIZACION = @isIdCotizacion

		OPEN CotDet_Cursor;

		FETCH NEXT FROM CotDet_Cursor
		INTO @IdCotDetalle

		WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC USP_UPD_TOTALIZAR_COTDET @IdCotDetalle;				
			FETCH NEXT FROM CotDet_Cursor
			INTO @IdCotDetalle
		END;

		CLOSE CotDet_Cursor;

		SET  @CODIGO = @isIdCotizacion
		SET @MSG ='Registro Insertado con éxito'
	END

	SELECT @CODIGO COD, @MSG MSG
	SET NOCOUNT OFF;

END