USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_MANT_TBD_COTIZACIONVENTA] 
(
	 @isTipoProceso			CHAR(1)
	,@isID					BIGINT
	,@isID_COTIZACION		BIGINT
	,@isNROITEM				INT
	,@isTIPOITEM			VARCHAR(5)
	,@isCODITEM				VARCHAR(35)
	,@isDESCRIPCION			VARCHAR(200)
	,@isDESCRIPADIC			VARCHAR(1000)
	,@isMARCA				VARCHAR(60)
	,@isMODELO				VARCHAR(60)
	,@isCODFAMILIA			VARCHAR(12)
	,@isCODALMACEN			VARCHAR(4)
	,@isSTOCK				INT
	,@isINDSTOCK			CHAR(1)
	,@isUNDMED				VARCHAR(3)
	,@isCANTIDAD			INT
	,@isCOSTOFOB			VARCHAR(50)
	,@isVVENTAUNI			DECIMAL(18,9)
	,@isPORCGANANCIA		DECIMAL(18,9)
	,@isELIMINADO			CHAR(1)
	,@isUsrEjecuta			VARCHAR(50)
	,@IsITEMPADRE			CHAR(1)
	,@isFecEjecuta			DATETIME
)
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		27.09.24		Realiza el mantenimiento de la tabla TBD_COTIZACIONVENTA con parametros.
  =======================================================================================================*/
AS
BEGIN

	DECLARE @CANTREG INT
	DECLARE @CANTREGVALORIZADOS INT
	DECLARE @CODDETALLE INT, @MSG VARCHAR(20)
	DECLARE @NUM INT
	DECLARE @ID_SOLICITUD INT
	DECLARE @TIPO_SOL VARCHAR(10)
	
	SET NOCOUNT ON;

	IF (@isTipoProceso = 'I')
	BEGIN

		INSERT INTO TBD_COTIZACIONVENTA
		(ID_COTIZACION,NROITEM,TIPOITEM,CODITEM,DESCRIPCION,DESCRIPADIC,MARCA,MODELO,CODFAMILIA ,CODALMACEN,STOCK,INDSTOCK,UNDMED,CANTIDAD,COSTOFOB,VVENTAUNI,PORCGANANCIA,ELIMINADO,USR_REG,FEC_REG)
		VALUES
		(@isID_COTIZACION,@isNROITEM,@isTIPOITEM,@isCODITEM,@isDESCRIPCION,@isDESCRIPADIC,@isMARCA, @isMODELO,@isCODFAMILIA, @isCODALMACEN,@isSTOCK,@isINDSTOCK,@isUNDMED,@isCANTIDAD,@isCOSTOFOB,@isVVENTAUNI,@isPORCGANANCIA,@isELIMINADO,@isUsrEjecuta,@isFecEjecuta)
		SET  @CODDETALLE = @@IDENTITY
		SET @MSG ='Registro Insertado con éxito'
		
		EXEC USP_UPD_TOTALIZAR_COTDET @CODDETALLE

	END

	IF(@isTipoProceso = 'U')
	BEGIN

		UPDATE TBD_COTIZACIONVENTA
		SET 
		NROITEM = @isNROITEM
		,TIPOITEM = @isTIPOITEM
		,CODITEM = @isCODITEM
		,DESCRIPCION = @isDESCRIPCION
		,DESCRIPADIC = @isDESCRIPADIC		
		,STOCK = @isSTOCK
		,INDSTOCK = @isINDSTOCK
		,UNDMED = @isUNDMED
		,CANTIDAD = @isCANTIDAD			
		,COSTOFOB = @isCOSTOFOB
		,VVENTAUNI = @isVVENTAUNI
		,PORCGANANCIA = @isPORCGANANCIA
		,USR_MOD = @isUsrEjecuta		
		,FEC_MOD = @isFecEjecuta
		WHERE ID = @isID
		
		SELECT @CANTREG = COUNT(1) FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION = @isID_COTIZACION;

		SELECT @ID_SOLICITUD = ID_SOLICITUD FROM TBM_COTIZACIONVENTA WHERE ID_COTIZACION = @isID_COTIZACION;
		
		SELECT @TIPO_SOL = TIPO_SOL FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD = @ID_SOLICITUD;

		SELECT @CANTREGVALORIZADOS = COUNT(1) FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION = @isID_COTIZACION AND TIPOITEM = 'PRO';

		--Se valida si se termino la valorizacion por parte de los Jefes
		--pero REPUESTOS no usan COSTO FOB
		IF TRIM(@TIPO_SOL) IN ('TSOL02','TSOL03')  BEGIN
			SELECT @NUM = SUM(CASE WHEN ISNULL(VVENTAUNI,0) > 0 THEN 1 ELSE 0 END) 
			FROM TBD_COTIZACIONVENTA CD
			INNER JOIN TBM_COTIZACIONVENTA C ON CD.ID_COTIZACION = C.ID_COTIZACION
			WHERE CD.ID_COTIZACION = @isID_COTIZACION AND CD.TIPOITEM = 'PRO';
		END
		ELSE BEGIN
			SELECT @NUM = SUM(CASE ISNULL(CD.INDSTOCK,'') 
								WHEN 'S' THEN (CASE WHEN ISNULL(VVENTAUNI,0) > 0 THEN 1 ELSE 0 END) 
								ELSE (CASE WHEN LEN(ISNULL(COSTOFOB,'')) > 0 AND ISNULL(VVENTAUNI,0) > 0 THEN 1 ELSE 0 END) 
								END) 
			FROM TBD_COTIZACIONVENTA CD
			INNER JOIN TBM_COTIZACIONVENTA C ON CD.ID_COTIZACION = C.ID_COTIZACION
			WHERE CD.ID_COTIZACION = @isID_COTIZACION AND CD.TIPOITEM = 'PRO';
		END

		IF @NUM = 0 BEGIN
			UPDATE TBM_COTIZACIONVENTA SET INDVALORIZADO = NULL WHERE ID_COTIZACION = @isID_COTIZACION
		END
		ELSE BEGIN
			
			IF @CANTREGVALORIZADOS > @NUM BEGIN
				UPDATE TBM_COTIZACIONVENTA SET INDVALORIZADO = 'N' WHERE ID_COTIZACION = @isID_COTIZACION
			END
			ELSE BEGIN
				UPDATE TBM_COTIZACIONVENTA SET INDVALORIZADO = 'S' WHERE ID_COTIZACION = @isID_COTIZACION
			END
			
		END

		EXEC USP_UPD_TOTALIZAR_COTDET @isID

		SET @CODDETALLE = @isID
		SET @MSG ='Registro Actualizado con éxito'

	END

	IF(@isTipoProceso = 'D')
	BEGIN
		
		IF (@IsITEMPADRE = 'S')
		BEGIN
			UPDATE TBD_COTIZACIONVENTA
			SET 
			ELIMINADO = @isELIMINADO
			,USR_MOD = @isUsrEjecuta		
			,FEC_MOD = @isFecEjecuta
			WHERE NROITEM IN (SELECT NROITEM FROM TBD_COTIZACIONVENTA WHERE ID = @isID) AND ID_COTIZACION = @isID_COTIZACION

			--DELETE FROM TBD_COTIZACIONVENTA WHERE ID = @isID
			SET @CODDETALLE = @isID
			SET @MSG ='Registro eliminado con éxito'
		END
		ELSE
		BEGIN
			UPDATE TBD_COTIZACIONVENTA
			SET 
			ELIMINADO = @isELIMINADO
			,USR_MOD = @isUsrEjecuta		
			,FEC_MOD = @isFecEjecuta
			WHERE ID = @isID

			--DELETE FROM TBD_COTIZACIONVENTA WHERE ID = @isID
			SET @CODDETALLE = @isID
			SET @MSG ='Registro eliminado con éxito'
		END
	END

	SELECT @CODDETALLE COD, @MSG MSG
	SET NOCOUNT OFF;
END