USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_COTIZACIONVENTADETALLE]
/*==========================================================================================
	Nombre			Fecha		Descripción
	Samuel Gómez	16/10/24	Creación de Listado de Detalle y Despacho de Cotización
	EXEC [USP_SEL_COTIZACIONVENTADETALLE] @pId_Cotizacion = 10033
  ==========================================================================================*/
@pId_Cotizacion INT
AS
BEGIN

	IF OBJECT_ID('tempdb..#tmpConteo') IS NOT NULL
		DROP TABLE #tmpConteo

	;WITH CTE_1 AS (
		SELECT 
			ROW_NUMBER() OVER(ORDER BY NROITEM) CONT
			,NROITEM
			,ID_COTIZACION
		FROM TBD_COTIZACIONVENTA
		WHERE ID_COTIZACION = @pId_Cotizacion AND ELIMINADO != 'S'
		GROUP BY NROITEM, ID_COTIZACION
	)
	SELECT 
		CONCAT(CONT,'.',ROW_NUMBER() OVER( PARTITION BY [cte].[NROITEM] ORDER BY [cte].NROITEM, [coti].FEC_REG)) CONTADOR
		,coti.ID
	INTO #tmpConteo
	FROM CTE_1 cte
	INNER JOIN TBD_COTIZACIONVENTA coti ON coti.NROITEM = cte.NROITEM AND coti.ID_COTIZACION = cte.ID_COTIZACION
	WHERE ELIMINADO != 'S'
	ORDER BY coti.NROITEM, coti.FEC_REG, coti.ID, CONT


	SELECT
	CD1.ID,
	CD1.ID_COTIZACION,
	cont.CONTADOR,
	CD1.NROITEM,
	CD1.TIPOITEM,
	CD1.CODITEM,
	CD1.DESCRIPCION,
	CD1.DESCRIPADIC,
	CD1.STOCK,
	CD1.INDSTOCK,
	CD1.UNDMED,
	CD1.CANTIDAD,
	ISNULL(CD1.COSTOFOB,'' ) COSTOFOB,
	CD1.VVENTAUNI,
	CD1.VVTOTALSIGV,
	CD1.PORCGANANCIA,
	CD1.VVTOTALSIGVCGAN,
	CD1.MONTODSCTO,
	CD1.VVTOTALSIGVDSCTO,
	CD1.MARCA,
	CD1.MODELO,
	CD1.CODFAMILIA,
	CD1.CODALMACEN,
	ISNULL(CD1.MARGENUTILIDAD,'') MARGENUTILIDAD,
	ISNULL(CD1.CODTRANSPORTE,0) CODTRANSPORTE,
	ISNULL(D.VALOR1,'') NOMTRANSPORTE,
	CDD1.ID AS ID_COTDETDESPACHO,
	CDD1.INDINFOVIDEO,
	CDD1.INDINFOMANUAL,
	CDD1.INDINSTALACION,
	CDD1.INDCAPACITACION,
	CDD1.INDGARANADIC,
	CDD1.CODGARANADIC,
	CDD1.INDMANTPREVENT,
	CDD1.INDCALIB,
	CDD1.DIMENSIONES,
	CDD1.INDCOMPRALOCAL,
	CDD1.INDREQPLACA,
	CDD1.INDFLETE,
	CDD1.OBSCLIENTE,
	CDD1.OBSDESPACHO,
	CDD1.MTOTOTALCOSTO,
	CDD1.INDFIANZA,
	CDD1.NUMFIANZA,
	CDD1.MONTOPPRINC,
	CDD1.MONTOPACCE
	FROM DBO.TBD_COTIZACIONVENTA CD1
	LEFT JOIN DBO.TBM_COTDET_DESPACHO CDD1 ON CDD1.ID_COTDETALLE = CD1.ID 
	LEFT JOIN #tmpConteo cont on cont.ID = CD1.ID
	LEFT JOIN TBD_DATOS_GENERALES D WITH(NOLOCK) ON D.DOMINIO='TIPTRAN'  AND CD1.CODTRANSPORTE=D.COD_VALOR1
	WHERE (@pId_Cotizacion IS NULL OR ID_COTIZACION = @pId_Cotizacion) AND ISNULL(CD1.ELIMINADO,'N') != 'S'
	ORDER BY NROITEM, CD1.FEC_REG;

END