USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_COTIZACIONVENTADETALLE]
/*==========================================================================================
	Nombre			Fecha		Descripción
	Samuel Gómez	16/10/24	Creación de Listado de Detalle y Despacho de Cotización
  ==========================================================================================*/
@pId_Cotizacion INT
AS
BEGIN

	SELECT
	CD1.ID,
	CD1.ID_COTIZACION,
	CD1.NROITEM,
	CD1.TIPOITEM,
	CD1.CODITEM,
	CD1.DESCRIPCION,
	CD1.DESCRIPADIC,
	CD1.STOCK,
	CD1.INDSTOCK,
	CD1.UNDMED,
	CD1.CANTIDAD,
	CD1.COSTOFOB,
	CD1.VVENTAUNI,
	CD1.VVTOTALSIGV,
	CD1.PORCGANANCIA,
	CD1.VVTOTALSIGVCGAN,
	CD1.MONTODSCTO,
	CD1.VVTOTALSIGVDSCTO,
	CDD1.ID AS ID_COTDETDESPACHO,
	CDD1.INDINFOVIDEO,
	CDD1.INDINFOMANUAL,
	CDD1.INDINSTACAPA,
	CDD1.INDGARANADIC,
	CDD1.NMESGARANADIC,
	CDD1.INDMANTPREVENT,
	CDD1.DIMENSIONES,
	CDD1.INDCOMPRALOCAL,
	CDD1.OBSCLIENTE,
	CDD1.INDREQPLACA,
	CDD1.OBSDESPACHO,
	CDD1.MTOTOTALCOSTO,
	CDD1.INDFIANZA,
	CDD1.NUMFIANZA,
	CDD1.MONTOPPRINC,
	CDD1.MONTOPACCE
	FROM DBO.TBD_COTIZACIONVENTA CD1
	LEFT JOIN DBO.TBM_COTDET_DESPACHO CDD1 ON CDD1.ID_COTDETALLE = CD1.ID 
	WHERE (@pId_Cotizacion IS NULL OR ID_COTIZACION = @pId_Cotizacion);

END