USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_CREAR_COTIZACIONCLIENTE
/*===============================================================================================
	NOMBRE:					FECHA:			DESCRIPCIÓN:
	José A. Peralta		24.10.24			Se realiza la construcción del formato de cotización a entregar al cliente.
	EXEC USP_CREAR_COTIZACIONCLIENTE 7
  ===============================================================================================*/
@COD_COTIZACION BIGINT
AS
BEGIN

SET NOCOUNT ON;
	
	DECLARE @COD_SOLICITUD BIGINT,@RUTAIMAGEN VARCHAR(200),@NUM_COTIZACION VARCHAR(9),@ENCABEZADO VARCHAR(MAX),
					@RUC VARCHAR(12),@RAZONSOCIAL VARCHAR(200),@NOMBRECONTACTO VARCHAR(150),@AREACONTACTO VARCHAR(100),
				   @TELEFONOCONTACTO VARCHAR(50),@EMAILCONTACTO VARCHAR(75),@PLAZOENTREGA VARCHAR(100),@FORMAPAGO VARCHAR(100),
				   @MONEDA VARCHAR(50),@VIGENCIA VARCHAR(50),@GARANTIA VARCHAR(100),@OBSERVACION VARCHAR(100),
				   @CONTRATO VARCHAR(MAX),@USUARIO VARCHAR(50),@NUMDOCUSU VARCHAR(12),@NOMBREVENDEDOR VARCHAR(200),
				   @TELEFONOVENDEDOR VARCHAR(75),@CORREOVENDEDOR VARCHAR(75),@PIE VARCHAR(MAX),@SUBTOTAL VARCHAR(25),
				   @SIMBOLO_MONEDA VARCHAR(3),@MONTOIGV VARCHAR(25),@TOTALVENTA VARCHAR(25),@RUC_EMPRESA VARCHAR(15)

	IF OBJECT_ID('tempdb..#TMP_LISTAPREV') IS NOT NULL
		DROP TABLE #TMP_LISTAPREV

	CREATE TABLE #TMP_LISTAPREV(
		ID INT IDENTITY(1,1),
		CANT INT,
		NOMPRODUCTO VARCHAR(250),
		CICLO VARCHAR(50)
	)

	IF OBJECT_ID('tempdb..#TMP_LISTACALIB') IS NOT NULL
		DROP TABLE #TMP_LISTACALIB

	CREATE TABLE #TMP_LISTACALIB(
		ID INT IDENTITY(1,1),
		CANT INT,
		NOMPRODUCTO VARCHAR(250)
	)


	SELECT @COD_SOLICITUD=A.ID_SOLICITUD,
	@NOMBRECONTACTO =A.NOMBRECONTACTO,
	@AREACONTACTO = A.AREACONTACTO,
	@TELEFONOCONTACTO = A.TELEFONOCONTACTO,
	@EMAILCONTACTO = A.EMAILCONTACTO,
	@PLAZOENTREGA = A.PLAZOENTREGA,
	@FORMAPAGO = ISNULL(B.VALOR1,''),
	@MONEDA = ISNULL(C.VALOR1,''),
	@VIGENCIA = A.VIGENCIA,
	@GARANTIA = ISNULL(D.VALOR1,''),
	@USUARIO = UPPER(RTRIM(A.USR_REG)),
	@SUBTOTAL = CONVERT(VARCHAR,CAST(ISNULL(A.SUBTOTALVENTA ,0.00) AS MONEY) ,1) ,

	@MONTOIGV =CONVERT(VARCHAR,CAST(ISNULL(A.MONTOIGV ,0.00) AS MONEY) ,1) ,
	@TOTALVENTA=CONVERT(VARCHAR,CAST(ISNULL(A.TOTALVENTA ,0.00) AS MONEY) ,1) ,
	@SIMBOLO_MONEDA = ISNULL(C.COD_VALOR3,''),
	@OBSERVACION = ISNULL(A.OBSERVACION,'')
	FROM TBM_COTIZACIONVENTA A WITH(NOLOCK)
		LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='FORMAPAGO' AND A.FORMAPAGO=B.PARAMETRO 
		LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND A.MONEDA=C.COD_VALOR1 
		LEFT JOIN TBD_DATOS_GENERALES D ON D.DOMINIO='GARANTIAS' AND A.GARANTIA=D.PARAMETRO 
	WHERE A.ID_COTIZACION=@COD_COTIZACION;


	SELECT @RUTAIMAGEN=ISNULL(B.COD_VALOR1,'')+'.png', 
				  @RUC=A.RUC,
				  @RAZONSOCIAL=A.RAZONSOCIAL,
				  @RUC_EMPRESA=ISNULL(B.VALOR2,'')
	FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
	LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='RAZSOCIAL' AND A.COD_EMPRESA=B.PARAMETRO 
	WHERE A.ID_SOLICITUD=@COD_SOLICITUD;

	SELECT @NUMDOCUSU=NUM_DOC FROM TBM_SEGURIDAD_USUARIO WITH(NOLOCK) WHERE RTRIM(UPPER(USUARIO))=RTRIM(@USUARIO);
	


	SELECT TOP 1 
	@NOMBREVENDEDOR = RTRIM(ISNULL(NOMBRES,''))+ ' '+RTRIM(ISNULL(APELLIDOPATERNO,''))+' '+RTRIM(ISNULL(APELLIDOMATERNO,'')),
	@TELEFONOVENDEDOR = ISNULL(TELEFONO,''),
	@CORREOVENDEDOR = ISNULL(EMAIL,'')
	FROM TBM_EMPLEADOS WITH(NOLOCK) 
	WHERE RTRIM(NUMDOCUMENTO)=RTRIM(@NUMDOCUSU)
	ORDER BY FEC_REG DESC;


	SET  @NUM_COTIZACION= 'PC'+RIGHT('0000000'+CAST(@COD_COTIZACION AS VARCHAR),7)

	SET @ENCABEZADO='R.U.C.: '+RTRIM(@RUC_EMPRESA)+  '\r\n' 
	SET @ENCABEZADO=@ENCABEZADO+'Av. Máximo Abril N°524 Urb. Santa Beatriz'+  '\r\n' 
	SET @ENCABEZADO=@ENCABEZADO+'Jesús María – Lima'+  '\r\n' 
	SET @ENCABEZADO=@ENCABEZADO+'Sucursal: Av. Arenales N°500 – Jesús María - Lima'+  '\r\n' 
	SET @ENCABEZADO=@ENCABEZADO+'Teléfono: (511) 433 7227 / 433 6372'+  '\r\n' 
	SET @ENCABEZADO=@ENCABEZADO+'Email: ventas@ahsecoperu.com / www.ahsecoperu.com.pe';

	--CANTIDAD DE PREVENTIVOS:
	INSERT INTO #TMP_LISTAPREV
	SELECT  A.CANTPREVENTIVO,B.DESCRIPCION,ISNULL(C.DESCRIPCION,'') from TBD_COTIZACIONCOSTOS A
	INNER JOIN TBD_COTIZACIONVENTA B ON A.ID_COTDETALLE=B.ID
	LEFT JOIN TBD_DATOS_GENERALES C  ON  C.DOMINIO='CICLOPREV' AND A.CODCICLOPREVENT=C.PARAMETRO
	WHERE B.ID_COTIZACION = @COD_COTIZACION AND A.CODCOSTO='CXCD0006'
	AND A.CANTPREVENTIVO > 0

	--CANTIDAD DE CALIBRACIONES:
	INSERT INTO #TMP_LISTACALIB
	SELECT  A.CANTPREVENTIVO,B.DESCRIPCION from TBD_COTIZACIONCOSTOS A
	INNER JOIN TBD_COTIZACIONVENTA B ON A.ID_COTDETALLE=B.ID
	WHERE B.ID_COTIZACION = @COD_COTIZACION AND A.CODCOSTO='CXCD0007'
			AND A.CANTCOSTO > 0


	DECLARE @TOTAL INT,@X INT,@CANT INT,@DESC VARCHAR(250),@CICLO VARCHAR(50)
	SELECT @TOTAL =COUNT(1),@X=1 FROM #TMP_LISTAPREV

	DECLARE @TOTAL2 INT,@X2 INT,@CANT2 INT,@DESC2 VARCHAR(250)
	SELECT @TOTAL2 =COUNT(1),@X2=1 FROM #TMP_LISTACALIB
	SELECT @TOTAL2= ISNULL(@TOTAL2,0)


	SET @CONTRATO='*INSTALACION Y VERIFICACIÓN OPERACIONAL:'+  '\r\n' 
	SET @CONTRATO= @CONTRATO+'La empresa se responsabiliza por la instalación y puesta en marcha del equipo ofertado. '+  '\r\n' 
	IF(@TOTAL2 > 0)
	BEGIN
			WHILE(@X2 <=@TOTAL2)
			BEGIN
					SELECT @CANT2=ISNULL(CANT,0),@DESC2=ISNULL(NOMPRODUCTO,'') FROM  #TMP_LISTACALIB WHERE ID = @X2;
					SET @CONTRATO= @CONTRATO+'Se incluye :'+ ' '+CAST(@CANT2 AS VARCHAR)+' calibracion(es) para el producto '  + RTRIM(@DESC2) +', acreditadas ante INACAL, bajo la norma ISO/IEC 17025' + '\r\n' 
					SET @X2 = @X2+1
			END
	END
	SET @CONTRATO= @CONTRATO+  '\r\n' +  '\r\n' 
	SET @CONTRATO= @CONTRATO+'**ASESORÍA, CAPACITACIÓN Y POST VENTA:'+  '\r\n' 
	SET @CONTRATO= @CONTRATO+'Brindar la respectiva capacitación al personal usuario designado que se encargará de la operación del equipo ofrecido.'+  '\r\n'  +  '\r\n' 
	IF(LEN(RTRIM(@GARANTIA))> 0)
	BEGIN
		SET @CONTRATO= @CONTRATO+'***GARANTÍA Y SOPORTE TÉCNICO:'+  '\r\n' 
		SET @CONTRATO= @CONTRATO+'La empresa ofrece una Garantía Comercial de '+RTRIM(@GARANTIA)+  '\r\n' 
	END
	IF(@TOTAL > 0)
	BEGIN
		SET @CONTRATO= @CONTRATO+'Mantenimiento Preventivo dentro de la Garantía Comercial: '+  '\r\n' +  '\r\n' 
		WHILE(@X <=@TOTAL)
		BEGIN
			SELECT @CANT=ISNULL(CANT,0),@DESC=ISNULL(NOMPRODUCTO,''),@CICLO=ISNULL(CICLO,'') FROM  #TMP_LISTAPREV WHERE ID = @X;
					SET @CONTRATO= @CONTRATO+' '+RTRIM(@DESC) + ' '+CAST(@CANT AS VARCHAR)+' mantenimiento(s) '  + RTRIM(@CICLO) + '\r\n' 
			SET @X = @X+1
		END
	END
	SET @CONTRATO= @CONTRATO+  '\r\n' +  '\r\n' 
	SET @CONTRATO= @CONTRATO+'“AHSECO PERÚ SA Garantiza el stock de Repuestos Originales, así como Servicio Técnico y de Mantenimiento”'

	SET @PIE='El envío de los productos es de manera gratuita a partir de Facturas de US$ 200.00, solo en ciudad de Lima y para clientes finales.'+  '\r\n' 
	SET @PIE=@PIE+'El equipo se entrega en sus instalaciones en un primer piso, no incluye traslado interno al punto de instalación, el usuario deberá contar con personal para ubicación final del equipo sobre la mesa de trabajo.'+  '\r\n' 
	SET @PIE=@PIE+'Los envíos a provincia por intermedio de agencia corren a cuenta y riesgo del cliente, AHSECO PERÚ S.A. no se hace responsable cualquier problema que resulte del envío.'



	--ACTIVIDADES DE SERVICIOS:
	IF OBJECT_ID('tempdb..#TMP_LISTAACT') IS NOT NULL
		DROP TABLE #TMP_LISTAACT

	CREATE TABLE #TMP_LISTAACT(
		ID INT IDENTITY(1,1),
		CODDETALLE INT,
		DESCRIPCION VARCHAR(250)
	)

	IF OBJECT_ID('tempdb..#TMP_LISTAACTFINAL') IS NOT NULL
		DROP TABLE #TMP_LISTAACTFINAL

	CREATE TABLE #TMP_LISTAACTFINAL(
		ID INT IDENTITY(1,1),
		CODDETALLE INT,
		DESCRIPCION VARCHAR(8000)
	)

	IF OBJECT_ID('tempdb..#TMP_LISTADET') IS NOT NULL
		DROP TABLE #TMP_LISTADET

	CREATE TABLE #TMP_LISTADET(
		ID INT IDENTITY(1,1),
		CODDETALLE INT
	)

	DECLARE @TOTAL_DET INT,@I_X INT,@COD_DET BIGINT ,@I_X2 BIGINT,@TOTAL_DET2 INT,@ACTIVIDAD VARCHAR(8000)

	INSERT INTO #TMP_LISTADET
	SELECT ID FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION =@COD_COTIZACION

	SELECT @TOTAL_DET=COUNT(1),@I_X=1  FROM  #TMP_LISTADET
	

	WHILE(@I_X <=@TOTAL_DET)
	BEGIN
		
		SELECT @COD_DET=CODDETALLE FROM #TMP_LISTADET WHERE ID = @I_X

		INSERT INTO #TMP_LISTAACT
		SELECT ID_COTDETALLE,DESCACTIVIDAD FROM TBD_COTDET_ACTIVIDAD WITH(NOLOCK) WHERE ID_COTDETALLE=@COD_DET
		
		SELECT @I_X2=1,@TOTAL_DET2=COUNT(1),@ACTIVIDAD='' FROM #TMP_LISTAACT 

		WHILE(@I_X2 <=@TOTAL_DET2)
		BEGIN				
				SELECT @ACTIVIDAD= @ACTIVIDAD+CAST(@I_X2 AS VARCHAR)+'. '+ RTRIM(ISNULL(DESCRIPCION,''))+  '\r\n'  FROM #TMP_LISTAACT WHERE ID=@I_X2 
				SET @I_X2 = @I_X2+1
		END

		TRUNCATE TABLE #TMP_LISTAACT

		INSERT INTO #TMP_LISTAACTFINAL
		SELECT @COD_DET,@ACTIVIDAD

		SET @I_X = @I_X+1

	END


	--DATOS A MOSTRAR CABECERA
	SELECT @RUTAIMAGEN RUTAIMAGEN,
				  @NUM_COTIZACION  NUM_COTIZACION,
				  @ENCABEZADO ENCABEZADO,
				  @RUC RUC,
				  CONVERT(VARCHAR,GETDATE(),103) FECHA,
				  @RAZONSOCIAL RAZONSOCIAL,
				  @NOMBRECONTACTO NOMBRECONTACTO,
				  @AREACONTACTO AREA,
				  @TELEFONOCONTACTO TELEFONO,
				  @EMAILCONTACTO CORREO,
				  RTRIM(@PLAZOENTREGA)+' Días' PLAZOENTREGA,
				  @FORMAPAGO FORMAPAGO,
				  @MONEDA MONEDA,
				  RTRIM(@VIGENCIA)+' Días' VIGENCIA,
				  @GARANTIA GARANTIA,
				  @OBSERVACION OBSERVACION,
				  @CONTRATO CONTRATO,
				  @NOMBREVENDEDOR NOMBREVENDEDOR,
				  @TELEFONOVENDEDOR TELEFONOVENDEDOR,
				  @CORREOVENDEDOR CORREOVENDEDOR,
				  @PIE PIE,
				  (@SIMBOLO_MONEDA+' '+@SUBTOTAL) SUBTOTAL,
				  (@SIMBOLO_MONEDA+' '+@MONTOIGV) IGV,
				  (@SIMBOLO_MONEDA+' '+@TOTALVENTA) TOTAL


				SELECT CAST(A.NROITEM AS VARCHAR) NROITEM,
							CASE WHEN A.TIPOITEM = 'SER' THEN
							RIGHT('000000'+CAST(A.CODITEM AS VARCHAR),6)
							ELSE
							ISNULL(A.CODITEM,'') 
							END CATALOGO,
							CASE WHEN  A.TIPOITEM = 'SER' THEN
									''+UPPER(RTRIM(ISNULL(SV.VALOR1,'')))+  '\r\n' +
									'EQUIPO: '+RTRIM(ISNULL(SERV.DESCRIPCIONEQUIPO,'')) +  '\r\n' +
									'MARCA: '+RTRIM(ISNULL(SERV.NOMBREMARCA,''))  +  '\r\n' +
									'MODELO: '+RTRIM(ISNULL(SERV.NOMBREMODELO,''))  + '\r\n'  +
									CASE WHEN(LEN(ACT.DESCRIPCION) >0) THEN 
										'\r\n'+
										'CARACTERISTICAS:' + '\r\n'  +
										ISNULL(ACT.DESCRIPCION,'')
										ELSE
										'\r\n'
									END	+''						
							WHEN A.TIPOITEM = 'PRO' THEN
							''+ RTRIM(ISNULL(A.DESCRIPCION,''))+  '\r\n' +
							'MARCA: '+RTRIM(ISNULL(E.TG_CDESCRI,''))+  '\r\n' +
							'MODELO: '+RTRIM(ISNULL(MO.TG_CDESCRI,''))+  '\r\n' +
							IIF(A.DESCRIPADIC IS NULL, '','ESPECIFICACIONES/CARACTERÍSTICAS: '+RTRIM(A.DESCRIPADIC))
							ELSE
								''+ RTRIM(ISNULL(A.DESCRIPCION,''))+  '\r\n' +
								'MARCA: '+RTRIM(ISNULL(E.TG_CDESCRI,''))+  '\r\n' +
								'MODELO:'+RTRIM(ISNULL(MO.TG_CDESCRI,''))
							END
							DESCRIPCION,
							ISNULL(A.UNDMED,'')  UNIDAD,
							CAST(A.CANTIDAD AS VARCHAR) CANTIDAD,
							CASE WHEN A.TIPOITEM = 'ACC' THEN ''
							ELSE (RTRIM(ISNULL(@SIMBOLO_MONEDA,''))+' '+CONVERT(VARCHAR,CAST(ISNULL((
								  CASE WHEN A.PORCGANANCIA > 0 THEN
										CASE WHEN A.VVTOTALSIGVDSCTO IS NULL THEN
											ISNULL(A.VVTOTALSIGVCGAN,0.00) 
										ELSE
											ISNULL(A.VVTOTALSIGVDSCTO,0.00) 
										END
									ELSE 
										CASE WHEN A.VVTOTALSIGVDSCTO IS NULL THEN
											ISNULL(A.VVTOTALSIGV,0.00) 
										ELSE
											ISNULL(A.VVTOTALSIGVDSCTO,0.00) 
										END
									END)/A.CANTIDAD,0.00)  AS MONEY),1) ) 
							END PRECIOUNITARIO,
							CASE WHEN A.TIPOITEM = 'ACC' THEN ''
							ELSE
									(CASE WHEN A.PORCGANANCIA > 0 THEN
										CASE WHEN A.VVTOTALSIGVDSCTO IS NULL THEN
											RTRIM(ISNULL(@SIMBOLO_MONEDA,''))+' '+  CONVERT(VARCHAR,CAST(ISNULL(A.VVTOTALSIGVCGAN ,0.00) AS MONEY) ,1) 
										ELSE
											RTRIM(ISNULL(@SIMBOLO_MONEDA,''))+' '+  CONVERT(VARCHAR,CAST(ISNULL(A.VVTOTALSIGVDSCTO ,0.00) AS MONEY) ,1)
										END
									ELSE 
										CASE WHEN A.VVTOTALSIGVDSCTO IS NULL THEN
											RTRIM(ISNULL(@SIMBOLO_MONEDA,''))+' '+  CONVERT(VARCHAR,CAST(ISNULL(A.VVTOTALSIGV ,0.00) AS MONEY) ,1) 
										ELSE
											RTRIM(ISNULL(@SIMBOLO_MONEDA,''))+' '+  CONVERT(VARCHAR,CAST(ISNULL(A.VVTOTALSIGVDSCTO ,0.00) AS MONEY) ,1)
										END
									END)
							END TOTAL 
				FROM TBD_COTIZACIONVENTA A WITH(NOLOCK)
				LEFT JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON A.CODITEM=D.AR_CCODIGO  
				LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
					LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] MO WITH(NOLOCK) ON MO.TG_CCOD = '39' AND D.AR_CMODELO = MO.TG_CCLAVE
				LEFT JOIN TBM_SERVICIOS SERV WITH(NOLOCK) ON A.CODITEM=CAST(SERV.ID_SERVICIO AS VARCHAR) AND A.TIPOITEM='SER'
				LEFT JOIN TBD_DATOS_GENERALES SV WITH(NOLOCK) ON SV.DOMINIO='TIPOSERV' AND SERV.TIPO_SERVICIO=SV.COD_VALOR1 AND SV.ESTADO=1
				LEFT JOIN #TMP_LISTAACTFINAL ACT ON ISNULL(A.ID,0) = ACT.CODDETALLE
				WHERE A.ID_COTIZACION =@COD_COTIZACION AND  A.TIPOITEM IN ('PRO','ACC','SER')
				ORDER BY A.NROITEM;

				--CUENTAS DE BANCOS DE AHSECO:
				SELECT ISNULL(VALOR1,'') BANCO,
							  ISNULL(VALOR2,'') CUENTA, 
							  ISNULL(VALOR3,'') CCI 
				FROM TBD_DATOS_GENERALES WITH(NOLOCK) WHERE DOMINIO='CTACOTI' AND ESTADO=1


END


