USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_CREAR_COTIZACIONCLIENTE
/*===============================================================================================
	NOMBRE:					FECHA:			DESCRIPCIÓN:
	José A. Peralta		24.10.24			Se realiza la construcción del formato de cotización a entregar al cliente.
	EXEC USP_CREAR_COTIZACIONCLIENTE 5
  ===============================================================================================*/
@COD_COTIZACION BIGINT
AS
BEGIN
	
	DECLARE @COD_SOLICITUD BIGINT,@RUTAIMAGEN VARCHAR(200),@NUM_COTIZACION VARCHAR(9),@ENCABEZADO VARCHAR(MAX),
					@RUC VARCHAR(12),@RAZONSOCIAL VARCHAR(200),@NOMBRECONTACTO VARCHAR(150),@AREACONTACTO VARCHAR(100),
				   @TELEFONOCONTACTO VARCHAR(50),@EMAILCONTACTO VARCHAR(75),@PLAZOENTREGA VARCHAR(100),@FORMAPAGO VARCHAR(100),
				   @MONEDA VARCHAR(50),@VIGENCIA VARCHAR(50),@GARANTIA VARCHAR(100),@OBSERVACION VARCHAR(100),
				   @CONTRATO VARCHAR(MAX),@USUARIO VARCHAR(50),@NUMDOCUSU VARCHAR(12),@NOMBREVENDEDOR VARCHAR(200),
				   @TELEFONOVENDEDOR VARCHAR(75),@CORREOVENDEDOR VARCHAR(75),@PIE VARCHAR(MAX),@NUMITEMS INT

	SELECT @COD_SOLICITUD=A.ID_SOLICITUD,
	@NOMBRECONTACTO =A.NOMBRECONTACTO,
	@AREACONTACTO = A.AREACONTACTO,
	@TELEFONOCONTACTO = A.TELEFONOCONTACTO,
	@EMAILCONTACTO = A.EMAILCONTACTO,
	@PLAZOENTREGA = A.PLAZOENTREGA,
	@FORMAPAGO = ISNULL(B.VALOR1,''),
	@MONEDA = ISNULL(C.VALOR1,''),
	@VIGENCIA = A.VIGENCIA,
	@GARANTIA = ISNULL(D.VALOR1,''),
	@USUARIO = UPPER(RTRIM(A.USR_REG))
	FROM TBM_COTIZACIONVENTA A WITH(NOLOCK)
		LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='FORMAPAGO' AND A.FORMAPAGO=B.PARAMETRO 
		LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND A.MONEDA=C.COD_VALOR1 
		LEFT JOIN TBD_DATOS_GENERALES D ON D.DOMINIO='GARANTIAS' AND A.GARANTIA=D.PARAMETRO 
	WHERE A.ID_COTIZACION=@COD_COTIZACION;

	SELECT @RUTAIMAGEN=ISNULL(B.VALOR3,''),
				  @RUC=A.RUC,
				  @RAZONSOCIAL=A.RAZONSOCIAL
	FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
	LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='RAZSOCIAL' AND A.COD_EMPRESA=B.PARAMETRO 
	WHERE A.ID_SOLICITUD=@COD_SOLICITUD;

	SELECT @NUMDOCUSU=NUM_DOC FROM TBM_SEGURIDAD_USUARIO WITH(NOLOCK) WHERE RTRIM(UPPER(USUARIO))=RTRIM(@USUARIO);
	

	SELECT TOP 1 
	@NOMBREVENDEDOR = RTRIM(ISNULL(NOMBRES,''))+ ' '+RTRIM(ISNULL(APELLIDOPATERNO,''))+' '+RTRIM(ISNULL(APELLIDOMATERNO,'')),
	@TELEFONOVENDEDOR = ISNULL(TELEFONO,''),
	@CORREOVENDEDOR = ISNULL(EMAIL,'')
	FROM TBM_EMPLEADOS WITH(NOLOCK) 
	WHERE RTRIM(NUMDOCUMENTO)=RTRIM(@NUMDOCUSU)
	ORDER BY FEC_REG DESC;


	SET  @NUM_COTIZACION= 'PC'+RIGHT('0000000'+CAST(@COD_COTIZACION AS VARCHAR),7)

	SET @ENCABEZADO='R.U.C.: 20100162238\r\n'
	SET @ENCABEZADO=@ENCABEZADO+'Av. Máximo Abril N°524 Urb. Santa Beatriz\r\nJesús María – Lima\r\n'
	SET @ENCABEZADO=@ENCABEZADO+'Sucursal: Av. Arenales N°500 – Jesús María - Lima\r\nTeléfono: (511) 433 7227 / 433 6372\r\n'
	SET @ENCABEZADO=@ENCABEZADO+'Email: ventas@ahsecoperu.com / www.ahsecoperu.com.pe';

	SET @OBSERVACION='Precios Incluyen IGV.'

	SET @CONTRATO='*INSTALACION Y VERIFICACIÓN OPERACIONAL:\r\n'
	SET @CONTRATO= @CONTRATO+'La empresa se responsabiliza por la instalación y puesta en marcha del equipo ofertado.\r\n\r\n'
	SET @CONTRATO= @CONTRATO+'**ASESORÍA, CAPACITACIÓN Y POST VENTA:\r\n'
	SET @CONTRATO= @CONTRATO+'Brindar la respectiva capacitación al personal usuario designado que se encargará de la operación del equipo ofrecido.\r\n\r\n'
	SET @CONTRATO= @CONTRATO+'***GARANTÍA Y SOPORTE TÉCNICO:\r\nLa empresa ofrece una Garantía Comercial de 12 meses\r\n'
	SET @CONTRATO= @CONTRATO+'Mantenimiento Preventivo dentro de la Garantía Comercial: 1 mantenimiento anual\r\n\r\n'
	SET @CONTRATO= @CONTRATO+'“AHSECO PERÚ SA Garantiza el stock de Repuestos Originales, así como Servicio Técnico y de Mantenimiento”'

	SET @PIE='El envío de los productos es de manera gratuita a partir de Facturas de US$ 200.00, solo en ciudad de Lima y para clientes finales. \r\n'
	SET @PIE=@PIE+'El equipo se entrega en sus instalaciones en un primer piso, no incluye traslado interno al punto de instalación, el usuario deberá contar con personal para ubicación final del equipo sobre la mesa de trabajo. \r\n'
	SET @PIE=@PIE+'Los envíos a provincia por intermedio de agencia corren a cuenta y riesgo del cliente, AHSECO PERÚ S.A. no se hace responsable cualquier problema que resulte del envío.'


	SELECT @NUMITEMS=COUNT(1)
				FROM TBD_COTIZACIONVENTA WITH(NOLOCK)
				WHERE ID_COTIZACION =@COD_COTIZACION AND TIPOITEM='PROD';


	--DATOS A MOSTRAR CABECERA
	SELECT @RUTAIMAGEN RUTAIMAGEN,
				  @NUM_COTIZACION  NUM_COTIZACION,
				  @ENCABEZADO ENCABEZADO,
				  @RUC RUC,
				  CONVERT(varchar,GETDATE(),103) FECHA,
				  @RAZONSOCIAL RAZONSOCIAL,
				  @NOMBRECONTACTO NOMBRECONTACTO,
				  @AREACONTACTO AREA,
				  @TELEFONOCONTACTO TELEFONO,
				  @EMAILCONTACTO CORREO,
				  @PLAZOENTREGA PLAZOENTREGA,
				  @FORMAPAGO FORMAPAGO,
				  @MONEDA MONEDA,
				  @VIGENCIA VIGENCIA,
				  @GARANTIA GARANTIA,
				  @OBSERVACION OBSERVACION,
				  @CONTRATO CONTRATO,
				  @NOMBREVENDEDOR NOMBREVENDEDOR,
				  @TELEFONOVENDEDOR TELEFONOVENDEDOR,
				  @CORREOVENDEDOR CORREOVENDEDOR,
				  @PIE PIE,
				  'S/. 60.00' SUBTOTAL,
				  'S/. 10.80' IGV,
				  'S/. 70.80' TOTAL,
				  @NUMITEMS NUMITEMS


				SELECT NROITEM,
							'TSX505GA' CATALOGO,
							DESCRIPCION,
							UNIDAD,
							CANTIDAD,
							'S/. 30.00' PRECIOUNITARIO,
							'S/. 30.00' TOTAL 
				FROM TBD_COTIZACIONVENTA WITH(NOLOCK)
				WHERE ID_COTIZACION =@COD_COTIZACION AND TIPOITEM='PROD';

END
