USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_MANT_TBD_INSTALACION] 
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		24.10.24		Realiza el mantenimiento de la tabla TBD_INSTALACION con parametros.
  =======================================================================================================*/
(
	@IsTipoProceso			CHAR(1)
	,@IsID					BIGINT
	,@IsNUMREQ				BIGINT
	,@IsCODIGOPRODUCTO		VARCHAR(35)
	,@IsDESCRIPCION			VARCHAR(100)
	,@IsCANTIDAD			INT
	,@IsMARCA				VARCHAR(150)
	,@IsMODELO				VARCHAR(200)
	,@IsSERIE				VARCHAR(200)
	,@IsNUMFIANZA			VARCHAR(50)
	,@IsCANTIDADMP			INT
	,@IsPERIODICIDAD		VARCHAR(20)
	,@IsGARANTIA			VARCHAR(6)
	,@IsGARANTIAADIC		VARCHAR(50)
	,@IsINDLLAVEMANO		CHAR(1)
	,@IsCODUBIGEODEST		VARCHAR(6)
	,@IsDIRECCION			VARCHAR(150)
	,@IsNROPISO				INT
	,@IsDIMENSIONES			VARCHAR(50)
	,@IsINDCALIBRACION		CHAR(1)
	,@IsINDREQUIEREPLACA	CHAR(1)
	,@IsFECLIMINSTA			DATETIME
	,@IsINDFIANZA			CHAR(1)
	,@IsMONTOPPRINC			DECIMAL(18,9)
	,@IsMONTOPACCE			DECIMAL(18,9)
	,@IsFECHAPROGRAMACION	DATETIME
	,@IsFECHAREAL			DATETIME
	,@UsrEjecuta			NVARCHAR(50)
)
AS
BEGIN
	DECLARE @COD BIGINT, @MSG VARCHAR(100)
	SET NOCOUNT ON;

	IF (@IsTipoProceso = 'I')
		BEGIN
			INSERT INTO TBD_INSTALACION(NUMREQ,CODIGOPRODUCTO,DESCRIPCION,CANTIDAD,MARCA,MODELO,SERIE,NUMFIANZA,CANTIDADMP,PERIODICIDAD,GARANTIA,GARANTIAADIC,INDLLAVEMANO,
										CODUBIGEODEST,DIRECCION,NROPISO,DIMENSIONES,INDCALIBRACION,INDREQUIEREPLACA,FECLIMINSTA,INDFIANZA,MONTOPPRINC,MONTOPACCE,FECHAPROGRAMACION,FECHAREAL,USR_REG,FEC_REG)
			VALUES (@IsNUMREQ,@IsCODIGOPRODUCTO,@IsDESCRIPCION,@IsCANTIDAD,@IsMARCA,@IsMODELO,@IsSERIE,@IsNUMFIANZA,@IsCANTIDADMP,@IsPERIODICIDAD,@IsGARANTIA,@IsGARANTIAADIC,@IsINDLLAVEMANO,
					@IsCODUBIGEODEST,@IsDIRECCION,@IsNROPISO,@IsDIMENSIONES,@IsINDCALIBRACION,@IsINDREQUIEREPLACA,@IsFECLIMINSTA,@IsINDFIANZA,@IsMONTOPPRINC,@IsMONTOPACCE,@IsFECHAPROGRAMACION,@IsFECHAREAL,@UsrEjecuta,GETDATE())
			IF @@ROWCOUNT = 0
			BEGIN
				SET @COD = 0;
				SET @MSG = 'ERROR EN EL REGISTRO DE LA TABLA TBD_INSTALACION'
			END
			ELSE
			BEGIN
				SET @COD = @@IDENTITY;
				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
			END
		END
	ELSE
		IF(@IsTipoProceso = 'U')
			BEGIN
				UPDATE TBD_INSTALACION
				SET FECHAPROGRAMACION	= @IsFECHAPROGRAMACION
					,FECHAREAL			= @IsFECHAREAL
					,USR_MOD			= @UsrEjecuta
					,FEC_MOD			= GETDATE()
				WHERE ID = @IsID

				IF @@ROWCOUNT = 0
				BEGIN
					SET @COD = 0;
					SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA TBD_INSTALACION'
				END
				ELSE
				BEGIN
					SET @COD = @IsID;
					SET @MSG = 'REGISTRO REALIZADO CON EXITO'
				END
			END
	SELECT @COD COD, @MSG MSG
	SET NOCOUNT ON;
END