USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_MANT_TBD_INSTALACION] 
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		24.10.24		Realiza el mantenimiento de la tabla TBD_INSTALACION con parametros.
  =======================================================================================================*/
(
	@IsTipoProceso			CHAR(1)
	,@IsID					BIGINT
	,@IsID_DETALLECOTIZ		BIGINT
	,@IsID_DESPACHO_DIST	BIGINT
	,@IsNUMREQ				BIGINT
	,@IsCODIGOPRODUCTO		VARCHAR(35)
	,@IsDESCRIPCION			VARCHAR(100)
	,@IsCANTIDAD			INT
	,@IsMARCA				VARCHAR(150)
	,@IsSERIE				VARCHAR(200)
	,@IsNUMFIANZA			VARCHAR(50)
	,@IsCANTIDADMP			INT
	,@IsPERIODICIDAD		VARCHAR(20)
	,@IsCODUBIGEODEST		VARCHAR(6)
	,@IsDIRECCION			VARCHAR(150)
	,@IsNROPISO				INT
	,@IsDIMENSIONES			VARCHAR(50)
	,@IsINDFIANZA			CHAR(1)
	,@IsMONTOPPRINC			DECIMAL(18,9)
	,@IsMONTOPACCE			DECIMAL(18,9)
	,@UsrEjecuta			NVARCHAR(50)
)
AS
BEGIN
	DECLARE @COD BIGINT, @MSG VARCHAR(100)
	SET NOCOUNT ON;

	IF (@IsTipoProceso = 'I')
		BEGIN
			INSERT INTO TBD_INSTALACION(ID_DETALLECOTIZ,ID_DESPACHO_DIST,NUMREQ,CODIGOPRODUCTO,DESCRIPCION,CANTIDAD,MARCA,SERIE,NUMFIANZA,CANTIDADMP,PERIODICIDAD,
										CODUBIGEODEST,DIRECCION,NROPISO,DIMENSIONES,INDFIANZA,MONTOPPRINC,MONTOPACCE,USR_REG,FEC_REG)
			VALUES (@IsID_DETALLECOTIZ,@IsID_DESPACHO_DIST,@IsNUMREQ,@IsCODIGOPRODUCTO,@IsDESCRIPCION,@IsCANTIDAD,@IsMARCA,@IsSERIE,@IsNUMFIANZA,@IsCANTIDADMP,@IsPERIODICIDAD,
					@IsCODUBIGEODEST,@IsDIRECCION,@IsNROPISO,@IsDIMENSIONES,@IsINDFIANZA,@IsMONTOPPRINC,@IsMONTOPACCE,@UsrEjecuta,GETDATE())
			IF @@ROWCOUNT = 0
			BEGIN
				SET @COD = 0;
				SET @MSG = 'ERROR EN EL REGISTRO DE LA TABLA TBD_INSTALACION'
			END
			ELSE
			BEGIN
				SET @COD = @@IDENTITY;
				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
			END
		END
	--ELSE
	--	IF(@IsTipoProceso = 'U')
	--		BEGIN
	--			UPDATE TBD_INSTALACION
	--			SET FECHAPROGRAMACION	= @IsFECHAPROGRAMACION
	--				,FECHAINSTALACION	= @IsFECHAINSTALACION
	--				,USR_MOD			= @UsrEjecuta
	--				,FEC_MOD			= GETDATE()
	--			WHERE ID = @IsID

	--			IF @@ROWCOUNT = 0
	--			BEGIN
	--				SET @COD = 0;
	--				SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA TBD_INSTALACION'
	--			END
	--			ELSE
	--			BEGIN
	--				SET @COD = @IsID;
	--				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
	--			END
	--		END
	SELECT @COD COD, @MSG MSG
	SET NOCOUNT ON;
END