USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_MANT_TBM_INSTALACION] 
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		24.10.24		Realiza el mantenimiento de la tabla TBM_INSTALACION con parametros.
  =======================================================================================================*/
(
	@IsTipoProceso		 CHAR(1)
	,@NUMREQ 			 BIGINT
	,@ID_WORKFLOW		 BIGINT
	,@ID_SOLICITUD		 BIGINT
	,@CODEMPRESA		 VARCHAR(6)
	,@RUCEMPRESA		 VARCHAR(12)
	,@NOMEMPRESA		 VARCHAR(200)
	,@UBICACION			 VARCHAR(200)
	,@NOMBRECONTACTO	 VARCHAR(150)
	,@TELEFONOCONTACTO	 VARCHAR(50)
	,@CARGOCONTACTO		 VARCHAR(50)
	,@ESTABLECIMIENTO	 VARCHAR(100)
	,@TIPOVENTA			 VARCHAR(25)
	,@ORDENCOMPRA		 VARCHAR(35)
	,@NUMPROCESO		 VARCHAR(15)
	,@TIPOPROCESO 		 VARCHAR(200)
	,@CONTRATO			 VARCHAR(25)
	,@VENDEDOR			 VARCHAR(150)
	,@FECHAMAX			 DATETIME
	,@DESTINO			 VARCHAR(75)
	,@ESTADO			 VARCHAR(6)
	,@UsrEjecuta		 VARCHAR(50)
)
AS
BEGIN
	DECLARE @CODREQ BIGINT, @MSG VARCHAR(100)
	SET NOCOUNT ON;

	IF (@IsTipoProceso = 'I')
		BEGIN
			INSERT INTO TBM_INSTALACION(ID_WORKFLOW,ID_SOLICITUD,RUCEMPRESA,NOMEMPRESA,UBICACION,NOMBRECONTACTO,TELEFONOCONTACTO,CARGOCONTACTO,ESTABLECIMIENTO,
										TIPOVENTA,ORDENCOMPRA,NUMPROCESO,TIPOPROCESO, CONTRATO,VENDEDOR,CODEMPRESA,FECHAMAX,DESTINO,ESTADO,USR_REG,FEC_REG)
			VALUES (@ID_WORKFLOW, @ID_SOLICITUD, @RUCEMPRESA,@NOMEMPRESA,@UBICACION,@NOMBRECONTACTO,@TELEFONOCONTACTO,@CARGOCONTACTO,@ESTABLECIMIENTO
					,@TIPOVENTA,@ORDENCOMPRA,@NUMPROCESO,@TIPOPROCESO,@CONTRATO,@VENDEDOR,@CODEMPRESA,@FECHAMAX ,@DESTINO,@ESTADO,@UsrEjecuta, GETDATE())

			IF @@ROWCOUNT = 0
			BEGIN
				SET @CODREQ = 0;
				SET @MSG = 'ERROR EN EL REGISTRO DE LA TABLA TBM_INSTALACION'
			END
			ELSE
			BEGIN
				SET @CODREQ = @@IDENTITY;
				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
			END
		END
	ELSE
		IF(@IsTipoProceso = 'U')
			BEGIN
				UPDATE TBM_INSTALACION
				SET 
					FECHAMAX	= @FECHAMAX
					,DESTINO	= @DESTINO
					,ESTADO		= @ESTADO
					,USR_MOD	= @UsrEjecuta
					,FEC_MOD	= GETDATE()
				WHERE NUMREQ = @NUMREQ

				IF @@ROWCOUNT = 0
				BEGIN
					SET @CODREQ = 0;
					SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA TBM_INSTALACION'
				END
				ELSE
				BEGIN
					SET @CODREQ = @NUMREQ;
					SET @MSG = 'REGISTRO REALIZADO CON EXITO'
				END
			END
	SELECT @CODREQ COD, @MSG MSG
	SET NOCOUNT ON;
END