USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_SOLICITUD_INSTALL_TEC]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		24.10.24		Realiza el select del detalle de la solicitud de venta y de la cotización para la bandeja de instalación técnica.
	[USP_SEL_SOLICITUD_INSTALL_TEC] 1
  =======================================================================================================*/
	@isIdSolDespacho BIGINT
)
AS
BEGIN

SET NOCOUNT ON;
	
	SELECT
		SOL.ID_SOLICITUD					AS ID_SOLICITUD
		,SOL.ID_WORKFLOW					AS ID_WORKFLOW
		,datos.VALOR1						AS EMPRESA
		,SOL.COD_EMPRESA					AS CODEMPRESA
		,IDCLIENTE							AS IDCLIENTE
		,RUC								AS RUC
		,RAZONSOCIAL						AS RAZONSOCIAL
		,CONCAT(ISNULL(ubi.[NOMDEPARTAMENTO],''),' / ',ISNULL(ubi.[NOMPROVINCIA],''),' / ',ISNULL(ubi.[NOMDISTRITO],'')) AS UBIGEO
		,ASESORVENTA						AS ASESORVENTA
		,COTI.GARANTIA						AS GARANTIA
		,SOL.TIPOVENTA						AS TIPOVENTA
		,TIPO.VALOR1						AS TIPO
		,CONVERT(VARCHAR(10),FECHA_SOL,103)	AS FECHA_SOL
		,SOL.ESTADO							AS ESTADO
		,TIPOPROCESO						AS TIPOPROCESO
		,NROPROCESO							AS NROPROCESO
		,DESP.NUMORDEN						AS NUMORDEN
		,DESP.NUMCONTRATO					AS NUMCONTRATO
		,ISNULL(CONVERT(VARCHAR(10),DESP.FECHAMAX,103),'') AS FECHAMAX
	INTO #tmpSolicitudVenta										---Insertamos datos de la solicitud de venta
	FROM [dbo].[TBM_SOLICITUDVENTA] AS SOL WITH(NOLOCK)
	LEFT JOIN [dbo].[TBM_CLIENTES] AS cli WITH(NOLOCK) ON cli.ID = SOL.IDCLIENTE
	LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] AS COTI WITH(NOLOCK) ON SOL.ID_SOLICITUD = COTI.ID_SOLICITUD AND COTI.ESTADO = 'A'
	LEFT JOIN [dbo].[TBM_UBIGEO] AS ubi WITH(NOLOCK) ON ubi.CODUBIGEO = cli.CODUBIGEO
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] datos WITH(NOLOCK) ON datos.PARAMETRO = SOL.COD_EMPRESA AND datos.ESTADO = 1 AND datos.HABILITADO = 1
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS TIPO ON TIPO.COD_VALOR1 = SOL.TIPO_SOL AND TIPO.ESTADO = 1 AND TIPO.HABILITADO = 1
	LEFT JOIN (SELECT COD_VALOR1,VALOR1 FROM [dbo].[TBD_DATOS_GENERALES] WHERE DOMINIO = 'FLOWSOL' AND ESTADO = 1 AND HABILITADO = 1) AS FLUJO ON FLUJO.COD_VALOR1 = CAST(SOL.ID_FLUJO AS NVARCHAR)
	LEFT JOIN [dbo].[TBM_SOLDESPACHO] AS DESP WITH(NOLOCK) ON DESP.ID = @isIdSolDespacho
	WHERE SOL.ID_SOLICITUD = (SELECT ID_SOLICITUD FROM [dbo].[TBM_SOLDESPACHO] WHERE ID = @isIdSolDespacho)

	SELECT
		DETALLE.ID
		,DETALLE.CODITEM
		,DESCRIPCION
		,DETALLE.MARCA
		,ISNULL(DETALLE.MODELO,'')	AS MODELO
		,DETDESPACHO.CANTIDAD
		,COTIZ.GARANTIA
		,ISNULL(DESPACHO.INDFIANZA,'N') INDFIANZA
		,DESPACHO.NUMFIANZA
		,ISNULL(DESPACHO.DIMENSIONES,'') DIMENSIONES
		,ISNULL(DESPACHO.MONTOPPRINC,0) MONTOPPRINC
		,ISNULL(DESPACHO.MONTOPACCE	,0) MONTOPACCE
		,NUM.NUM_INST
		,NUM.NUM_PROG
	INTO #tmpDetalleCotiz
	FROM [dbo].[TBD_DESPACHO_COTIZACION] DETDESPACHO  WITH(NOLOCK)
	INNER JOIN [dbo].[TBD_COTIZACIONVENTA] AS DETALLE WITH(NOLOCK) ON DETDESPACHO.ID_COTDETALLE = DETALLE.ID
	LEFT JOIN [dbo].[TBM_COTDET_DESPACHO] DESPACHO WITH(NOLOCK) ON DESPACHO.ID_COTDETALLE = DETALLE.ID
	LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] COTIZ WITH(NOLOCK) ON COTIZ.ID_COTIZACION = DETALLE.ID_COTIZACION
	LEFT JOIN (SELECT A.ID AS ID_COTDETALLE,  
							COUNT(B.FECHAINSTALACION) NUM_INST,
							COUNT(C.FECHAPROGRAMACION) NUM_PROG
							from [TBD_DESPACHO_COTIZACION] A WITH(NOLOCK)
							LEFT JOIN TBD_DESPACHO_DIST B WITH(NOLOCK) ON A.ID=B.ID_COTDETALLE AND B.FECHAINSTALACION IS NOT NULL
							LEFT JOIN TBD_DESPACHO_DIST C WITH(NOLOCK) ON A.ID=C.ID_COTDETALLE AND C.FECHAPROGRAMACION IS NOT NULL
							GROUP BY A.ID
	) NUM ON DETALLE.ID = NUM.ID_COTDETALLE
	WHERE DETDESPACHO.ID_SOLDESPACHO = @isIdSolDespacho  AND DETALLE.TIPOITEM = 'PRO' AND DESPACHO.INDINSTALACION = 'S' AND ISNULL(DETALLE.ELIMINADO,'N') != 'S'

	SELECT	
			ROW_NUMBER() OVER(ORDER BY DESPACHO.ID ) CONTADOR
			,COTDET.ID AS ID_DETALLE
			,DESPACHO.ID AS ID_DESPACHO
			,COTDET.CODITEM		
			,COTDET.DESCRIPCION		
			,COTDET.MARCA
			,ISNULL(COTDET.MODELO,'') MODELO
			,ISNULL(DESPACHO.NUMSERIE,'') NUMSERIE
			,COTDET.GARANTIA
			,SUBSTRING(DESPACHO.COD_UBIGEO, 0,3) CODDEPARTAMENTO 
			,CONCAT(UBI.NOMDEPARTAMENTO, ' / ', UBI.NOMPROVINCIA, ' / ', UBI.NOMDISTRITO) AS DESCUBIGEODEST
			,DESPACHO.COD_UBIGEO CODUBIGEODEST
			,DESPACHO.DIRECCION
			,ISNULL(DESPACHO.NROPISO,1) NROPISO
	INTO #tmpDespachoParcial
	FROM [dbo].#tmpDetalleCotiz AS COTDET
	LEFT JOIN [dbo].[TBM_DESPACHO] DESP WITH(NOLOCK) ON DESP.ID_SOLDESPACHO = @isIdSolDespacho
	LEFT JOIN [TBD_DESPACHO_DIST] DESPACHO WITH(NOLOCK) ON COTDET.ID  =  DESPACHO.ID_COTDETALLE AND DESPACHO.ID_DESPACHO = DESP.ID
	LEFT JOIN [dbo].[TBM_UBIGEO] UBI WITH(NOLOCK) ON UBI.CODUBIGEO = DESPACHO.COD_UBIGEO

	/*Insertamos de forma parcial*/-------------------------------------------------------------------------------------------------------
	;WITH CTE_1 AS (
		SELECT 
			ID_COTDETALLE,
			CANTCOSTO
		FROM TBD_COTIZACIONCOSTOS 
		WHERE CODCOSTO = 'CXCD0002' 
		AND ID_COTDETALLE IN (SELECT ID_COTDETALLE FROM [dbo].[TBD_DESPACHO_COTIZACION] WHERE ID_SOLDESPACHO = @isIdSolDespacho)
	),
	Numeros AS (
		SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
		FROM master.dbo.spt_values
	)
	SELECT
	ROW_NUMBER () OVER( ORDER BY ID_COTDETALLE) CUENTA,
	*
	INTO #cantidadCostos
	FROM CTE_1 t
	CROSS JOIN Numeros n
	WHERE n.n <=t.CANTCOSTO

/*Insertamos de forma parcial preventivos*/-------------------------------------------------------------------------------------------------------
	;WITH CTE_1 AS (
		SELECT
			ID_COTDETALLE,
			CANTCOSTO,
			CANTPREVENTIVO,
			CODCICLOPREVENT
		FROM TBD_COTIZACIONCOSTOS
		WHERE CODCOSTO = 'CXCD0006'
		AND ID_COTDETALLE IN (SELECT ID_COTDETALLE FROM [dbo].[TBD_DESPACHO_COTIZACION] WHERE ID_SOLDESPACHO = @isIdSolDespacho)
	),
	Numeros AS (
		SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
		FROM master.dbo.spt_values
	)
	SELECT
	ROW_NUMBER () OVER( ORDER BY ID_COTDETALLE) CUENTA,
	*
	INTO #cantidadPreventivos
	FROM CTE_1 t
	CROSS JOIN Numeros n
	WHERE n.n <=t.CANTCOSTO


	SELECT 
			ROW_NUMBER () OVER( ORDER BY CONT.ID_COTDETALLE) CUENTA
			--,'' NUMSEC
			,PREV.CANTPREVENTIVO
			,CODCICLOPREVENT
	INTO #CostosFinal
	FROM #cantidadCostos CONT
	LEFT JOIN #cantidadPreventivos PREV ON CONT.CUENTA = PREV.CUENTA

	SELECT 
		* 
	INTO #tmpDespacho
	FROM #tmpDespachoParcial desp
	LEFT JOIN #CostosFinal costos ON costos.CUENTA = desp.CONTADOR

	SELECT * FROM #tmpSolicitudVenta --Detalle de Solicitud
	SELECT * FROM #tmpDetalleCotiz	 --Detalle de Cotización
	SELECT * FROM #tmpDespacho--Detalle de Costos y despacho

	SET NOCOUNT OFF;
END
