USE [DB_AHSECO]
GO

CREATE OR ALTER   PROCEDURE [dbo].[USP_CREAR_GUIA]
/*===========================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		28.10.24		Se obtiene los datos para la guia de pedidos y guia de BO.
	EXEC USP_CREAR_GUIA 25,'GP'
  ===========================================================================================*/
@CodigoSol BIGINT,
@Tipo VARCHAR(2)
AS
BEGIN

SET NOCOUNT ON;

DECLARE @RUTAIMAGEN VARCHAR(200),@FECHAOC VARCHAR(10),@PLAZOENTREGA VARCHAR(100),@USUARIO VARCHAR(50),
@NUMDOCUSU VARCHAR(12),@NOMBREVENDEDOR VARCHAR(200),@TITULO VARCHAR(50),@RAZONSOCIAL VARCHAR(200),
@RUC VARCHAR(12),@DIRECCION VARCHAR(150),@CIUDAD VARCHAR(50),@NUMOC VARCHAR(50),@COD_COTIZACION BIGINT

DECLARE @SUBTOTAL VARCHAR(35),@IGV VARCHAR(25),@TOTAL VARCHAR(35),@MONEDA VARCHAR(25)

	SELECT @TITULO = CASE WHEN @Tipo = 'GP' THEN 'GUÍA DE PEDIDO'
										 WHEN @Tipo = 'BO' THEN 'B/O'
										 ELSE '' END;
												   

	SELECT @RUTAIMAGEN=ISNULL(B.COD_VALOR1 ,'')+'.png',
	@PLAZOENTREGA=ISNULL(COTI.PLAZOENTREGA,''),
	@USUARIO=UPPER(RTRIM(A.USR_REG)),
	@RAZONSOCIAL=A.RAZONSOCIAL,
	@RUC=A.RUC,
	@COD_COTIZACION=COTI.ID_COTIZACION,
	@SUBTOTAL = RTRIM(ISNULL(C.COD_VALOR3,''))+' '+ CONVERT(VARCHAR, CAST(ISNULL(COTI.SUBTOTALVENTA,0) AS MONEY), 1),
	@IGV = RTRIM(ISNULL(C.COD_VALOR3,''))+' '+ CONVERT(VARCHAR, CAST(ISNULL(COTI.MONTOIGV,0) AS MONEY), 1),
	@TOTAL = RTRIM(ISNULL(C.COD_VALOR3,''))+' '+ CONVERT(VARCHAR, CAST(ISNULL(COTI.TOTALVENTA,0) AS MONEY), 1),
	@MONEDA = UPPER(ISNULL(C.VALOR1,''))
	FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
	INNER JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON A.ID_SOLICITUD=COTI.ID_SOLICITUD AND COTI.ESTADO='A' 
	LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='RAZSOCIAL' AND A.COD_EMPRESA=B.PARAMETRO 
	LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND  COTI.MONEDA=C.COD_VALOR1
	WHERE A.ID_SOLICITUD=@CodigoSol;

	SELECT TOP 1 
	@FECHAOC=CONVERT(varchar,FECHAORDEN,103) ,
	@NUMOC =RIGHT('00000000'+ISNULL(NUMORDEN,''),8)
	FROM TBM_DESPACHO WHERE ID_SOLICITUD= @CodigoSol;

	SELECT @NUMDOCUSU=NUM_DOC FROM TBM_SEGURIDAD_USUARIO WITH(NOLOCK) WHERE RTRIM(UPPER(USUARIO))=RTRIM(@USUARIO) AND HABILITADO=1;

	SELECT TOP 1 
	@NOMBREVENDEDOR = RTRIM(ISNULL(NOMBRES,''))+ ' '+RTRIM(ISNULL(APELLIDOPATERNO,''))+' '+RTRIM(ISNULL(APELLIDOMATERNO,''))
	FROM TBM_EMPLEADOS WITH(NOLOCK) 
	WHERE RTRIM(NUMDOCUMENTO)=RTRIM(@NUMDOCUSU)
	ORDER BY FEC_REG DESC;


	 SELECT @DIRECCION=A.DIRECCION,
					@CIUDAD = B.NOMCAPITALLEGAL
		FROM TBM_CLIENTES A WITH(NOLOCK) 
		LEFT JOIN TBM_UBIGEO B ON A.CODUBIGEO=B.CODUBIGEO
		WHERE A.RUCEMPRESA=@RUC;

	SELECT @RUTAIMAGEN RUTAIMAGEN, 
				  @TITULO TITULO,
				  @FECHAOC FECHAOC,
				  @PLAZOENTREGA PLAZOENTREGA,
				  @NOMBREVENDEDOR NOMBREVENDEDOR,
				  @RAZONSOCIAL VENDIDOA,
				  @RAZONSOCIAL ENVIADOA,
				  @RUC RUC,
				  @DIRECCION DIRECCION,
				  @CIUDAD CIUDAD,
				  @NUMOC NUMOC,
				  @MONEDA MONEDA,
				  @SUBTOTAL SUBTOTAL,
				  @IGV IGV,
				  @TOTAL TOTAL;

SELECT CAST(B.NROITEM AS VARCHAR) NROITEM, 
	B.CODITEM CATALOGO,
	(B.DESCRIPCION+ CHAR(13) + CHAR(10) +' MARCA:'+E.TG_CDESCRI) DESCRIPCION,
	B.UNDMED UNIDAD,
	CAST(B.CANTIDAD AS VARCHAR) CANTIDAD,
	RTRIM(ISNULL(C.COD_VALOR3,''))+' '+ CONVERT(VARCHAR, CAST(B.VVENTAUNI AS MONEY), 1) PRECIOUNITARIO,
	RTRIM(ISNULL(C.COD_VALOR3,''))+' '+ CONVERT(VARCHAR, CAST(ISNULL(B.VVTOTALSIGVDSCTO,ISNULL(B.VVTOTALSIGVCGAN,B.VVTOTALSIGV)) AS MONEY), 1) TOTAL
	FROM TBM_COTIZACIONVENTA A WITH(NOLOCK)
	INNER JOIN TBD_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION AND B.TIPOITEM='PRO'	
	INNER JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON B.CODITEM=D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND  A.MONEDA=C.COD_VALOR1
	WHERE A.ID_COTIZACION=@COD_COTIZACION

	SET NOCOUNT OFF;
END