USE [DB_AHSECO]
GO

CREATE OR ALTER   PROCEDURE [dbo].[USP_CREAR_GUIA]
/*===========================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		28.10.24		Se obtiene los datos para la guia de pedidos y guia de BO.
	EXEC USP_CREAR_GUIA 65,'GP','N'
  ===========================================================================================*/
@CodigoSol BIGINT,
@Tipo VARCHAR(2),
@Stock VARCHAR(1)
AS
BEGIN

SET NOCOUNT ON;

DECLARE @RUTAIMAGEN VARCHAR(200),@FECHAOC VARCHAR(10),@PLAZOENTREGA VARCHAR(100),@USUARIO VARCHAR(50),
@NUMDOCUSU VARCHAR(12),@NOMBREVENDEDOR VARCHAR(200),@TITULO VARCHAR(50),@RAZONSOCIAL VARCHAR(200),
@RUC VARCHAR(12),@DIRECCION VARCHAR(150),@CIUDAD VARCHAR(50),@NUMOC VARCHAR(50),@COD_COTIZACION BIGINT,@SIMBOLO VARCHAR(6),
@TIPOSOL VARCHAR(6)

DECLARE @SUBTOTAL VARCHAR(35),@IGV VARCHAR(25),@TOTAL VARCHAR(35),@MONEDA VARCHAR(25)
DECLARE @SUBTOT DECIMAL(18,9)

	SELECT @TITULO = CASE WHEN @Tipo = 'GP' THEN 'GUÍA DE PEDIDO'
										 WHEN @Tipo = 'BO' THEN 'B/O'
										 WHEN @Tipo = 'MA' THEN 'GUÍA MANUSCRITA'
										 WHEN @Tipo = 'MI' THEN 'GUÍA MANUSCRITA'
										 ELSE '' END;


	SELECT @RUTAIMAGEN=ISNULL(B.COD_VALOR1 ,'')+'.png',
	@PLAZOENTREGA=ISNULL(COTI.PLAZOENTREGA,''),
	@USUARIO=UPPER(RTRIM(A.USR_REG)),
	@RAZONSOCIAL=A.RAZONSOCIAL,
	@RUC=A.RUC,
	@COD_COTIZACION=COTI.ID_COTIZACION,
	@SIMBOLO=ISNULL(C.COD_VALOR3,''),
	@MONEDA = UPPER(ISNULL(C.VALOR1,'')),
	@TIPOSOL =ISNULL(A.TIPO_SOL,'')
	FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
	INNER JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON A.ID_SOLICITUD=COTI.ID_SOLICITUD AND COTI.ESTADO='A' 
	LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='RAZSOCIAL' AND A.COD_EMPRESA=B.PARAMETRO 
	LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND  COTI.MONEDA=C.COD_VALOR1
	WHERE A.ID_SOLICITUD=@CodigoSol;



		IF OBJECT_ID('tempdb..#TMP_LISTA') IS NOT NULL
		DROP TABLE #TMP_LISTA

	CREATE TABLE #TMP_LISTA(
		NROITEM INT,
		CANT INT
	)

	INSERT INTO #TMP_LISTA
	SELECT NROITEM,COUNT(1) FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION=@COD_COTIZACION
	GROUP BY NROITEM


	IF OBJECT_ID('tempdb..#TMP_ITEM') IS NOT NULL
		DROP TABLE #TMP_ITEM

	CREATE TABLE #TMP_ITEM(ID INT IDENTITY(1,1),ITEM VARCHAR(3))


		IF OBJECT_ID('tempdb..#TMP_LISTAACT') IS NOT NULL
		DROP TABLE #TMP_LISTAACT

	CREATE TABLE #TMP_LISTAACT(
		ID INT IDENTITY(1,1),
		CODDETALLE INT,
		DESCRIPCION VARCHAR(250)
	)


	IF OBJECT_ID('tempdb..#TMP_LISTAACTFINAL') IS NOT NULL
		DROP TABLE #TMP_LISTAACTFINAL

	CREATE TABLE #TMP_LISTAACTFINAL(
		ID INT IDENTITY(1,1),
		CODDETALLE INT,
		DESCRIPCION VARCHAR(8000)
	)

	IF OBJECT_ID('tempdb..#TMP_LISTADET') IS NOT NULL
		DROP TABLE #TMP_LISTADET

	CREATE TABLE #TMP_LISTADET(
		ID INT IDENTITY(1,1),
		CODDETALLE INT
	)

	DECLARE @TOTAL_DET INT,@I_X INT,@COD_DET BIGINT ,@I_X2 BIGINT,@TOTAL_DET2 INT,@ACTIVIDAD VARCHAR(8000)

	INSERT INTO #TMP_LISTADET
	SELECT ID FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION =@COD_COTIZACION

	SELECT @TOTAL_DET=COUNT(1),@I_X=1  FROM  #TMP_LISTADET
	

	WHILE(@I_X <=@TOTAL_DET)
	BEGIN
		
		SELECT @COD_DET=CODDETALLE FROM #TMP_LISTADET WHERE ID = @I_X

		INSERT INTO #TMP_LISTAACT
		SELECT ID_COTDETALLE,DESCACTIVIDAD FROM TBD_COTDET_ACTIVIDAD WITH(NOLOCK) WHERE ID_COTDETALLE=@COD_DET
		
		SELECT @I_X2=1,@TOTAL_DET2=COUNT(1),@ACTIVIDAD='' FROM #TMP_LISTAACT 

		WHILE(@I_X2 <=@TOTAL_DET2)
		BEGIN				
				SELECT @ACTIVIDAD= @ACTIVIDAD+CAST(@I_X2 AS VARCHAR)+'. '+ RTRIM(ISNULL(DESCRIPCION,''))+   CHAR(13) + CHAR(10)   FROM #TMP_LISTAACT WHERE ID=@I_X2 
				SET @I_X2 = @I_X2+1
		END

		TRUNCATE TABLE #TMP_LISTAACT

		INSERT INTO #TMP_LISTAACTFINAL
		SELECT @COD_DET,@ACTIVIDAD

		SET @I_X = @I_X+1

	END



	IF(@TIPOSOL IN ('TSOL02','TSOL04','TSOL05'))
	BEGIN
		INSERT INTO #TMP_ITEM
		SELECT 'PRO' UNION SELECT 'ACC';

	END
	ELSE IF(@TIPOSOL='TSOL01')
	BEGIN
			INSERT INTO #TMP_ITEM
			SELECT 'SER';
	END
	ELSE IF(@TIPOSOL='TSOL01' AND @Tipo='MA')
	BEGIN
			INSERT INTO #TMP_ITEM
			SELECT 'SER';
	END
	ELSE IF(@TIPOSOL='TSOL03' AND @Tipo='MI')
	BEGIN
			INSERT INTO #TMP_ITEM
			SELECT 'PRO' UNION SELECT 'ACC' UNION SELECT 'SER';
	END
	ELSE IF(@TIPOSOL='TSOL03' AND @Tipo='BO')
	BEGIN
			INSERT INTO #TMP_ITEM
			SELECT 'PRO' UNION SELECT 'ACC';
	END



		-- Se calcula el SUBTOTAL
		SELECT @SUBTOTAL=RTRIM(ISNULL(@SIMBOLO,''))+' '+ CONVERT(VARCHAR, CAST(SUM(

							ISNULL(VVENTAUNI,0) *CANTIDAD

							)  AS MONEY),1)  ,
					@SUBTOT =ISNULL(SUM(

								ISNULL(VVENTAUNI,0)  *CANTIDAD

								) 
								,0.00)
		FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION = @COD_COTIZACION AND 
		ISNULL(INDSTOCK,'')=(CASE WHEN @Stock='X' THEN ISNULL(INDSTOCK,'') ELSE @Stock END);
		


		
		-- Se calcula el SUBTOTAL y TOTAL DE VENTA

		SET @IGV =RTRIM(ISNULL(@SIMBOLO,''))+' '+  CONVERT(VARCHAR,CAST(ISNULL(@SUBTOT * 0.18 ,0) AS MONEY) ,1) 
		SET @TOTAL = RTRIM(ISNULL(@SIMBOLO,''))+' '+ CONVERT(VARCHAR,CAST(ISNULL(@SUBTOT + (@SUBTOT * 0.18) ,0) AS MONEY) ,1)

		
	SELECT TOP 1 
	@FECHAOC=CONVERT(varchar,FECHAORDEN,103) ,
	@NUMOC =ISNULL(NUMORDEN,'')
	FROM TBM_DESPACHO WHERE ID_SOLICITUD= @CodigoSol;

	SELECT @NUMDOCUSU=NUM_DOC FROM TBM_SEGURIDAD_USUARIO WITH(NOLOCK) WHERE RTRIM(UPPER(USUARIO))=RTRIM(@USUARIO) AND HABILITADO=1;

	SELECT TOP 1 
	@NOMBREVENDEDOR = RTRIM(ISNULL(NOMBRES,''))+ ' '+RTRIM(ISNULL(APELLIDOPATERNO,''))+' '+RTRIM(ISNULL(APELLIDOMATERNO,''))
	FROM TBM_EMPLEADOS WITH(NOLOCK) 
	WHERE RTRIM(NUMDOCUMENTO)=RTRIM(@NUMDOCUSU)
	ORDER BY FEC_REG DESC;


	 SELECT @DIRECCION=A.DIRECCION,
					@CIUDAD = B.NOMCAPITALLEGAL
		FROM TBM_CLIENTES A WITH(NOLOCK) 
		LEFT JOIN TBM_UBIGEO B ON A.CODUBIGEO=B.CODUBIGEO
		WHERE A.RUCEMPRESA=@RUC;

	SELECT @RUTAIMAGEN RUTAIMAGEN, 
				  @TITULO TITULO,
				  @FECHAOC FECHAOC,
				  @PLAZOENTREGA PLAZOENTREGA,
				  @NOMBREVENDEDOR NOMBREVENDEDOR,
				  @RAZONSOCIAL VENDIDOA,
				  @RAZONSOCIAL ENVIADOA,
				  @RUC RUC,
				  @DIRECCION DIRECCION,
				  @CIUDAD CIUDAD,
				  @NUMOC NUMOC,
				  @MONEDA MONEDA,
				  @SUBTOTAL SUBTOTAL,
				  @IGV IGV,
				  @TOTAL TOTAL;
  

	SELECT CAST(B.NROITEM AS VARCHAR) NROITEM, 
	CASE WHEN B.TIPOITEM  IN ('SER') THEN
	RIGHT('000000'+CAST(B.CODITEM AS VARCHAR),6)
	ELSE B.CODITEM
	END CATALOGO,
		CASE WHEN  B.TIPOITEM = 'SER' THEN
									''+UPPER(RTRIM(ISNULL(SV.VALOR1,'')))+  CHAR(13) + CHAR(10) +
									'EQUIPO: '+RTRIM(ISNULL(SERV.DESCRIPCIONEQUIPO,'')) +  CHAR(13) + CHAR(10) +
									'MARCA: '+RTRIM(ISNULL(SERV.NOMBREMARCA,''))  +  CHAR(13) + CHAR(10) +
									'MODELO: '+RTRIM(ISNULL(SERV.NOMBREMODELO,''))  + CHAR(13) + CHAR(10)  +
									CASE WHEN(LEN(ACT.DESCRIPCION) >0) THEN 
										CHAR(13) + CHAR(10)+
										'CARACTERISTICAS:' + CHAR(13) + CHAR(10)  +
										ISNULL(ACT.DESCRIPCION,'')
										ELSE
										CHAR(13) + CHAR(10)
									END	+''
	ELSE
	(B.DESCRIPCION+ CHAR(13) + CHAR(10) +' MARCA:'+ISNULL(E.TG_CDESCRI,'') + CHAR(13) + CHAR(10) + 'MODELO:'+ ISNULL(MO.TG_CDESCRI,'')) 
	END DESCRIPCION,
	ISNULL(B.UNDMED,'') UNIDAD,
	CAST(B.CANTIDAD AS VARCHAR) CANTIDAD,
	RTRIM(ISNULL(C.COD_VALOR3,''))+' '+CONVERT( VARCHAR, CAST(ISNULL(B.VVENTAUNI,0) AS MONEY),1) PRECIOUNITARIO,
	RTRIM(ISNULL(C.COD_VALOR3,''))+' '+CONVERT( VARCHAR, CAST(ISNULL(B.VVENTAUNI,0)*B.CANTIDAD AS MONEY),1)	TOTAL
	FROM TBM_COTIZACIONVENTA A WITH(NOLOCK)
	INNER JOIN TBD_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION  AND ISNULL(B.INDSTOCK,'')=(CASE WHEN @Stock='X' THEN ISNULL(B.INDSTOCK,'') ELSE @Stock END)
	LEFT JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON B.CODITEM=D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] MO WITH(NOLOCK) ON MO.TG_CCOD = '39' AND D.AR_CMODELO = MO.TG_CCLAVE
	LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND  A.MONEDA=C.COD_VALOR1
	LEFT JOIN TBM_SERVICIOS SERV WITH(NOLOCK) ON B.CODITEM=CAST(SERV.ID_SERVICIO AS VARCHAR) AND B.TIPOITEM='SER'
	LEFT JOIN TBD_DATOS_GENERALES SV WITH(NOLOCK) ON SV.DOMINIO='TIPOSERV' AND SERV.TIPO_SERVICIO=SV.COD_VALOR1 AND SV.ESTADO=1
	LEFT JOIN #TMP_LISTAACTFINAL ACT ON ISNULL(B.ID,0) = ACT.CODDETALLE
	WHERE A.ID_COTIZACION=@COD_COTIZACION AND   B.TIPOITEM IN(SELECT ITEM FROM #TMP_ITEM)

	SET NOCOUNT OFF;
END
