USE [DB_AHSECO]
GO

CREATE OR ALTER   PROCEDURE [dbo].[USP_CREAR_GUIA]
/*===========================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		28.10.24		Se obtiene los datos para la guia de pedidos y guia de BO.
	EXEC USP_CREAR_GUIA 191,'BO','N'
  ===========================================================================================*/
@CodigoSol BIGINT,
@Tipo VARCHAR(2),
@Stock VARCHAR(1)
AS
BEGIN

SET NOCOUNT ON;

DECLARE @RUTAIMAGEN VARCHAR(200),@FECHAOC VARCHAR(10),@PLAZOENTREGA VARCHAR(100),@USUARIO VARCHAR(50),
@NUMDOCUSU VARCHAR(12),@NOMBREVENDEDOR VARCHAR(200),@TITULO VARCHAR(50),@RAZONSOCIAL VARCHAR(200),
@RUC VARCHAR(12),@DIRECCION VARCHAR(150),@CIUDAD VARCHAR(50),@NUMOC VARCHAR(50),@COD_COTIZACION BIGINT,@SIMBOLO VARCHAR(6)

DECLARE @SUBTOTAL VARCHAR(35),@IGV VARCHAR(25),@TOTAL VARCHAR(35),@MONEDA VARCHAR(25)
DECLARE @SUBTOT DECIMAL(18,9)

	SELECT @TITULO = CASE WHEN @Tipo = 'GP' THEN 'GUÍA DE PEDIDO'
										 WHEN @Tipo = 'BO' THEN 'B/O'
										 ELSE '' END;
			
			




	SELECT @RUTAIMAGEN=ISNULL(B.COD_VALOR1 ,'')+'.png',
	@PLAZOENTREGA=ISNULL(COTI.PLAZOENTREGA,''),
	@USUARIO=UPPER(RTRIM(A.USR_REG)),
	@RAZONSOCIAL=A.RAZONSOCIAL,
	@RUC=A.RUC,
	@COD_COTIZACION=COTI.ID_COTIZACION,
	@SIMBOLO=ISNULL(C.COD_VALOR3,''),
	@MONEDA = UPPER(ISNULL(C.VALOR1,''))
	FROM TBM_SOLICITUDVENTA A WITH(NOLOCK)
	INNER JOIN TBM_COTIZACIONVENTA COTI WITH(NOLOCK) ON A.ID_SOLICITUD=COTI.ID_SOLICITUD AND COTI.ESTADO='A' 
	LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='RAZSOCIAL' AND A.COD_EMPRESA=B.PARAMETRO 
	LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND  COTI.MONEDA=C.COD_VALOR1
	WHERE A.ID_SOLICITUD=@CodigoSol;



		IF OBJECT_ID('tempdb..#TMP_LISTA') IS NOT NULL
		DROP TABLE #TMP_LISTA

	CREATE TABLE #TMP_LISTA(
		NROITEM INT,
		CANT INT
	)

	INSERT INTO #TMP_LISTA
	SELECT NROITEM,COUNT(1) FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION=@COD_COTIZACION
	GROUP BY NROITEM



		-- Se calcula el SUBTOTAL
		SELECT @SUBTOTAL=RTRIM(ISNULL(@SIMBOLO,''))+' '+ CONVERT(VARCHAR, CAST(SUM(
							--CASE WHEN ISNULL(MONTODSCTO,0) > 0 THEN ISNULL(VVTOTALSIGVDSCTO,0) 
							--		WHEN ISNULL(PORCGANANCIA,0) > 0 THEN ISNULL(VVTOTALSIGVCGAN,0) 
							--		ELSE 
							ISNULL(VVENTAUNI,0) *CANTIDAD
							--END
							)  AS MONEY),1)  ,
					@SUBTOT =ISNULL(SUM(
								--CASE WHEN ISNULL(MONTODSCTO,0) > 0 THEN ISNULL(VVTOTALSIGVDSCTO,0) 
								--	WHEN ISNULL(PORCGANANCIA,0) > 0 THEN ISNULL(VVTOTALSIGVCGAN,0) 
								--	ELSE 
								ISNULL(VVENTAUNI,0)  *CANTIDAD
								--END
								) 
								,0.00)
		FROM TBD_COTIZACIONVENTA WHERE ID_COTIZACION = @COD_COTIZACION AND INDSTOCK=@Stock;
		
	
		
		-- Se calcula el SUBTOTAL y TOTAL DE VENTA

		SET @IGV =RTRIM(ISNULL(@SIMBOLO,''))+' '+  CONVERT(VARCHAR,CAST(ISNULL(@SUBTOT * 0.18 ,0) AS MONEY) ,1) 
		SET @TOTAL = RTRIM(ISNULL(@SIMBOLO,''))+' '+ CONVERT(VARCHAR,CAST(ISNULL(@SUBTOT + (@SUBTOT * 0.18) ,0) AS MONEY) ,1)

		
	SELECT TOP 1 
	@FECHAOC=CONVERT(varchar,FECHAORDEN,103) ,
	@NUMOC =ISNULL(NUMORDEN,'')
	FROM TBM_DESPACHO WHERE ID_SOLICITUD= @CodigoSol;

	SELECT @NUMDOCUSU=NUM_DOC FROM TBM_SEGURIDAD_USUARIO WITH(NOLOCK) WHERE RTRIM(UPPER(USUARIO))=RTRIM(@USUARIO) AND HABILITADO=1;

	SELECT TOP 1 
	@NOMBREVENDEDOR = RTRIM(ISNULL(NOMBRES,''))+ ' '+RTRIM(ISNULL(APELLIDOPATERNO,''))+' '+RTRIM(ISNULL(APELLIDOMATERNO,''))
	FROM TBM_EMPLEADOS WITH(NOLOCK) 
	WHERE RTRIM(NUMDOCUMENTO)=RTRIM(@NUMDOCUSU)
	ORDER BY FEC_REG DESC;


	 SELECT @DIRECCION=A.DIRECCION,
					@CIUDAD = B.NOMCAPITALLEGAL
		FROM TBM_CLIENTES A WITH(NOLOCK) 
		LEFT JOIN TBM_UBIGEO B ON A.CODUBIGEO=B.CODUBIGEO
		WHERE A.RUCEMPRESA=@RUC;

	SELECT @RUTAIMAGEN RUTAIMAGEN, 
				  @TITULO TITULO,
				  @FECHAOC FECHAOC,
				  @PLAZOENTREGA PLAZOENTREGA,
				  @NOMBREVENDEDOR NOMBREVENDEDOR,
				  @RAZONSOCIAL VENDIDOA,
				  @RAZONSOCIAL ENVIADOA,
				  @RUC RUC,
				  @DIRECCION DIRECCION,
				  @CIUDAD CIUDAD,
				  @NUMOC NUMOC,
				  @MONEDA MONEDA,
				  @SUBTOTAL SUBTOTAL,
				  @IGV IGV,
				  @TOTAL TOTAL;



	SELECT CAST(B.NROITEM AS VARCHAR) NROITEM, 
	B.CODITEM CATALOGO,
	(B.DESCRIPCION+ CHAR(13) + CHAR(10) +' MARCA:'+E.TG_CDESCRI + CHAR(13) + CHAR(10) + 'MODELO:'+ MO.TG_CDESCRI) DESCRIPCION,
	ISNULL(B.UNDMED,'') UNIDAD,
	CAST(B.CANTIDAD AS VARCHAR) CANTIDAD,

	--CASE WHEN B.TIPOITEM ='ACC' THEN
	RTRIM(ISNULL(C.COD_VALOR3,''))+' '+CONVERT( VARCHAR, CAST(ISNULL(B.VVENTAUNI,0) AS MONEY),1)
	--ELSE
	--RTRIM(ISNULL(C.COD_VALOR3,''))+' '+CONVERT(VARCHAR,CAST(((CASE WHEN B.PORCGANANCIA > 0 THEN
	--										ISNULL(B.VVTOTALSIGVCGAN,0.00) 
	--								ELSE 
	--										ISNULL(B.VVTOTALSIGV,0.00) 
	--								END)/B.CANTIDAD) AS MONEY),1) 
	--		END 
			PRECIOUNITARIO,
	--CASE WHEN B.TIPOITEM ='ACC' THEN
		RTRIM(ISNULL(C.COD_VALOR3,''))+' '+CONVERT( VARCHAR, CAST(ISNULL(B.VVENTAUNI,0)*B.CANTIDAD AS MONEY),1)
	--ELSE 
	--RTRIM(ISNULL(C.COD_VALOR3,''))+' '+ CONVERT(VARCHAR, CAST(ISNULL(B.VVTOTALSIGVDSCTO,ISNULL(B.VVTOTALSIGVCGAN,B.VVTOTALSIGV)) AS MONEY), 1) 
	--END 
	TOTAL
	FROM TBM_COTIZACIONVENTA A WITH(NOLOCK)
	INNER JOIN TBD_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION  AND B.INDSTOCK=@Stock
	LEFT JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON B.CODITEM=D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] MO WITH(NOLOCK) ON MO.TG_CCOD = '39' AND D.AR_CMODELO = MO.TG_CCLAVE
	LEFT JOIN TBD_DATOS_GENERALES C ON C.DOMINIO='TIPMONEDA' AND  A.MONEDA=C.COD_VALOR1
	WHERE A.ID_COTIZACION=@COD_COTIZACION AND   B.TIPOITEM<>'SER'


	SET NOCOUNT OFF;
END

