USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE DBO.USP_SEL_ALMACENES
AS
BEGIN

	DECLARE @pLinkServer VARCHAR(100) = 'AH-SRV4';
	DECLARE @SQL VARCHAR(MAX);

	SET @SQL = '
	SELECT
	A1_CALMA,
	A1_CDESCRI
	FROM RSFACCAR.dbo.AL0007ALMA WITH(NOLOCK);
	';

	IF EXISTS(SELECT 1 FROM SYS.SERVERS WHERE UPPER(NAME) LIKE '%'+@pLinkServer+'%')
	BEGIN
		SET @SQL = REPLACE(@SQL,'''','''''');
		SET @SQL = 'SELECT * FROM OPENQUERY(['+@pLinkServer+'],'''+@SQL+''')';
	END;

	EXEC(@SQL);

END;
