USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE DBO.USP_SEL_UNIDADMEDIDAS
AS
BEGIN

	DECLARE @pLinkServer VARCHAR(100) = 'AH-SRV4';
	DECLARE @SQL VARCHAR(MAX);

	SET @SQL = '
	SELECT
	TG_CCOD,
	TG_CCLAVE,
	TG_CDESCRI
	FROM RSFACCAR.dbo.AL0007TABL WITH(NOLOCK) WHERE TG_CCOD=''05'';
	';

	IF EXISTS(SELECT 1 FROM SYS.SERVERS WHERE UPPER(NAME) LIKE '%'+@pLinkServer+'%')
	BEGIN
		SET @SQL = REPLACE(@SQL,'''','''''');
		SET @SQL = 'SELECT * FROM OPENQUERY(['+@pLinkServer+'],'''+@SQL+''')';
	END;

	EXEC(@SQL);

END;
