USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_DETALLE_INSTALL]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		03.11.24		Realiza el select del detalle de la instalación técnica.
	[USP_SEL_DETALLE_INSTALL] 1
  =======================================================================================================*/
	@isNumReq			BIGINT
)
AS
BEGIN
	SELECT  --cabecera de detalle.
		ID_DETALLECOTIZ
		,NUMREQ
		,CODIGOPRODUCTO
		,DESCRIPCION
		,CANTIDAD
		,MARCA
		,NUMFIANZA
		,INDLLAVEMANO
		,DIMENSIONES
		,FECLIMINSTA
		,MONTOPPRINC
		,MONTOPACCE
	FROM
	TBD_INSTALACION AS INSTAL WITH(NOLOCK)
	WHERE NUMREQ = @isNumReq
	GROUP BY ID_DETALLECOTIZ,CODIGOPRODUCTO,DESCRIPCION,CANTIDAD,MARCA,NUMFIANZA,INDLLAVEMANO,DIMENSIONES,FECLIMINSTA,MONTOPPRINC,MONTOPACCE,NUMREQ


	SELECT --cuerpo de detalle.
		INSTAL.ID
		,INSTAL.ID_DETALLECOTIZ
		,INSTAL.ID_DESPACHO_DIST
		,INSTAL.CODIGOPRODUCTO
		,INSTAL.DESCRIPCION
		,INSTAL.MARCA
		,INSTAL.SERIE
		,INSTAL.CANTIDADMP
		,INSTAL.PERIODICIDAD
		,INSTAL.CODUBIGEODEST
		,CONCAT(UBI.NOMDEPARTAMENTO,' / ',UBI.NOMPROVINCIA, ' / ', UBI.NOMDISTRITO) AS DESCUBIGEODEST
		,INSTAL.DIRECCION
		,INSTAL.NROPISO
		,CONCAT(EMPLEADO.APELLIDOPATERNO,' ',EMPLEADO.APELLIDOMATERNO,' ',EMPLEADO.NOMBRES) AS NOMBRECOMPLETO
		,DESPACHO.EMPRESA
		,CONVERT(VARCHAR(10),DESPACHO.FECHAPROGRAMACION,23) AS FECHAPROGRAMACION
		,CONVERT(VARCHAR(10),DESPACHO.FECHAINSTALACION,23) AS FECHAINSTALACION
	FROM
	TBD_INSTALACION AS INSTAL WITH(NOLOCK)
	LEFT JOIN [dbo].[TBD_DESPACHO_DIST] AS DESPACHO ON INSTAL.ID_DESPACHO_DIST = DESPACHO.ID
	LEFT JOIN [dbo].[TBM_EMPLEADOS] AS EMPLEADO ON DESPACHO.COD_TECNICO = EMPLEADO.ID_EMPLEADO
	LEFT JOIN [dbo].[TBM_UBIGEO] AS UBI ON UBI.CODUBIGEO = INSTAL.CODUBIGEODEST
	WHERE NUMREQ = @isNumReq
END
