USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_DETALLE_INSTALL]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		03.11.24		Realiza el select del detalle de la instalación técnica.
	[USP_SEL_DETALLE_INSTALL] 2
  =======================================================================================================*/
	@isNumReq			BIGINT
)
AS
BEGIN
	SELECT  --cabecera de detalle.
		ID_DETALLECOTIZ
		,NUMREQ
		,INSTAL.CODIGOPRODUCTO
		,DESCRIPCION
		,CANTIDAD
		,MARCA
		,RGA.DESC_MODELO AS MODELO
		,NUMFIANZA
		,DIMENSIONES
		,MONTOPPRINC
		,MONTOPACCE
		,NUM.NUM_PROG
		,NUM2.NUM_INST
	FROM
	TBD_INSTALACION AS INSTAL WITH(NOLOCK)
		LEFT JOIN (SELECT C.ID_COTDETALLE,  
							COUNT(C.FECHAPROGRAMACION) NUM_PROG
							from  TBD_DESPACHO_DIST C WITH(NOLOCK) 
							WHERE C.FECHAPROGRAMACION IS NOT NULL
							GROUP BY C.ID_COTDETALLE
	) NUM ON INSTAL.ID_DETALLECOTIZ = NUM.ID_COTDETALLE
	LEFT JOIN (SELECT B.ID_COTDETALLE,  
							COUNT(B.FECHAINSTALACION) NUM_INST
							from TBD_DESPACHO_DIST B WITH(NOLOCK) 
							WHERE B.FECHAINSTALACION IS NOT NULL
							GROUP BY B.ID_COTDETALLE
	) NUM2 ON INSTAL.ID_DETALLECOTIZ = NUM2.ID_COTDETALLE
	LEFT JOIN (SELECT [DESC_MODELO], [CODIGOPRODUCTO] FROM OPENQUERY([AH-SRV4],'
		SELECT
			A.AR_CCODIGO CODIGOPRODUCTO,
			MO.TG_CDESCRI AS DESC_MODELO
		FROM  [RSFACCAR].[dbo].[AL0007ARTI] A WITH(NOLOCK)
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007STOC] B WITH(NOLOCK) ON A.AR_CCODIGO=B.SK_CCODIGO
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] D WITH(NOLOCK) ON D.TG_CCOD=''V7'' AND A.AR_CMARCA=D.TG_CCLAVE 
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] MO WITH(NOLOCK) ON MO.TG_CCOD = ''39'' AND A.AR_CMODELO = MO.TG_CCLAVE
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007SERI] F WITH(NOLOCK) ON A.AR_CCODIGO=F.SR_CCODIGO AND B.SK_CALMA=F.SR_CALMA AND F.SR_NSKDIS<>0 
		WHERE B.SK_CALMA IN (''0001'',''0015'',''0017'') GROUP BY A.AR_CCODIGO,A.AR_CDESCRI,D.TG_CDESCRI,MO.TG_CDESCRI' )) RGA ON RGA.CODIGOPRODUCTO = INSTAL.CODIGOPRODUCTO
	WHERE NUMREQ = @isNumReq
	GROUP BY ID_DETALLECOTIZ,INSTAL.CODIGOPRODUCTO,DESCRIPCION,CANTIDAD,MARCA,DESC_MODELO,NUMFIANZA,DIMENSIONES,MONTOPPRINC,MONTOPACCE,NUMREQ,NUM.NUM_PROG,NUM2.NUM_INST


	SELECT --cuerpo de detalle.
		INSTAL.ID
		,INSTAL.ID_DETALLECOTIZ
		,INSTAL.ID_DESPACHO_DIST
		,INSTAL.CODIGOPRODUCTO
		,INSTAL.DESCRIPCION
		,INSTAL.MARCA
		,RGA.[DESC_MODELO] AS MODELO
		,ISNULL(INSTAL.SERIE, DESPACHO.NUMSERIE) SERIE
		,INSTAL.CANTIDADMP
		,INSTAL.PERIODICIDAD
		,INSTAL.CODUBIGEODEST
		,CONCAT(UBI.NOMDEPARTAMENTO,' / ',UBI.NOMPROVINCIA, ' / ', UBI.NOMDISTRITO) AS DESCUBIGEODEST
		,INSTAL.DIRECCION
		,INSTAL.NROPISO
		,CONCAT(EMPLEADO.APELLIDOPATERNO,' ',EMPLEADO.APELLIDOMATERNO,' ',EMPLEADO.NOMBRES) AS NOMBRECOMPLETO
		,DESPACHO.EMPRESA
		,CONVERT(VARCHAR(10),DESPACHO.FECHAPROGRAMACION,23) AS FECHAPROGRAMACION
		,CONVERT(VARCHAR(10),DESPACHO.FECHAINSTALACION,23) AS FECHAINSTALACION
	FROM
	TBD_INSTALACION AS INSTAL WITH(NOLOCK)
	LEFT JOIN [dbo].[TBD_DESPACHO_DIST] AS DESPACHO ON INSTAL.ID_DESPACHO_DIST = DESPACHO.ID
	LEFT JOIN [dbo].[TBM_EMPLEADOS] AS EMPLEADO ON DESPACHO.COD_TECNICO = EMPLEADO.ID_EMPLEADO
	LEFT JOIN [dbo].[TBM_UBIGEO] AS UBI ON UBI.CODUBIGEO = INSTAL.CODUBIGEODEST
	LEFT JOIN (SELECT [DESC_MODELO], [CODIGOPRODUCTO] FROM OPENQUERY([AH-SRV4],'
		SELECT
			A.AR_CCODIGO CODIGOPRODUCTO,
			MO.TG_CDESCRI AS DESC_MODELO
		FROM  [RSFACCAR].[dbo].[AL0007ARTI] A WITH(NOLOCK)
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007STOC] B WITH(NOLOCK) ON A.AR_CCODIGO=B.SK_CCODIGO
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] D WITH(NOLOCK) ON D.TG_CCOD=''V7'' AND A.AR_CMARCA=D.TG_CCLAVE 
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] MO WITH(NOLOCK) ON MO.TG_CCOD = ''39'' AND A.AR_CMODELO = MO.TG_CCLAVE
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007SERI] F WITH(NOLOCK) ON A.AR_CCODIGO=F.SR_CCODIGO AND B.SK_CALMA=F.SR_CALMA AND F.SR_NSKDIS<>0 
		WHERE B.SK_CALMA IN (''0001'',''0015'',''0017'') GROUP BY A.AR_CCODIGO,A.AR_CDESCRI,D.TG_CDESCRI,MO.TG_CDESCRI' )) RGA ON RGA.CODIGOPRODUCTO = INSTAL.CODIGOPRODUCTO
	WHERE NUMREQ = @isNumReq
END

