USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_DESPACHOVENTAS
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		14.11.24		Se realiza la gestión de despacho de la venta concretada.
	EXEC USP_MANT_DESPACHOVENTAS 'I',1,1,123,'representante ventas','XXXX123','20241101','20241130','JPERALTA'
  ==================================================================================================*/
@TIPO CHAR(1),
@CODSOLICITUD BIGINT,
@CODCOTIZACION BIGINT,
@ID_WORKFLOW BIGINT,
@NOMPERFIL VARCHAR(100),
@NUMRODEN VARCHAR(50),
@FECHAORDEN DATETIME,
@FECHAMAX DATETIME,
@STOCK CHAR(1),
@FECHAENTREGA DATETIME,
@NUMFACTURA VARCHAR(50),
@NUMGUIAREM VARCHAR(50),
@NUMPEDIDO VARCHAR(50),
@FECHAINGRESO DATETIME,
@ESTAPROB VARCHAR(3),
@OBSERVACION VARCHAR(1000),
@USRREG VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	IF OBJECT_ID('tempdb..#TMP_LISTASTOCKS') IS NOT NULL
		DROP TABLE #TMP_LISTASTOCKS

	CREATE TABLE #TMP_LISTASTOCKS(ID INT IDENTITY(1,1),STOCK CHAR(1));

	IF OBJECT_ID('tempdb..#TMP_LISTAUNIDAD') IS NOT NULL
		DROP TABLE #TMP_LISTAUNIDAD

	CREATE TABLE #TMP_LISTAUNIDAD(ID INT IDENTITY(1,1),ID_COTDETALLE BIGINT,CANTIDAD INT,STOCK VARCHAR(1));

	DECLARE @CODIGO BIGINT,@MSG VARCHAR(250) ,@NOMUSUARIO VARCHAR(250),@ID_DESPACHO BIGINT,
	@TIPO_SOL VARCHAR(6),@TOTAL1 INT ,@I INT,@COD_STOCK VARCHAR(1),@TOTAL2 INT, @J INT,@TOTAL3 INT ,@K INT

	DECLARE @ID_COTDETALLE BIGINT,@CANTIDAD INT


	SELECT @CODIGO=0,@MSG='No se pudo realizar ninguna accion'

	SELECT @TIPO_SOL=TIPO_SOL FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD =@CODSOLICITUD;

	IF(@TIPO = 'I')
	BEGIN

	

	 --REGISTRO DE DESPACHO
		WITH STOCKS AS (
    		SELECT DISTINCT INDSTOCK FROM TBD_COTIZACIONVENTA A WITH(NOLOCK)
			INNER JOIN TBM_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION
			WHERE B.ID_COTIZACION = @CODCOTIZACION
		)
		INSERT INTO #TMP_LISTASTOCKS
		SELECT  INDSTOCK AS STOCK FROM STOCKS;

		SELECT @TOTAL1= COUNT(1),@I=1 FROM #TMP_LISTASTOCKS

		WHILE(@I <=@TOTAL1)
		BEGIN

			SELECT  @COD_STOCK=STOCK
			FROM #TMP_LISTASTOCKS WHERE ID=@I;

			--INSERTA CABECERA DE DESPACHO:
			INSERT INTO TBM_DESPACHO (ID_SOLICITUD,ID_COTIZACION,STOCK,NUMORDEN,FECHAORDEN,FECHAMAX,USR_REG,FEC_REG)
			SELECT @CODSOLICITUD ID_SOLICITUD, 
					  @CODCOTIZACION ID_COTIZACION,
					  @COD_STOCK STOCK,
					  @NUMRODEN NUMORDEN,
					  @FECHAORDEN FECHAORDEN,
					  @FECHAMAX FECHAMAX,
					  @USRREG USR_REG,
					  GETDATE() FEC_REG

			
			SET @ID_DESPACHO=@@IDENTITY
			--REGISTRO DE DETALLE DEL DESPACHO:


			IF(@TIPO_SOL IN ('TSOL05','TSOL02','TSOL03')) --SE GENERA LAS SERIES PARA TIPO: VENTA EQUIPO, REPUESTOS Y REPUESTO Y SERVICIO
			BEGIN
		
				INSERT INTO #TMP_LISTAUNIDAD
				SELECT ID,CANTIDAD,ISNULL(INDSTOCK,'N') 
						FROM TBD_COTIZACIONVENTA WITH(NOLOCK)
						WHERE ISNULL(INDSTOCK,'N') =@COD_STOCK

				SELECT @TOTAL2= COUNT(1),@J=1 FROM #TMP_LISTAUNIDAD

				WHILE(@J <=@TOTAL2)
				BEGIN

					SELECT @ID_COTDETALLE=ID_COTDETALLE,
								  @CANTIDAD=CANTIDAD,
								  @K = 1
								  FROM #TMP_LISTAUNIDAD
					WHERE ID= @J

					WHILE(@K <=@CANTIDAD)
						BEGIN
							INSERT INTO TBD_DESPACHO_DIST(ID_DESPACHO,ID_COTDETALLE,NUMSEC,USR_REG,FEC_REG)
							VALUES(@ID_DESPACHO,@ID_COTDETALLE,@K ,@USRREG,GETDATE())

							SET @K = @K + 1
						END

					SET @J = @J + 1
				END

			END


			SET @I = @I+1
		END



		--CAMBIO DE ESTADO DE LA SOLICITUD: En proceso de Ventas: (PRVT) 
		UPDATE TBM_SOLICITUDVENTA 
			SET ESTADO='PRVT'
			WHERE ID_SOLICITUD=@CODSOLICITUD;

		--SE REGISTRA LOG DE CAMBIO DE ESTADO:

		INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
		VALUES(@ID_WORKFLOW,'PRVT',@NOMPERFIL,@USRREG,GETDATE());

		--VALIDACION DE INDICADOR DE INSTALACION DE EQUIPO: ENVIO DE CORREO A SERVICIO TECNICO.
		IF EXISTS(SELECT * FROM TBM_COTDET_DESPACHO WHERE ID_COTDETALLE IN (SELECT ID FROM TBD_COTIZACIONVENTA A
																																	INNER JOIN TBM_COTIZACIONVENTA B ON A.ID_COTIZACION=B.ID_COTIZACION
																																		WHERE B.ID_SOLICITUD=@CODSOLICITUD) AND INDINSTALACION='S')
		BEGIN
				SET @CODIGO=2
		END
		ELSE
		BEGIN
				SET  @CODIGO = 1
		END
		
		SET @MSG ='Se realizó el registro de despacho con éxito'

	END

	IF(@TIPO = 'U')
	BEGIN
		
		UPDATE TBM_DESPACHO
		SET NUMORDEN = @NUMRODEN,
				FECHAORDEN = @FECHAORDEN,
				FECHAMAX = @FECHAMAX,
				USR_MOD = @USRREG,
				FEC_MOD = GETDATE()
				WHERE ID_SOLICITUD = @CODSOLICITUD;

		SET  @CODIGO = 1
		SET @MSG ='Se actualizó el registro de despacho con éxito'

	END

	IF(@TIPO = 'P')
	BEGIN
		
		UPDATE TBM_DESPACHO
			SET FECHAENTREGA =@FECHAENTREGA,
				   NUMFACTURA = @NUMFACTURA,
				   NUMGUIAREM = @NUMGUIAREM,
				   GESLOG = 1,
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = @STOCK;

		IF(@TIPO_SOL = 'TSOL04') --VENTA DE MATERIALES
		BEGIN
				--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
				UPDATE TBM_SOLICITUDVENTA 
					SET ESTADO='VTPG',
					  USR_MOD = @USRREG,
				      FEC_MOD = GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD;

				--SE REGISTRA LOG DE CAMBIO DE ESTADO:

				INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
				VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());
		END
			
		SET  @CODIGO = 1
		SET @MSG ='Se actualizó el registro de despacho con éxito'
	END

	IF(@TIPO = 'Y')
	BEGIN
		
		UPDATE TBM_DESPACHO
			SET NUMPEDIDO =  @NUMPEDIDO,
				   FECHAINGRESO = @FECHAINGRESO,
				   ESTAPROB='IMP',
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = 'N';
			
		SET  @CODIGO = 1
		SET @MSG ='Se actualizó el registro de importación con éxito'
	END

	IF(@TIPO = 'A')
	BEGIN
		UPDATE TBM_DESPACHO
			SET OBSERVACION ='',
				   FECAPROB = GETDATE(),
				   ESTAPROB = 'APR',
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = 'N';

		SELECT @NOMUSUARIO=RTRIM(ISNULL(NOMBRES,''))+' '+RTRIM(ISNULL(APELLIDOS,'')) 
		FROM TBM_SEGURIDAD_USUARIO
		WHERE UPPER(USUARIO) = UPPER(@USRREG);

		--SE REGISTRA LA OBSERVACION:
		INSERT INTO TBM_OBSERVACIONES(ID_WORKFLOW,ESTADO_INSTANCIA,OBSERVACION,NOMBRE_USUARIO,PERFIL_USUARIO,USR_REG,FEC_REG)
			VALUES(@ID_WORKFLOW,'PRVT','[Aprobación de Gerencia] - Se realiza la aprobación de la Importación',@NOMUSUARIO,@NOMPERFIL,@USRREG,GETDATE());


		SET  @CODIGO = 1
		SET @MSG ='Aprobación exitosa de la importación.'
	END

	IF(@TIPO = 'O')
	BEGIN
		UPDATE TBM_DESPACHO
			SET OBSERVACION =@OBSERVACION,
				   ESTAPROB = 'OBS',
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = 'N';

		SELECT @NOMUSUARIO=RTRIM(ISNULL(NOMBRES,''))+' '+RTRIM(ISNULL(APELLIDOS,'')) 
		FROM TBM_SEGURIDAD_USUARIO
		WHERE UPPER(USUARIO) = UPPER(@USRREG);

		--SE REGISTRA LA OBSERVACION:
		INSERT INTO TBM_OBSERVACIONES(ID_WORKFLOW,ESTADO_INSTANCIA,OBSERVACION,NOMBRE_USUARIO,PERFIL_USUARIO,USR_REG,FEC_REG)
			VALUES(@ID_WORKFLOW,'PRVT','[Observación de Gerencia] - '+RTRIM(@OBSERVACION),@NOMUSUARIO,@NOMPERFIL,@USRREG,GETDATE());

		--SE RESETEA EL ENVIO DE BO
		UPDATE TBM_DESPACHO 
			SET ENVIOBO=0,
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
		WHERE ID_SOLICITUD=20 AND STOCK='N';

		SET  @CODIGO = 1
		SET @MSG ='Se observo el pedido de importación'
	END



	IF(@TIPO = 'X')
	BEGIN

	UPDATE TBM_DESPACHO
	SET GESLOG = 1
	WHERE ID_SOLICITUD = @CODSOLICITUD AND STOCK = @STOCK; 

	DECLARE @TOTAL INT ,@TOTAL_GEST INT 
	SELECT @TOTAL=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD;
	SELECT @TOTAL_GEST=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD AND GESLOG=1;
		
	IF(@TOTAL = @TOTAL_GEST)
	BEGIN
		--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
		UPDATE TBM_SOLICITUDVENTA 
			SET ESTADO='VTPG',
					USR_MOD = @USRREG,
				    FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD=@CODSOLICITUD;

		--SE REGISTRA LOG DE CAMBIO DE ESTADO:

		INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
		VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());
	END
	

	
		SET  @CODIGO = 1
		SET @MSG ='Se realizó la programacion de la venta'
	END

	IF(@TIPO = 'F') --GESTION DE FACTURACION PARA SERVICIOS:
	BEGIN
		--SE ACTUALIZA LOS CAMPOS DE LA FACTURA DEL DESPACHO:
		  UPDATE TBM_DESPACHO
			SET GESFAC = 1,
					FECHAFACTURA =@FECHAENTREGA,
					NUMFACTSERV = @NUMFACTURA,
					USR_MOD=@USRREG,
					FEC_MOD=GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD;

		--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
		UPDATE TBM_SOLICITUDVENTA 
			SET ESTADO='VTPG',
				  USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()				
			WHERE ID_SOLICITUD=@CODSOLICITUD;

		--SE REGISTRA LOG DE CAMBIO DE ESTADO:

		INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
		VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());

		SET  @CODIGO = 1
		SET @MSG ='Se realizó la facturación del servicio'
	END

		SELECT @CODIGO COD ,@MSG MSG
		SET NOCOUNT OFF;

END