USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_DESPACHOVENTAS
/*==================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		14.11.24		Se realiza la gestión de despacho de la venta concretada.
	EXEC USP_MANT_DESPACHOVENTAS 'I',1,1,123,'representante ventas','XXXX123','20241101','20241130','JPERALTA'
  ==================================================================================================*/
@TIPO CHAR(1),
@CODSOLICITUD BIGINT,
@CODCOTIZACION BIGINT,
@ID_WORKFLOW BIGINT,
@NOMPERFIL VARCHAR(100),
@NUMRODEN VARCHAR(50),
@FECHAORDEN DATETIME,
@FECHAMAX DATETIME,
@STOCK CHAR(1),
@FECHAENTREGA DATETIME,
@NUMFACTURA VARCHAR(50),
@NUMGUIAREM VARCHAR(50),
@NUMPEDIDO VARCHAR(50),
@FECHAINGRESO DATETIME,
@ESTAPROB VARCHAR(3),
@OBSERVACION VARCHAR(1000),
@USRREG VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	IF OBJECT_ID('tempdb..#TMP_LISTASTOCKS') IS NOT NULL
		DROP TABLE #TMP_LISTASTOCKS

	CREATE TABLE #TMP_LISTASTOCKS(ID INT IDENTITY(1,1),STOCK CHAR(1));

	IF OBJECT_ID('tempdb..#TMP_LISTAUNIDAD') IS NOT NULL
		DROP TABLE #TMP_LISTAUNIDAD

	CREATE TABLE #TMP_LISTAUNIDAD(ID INT IDENTITY(1,1),ID_COTDETALLE BIGINT,CANTIDAD INT,STOCK VARCHAR(1));

	IF OBJECT_ID('tempdb..#TMP_LISTADIRECCIONES') IS NOT NULL
		DROP TABLE #TMP_LISTADIRECCIONES

	CREATE TABLE #TMP_LISTADIRECCIONES(ID INT IDENTITY(1,1),ID_COTDETALLE BIGINT,CODUBIGEODEST VARCHAR(6),DIRECCION VARCHAR(150),CANTCOSTO INT,INICIO INT,FIN INT);

	DECLARE @CODIGO BIGINT,@MSG VARCHAR(250) ,@NOMUSUARIO VARCHAR(250),@ID_DESPACHO BIGINT,
	@TIPO_SOL VARCHAR(6),@TOTAL1 INT ,@I INT,@COD_STOCK VARCHAR(1),@TOTAL2 INT, @J INT,@TOTAL3 INT ,@K INT

	DECLARE @ID_COTDETALLE BIGINT,@CANTIDAD INT


	SELECT @CODIGO=0,@MSG='No se pudo realizar ninguna accion'

	SELECT @TIPO_SOL=TIPO_SOL FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD =@CODSOLICITUD;

	IF(@TIPO = 'I')
	BEGIN

	

	 --REGISTRO DE DESPACHO
		WITH STOCKS AS (
    		SELECT DISTINCT INDSTOCK FROM TBD_COTIZACIONVENTA A WITH(NOLOCK)
			INNER JOIN TBM_COTIZACIONVENTA B WITH(NOLOCK) ON A.ID_COTIZACION=B.ID_COTIZACION
			WHERE B.ID_COTIZACION = @CODCOTIZACION
		)
		INSERT INTO #TMP_LISTASTOCKS
		SELECT  INDSTOCK AS STOCK FROM STOCKS;


		--ACTUALIZA EL STOCK SI ES NULO PARA SERVICIOS:
		UPDATE #TMP_LISTASTOCKS SET STOCK='X' WHERE STOCK IS NULL;

		SELECT @TOTAL1= COUNT(1),@I=1 FROM #TMP_LISTASTOCKS

		WHILE(@I <=@TOTAL1)
		BEGIN

			SELECT  @COD_STOCK=STOCK
			FROM #TMP_LISTASTOCKS WHERE ID=@I;

			--INSERTA CABECERA DE DESPACHO:
			INSERT INTO TBM_DESPACHO (ID_SOLICITUD,ID_COTIZACION,STOCK,NUMORDEN,FECHAORDEN,FECHAMAX,USR_REG,FEC_REG)
			SELECT @CODSOLICITUD ID_SOLICITUD, 
					  @CODCOTIZACION ID_COTIZACION,
					  @COD_STOCK STOCK,
					  @NUMRODEN NUMORDEN,
					  @FECHAORDEN FECHAORDEN,
					  @FECHAMAX FECHAMAX,
					  @USRREG USR_REG,
					  GETDATE() FEC_REG

			
			SET @ID_DESPACHO=@@IDENTITY
			--REGISTRO DE DETALLE DEL DESPACHO:


			IF(@TIPO_SOL IN ('TSOL05','TSOL02','TSOL03')) --SE GENERA LAS SERIES PARA TIPO: VENTA EQUIPO, REPUESTOS Y REPUESTO Y SERVICIO
			BEGIN

				DECLARE @COD_UBIGEO VARCHAR(6),@DIRECCION VARCHAR(150),@TOTALDIR INT
		
				INSERT INTO #TMP_LISTAUNIDAD
				SELECT ID,CANTIDAD,INDSTOCK 
						FROM TBD_COTIZACIONVENTA WITH(NOLOCK)
						WHERE ID_COTIZACION=@CODCOTIZACION  AND INDSTOCK =@COD_STOCK
						AND INDSTOCK IS NOT NULL AND TIPOITEM='PRO'
						ORDER BY ID ASC;

				SELECT @TOTAL2= COUNT(1),@J=1 FROM #TMP_LISTAUNIDAD WHERE STOCK=@COD_STOCK

				WHILE(@J <=@TOTAL2)
				BEGIN

					SELECT @ID_COTDETALLE=ID_COTDETALLE,
								  @CANTIDAD=CANTIDAD,
								  @K = 1
								  FROM #TMP_LISTAUNIDAD
					WHERE ID= @J 

					INSERT INTO #TMP_LISTADIRECCIONES
					SELECT ID_COTDETALLE,CODUBIGEODEST,DIRECCION,CANTCOSTO, 
					 (SUM(CANTCOSTO) OVER (ORDER BY ID ASC) -CANTCOSTO +1) ,
					  SUM(CANTCOSTO) OVER (ORDER BY ID ASC)
					FROM (
					SELECT 
					 ROW_NUMBER() OVER (PARTITION BY NUMSEC ORDER BY ID ASC) AS ROW_NUM,ID_COTDETALLE,CODUBIGEODEST,DIRECCION,CANTCOSTO,ID
					FROM TBD_COTIZACIONCOSTOS 
					WHERE ID_COTDETALLE=@ID_COTDETALLE
					)X WHERE ROW_NUM=1

					SELECT @TOTALDIR=COUNT(1) FROM #TMP_LISTADIRECCIONES

					WHILE(@K <=@CANTIDAD)
						BEGIN

							IF(@TOTALDIR > 0)
							BEGIN
								SELECT @COD_UBIGEO=CODUBIGEODEST, @DIRECCION=DIRECCION
								FROM #TMP_LISTADIRECCIONES 
								WHERE ID_COTDETALLE=@ID_COTDETALLE AND @K BETWEEN INICIO AND FIN
							END
							ELSE
							BEGIN
								SELECT @COD_UBIGEO='',@DIRECCION=''
							END

							INSERT INTO TBD_DESPACHO_DIST(ID_DESPACHO,ID_COTDETALLE,NUMSEC,COD_UBIGEO,DIRECCION,USR_REG,FEC_REG)
							VALUES(@ID_DESPACHO,@ID_COTDETALLE,@K ,@COD_UBIGEO,@DIRECCION,@USRREG,GETDATE())

							SET @K = @K + 1
						END
					
					TRUNCATE TABLE #TMP_LISTADIRECCIONES
					SET @J = @J + 1
				END

				TRUNCATE TABLE #TMP_LISTAUNIDAD

			END


			SET @I = @I+1
		END



		--CAMBIO DE ESTADO DE LA SOLICITUD: En proceso de Ventas: (PRVT) 
		UPDATE TBM_SOLICITUDVENTA 
			SET ESTADO='PRVT'
			WHERE ID_SOLICITUD=@CODSOLICITUD;

		--SE REGISTRA LOG DE CAMBIO DE ESTADO:

		INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
		VALUES(@ID_WORKFLOW,'PRVT',@NOMPERFIL,@USRREG,GETDATE());

		--VALIDACION DE INDICADOR DE INSTALACION DE EQUIPO: ENVIO DE CORREO A SERVICIO TECNICO.
		IF EXISTS(SELECT * FROM TBM_COTDET_DESPACHO WHERE ID_COTDETALLE IN (SELECT ID FROM TBD_COTIZACIONVENTA A
																																	INNER JOIN TBM_COTIZACIONVENTA B ON A.ID_COTIZACION=B.ID_COTIZACION
																																		WHERE B.ID_SOLICITUD=@CODSOLICITUD) AND INDINSTALACION='S')
		BEGIN
				SET @CODIGO=2
		END
		ELSE
		BEGIN
				SET  @CODIGO = 1
		END
		
		SET @MSG ='Se realizó el registro de despacho con éxito'

	END

	IF(@TIPO = 'U')
	BEGIN
		
		UPDATE TBM_DESPACHO
		SET NUMORDEN = @NUMRODEN,
				FECHAORDEN = @FECHAORDEN,
				FECHAMAX = @FECHAMAX,
				USR_MOD = @USRREG,
				FEC_MOD = GETDATE()
				WHERE ID_SOLICITUD = @CODSOLICITUD;

		SET  @CODIGO = 1
		SET @MSG ='Se actualizó el registro de despacho con éxito'

	END

	IF(@TIPO = 'P') --GUARDAR:
	BEGIN
		
		UPDATE TBM_DESPACHO
			SET FECHAENTREGA =@FECHAENTREGA,
				   NUMFACTURA = @NUMFACTURA,
				   NUMGUIAREM = @NUMGUIAREM,
				   GESLOG = 1,
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = @STOCK;

		IF(@TIPO_SOL IN ('TSOL02','TSOL04','TSOL05')) --VENTA DE REPUESTOS,MATERIALES Y EQUIPOS
		BEGIN
				DECLARE @TOT INT,@CANT INT,@CANT_FAC INT
				SELECT @TOT= COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@CODSOLICITUD;
				SELECT @CANT=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@CODSOLICITUD AND GESLOG =1;
				SELECT @CANT_FAC=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@CODSOLICITUD AND GESFAC =1 ;

	


				IF(@TOT =@CANT )
				BEGIN
				--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
					UPDATE TBM_DESPACHO SET ENVIOVT=1 WHERE  ID_SOLICITUD= @CODSOLICITUD;

					UPDATE TBM_SOLICITUDVENTA 
					SET ESTADO='VTPG',
					  USR_MOD = @USRREG,
				      FEC_MOD = GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD;

				--SE REGISTRA LOG DE CAMBIO DE ESTADO:

				INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
				VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());
				END
			
		END
			
		SET  @CODIGO = 1

		IF EXISTS(SELECT 1 FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD= @CODSOLICITUD AND ESTADO='VTPG')
		BEGIN
			SET @CODIGO = 2
				IF EXISTS(SELECT * FROM TBM_COTDET_DESPACHO WHERE ID_COTDETALLE IN (SELECT ID FROM TBD_COTIZACIONVENTA A
																																	INNER JOIN TBM_COTIZACIONVENTA B ON A.ID_COTIZACION=B.ID_COTIZACION
																																		WHERE B.ID_SOLICITUD=@CODSOLICITUD) AND INDINSTALACION='S')
				BEGIN
						SET @CODIGO=3
				END
		END

		SET @MSG ='Se actualizó el registro de despacho con éxito'
	END

	IF(@TIPO = 'Y')
	BEGIN
		
		UPDATE TBM_DESPACHO
			SET NUMPEDIDO =  @NUMPEDIDO,
				   FECHAINGRESO = @FECHAINGRESO,
				   ESTAPROB='IMP',
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = 'N';
			
		SET  @CODIGO = 1
		SET @MSG ='Se actualizó el registro de importación con éxito'
	END

	IF(@TIPO = 'A')
	BEGIN
		UPDATE TBM_DESPACHO
			SET OBSERVACION ='',
				   FECAPROB = GETDATE(),
				   ESTAPROB = 'APR',
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = 'N';

		SELECT @NOMUSUARIO=RTRIM(ISNULL(NOMBRES,''))+' '+RTRIM(ISNULL(APELLIDOS,'')) 
		FROM TBM_SEGURIDAD_USUARIO
		WHERE UPPER(USUARIO) = UPPER(@USRREG);

		--SE REGISTRA LA OBSERVACION:
		INSERT INTO TBM_OBSERVACIONES(ID_WORKFLOW,ESTADO_INSTANCIA,OBSERVACION,NOMBRE_USUARIO,PERFIL_USUARIO,USR_REG,FEC_REG)
			VALUES(@ID_WORKFLOW,'PRVT','Se realiza la aprobación de la Importación',@NOMUSUARIO,@NOMPERFIL,@USRREG,GETDATE());


		SET  @CODIGO = 1
		SET @MSG ='Aprobación exitosa de la importación.'
	END

	IF(@TIPO = 'O')
	BEGIN
		UPDATE TBM_DESPACHO
			SET OBSERVACION =@OBSERVACION,
				   ESTAPROB = 'OBS',
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD= @CODSOLICITUD
				AND STOCK = 'N';

		SELECT @NOMUSUARIO=RTRIM(ISNULL(NOMBRES,''))+' '+RTRIM(ISNULL(APELLIDOS,'')) 
		FROM TBM_SEGURIDAD_USUARIO
		WHERE UPPER(USUARIO) = UPPER(@USRREG);

		--SE REGISTRA LA OBSERVACION:
		INSERT INTO TBM_OBSERVACIONES(ID_WORKFLOW,ESTADO_INSTANCIA,OBSERVACION,NOMBRE_USUARIO,PERFIL_USUARIO,USR_REG,FEC_REG)
			VALUES(@ID_WORKFLOW,'PRVT',RTRIM(@OBSERVACION),@NOMUSUARIO,@NOMPERFIL,@USRREG,GETDATE());

		--SE RESETEA EL ENVIO DE BO
		UPDATE TBM_DESPACHO 
			SET ENVIOBO=0,
					GENBO=0,
				   USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()
		WHERE ID_SOLICITUD=@CODSOLICITUD AND STOCK='N';

		SET  @CODIGO = 1
		SET @MSG ='Se observo el pedido de importación'
	END

	IF(@TIPO = 'X') ---MANDAR A EDITAR
	BEGIN

	UPDATE TBM_DESPACHO
	SET ENVIOVT = 1
	WHERE ID_SOLICITUD = @CODSOLICITUD AND STOCK = @STOCK; 

	DECLARE @TOTAL INT ,@TOTAL_GEST INT ,@CANT_FAC1 INT
	SELECT @TOTAL=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD;
	SELECT @TOTAL_GEST=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD AND GESLOG=1;
	SELECT @CANT_FAC1=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@CODSOLICITUD AND GESFAC =1 AND STOCK='X' ;

		IF(@TIPO_SOL IN ('TSOL03')) --SERVICIOS Y REPUESTOS:
		BEGIN
			SET @TOTAL_GEST = @TOTAL_GEST + ISNULL(@CANT_FAC1,0)
		END


	IF(@TOTAL = @TOTAL_GEST)
	BEGIN
		--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
		UPDATE TBM_SOLICITUDVENTA 
			SET ESTADO='VTPG',
					USR_MOD = @USRREG,
				    FEC_MOD = GETDATE()
			WHERE ID_SOLICITUD=@CODSOLICITUD;

		--SE REGISTRA LOG DE CAMBIO DE ESTADO:

		INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
		VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());
	END
	

		--VALIDACION DE INDICADOR DE INSTALACION DE EQUIPO: ENVIO DE CORREO A SERVICIO TECNICO.
		IF EXISTS(SELECT * FROM TBM_COTDET_DESPACHO WHERE ID_COTDETALLE IN (SELECT ID FROM TBD_COTIZACIONVENTA A
																																	INNER JOIN TBM_COTIZACIONVENTA B ON A.ID_COTIZACION=B.ID_COTIZACION
																																		WHERE B.ID_SOLICITUD=@CODSOLICITUD) AND INDINSTALACION='S')
		BEGIN
				SET @CODIGO=2
		END
		ELSE
		BEGIN
				SET  @CODIGO = 1
		END
	
		SET @MSG ='Se realizó la programacion de la venta'
	END

	IF(@TIPO = 'F') --GESTION DE FACTURACION PARA SERVICIOS:
	BEGIN
		--SE ACTUALIZA LOS CAMPOS DE LA FACTURA DEL DESPACHO:
		  UPDATE TBM_DESPACHO
			SET GESFAC = 1,
					FECHAFACTURA =@FECHAENTREGA,
					NUMFACTSERV = @NUMFACTURA,
					USR_MOD=@USRREG,
					FEC_MOD=GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD
					AND STOCK='X';


	IF(@TIPO_SOL ='TSOL01') --SOLO SERVICIOS:
	BEGIN
		--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
		UPDATE TBM_SOLICITUDVENTA 
			SET ESTADO='VTPG',
				  USR_MOD = @USRREG,
				   FEC_MOD = GETDATE()				
			WHERE ID_SOLICITUD=@CODSOLICITUD;

		--SE REGISTRA LOG DE CAMBIO DE ESTADO:

		INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
		VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());
	END

	IF(@TIPO_SOL ='TSOL03') --SOLO SERVICIOS Y REPUESTOS:
	BEGIN
	
		DECLARE @TOTALF INT ,@TOTAL_GEST1 INT,@TOTAL_FACT INT
		SELECT @TOTALF=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD;
		SELECT @TOTAL_GEST1=COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD AND GESLOG=1;
		SELECT @TOTAL_FACT = COUNT(1) FROM TBM_DESPACHO WHERE ID_SOLICITUD = @CODSOLICITUD AND GESFAC=1

		IF(@TOTALF = (@TOTAL_GEST1+@TOTAL_FACT))
		BEGIN
			--CAMBIO DE ESTADO DE LA SOLICITUD: Venta Programada: (VTPG) 
			UPDATE TBM_SOLICITUDVENTA 
				SET ESTADO='VTPG',
					  USR_MOD = @USRREG,
					   FEC_MOD = GETDATE()				
				WHERE ID_SOLICITUD=@CODSOLICITUD;

			--SE REGISTRA LOG DE CAMBIO DE ESTADO:

			INSERT INTO TBM_WORKFLOWLOG(ID_WORKFLOW,COD_ESTADO,CARGO,AUDIT_REG_USR,AUDIT_REG_FEC)
			VALUES(@ID_WORKFLOW,'VTPG',@NOMPERFIL,@USRREG,GETDATE());
		END

	END
		

		SET  @CODIGO = 1
		SET @MSG ='Se realizó la facturación del servicio'
	END

	IF(@TIPO = 'T')
	BEGIN
		--SE ACTUALIZA LA FECHA DE PROGRAMACION DEL TECNICO:
		  UPDATE TBM_DESPACHO
			SET FECHAPROGTEC =@FECHAENTREGA,
					USR_MOD=@USRREG,
					FEC_MOD=GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD;

		
		SET  @CODIGO = 1
		SET @MSG ='Se realizó la actualización de la fecha de programación'

	END

	IF(@TIPO ='G')
	BEGIN
		--SE ACTUALIZA EL LOG DE GENERACION DE GUIAS:
		  UPDATE TBM_DESPACHO
			SET GENGP =1,
					USR_MOD=@USRREG,
					FEC_MOD=GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD AND STOCK=@STOCK;

		
		SET  @CODIGO = 1
		SET @MSG ='Se realizó la actualizacion de generacion de guia de pedidos'
	END

	IF(@TIPO ='B')
	BEGIN
		--SE ACTUALIZA EL LOG DE GENERACION DE GUIAS:
		  UPDATE TBM_DESPACHO
			SET GENBO =1,
					USR_MOD=@USRREG,
					FEC_MOD=GETDATE()
					WHERE ID_SOLICITUD=@CODSOLICITUD AND STOCK=@STOCK;

		
		SET  @CODIGO = 1
		SET @MSG ='Se realizó la actualizacion de generacion de guia de BO'
	END

		SELECT @CODIGO COD ,@MSG MSG
		SET NOCOUNT OFF;

END