USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_DESPACHO] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Jose Peralta		14.11.24		Realiza consulta de datos del despacho.
	EXEC [USP_SEL_DESPACHO]  42
=======================================================================================================*/
	@isIdSolicitud BIGINT
)
AS
BEGIN

SET NOCOUNT ON;

	DECLARE @CONT_TOTAL INT, @CONT_CS INT, @CONT_SS INT,@ENVIOFC INT,@GESFAC INT
	DECLARE @FECHAPROGTEC VARCHAR(10),@FECHAFACTURA VARCHAR(10),@NUMFACTSERV VARCHAR(50)
	DECLARE @TIPOVENTA VARCHAR(6),@NUMORDEN VARCHAR(50),@FECHAORDEN VARCHAR(10),@FECHAMAX VARCHAR(10)
	DECLARE @NUM_CS INT ,@NUM_SS INT,@ENVIOGP_CS INT,@ENVIOGP_SS INT,@ENVIOBO_SS INT
	DECLARE @GESLOG_CS INT,@GESLOG_SS INT,@SERIE_CS INT,@SERIE_SS INT



	SELECT @TIPOVENTA=TIPO_SOL FROM TBM_SOLICITUDVENTA WHERE ID_SOLICITUD=@isIdSolicitud;

	
	 SELECT @CONT_TOTAL = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud;
	 SELECT @CONT_CS = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK='S';
	 SELECT @CONT_SS = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'N';
	 SELECT @ENVIOFC = ISNULL(ENVIOFC,0) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';
	 SELECT @GESFAC = ISNULL(GESFAC,0) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';

	SELECT @FECHAPROGTEC = ISNULL(CONVERT(VARCHAR,FECHAPROGTEC,103),'') FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';
	SELECT @FECHAFACTURA = ISNULL(CONVERT(VARCHAR,FECHAFACTURA,103),'') FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';
	SELECT @NUMFACTSERV = ISNULL(NUMFACTSERV,'') FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';


	SELECT @NUMORDEN=MAX(NUMORDEN),
				@FECHAORDEN =ISNULL(CONVERT(VARCHAR,MAX(FECHAORDEN),103),''),
				@FECHAMAX=ISNULL(CONVERT(VARCHAR,MAX(FECHAMAX),103),'') 
				FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud
	
	SELECT @NUM_CS=COUNT(1) FROM TBD_DESPACHO_DIST 
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S')

	SELECT @NUM_SS=COUNT(1) FROM TBD_DESPACHO_DIST 
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N')

		SELECT @ENVIOGP_CS=ENVIOGP ,
					  @GESLOG_CS =GESLOG
		FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S';

		SELECT @ENVIOGP_SS=ENVIOGP,
					  @ENVIOBO_SS=ENVIOBO,
					  @GESLOG_SS =GESLOG
		FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N';

		SELECT @SERIE_CS=COUNT(1) FROM TBD_DESPACHO_DIST
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S') 
				AND ISNULL(NUMSERIE,'') <> '' ;

		SELECT @SERIE_SS=COUNT(1) FROM TBD_DESPACHO_DIST
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N') 
				AND ISNULL(NUMSERIE,'') <> '' ;


			SELECT ISNULL(@isIdSolicitud,0) ID_SOLICITUD, 
		ISNULL(@NUMORDEN,'') NUMORDEN,
		ISNULL(@FECHAORDEN,'') FECHAORDEN,
		ISNULL(@FECHAMAX,'') FECHAMAX,
		ISNULL(@CONT_CS,0) CONT_CS,
		ISNULL(@CONT_SS,0) CONT_SS,
		ISNULL(@NUM_CS,0) NUM_CS,
		ISNULL(@NUM_SS,0) NUM_SS,
		ISNULL(@ENVIOGP_CS,0) ENVIOGP_CS,
		ISNULL(@ENVIOGP_SS,0) ENVIOGP_SS,
		ISNULL(@ENVIOBO_SS,0)  ENVIOBO_SS,
		ISNULL(@GESLOG_CS,0) GESLOG_CS,
		ISNULL(@GESLOG_SS,0)  GESLOG_SS,
		ISNULL(@SERIE_CS,0) SERIE_CS,
		ISNULL(@SERIE_SS,0) SERIE_SS,
		ISNULL(@ENVIOFC,0)  ENVIOFC,
		ISNULL(@GESFAC,0)  GESFAC,
		ISNULL(@FECHAPROGTEC,'') FECHAPROGTEC,
		ISNULL(@FECHAFACTURA,'') FECHAFACTURA,
		ISNULL(@NUMFACTSERV,'') NUMFACTSERV



	SELECT  ID,ID_SOLICITUD,STOCK,NUMORDEN,
	CONVERT(VARCHAR,FECHAORDEN,103) FECHAORDEN,
	CONVERT(VARCHAR,FECHAMAX,103) FECHAMAX,
	ISNULL(CONVERT(VARCHAR,FECHAENTREGA,103),'') FECHAENTREGA,
	ISNULL(NUMFACTURA,'') NUMFACTURA,
	ISNULL(NUMGUIAREM,'') NUMGUIAREM,
	ISNULL(NUMPEDIDO,'') NUMPEDIDO,
	ISNULL(CONVERT(VARCHAR,FECHAINGRESO,103),'') FECHAINGRESO,
	ISNULL(ESTAPROB,'') ESTAPROB,
	ISNULL(CONVERT(VARCHAR,FECAPROB,103),'') FECAPROB,
	ISNULL(OBSERVACION,'') OBSERVACION,
	ISNULL(NUMFACTSERV,'') NUMFACTSERV,
	ISNULL(CONVERT(VARCHAR,FECHAFACTURA,103),'') FECHAFACTURA,
	ISNULL(CONVERT(VARCHAR,FECHAPROGTEC,103),'') FECHAPROGTEC,
	USR_REG,
	FEC_REG,
	USR_MOD,
	FEC_MOD
	FROM TBM_DESPACHO A WITH(NOLOCK) WHERE ID_SOLICITUD= @isIdSolicitud AND STOCK='S'

	SELECT ROW_NUMBER() OVER (ORDER BY A.ID) AS ROWNUM,
	B.CODITEM CODEQUIPO,
	B.DESCRIPCION,
	E.TG_CDESCRI MARCA,
	ISNULL(A.NUMSERIE,'') NUMSERIE ,
	A.ID
	FROM TBM_COTIZACIONVENTA CV 
	INNER JOIN TBD_COTIZACIONVENTA B ON CV.ID_COTIZACION = B.ID_COTIZACION
	INNER JOIN TBD_DESPACHO_DIST A ON A.ID_COTDETALLE = B.ID
	INNER JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON B.CODITEM = D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD = 'V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	WHERE 
	CV.ID_SOLICITUD = @isIdSolicitud AND
	A.ID_DESPACHO IN (SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S' )


	SELECT  ID,ID_SOLICITUD,STOCK,NUMORDEN,
	CONVERT(VARCHAR,FECHAORDEN,03) FECHAORDEN,
	CONVERT(VARCHAR,FECHAMAX,103) FECHAMAX,
	ISNULL(CONVERT(VARCHAR,FECHAENTREGA,103),'') FECHAENTREGA,
	ISNULL(NUMFACTURA,'') NUMFACTURA,
	ISNULL(NUMGUIAREM,'') NUMGUIAREM,
	ISNULL(NUMPEDIDO,'') NUMPEDIDO,
	ISNULL(CONVERT(VARCHAR,FECHAINGRESO,103),'') FECHAINGRESO,
	ISNULL(ESTAPROB,'') ESTAPROB,
	ISNULL(CONVERT(VARCHAR,FECAPROB,103),'') FECAPROB,
	ISNULL(OBSERVACION,'') OBSERVACION,
	ISNULL(NUMFACTSERV,'') NUMFACTSERV,
	ISNULL(CONVERT(VARCHAR,FECHAFACTURA,103),'') FECHAFACTURA,
	ISNULL(CONVERT(VARCHAR,FECHAPROGTEC,103),'') FECHAPROGTEC,
	USR_REG,
	FEC_REG,
	USR_MOD,
	FEC_MOD
	FROM TBM_DESPACHO A WITH(NOLOCK) WHERE ID_SOLICITUD= @isIdSolicitud AND STOCK='N'

	SELECT ROW_NUMBER() OVER (ORDER BY A.ID) AS ROWNUM,
	C.CODITEM CODEQUIPO,
	C.DESCRIPCION,
	E.TG_CDESCRI MARCA,
	ISNULL(A.NUMSERIE,'') NUMSERIE,
	A.ID
	FROM TBD_DESPACHO_DIST A WITH(NOLOCK) 
	INNER JOIN TBD_COTIZACIONVENTA C ON A.ID_COTDETALLE=C.ID
	INNER JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON C.CODITEM=D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	WHERE 
	A.ID_DESPACHO IN (SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N' )

	SET NOCOUNT OFF;

END