USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_VAL_DESPACHO] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Jose Peralta		14.11.24		Realiza consulta de la validacion del despacho.
	EXEC [USP_VAL_DESPACHO] 11
=======================================================================================================*/
	@isIdSolicitud BIGINT
)
AS
BEGIN

SET NOCOUNT ON;


	DECLARE @CONT_TOTAL INT, @CONT_CS INT, @CONT_SS INT,@ENVIOFC INT,@GESFAC INT
	DECLARE @TIPOVENTA VARCHAR(6),@NUMORDEN VARCHAR(50),@FECHAORDEN VARCHAR(10),@FECHAMAX VARCHAR(10)
	DECLARE @NUM_CS INT ,@NUM_SS INT,@ENVIOGP_CS INT,@ENVIOGP_SS INT,@ENVIOBO_SS INT
	DECLARE @GESLOG_CS INT,@GESLOG_SS INT,@SERIE_CS INT,@SERIE_SS INT,@ENVIOVT_CS INT,@ENVIOVT_SS INT 
	DECLARE @GENGP_CS INT, @GENGP_SS INT, @GENBO_SS INT,@TIPODESPACHO CHAR(1),@GENMAN_SERV INT
	
	 SELECT @CONT_TOTAL = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud;
	 SELECT @CONT_CS = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK='S';
	 SELECT @CONT_SS = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'N';
	 SELECT @ENVIOFC = ISNULL(ENVIOFC,0) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';
	 SELECT @GESFAC = ISNULL(GESFAC,0) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'X';

	 
	SELECT @NUMORDEN=MAX(NUMORDEN),
				@FECHAORDEN =ISNULL(CONVERT(VARCHAR,MAX(FECHAORDEN),103),''),
				@FECHAMAX=ISNULL(CONVERT(VARCHAR,MAX(FECHAMAX),103),'') 
				FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud

	SELECT @NUM_CS=COUNT(1) FROM TBD_DESPACHO_DIST 
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S')

	SELECT @NUM_SS=COUNT(1) FROM TBD_DESPACHO_DIST 
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N')

	SELECT @ENVIOGP_CS=ENVIOGP ,
					  @GESLOG_CS =GESLOG,
					  @ENVIOVT_CS = ENVIOVT
		FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S';

		SELECT @ENVIOGP_SS=ENVIOGP,
					  @ENVIOBO_SS=ENVIOBO,
					  @GESLOG_SS =GESLOG,
					  @ENVIOVT_SS =ENVIOVT
		FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N';

		SELECT @SERIE_CS=COUNT(1) FROM TBD_DESPACHO_DIST
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S') 
				AND ISNULL(NUMSERIE,'') <> '' ;

		SELECT @SERIE_SS=COUNT(1) FROM TBD_DESPACHO_DIST
		WHERE ID_DESPACHO =(SELECT ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N') 
				AND ISNULL(NUMSERIE,'') <> '' ;


		SELECT @TIPODESPACHO=MAX(TIPODESP) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud;



	SELECT @GENGP_CS=ISNULL(GENGP,0) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='S'
	SELECT @GENGP_SS=ISNULL(GENGP,0) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N'
	SELECT @GENBO_SS=ISNULL(GENBO,0) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='N'
	SELECT @GENMAN_SERV = ISNULL(GENGP,0) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@isIdSolicitud AND STOCK='X'

	 SELECT ISNULL(@isIdSolicitud,0) ID_SOLICITUD, 
					ISNULL(@NUMORDEN,0) NUMORDEN,
					ISNULL(@FECHAORDEN,0) FECHAORDEN,
					ISNULL(@FECHAMAX,0) FECHAMAX,
					ISNULL(@CONT_CS,0) CONT_CS,
					ISNULL(@CONT_SS,0) CONT_SS,
					ISNULL(@NUM_CS,0) NUM_CS,
					ISNULL(@NUM_SS,0) NUM_SS,
					ISNULL(@ENVIOGP_CS,0)  ENVIOGP_CS,
					ISNULL(@ENVIOGP_SS,0) ENVIOGP_SS,
					ISNULL(@ENVIOBO_SS,0)  ENVIOBO_SS,
					ISNULL(@GESLOG_CS,0) GESLOG_CS,
					ISNULL(@GESLOG_SS,0)  GESLOG_SS,
					ISNULL(@SERIE_CS,0) SERIE_CS,
					ISNULL(@SERIE_SS,0) SERIE_SS,
					ISNULL(@ENVIOFC,0)  ENVIOFC,
					ISNULL(@GESFAC,0) GESFAC,
					ISNULL(@ENVIOVT_CS,0)  ENVIOVT_CS,
					ISNULL(@ENVIOVT_SS,0)  ENVIOVT_SS,
					ISNULL(@GENGP_CS,0) GENGP_CS,
					ISNULL(@GENGP_SS,0) GENGP_SS,
					ISNULL(@GENBO_SS,0) GENBO_SS,
					ISNULL(@TIPODESPACHO,'') TIPODESPACHO,
					ISNULL(@GENMAN_SERV,0) GENMAN_SERV

			SET NOCOUNT OFF;

END