USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_VAL_DESPACHO] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Jose Peralta		14.11.24		Realiza consulta de la validacion del despacho.
	EXEC [USP_VAL_DESPACHO]  20
=======================================================================================================*/
	@isIdSolicitud BIGINT
)
AS
BEGIN

SET NOCOUNT ON;


		DECLARE @CONT_TOTAL INT, @CONT_CS INT, @CONT_SS INT

	IF OBJECT_ID('tempdb..#TMP_DESPACHO') IS NOT NULL
		DROP TABLE #TMP_DESPACHO

	CREATE TABLE #TMP_DESPACHO(
		IDNUM INT IDENTITY(1,1),
		ID_SOLICITUD BIGINT,
		ID INT ,
		STOCK CHAR(1),
		NUMORDEN VARCHAR(50),
		FECHAORDEN VARCHAR(10),
		FECHAMAX VARCHAR(10),
		ENVIOGP BIT,
		ENVIOBO BIT,
		GESLOG BIT
	);

	INSERT INTO #TMP_DESPACHO
    		SELECT ID_SOLICITUD,ID,STOCK,NUMORDEN,
			ISNULL(CONVERT(VARCHAR,FECHAORDEN,103),'') FECHAORDEN,
			ISNULL(CONVERT(VARCHAR,FECHAMAX,103),'') FECHAMAX,
			ISNULL(ENVIOGP,0) ENVIOGP,
			ISNULL(ENVIOBO,0) ENVIOBO,
			ISNULL(GESLOG,0) GESLOG
						  FROM TBM_DESPACHO WHERE ID_SOLICITUD = @isIdSolicitud

	
	 SELECT @CONT_TOTAL = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud;
	 SELECT @CONT_CS = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK='S';
	 SELECT @CONT_SS = COUNT(1) FROM TBM_DESPACHO WITH(NOLOCK) WHERE ID_SOLICITUD = @isIdSolicitud AND STOCK = 'N';

	 IF(@CONT_TOTAL >1) 
	 BEGIN

		WITH CON_STOCK AS (
		SELECT ID_SOLICITUD,  ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG,
		COUNT(1) CONTADOR 
		FROM #TMP_DESPACHO WHERE STOCK='S'
		GROUP BY ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG
		),
		SIN_STOCK AS (
				SELECT  ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG,
				COUNT(1) CONTADOR 
				FROM #TMP_DESPACHO WHERE STOCK='N'
				GROUP BY ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG
		),
		CONTAR_CS AS (
		SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST  A
		INNER JOIN CON_STOCK  B ON A.ID_DESPACHO=B.ID
		GROUP BY B.ID
		),
		CONTAR_SS AS (
		SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST  A
		INNER JOIN SIN_STOCK  B ON A.ID_DESPACHO=B.ID
		GROUP BY B.ID
		),
		SERIES_CS AS(
			SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST A 
			INNER JOIN CON_STOCK B ON A.ID_DESPACHO=B.ID
			WHERE ISNULL(A.NUMSERIE,'') <> '' 
			GROUP BY B.ID
		),
		SERIES_SS AS(
			SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST A 
			INNER JOIN SIN_STOCK B ON A.ID_DESPACHO=B.ID
			WHERE ISNULL(A.NUMSERIE,'') <> '' 
			GROUP BY B.ID
		)
		SELECT ISNULL(A.ID_SOLICITUD,B.ID_SOLICITUD) ID_SOLICITUD, 
		ISNULL(A.NUMORDEN,B.NUMORDEN) NUMORDEN,
		ISNULL(A.FECHAORDEN,B.FECHAORDEN) FECHAORDEN,
		ISNULL(A.FECHAMAX,B.FECHAMAX) FECHAMAX,
		ISNULL(A.CONTADOR,0) CONT_CS,
		ISNULL(B.CONTADOR,0) CONT_SS,
		ISNULL(C.CONTADOR,0) NUM_CS,
		ISNULL(D.CONTADOR,0) NUM_SS,
		CAST(ISNULL(A.ENVIOGP,0) AS INT) ENVIOGP_CS,
		CAST(ISNULL(B.ENVIOGP,0)AS INT) ENVIOGP_SS,
		CAST(ISNULL(B.ENVIOBO,0) AS INT) ENVIOBO_SS,
		CAST(ISNULL(A.GESLOG,0)AS INT) GESLOG_CS,
		CAST(ISNULL(B.GESLOG,0) AS INT) GESLOG_SS,
		ISNULL(E.CONTADOR,0) SERIE_CS,
		ISNULL(F.CONTADOR,0) SERIE_SS
		FROM  CON_STOCK A 
		LEFT JOIN SIN_STOCK B ON A.ID_SOLICITUD=B.ID_SOLICITUD
		LEFT JOIN CONTAR_CS C ON A.ID=C.ID
		LEFT JOIN CONTAR_SS D ON A.ID=D.ID
		LEFT JOIN SERIES_CS E ON A.ID=E.ID
		LEFT JOIN SERIES_SS F ON A.ID=F.ID;

	 END
	 ELSE
	 BEGIN
			IF(@CONT_CS > 0)
			BEGIN
							WITH CON_STOCK AS (
				SELECT ID_SOLICITUD,  ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG,
				COUNT(1) CONTADOR 
				FROM #TMP_DESPACHO WHERE STOCK='S'
				GROUP BY ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG
				),
				SIN_STOCK AS (
						SELECT  ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG,
						COUNT(1) CONTADOR 
						FROM #TMP_DESPACHO WHERE STOCK='N'
						GROUP BY ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG
				),
				CONTAR_CS AS (
				SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST  A
				INNER JOIN CON_STOCK  B ON A.ID_DESPACHO=B.ID
				GROUP BY B.ID
				),
				CONTAR_SS AS (
				SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST  A
				INNER JOIN SIN_STOCK  B ON A.ID_DESPACHO=B.ID
				GROUP BY B.ID
				),
				SERIES_CS AS(
					SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST A 
					INNER JOIN CON_STOCK B ON A.ID_DESPACHO=B.ID
					WHERE ISNULL(A.NUMSERIE,'') <> '' 
					GROUP BY B.ID
				),
				SERIES_SS AS(
					SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST A 
					INNER JOIN SIN_STOCK B ON A.ID_DESPACHO=B.ID
					WHERE ISNULL(A.NUMSERIE,'') <> '' 
					GROUP BY B.ID
				)
				SELECT ISNULL(A.ID_SOLICITUD,B.ID_SOLICITUD) ID_SOLICITUD, 
				ISNULL(A.NUMORDEN,B.NUMORDEN) NUMORDEN,
				ISNULL(A.FECHAORDEN,B.FECHAORDEN) FECHAORDEN,
				ISNULL(A.FECHAMAX,B.FECHAMAX) FECHAMAX,
				ISNULL(A.CONTADOR,0) CONT_CS,
				ISNULL(B.CONTADOR,0) CONT_SS,
				ISNULL(C.CONTADOR,0) NUM_CS,
				ISNULL(D.CONTADOR,0) NUM_SS,
				CAST(ISNULL(A.ENVIOGP,0) AS INT) ENVIOGP_CS,
				CAST(ISNULL(B.ENVIOGP,0)AS INT) ENVIOGP_SS,
				CAST(ISNULL(B.ENVIOBO,0) AS INT) ENVIOBO_SS,
				CAST(ISNULL(A.GESLOG,0)AS INT) GESLOG_CS,
				CAST(ISNULL(B.GESLOG,0) AS INT) GESLOG_SS,
				ISNULL(E.CONTADOR,0) SERIE_CS,
				ISNULL(F.CONTADOR,0) SERIE_SS
				FROM  CON_STOCK A 
				LEFT JOIN SIN_STOCK B ON A.ID_SOLICITUD=B.ID_SOLICITUD
				LEFT JOIN CONTAR_CS C ON A.ID=C.ID
				LEFT JOIN CONTAR_SS D ON A.ID=D.ID
				LEFT JOIN SERIES_CS E ON A.ID=E.ID
				LEFT JOIN SERIES_SS F ON A.ID=F.ID;
			END

			IF(@CONT_SS > 0)
			BEGIN
						WITH CON_STOCK AS (
				SELECT ID_SOLICITUD,  ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG,
				COUNT(1) CONTADOR 
				FROM #TMP_DESPACHO WHERE STOCK='S'
				GROUP BY ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG
				),
				SIN_STOCK AS (
						SELECT  ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG,
						COUNT(1) CONTADOR 
						FROM #TMP_DESPACHO WHERE STOCK='N'
						GROUP BY ID_SOLICITUD,ID,NUMORDEN,FECHAORDEN,FECHAMAX,ENVIOGP,ENVIOBO,GESLOG
				),
				CONTAR_CS AS (
				SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST  A
				INNER JOIN CON_STOCK  B ON A.ID_DESPACHO=B.ID
				GROUP BY B.ID
				),
				CONTAR_SS AS (
				SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST  A
				INNER JOIN SIN_STOCK  B ON A.ID_DESPACHO=B.ID
				GROUP BY B.ID
				),
				SERIES_CS AS(
					SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST A 
					INNER JOIN CON_STOCK B ON A.ID_DESPACHO=B.ID
					WHERE ISNULL(A.NUMSERIE,'') <> '' 
					GROUP BY B.ID
				),
				SERIES_SS AS(
					SELECT B.ID,COUNT(1) CONTADOR FROM TBD_DESPACHO_DIST A 
					INNER JOIN SIN_STOCK B ON A.ID_DESPACHO=B.ID
					WHERE ISNULL(A.NUMSERIE,'') <> '' 
					GROUP BY B.ID
				)
				SELECT ISNULL(A.ID_SOLICITUD,B.ID_SOLICITUD) ID_SOLICITUD, 
				ISNULL(A.NUMORDEN,B.NUMORDEN) NUMORDEN,
				ISNULL(A.FECHAORDEN,B.FECHAORDEN) FECHAORDEN,
				ISNULL(A.FECHAMAX,B.FECHAMAX) FECHAMAX,
				ISNULL(B.CONTADOR,0) CONT_CS,
				ISNULL(A.CONTADOR,0) CONT_SS,
				ISNULL(C.CONTADOR,0) NUM_CS,
				ISNULL(D.CONTADOR,0) NUM_SS,
				CAST(ISNULL(B.ENVIOGP,0) AS INT) ENVIOGP_CS,
				CAST(ISNULL(A.ENVIOGP,0)AS INT) ENVIOGP_SS,
				CAST(ISNULL(A.ENVIOBO,0) AS INT) ENVIOBO_SS,
				CAST(ISNULL(B.GESLOG,0)AS INT) GESLOG_CS,
				CAST(ISNULL(A.GESLOG,0) AS INT) GESLOG_SS,
				ISNULL(E.CONTADOR,0) SERIE_CS,
				ISNULL(F.CONTADOR,0) SERIE_SS
				FROM  SIN_STOCK A 
				LEFT JOIN CON_STOCK B ON A.ID_SOLICITUD=B.ID_SOLICITUD
				LEFT JOIN CONTAR_CS C ON A.ID=C.ID
				LEFT JOIN CONTAR_SS D ON A.ID=D.ID
				LEFT JOIN SERIES_CS E ON A.ID=E.ID
				LEFT JOIN SERIES_SS F ON A.ID=F.ID;


			END

	 END

			SET NOCOUNT OFF;

END