USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_CONSULTA_DETALLEDESPACHO] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Jose Peralta		14.11.24		Realiza consulta de detalle del despacho.
	EXEC [USP_CONSULTA_DETALLEDESPACHO]  20
=======================================================================================================*/
	@IDDETALLEDESPACHO BIGINT
)
AS
BEGIN

	SELECT A.ID,A.ID_DESPACHO ,
	ROW_NUMBER() OVER (ORDER BY A.ID) AS ROWNUM,
	C.CODITEM CODEQUIPO,
	C.DESCRIPCION,
	E.TG_CDESCRI MARCA,
	ISNULL(A.NUMSERIE,'') NUMSERIE ,
	ISNULL(A.COD_UBIGEO,'') COD_UBIGEO,
	CASE WHEN(LEN(ISNULL(A.COD_UBIGEO,'') )> 0) THEN	ISNULL(F.NOMDEPARTAMENTO,'')+'/'+ISNULL(F.NOMPROVINCIA,'')+'/'+ISNULL(F.NOMDISTRITO,'') ELSE '' END NOMUBIGEO,
	ISNULL(A.DIRECCION,'') DIRECCION,
	A.NROPISO NROPISO,
	ISNULL(A.RUTA_DOCUMENTO,'') RUTA_DOCUMENTO,
	ISNULL(A.NUM_GUIA,'') NUM_GUIA,
	ISNULL(A.ID_DOCUMENTO,0) ID_DOCUMENTO
	FROM TBD_DESPACHO_DIST A WITH(NOLOCK)
	INNER JOIN TBD_COTIZACIONVENTA C ON A.ID_COTDETALLE=C.ID
	LEFT JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON C.CODITEM=D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	LEFT JOIN TBM_UBIGEO F WITH(NOLOCK) ON A.COD_UBIGEO=F.CODUBIGEO
	WHERE A.ID= @IDDETALLEDESPACHO AND ISNULL(C.ELIMINADO,'N') != 'S'

END