USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_CONSULTA_DETALLEDESPACHO] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Jose Peralta		14.11.24		Realiza consulta de detalle del despacho.
	EXEC [USP_CONSULTA_DETALLEDESPACHO]  20
=======================================================================================================*/
	@IDDETALLEDESPACHO BIGINT
)
AS
BEGIN

	SELECT A.ID,A.ID_DESPACHO ,
	ROW_NUMBER() OVER (ORDER BY A.ID) AS ROWNUM,
	C.CODITEM CODEQUIPO,
	C.DESCRIPCION,
	E.TG_CDESCRI MARCA,
	ISNULL(A.NUMSERIE,'') NUMSERIE 
	FROM TBD_DESPACHO_DIST A WITH(NOLOCK)
	INNER JOIN TBD_COTIZACIONCOSTOS B ON A.ID_COTCOSTOS=B.ID
	INNER JOIN TBD_COTIZACIONVENTA C ON B.ID_COTDETALLE=C.ID
	INNER JOIN [AH-SRV4].[RSFACCAR].[dbo].[AL0007ARTI] D WITH(NOLOCK) ON C.CODITEM=D.AR_CCODIGO
	LEFT JOIN  [AH-SRV4].[RSFACCAR].[dbo].[AL0007TABL] E WITH(NOLOCK) ON E.TG_CCOD='V7' AND D.AR_CMARCA=E.TG_CCLAVE 
	WHERE A.ID= @IDDETALLEDESPACHO

END