USE [DB_AHSECO]
GO


CREATE OR ALTER PROCEDURE [dbo].[USP_ACTUALIZAR_SERIE] 
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Jose Peralta		14.11.24		Realiza la actualizacion de series por codigo detalle de despacho
	EXEC [USP_ACTUALIZAR_SERIE]  1,'XXXXX'
=======================================================================================================*/
	@IDDETALLEDESPACHO BIGINT,
	@NUMSERIE VARCHAR(50),
	@CODUBIGEO VARCHAR(6),
	@DIRECCION VARCHAR(150),
	@NROPISO INT,
	@NROGUIA VARCHAR(50),
	@RUTADOC VARCHAR(350),
	@TIPO VARCHAR(1),
	@IDS VARCHAR(8000),
	@SERIES VARCHAR(8000),
	@GUIAS VARCHAR(8000),
	@USRREG VARCHAR(50),
	@IDDOCUMENTO BIGINT
)
AS
BEGIN
		SET NOCOUNT ON;

		DECLARE @CODIGO BIGINT,@MSG VARCHAR(250),@ID_DESPACHO INT
		SET @CODIGO=2

		IF OBJECT_ID('tempdb..#TMP_IDS') IS NOT NULL
		DROP TABLE #TMP_IDS

		CREATE TABLE #TMP_IDS(ID INT IDENTITY(1,1),IDDETALLEDESPACHO BIGINT);

		IF OBJECT_ID('tempdb..#TMP_SERIES') IS NOT NULL
		DROP TABLE #TMP_SERIES

		CREATE TABLE #TMP_SERIES(ID INT IDENTITY(1,1),SERIE VARCHAR(50));

		IF OBJECT_ID('tempdb..#TMP_GUIAS') IS NOT NULL
		DROP TABLE #TMP_GUIAS

		CREATE TABLE #TMP_GUIAS(ID INT IDENTITY(1,1),NROGUIA VARCHAR(50));

		BEGIN TRY

		IF(@TIPO = 'U')
		BEGIN
			SELECT @ID_DESPACHO=ID_DESPACHO 
				FROM TBD_DESPACHO_DIST WHERE ID=@IDDETALLEDESPACHO;
			
			IF EXISTS(SELECT 1 FROM TBD_DESPACHO_DIST WHERE  NUMSERIE=@NUMSERIE AND ID NOT IN(@IDDETALLEDESPACHO)) AND ISNULL(@NUMSERIE,'') != ''
			BEGIN
						SET @CODIGO=0
						SET @MSG ='La serie ingresada ya se encuentra registrada.'
			END
			ELSE
			BEGIN
					UPDATE TBD_DESPACHO_DIST
					SET NUMSERIE = @NUMSERIE,
							COD_UBIGEO=@CODUBIGEO,
							DIRECCION=@DIRECCION,
							NROPISO =@NROPISO, 
							RUTA_DOCUMENTO=@RUTADOC,
							ID_DOCUMENTO =@IDDOCUMENTO,
							NUM_GUIA=@NROGUIA,
							USR_MOD =@USRREG,
							FEC_MOD=GETDATE()
					WHERE ID= @IDDETALLEDESPACHO;

					SET @CODIGO=1
					SET @MSG ='Se actualizo de manera correcta los datos de despacho'
			END		
		END
		ELSE
		BEGIN

			INSERT INTO #TMP_IDS
			SELECT CAST(value AS BIGINT)
			FROM STRING_SPLIT(@IDS, ',');
			
			INSERT INTO #TMP_SERIES
			SELECT value AS Elemento
			FROM STRING_SPLIT(@SERIES, ',');

			INSERT INTO #TMP_GUIAS
			SELECT value AS Elemento
			FROM STRING_SPLIT(@GUIAS, ',');


			DECLARE @I INT,@TOTAL INT,@NUMSER VARCHAR(50)

			SELECT @I=1,@TOTAL=COUNT(1) FROM #TMP_SERIES

			WHILE(@I <=@TOTAL)
			BEGIN
				SELECT @NUMSER=SERIE FROM #TMP_SERIES WHERE ID=@I
				IF EXISTS(SELECT 1 FROM TBD_DESPACHO_DIST WHERE NUMSERIE = @NUMSER)
				BEGIN
						SET @CODIGO=0
						SET @MSG ='La serie '+@NUMSER+' ya se encuentra registrada.'
					BREAK
				END
						
				SET @I=@I+1
			END

			IF(@CODIGO = 2)
			BEGIN
					
					UPDATE  A
					SET A.NUM_GUIA = C.NROGUIA,
						   A.NUMSERIE =D.SERIE,
						   A.COD_UBIGEO=@CODUBIGEO,
						   A.DIRECCION=@DIRECCION,
						   A.RUTA_DOCUMENTO=@RUTADOC,
						    A.ID_DOCUMENTO =@IDDOCUMENTO,
						   A.USR_MOD =@USRREG,
						   A.FEC_MOD=GETDATE()
					FROM TBD_DESPACHO_DIST A
					INNER JOIN #TMP_IDS B ON A.ID=B.IDDETALLEDESPACHO
					INNER JOIN #TMP_GUIAS C ON B.ID = C.ID
					INNER JOIN #TMP_SERIES D ON B.ID=D.ID


					SET @CODIGO=1
					SET @MSG ='Se actualizo de manera correcta los datos de despacho'
			END

		END

			

		END TRY
		BEGIN CATCH
			SET @CODIGO = 0
			SET @MSG=ERROR_MESSAGE();
		END CATCH


		SELECT @CODIGO COD ,@MSG MSG

		SET NOCOUNT OFF;


END