USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_GAR_SEL_FILTROS]
/*=================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		18/11/2024	Extrae los filtros para la bandeja garantias.
	EXEC [USP_GAR_SEL_FILTROS]
  =================================================================================================*/
AS
BEGIN
	--ComboBox Empresas
	SELECT D.COD_VALOR1 CODEMPRESA, D.VALOR1 RAZONSOCIAL FROM TBD_DATOS_GENERALES D WHERE DOMINIO='RAZSOCIAL' AND ESTADO=1
	--ComboBox Estado
	SELECT COD_ESTADO Codigo, ABREV_ESTADO Abrev FROM TBM_PROCESOESTADOS WHERE ID_PROCESO = 7
	--ComboBox Clientes
	SELECT RUCEMPRESA ID, NOMEMPRESA FROM TBM_CLIENTES
	--ComboBox para Tip.Ventas
	SELECT COD_VALOR1 CODVENTA, VALOR1 DESCVENTA FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'TIPOVENTA' AND ESTADO = 1
	--ComboBox Tipo de Empleado
	SELECT COD_VALOR1 CODTIPO, DESCRIPCION DESCTIPO FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'TIPEMPL' AND ESTADO = 1
	--ComboBox Urgencia
	SELECT COD_VALOR1 CODURGENCIA, VALOR1 DESCURGENCIA FROM TBD_DATOS_GENERALES WHERE DOMINIO  = 'URGENCIA'
	--ComboBox Motivos
	SELECT COD_VALOR1 CODMOTIVO, VALOR1 DESCMOTIVO FROM TBD_DATOS_GENERALES WHERE DOMINIO  = 'MOTIVOSREC'

END
