USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_MANT_TBD_COTIZACIONCOSTOS]
(
@pTipoProceso CHAR(1),
@pId BIGINT,
@pId_CotDetalle BIGINT,
@pNumSec INT,
@pCodCosto NVARCHAR(10),
@pCantCosto INT,
@pCantPreventivo INT,
@pCodCicloPrevent NVARCHAR(10),
@pCodUbigeoDest NVARCHAR(6),
@pDireccion VARCHAR(150),
@pAmbienteDest VARCHAR(200),
@pNroPiso INT,
@pMontoUniCosto DECIMAL(18,9),
@pMontoTotCosto DECIMAL(18,9),
@pUsuarioRegistro VARCHAR(50)
)
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Samuel Gómez		19.11.24		mantenimiento de la tabla TBD_COTIZACIONCOSTOS con parametros.
  =======================================================================================================*/
AS
DECLARE @NUM INT
DECLARE @INDINFOVIDEO CHAR(1)
DECLARE @INDINFOMANUAL CHAR(1)
DECLARE @INDINSTALACION CHAR(1)
DECLARE @INDCAPACITACION CHAR(1)
DECLARE @INDGARANADIC CHAR(1)
DECLARE @INDMANTPREVENT CHAR(1)
DECLARE @INDCALIB CHAR(1)
DECLARE @INDFLETE CHAR(1)
DECLARE @INDCOSTEADO CHAR(1)
DECLARE @TOTALCANTCOSTO INT
DECLARE @IDCOTIZACION INT
DECLARE @CANTCOTIZADO INT
DECLARE @FLAG_LLAVEMANO INT
DECLARE @FLAG_MANUALES INT
DECLARE @FLAG_VIDEOS INT
DECLARE @FLAG_INSTALACION INT
DECLARE @FLAG_CAPACITACION INT
DECLARE @FLAG_GARANTADIC INT
DECLARE @FLAG_MANTPREV INT
DECLARE @FLAG_CALIB INT
DECLARE @FLAG_FLETE INT
BEGIN

	DECLARE @CODIGO BIGINT, @MSG VARCHAR(20)
	SET NOCOUNT ON;
	
	IF (@pTipoProceso = 'I') BEGIN
		
		INSERT INTO [dbo].[TBD_COTIZACIONCOSTOS]
		([ID_COTDETALLE],
		[NUMSEC],[CODCOSTO],[CANTCOSTO],
		[CANTPREVENTIVO],[CODCICLOPREVENT],[CODUBIGEODEST],
		[DIRECCION],[AMBIENTEDEST],[NROPISO],
		[MONTOUNICOSTO],[MONTOTOTCOSTO],[USR_REG],[FEC_REG])
		VALUES
		(@pId_CotDetalle,
		@pNumSec,@pCodCosto,@pCantCosto,
		@pCantPreventivo,@pCodCicloPrevent,@pCodUbigeoDest,
		@pDireccion,@pAmbienteDest,@pNroPiso,
		@pMontoUniCosto,@pMontoTotCosto,@pUsuarioRegistro,GETDATE())
		
		SET  @CODIGO = @@IDENTITY
		SET @MSG ='Registro Insertado con éxito'
		
	END

	IF (@pTipoProceso = 'U') BEGIN
		
		UPDATE [dbo].[TBD_COTIZACIONCOSTOS]
		SET ID_COTDETALLE = @pId_CotDetalle,
		NUMSEC = @pNumSec, CODCOSTO = @pCodCosto, CANTCOSTO = @pCantCosto,
		CANTPREVENTIVO = @pCantPreventivo, CODCICLOPREVENT = @pCodCicloPrevent, CODUBIGEODEST = @pCodUbigeoDest,
		DIRECCION = @pDireccion, AMBIENTEDEST = @pAmbienteDest, NROPISO = @pNroPiso,
		MONTOUNICOSTO = @pMontoUniCosto, MONTOTOTCOSTO = @pMontoTotCosto,
		USR_MOD = @pUsuarioRegistro, FEC_MOD = GETDATE()
		WHERE ID = @pId
		
		SET @MSG ='Registro Modificado con éxito'
		
	END

	IF (@pTipoProceso = 'D') BEGIN
		
		DELETE FROM [dbo].[TBD_COTIZACIONCOSTOS] WHERE 
		(ISNULL(@pId,0) = 0 OR ID = @pId)
		AND (ISNULL(@pId_CotDetalle,0) = 0 OR ID_COTDETALLE = @pId_CotDetalle)

	END
	
	IF (@pTipoProceso IN ('I','U','D')) BEGIN
		
		-- 0: Sin Costear
		-- 1: Costeo Parcial
		-- 2: Costeo Completo
		SET @FLAG_LLAVEMANO = 0;
		SET @FLAG_INSTALACION = 0;
		SET @FLAG_CAPACITACION = 0;
		SET @FLAG_MANUALES = 0;
		SET @FLAG_VIDEOS = 0;
		SET @FLAG_MANTPREV = 0;
		SET @FLAG_GARANTADIC = 0;
		SET @FLAG_CALIB = 0;
		SET @FLAG_FLETE = 0;

		SELECT TOP 1 @IDCOTIZACION = C.ID_COTIZACION, @CANTCOTIZADO = ISNULL(CD.CANTIDAD,0) 
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTIZACIONVENTA] C ON CD.ID_COTIZACION = C.ID_COTIZACION
		WHERE CD.ID = @pId_CotDetalle;

		SELECT TOP 1 @INDINFOVIDEO = CDD.INDINFOVIDEO, @INDINFOMANUAL = CDD.INDINFOMANUAL,
		@INDINSTALACION = CDD.INDINSTALACION, @INDCAPACITACION = CDD.INDCAPACITACION, @INDGARANADIC = CDD.INDGARANADIC,
		@INDMANTPREVENT = CDD.INDMANTPREVENT, @INDCALIB = CDD.INDCALIB
		FROM [dbo].[TBD_COTIZACIONVENTA] CD
		INNER JOIN [dbo].[TBM_COTDET_DESPACHO] CDD ON CD.ID = CDD.ID_COTDETALLE
		WHERE CD.ID = @pId_CotDetalle;

		--
		-- LLAVE EN MANO
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0001' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_LLAVEMANO = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_LLAVEMANO = 1;
			END
		END
		
		--
		-- INSTALACION Y CAPACITACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0002' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_INSTALACION = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_INSTALACION = 1;
			END
		END
		
		--
		-- INSTALACION Y CAPACITACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0003' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_CAPACITACION = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_CAPACITACION = 1;
			END
		END
		
		--
		-- MANUALES
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0004' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_MANUALES = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_MANUALES = 1;
			END
		END
		
		--
		-- VIDEOS
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0005' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_VIDEOS = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_VIDEOS = 1;
			END
		END
		
		--
		-- MANTENIMIENTO PREVENTIVO
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0006' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_MANTPREV = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_MANTPREV = 1;
			END
		END
		
		--
		-- GARANTIA ADICIONAL
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0007' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_GARANTADIC = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_GARANTADIC = 1;
			END
		END
		
		--
		-- CALIBRACION
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0008' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_CALIB = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_CALIB = 1;
			END
		END
		
		--
		-- FLETE
		--
		SELECT @TOTALCANTCOSTO = SUM(ISNULL(CANTCOSTO,0)) FROM [dbo].[TBD_COTIZACIONCOSTOS]
		WHERE ID_COTDETALLE = @pId_CotDetalle AND CODCOSTO = 'CXCD0009' AND (ISNULL(MONTOUNICOSTO,0) > 0 OR ISNULL(MONTOTOTCOSTO,0) > 0);

		IF @TOTALCANTCOSTO = @CANTCOTIZADO BEGIN
			SET @FLAG_FLETE = 2;
		END
		ELSE BEGIN
			IF @TOTALCANTCOSTO > 0 BEGIN
				SET @FLAG_FLETE = 1;
			END
		END

		SET @INDCOSTEADO = 'S';

		IF @INDINFOVIDEO IS NOT NULL BEGIN
			IF ISNULL(@INDINFOVIDEO,'') = 'S' AND ISNULL(@FLAG_VIDEOS,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDINFOMANUAL IS NOT NULL BEGIN
			IF ISNULL(@INDINFOMANUAL,'') = 'S' AND ISNULL(@FLAG_MANUALES,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDINSTALACION IS NOT NULL BEGIN
			IF ISNULL(@INDINSTALACION,'') = 'S' AND ISNULL(@FLAG_INSTALACION,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDCAPACITACION IS NOT NULL BEGIN
			IF ISNULL(@INDCAPACITACION,'') = 'S' AND ISNULL(@FLAG_CAPACITACION,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDGARANADIC IS NOT NULL BEGIN
			IF ISNULL(@INDGARANADIC,'') = 'S' AND ISNULL(@FLAG_GARANTADIC,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDMANTPREVENT IS NOT NULL BEGIN
			IF ISNULL(@INDMANTPREVENT,'') = 'S' AND ISNULL(@FLAG_MANTPREV,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		IF @INDCALIB IS NOT NULL BEGIN
			IF ISNULL(@INDCALIB,'') = 'S' AND ISNULL(@FLAG_CALIB,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END
		
		IF @INDFLETE IS NOT NULL BEGIN
			IF ISNULL(@INDFLETE,'') = 'S' AND ISNULL(@FLAG_FLETE,0) = 0 BEGIN
				SET @INDCOSTEADO = 'N'
			END
		END

		UPDATE TBM_COTIZACIONVENTA SET INDCOSTEADO = @INDCOSTEADO WHERE ID_COTIZACION = @IDCOTIZACION;
		
		EXEC USP_UPD_TOTALIZAR_COTDET @pId_CotDetalle

	END

	SELECT @CODIGO COD, @MSG MSG
	SET NOCOUNT OFF;

END