USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_GAR_SEL_DETALLE_RECLAMO]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		18.11.24		Realiza la búsqueda del detalle de reclamo.
	EXEC [USP_GAR_SEL_DETALLE_RECLAMO] 1 
  =======================================================================================================*/
  @IsReclamo			BIGINT
)
AS
BEGIN
SET NOCOUNT ON
	IF OBJECT_ID('tempdb..#tmpDetalleGarantia') IS NOT NULL DROP TABLE #tmpDetalleGarantia
	IF OBJECT_ID('tempdb..#tmpMantPrev') IS NOT NULL DROP TABLE #tmpMantPrev

	
	CREATE TABLE #tmpMantPrev
	(
		ID_RECLAMO BIGINT
		,TOTALPREVE INT
		,PENDIENTES INT
		,COMPLETADOS INT
	)


/****Obtenemos el número de preventivos *********************************************************************/
	;WITH CTE_1 As (
		SELECT
			COUNT(MANTDET.ID_MANT) TOTALPREVE
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT
		LEFT JOIN [dbo].[TBM_RECLAMOS] DESPACHO ON DESPACHO.SERIE = MANT.SERIE
		WHERE DESPACHO.ID_RECLAMO = @IsReclamo
		GROUP BY MANTDET.ID_MANT
		),
	CTE_2 AS (
		SELECT
			COUNT(MANTDET.ID_MANT) PENDIENTES
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND MANTDET.ESTADO != 'COM'
		LEFT JOIN [dbo].[TBM_RECLAMOS] DESPACHO ON DESPACHO.SERIE = MANT.SERIE
		WHERE DESPACHO.ID_RECLAMO = @IsReclamo
		GROUP BY MANTDET.ID_MANT
	),
	CTE_3 AS (																						----------------------------------
		SELECT
			COUNT(MANTDET.ID_MANT) COMPLETADOS
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT 		
		LEFT JOIN [dbo].[TBM_RECLAMOS] DESPACHO ON DESPACHO.SERIE = MANT.SERIE
		WHERE MANTDET.ESTADO = 'COM' AND DESPACHO.ID_RECLAMO = @IsReclamo
		GROUP BY MANTDET.ID_MANT
	)
	INSERT INTO #tmpMantPrev(ID_RECLAMO, TOTALPREVE, PENDIENTES, COMPLETADOS)
	SELECT
		DESPACHO.ID_RECLAMO
		,ISNULL(TOTALPREVE,0)  TOTALPREVE
		,ISNULL(PENDIENTES,0)  PENDIENTES
		,ISNULL(COMPLETADOS,0) COMPLETADOS
	FROM [dbo].[TBM_MANT_PREV] MANT
	LEFT JOIN CTE_1 cte1 ON cte1.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_2 cte2 ON cte2.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_3 cte3 ON cte3.ID_MANT = MANT.ID_MANT
	LEFT JOIN [dbo].[TBM_RECLAMOS] DESPACHO ON DESPACHO.SERIE = MANT.SERIE
	WHERE DESPACHO.ID_RECLAMO = @IsReclamo

	SELECT
		NUMSERIE							AS NUMSERIE
		,COTCOST.CANTPREVENTIVO				AS MANTPREVENTIVO
		,tmp.COMPLETADOS AS PREVREAL--Pendiente preventivos realizados
		,tmp.PENDIENTES AS PREVPEND--Pendientes preventivos pendientes
		,DATEADD(month,CAST((SUBSTRING(TRIM(DATOS.VALOR1),0,CHARINDEX(' ',DATOS.VALOR1,0))) AS INT) ,DESPACHO.FECHAINSTALACION) AS FECHAVENCIMIENTO
	INTO #tmpDetalleGarantia
	FROM [dbo].[TBM_RECLAMOS] AS RECLAMO WITH(NOLOCK)
	LEFT JOIN [dbo].[TBD_DESPACHO_DIST] DESPACHO WITH(NOLOCK) ON DESPACHO.NUMSERIE = RECLAMO.SERIE
	LEFT JOIN [dbo].[TBD_COTIZACIONVENTA] AS COTDET WITH(NOLOCK) ON COTDET.ID = DESPACHO.ID_COTDETALLE
	LEFT JOIN [dbo].[TBD_COTIZACIONCOSTOS] AS COTCOST WITH(NOLOCK) ON COTCOST.ID_COTDETALLE = DESPACHO.ID_COTDETALLE
	LEFT JOIN [dbo].[TBM_COTDET_DESPACHO] AS COTDETDES WITH(NOLOCK) ON COTDET.ID = COTDETDES.ID_COTDETALLE
	LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] AS COTIZ WITH(NOLOCK) ON COTDET.ID_COTIZACION = COTIZ.ID_COTIZACION
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS DATOS WITH(NOLOCK) ON DATOS.DOMINIO = 'GARANTIAS' AND DATOS.PARAMETRO = COTIZ.GARANTIA AND DATOS.ESTADO = '1'
	LEFT JOIN #tmpMantPrev tmp ON tmp.ID_RECLAMO = RECLAMO.ID_RECLAMO
	WHERE RECLAMO.ID_RECLAMO = @IsReclamo


	SELECT
			RECLAMO.ID_RECLAMO
			,RECLAMO.ID_WORKFLOW
			,RECLAMO.ID_SOLICITUD
			,RECLAMO.RUCEMPRESA						
			,RECLAMO.NOMEMPRESA						AS RAZONSOCIAL
			,RECLAMO.UBICACION
			,RECLAMO.NOMBRECONTACTO
			,ISNULL(RECLAMO.TELEFONOCONTACTO,'')	AS TELEFONOCONTACTO
			,ISNULL(RECLAMO.CARGOCONTACTO,'')		AS CARGOCONTACTO 
			,ISNULL(RECLAMO.ESTABLECIMIENTO,'')	AS ESTABLECIMIENTO
			,RECLAMO.ORDENCOMPRA
			,RECLAMO.NUMPROCESO
			,RECLAMO.TIPOPROCESO
			,RECLAMO.CONTRATO
			,RECLAMO.CODEMPRESA
			,datos.VALOR1							AS NOMEMPRESA
			,RECLAMO.VENDEDOR
			,RECLAMO.CODIGOPRODUCTO
			,RECLAMO.DESCRIPCION
			,RECLAMO.MARCA
			,RECLAMO.TIPOVENTA
			,tipos.VALOR1							AS NOMTIPOVENTA
			,RECLAMO.MODELO
			,RECLAMO.SERIE
			,RECLAMO.NUMFIANZA
			,RECLAMO.FECHAINSTALACION
			,RECLAMO.FECHARECLAMO
			,RECLAMO.FECHAPROGRAMACION
			,RECLAMO.UBIGEO
			,CONCAT(UBI.NOMDEPARTAMENTO,' / ',UBI.NOMPROVINCIA, ' / ', UBI.NOMDISTRITO) AS DESCUBIGEODEST
			,RECLAMO.DIRECCION
			,RECLAMO.URGENCIA
			,RECLAMO.TIPOMOTIVO
			,RECLAMO.MOTIVO
			,estado.NOM_ESTADO						As ESTADO
			,RECLAMO.ESTADO							AS CODESTADO
			,RECLAMO.USR_REG
			,RECLAMO.FEC_REG
			,garantia.MANTPREVENTIVO				AS MANTPREVENTIVO
			,ISNULL(garantia.PREVREAL,0) AS PREVREAL--Pendiente preventivos realizados
			,ISNULL(garantia.PREVPEND,garantia.MANTPREVENTIVO) AS PREVPEND--Pendientes preventivos pendientes
			,CONVERT(VARCHAR(10),FECHAVENCIMIENTO,103) AS FECHAVENCIMIENTO
			,CASE WHEN FECHAVENCIMIENTO >= GETDATE() THEN 'VIGENTE' 
				ELSE 'VENCIDO' END ESTADOGARANT
		FROM [TBM_RECLAMOS] AS RECLAMO WITH(NOLOCK)
		LEFT JOIN [dbo].[#tmpDetalleGarantia] garantia WITH(NOLOCK) ON RECLAMO.SERIE = garantia.NUMSERIE
		LEFT JOIN [dbo].[TBD_DATOS_GENERALES] datos WITH(NOLOCK) ON datos.COD_VALOR1 = RECLAMO.CODEMPRESA
		LEFT JOIN [dbo].[TBD_DATOS_GENERALES] tipos WITH(NOLOCK) ON tipos.COD_VALOR1 = RECLAMO.TIPOVENTA AND tipos.DOMINIO = 'TIPOVENTA'
		LEFT JOIN [dbo].[TBM_PROCESOESTADOS] estado WITH(NOLOCK) ON estado.COD_ESTADO = RECLAMO.ESTADO AND ID_PROCESO = 7
		LEFT JOIN [dbo].[TBD_DATOS_GENERALES] urgencia WITH(NOLOCK) ON urgencia.COD_VALOR1 = RECLAMO.URGENCIA
		LEFT JOIN [dbo].[TBM_UBIGEO] ubi WITH(NOLOCK) ON ubi.CODUBIGEO = RECLAMO.UBIGEO
		WHERE ID_RECLAMO = @IsReclamo

SET NOCOUNT OFF
END