USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_GAR_SEL_DETALLE_RECLAMO]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		18.11.24		Realiza la búsqueda del detalle de reclamo.
	EXEC [USP_GAR_SEL_DETALLE_RECLAMO] 1
  =======================================================================================================*/
  @IsReclamo			BIGINT
)
AS
BEGIN
SET NOCOUNT ON
	IF OBJECT_ID('tempdb..#tmpDetalleGarantia') IS NOT NULL DROP TABLE #tmpDetalleGarantia


	SELECT
		NUMSERIE							AS NUMSERIE
		,COTCOST.CANTPREVENTIVO				AS MANTPREVENTIVO
		,0 AS PREVREAL--Pendiente preventivos realizados
		,0 AS PREVPEND--Pendientes preventivos pendientes
		,DATEADD(month,CAST((SUBSTRING(TRIM(DATOS.VALOR1),0,CHARINDEX(' ',DATOS.VALOR1,0))) AS INT) ,DESPACHO.FECHAINSTALACION) AS FECHAVENCIMIENTO
	INTO #tmpDetalleGarantia
	FROM [dbo].[TBM_RECLAMOS] AS RECLAMO WITH(NOLOCK)
	LEFT JOIN [dbo].[TBD_DESPACHO_DIST] DESPACHO WITH(NOLOCK) ON DESPACHO.NUMSERIE = RECLAMO.SERIE
	LEFT JOIN [dbo].[TBD_COTIZACIONCOSTOS] AS COTCOST WITH(NOLOCK) ON COTCOST.ID = DESPACHO.ID_COTCOSTOS
	LEFT JOIN [dbo].[TBD_COTIZACIONVENTA] AS COTDET WITH(NOLOCK) ON COTDET.ID = COTCOST.ID_COTDETALLE
	LEFT JOIN [dbo].[TBM_COTDET_DESPACHO] AS COTDETDES WITH(NOLOCK) ON COTDET.ID = COTDETDES.ID_COTDETALLE
	LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] AS COTIZ WITH(NOLOCK) ON COTDET.ID_COTIZACION = COTIZ.ID_COTIZACION
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] AS DATOS WITH(NOLOCK) ON DATOS.DOMINIO = 'GARANTIAS' AND DATOS.COD_VALOR1 = COTIZ.GARANTIA
	WHERE ID_RECLAMO = 1


	SELECT
			RECLAMO.ID_RECLAMO
			,RECLAMO.ID_WORKFLOW
			,RECLAMO.ID_SOLICITUD
			,RECLAMO.RUCEMPRESA						
			,RECLAMO.NOMEMPRESA						AS RAZONSOCIAL
			,RECLAMO.UBICACION
			,RECLAMO.NOMBRECONTACTO
			,ISNULL(RECLAMO.TELEFONOCONTACTO,'')	AS TELEFONOCONTACTO
			,ISNULL(RECLAMO.CARGOCONTACTO,'')		AS CARGOCONTACTO 
			,ISNULL(RECLAMO.ESTABLECIMIENTO,'')	AS ESTABLECIMIENTO
			,RECLAMO.ORDENCOMPRA
			,RECLAMO.NUMPROCESO
			,RECLAMO.TIPOPROCESO
			,RECLAMO.CONTRATO
			,RECLAMO.CODEMPRESA
			,datos.VALOR1							AS NOMEMPRESA
			,RECLAMO.VENDEDOR
			,RECLAMO.CODIGOPRODUCTO
			,RECLAMO.DESCRIPCION
			,RECLAMO.MARCA
			,RECLAMO.TIPOVENTA
			,tipos.VALOR1							AS NOMTIPOVENTA
			,RECLAMO.MODELO
			,RECLAMO.SERIE
			,RECLAMO.NUMFIANZA
			,RECLAMO.FECHAINSTALACION
			,RECLAMO.FECHARECLAMO
			,RECLAMO.FECHAPROGRAMACION
			,RECLAMO.UBIGEO
			,CONCAT(UBI.NOMDEPARTAMENTO,' / ',UBI.NOMPROVINCIA, ' / ', UBI.NOMDISTRITO) AS DESCUBIGEODEST
			,RECLAMO.DIRECCION
			,RECLAMO.URGENCIA
			,RECLAMO.TIPOMOTIVO
			,RECLAMO.MOTIVO
			,estado.NOM_ESTADO						As ESTADO
			,RECLAMO.ESTADO							AS CODESTADO
			,RECLAMO.USR_REG
			,RECLAMO.FEC_REG
			,garantia.MANTPREVENTIVO				AS MANTPREVENTIVO
			,garantia.PREVREAL--Pendiente preventivos realizados
			,garantia.PREVPEND--Pendientes preventivos pendientes
			,CONVERT(VARCHAR(10),FECHAVENCIMIENTO,103) AS FECHAVENCIMIENTO
			,CASE WHEN FECHAVENCIMIENTO >= GETDATE() THEN 'VIGENTE' 
				ELSE 'VENCIDO' END ESTADOGARANT
		FROM [TBM_RECLAMOS] AS RECLAMO WITH(NOLOCK)
		LEFT JOIN [dbo].[#tmpDetalleGarantia] garantia WITH(NOLOCK) ON RECLAMO.SERIE = garantia.NUMSERIE
		LEFT JOIN [dbo].[TBD_DATOS_GENERALES] datos WITH(NOLOCK) ON datos.COD_VALOR1 = RECLAMO.CODEMPRESA
		LEFT JOIN [dbo].[TBD_DATOS_GENERALES] tipos WITH(NOLOCK) ON tipos.COD_VALOR1 = RECLAMO.TIPOVENTA AND tipos.DOMINIO = 'TIPOVENTA'
		LEFT JOIN [dbo].[TBM_PROCESOESTADOS] estado WITH(NOLOCK) ON estado.COD_ESTADO = RECLAMO.ESTADO AND ID_PROCESO = 7
		LEFT JOIN [dbo].[TBD_DATOS_GENERALES] urgencia WITH(NOLOCK) ON urgencia.COD_VALOR1 = RECLAMO.URGENCIA
		LEFT JOIN [dbo].[TBM_UBIGEO] ubi WITH(NOLOCK) ON ubi.CODUBIGEO = RECLAMO.UBIGEO

SET NOCOUNT OFF
END