USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_SEL_INS_MANT_PREV]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		26.11.24		Realiza el insert de los mantenimientos a realizarce después de acabar la instalación técnica.
	EXEC [USP_SEL_INS_MANT_PREV] 1
  =======================================================================================================*/
	@isIdSolicitud BIGINT
)
AS
BEGIN

	SELECT
		DETALLE.ID
		,DESCRIPCION
		,RGA.DESMARCA
		,COTIZ.GARANTIA
		,DESPACHO.NUMFIANZA
		,DESPACHO.
	INTO #tmpDetalleCotiz
	FROM [dbo].[TBD_COTIZACIONVENTA] AS DETALLE WITH(NOLOCK)
	LEFT JOIN [dbo].[TBM_COTDET_DESPACHO] DESPACHO WITH(NOLOCK) ON DESPACHO.ID_COTDETALLE = DETALLE.ID
	LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] AS COTIZ WITH(NOLOCK) ON DETALLE.ID_COTIZACION = COTIZ.ID_COTIZACION AND ID_SOLICITUD = @isIdSolicitud
	LEFT JOIN [dbo].[TBM_SOLICITUDVENTA] AS SOL WITH(NOLOCK) ON SOL.ID_SOLICITUD = COTIZ.ID_SOLICITUD
	LEFT JOIN (SELECT [NOMPRODUCTO],[DESMARCA],[CODIGOPRODUCTO],[LOTESERIE] FROM OPENQUERY([AH-SRV4],'
	SELECT
		A.AR_CCODIGO CODIGOPRODUCTO,
		A.AR_CDESCRI NOMPRODUCTO,
		D.TG_CDESCRI DESMARCA,
		ISNULL(F.SR_CSERIE,'''') LOTESERIE
	FROM  [RSFACCAR].[dbo].[AL0007ARTI] A WITH(NOLOCK)
	LEFT JOIN  [RSFACCAR].[dbo].[AL0007STOC] B WITH(NOLOCK) ON A.AR_CCODIGO=B.SK_CCODIGO
	LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] D WITH(NOLOCK) ON D.TG_CCOD=''V7'' AND A.AR_CMARCA=D.TG_CCLAVE 
	LEFT JOIN  [RSFACCAR].[dbo].[AL0007SERI] F WITH(NOLOCK) ON A.AR_CCODIGO=F.SR_CCODIGO AND B.SK_CALMA=F.SR_CALMA AND F.SR_NSKDIS<>0 
	WHERE B.SK_CALMA IN (''0001'',''0015'',''0017'') GROUP BY A.AR_CCODIGO,A.AR_CDESCRI,D.TG_CDESCRI,F.SR_CSERIE' )) RGA ON RGA.CODIGOPRODUCTO = DETALLE.CODITEM
	WHERE COTIZ.ID_SOLICITUD = @isIdSolicitud  AND DETALLE.TIPOITEM = 'PRO' 

	SELECT	
			COTDET.ID AS ID_DETALLE
			,DESPACHO.ID AS ID_DESPACHO
			,COTDET.CODIGOPRODUCTO		
			,COTDET.DESCRIPCION		
			,COTDET.DESMARCA
			,DESPACHO.NUMSERIE
			,COTDET.GARANTIA
			,CANTPREVENTIVO
			,CODCICLOPREVENT
			,CODUBIGEODEST
			,DESPACHO.FECHAINSTALACION
			,CONCAT(UBI.NOMDEPARTAMENTO, ' / ', UBI.NOMPROVINCIA, ' / ', UBI.NOMDISTRITO) AS DESCUBIGEODEST
			,DIRECCION
	INTO #tmpDespacho 
	FROM [dbo].#tmpDetalleCotiz AS COTDET
	LEFT JOIN [dbo].[TBD_COTIZACIONCOSTOS] AS COTCOST WITH(NOLOCK) ON COTCOST.ID_COTDETALLE  = COTDET.ID
	LEFT JOIN [TBD_DESPACHO_DIST] DESPACHO WITH(NOLOCK) ON COTCOST.ID =  DESPACHO.ID_COTCOSTOS
	LEFT JOIN [dbo].[TBM_UBIGEO] AS UBI WITH(NOLOCK) ON UBI.CODUBIGEO = COTCOST.CODUBIGEODEST
	

	select * FROM [TBD_DESPACHO_DIST]
	SELECT * FROM #tmpDetalleCotiz	 --Detalle de Cotización
	select * FROM #tmpDespacho--Detalle de Costos y despacho
END
