USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_SEL_FILTROS]
/*=================================================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	Diego A. Bazalar		18/11/2024	Extrae los filtros para la bandeja de mant. preventivos.
	EXEC [USP_PREV_SEL_FILTROS]
  =================================================================================================*/
AS
BEGIN
SET NOCOUNT ON
	--ComboBox Empresas
	SELECT D.PARAMETRO CODEMPRESA, D.VALOR1 RAZONSOCIAL FROM TBD_DATOS_GENERALES D WHERE DOMINIO='RAZSOCIAL' AND HABILITADO = '1' AND ESTADO = '1'
	--ComboBox Estado
	SELECT COD_ESTADO Codigo, ABREV_ESTADO Abrev FROM TBM_PROCESOESTADOS WHERE ID_PROCESO = 6
	--ComboBox Tipo de Empleado
	SELECT COD_VALOR1 CODTIPO, DESCRIPCION DESCTIPO FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'TIPEMPL' AND HABILITADO = '1' AND ESTADO = '1'
	--ComboBox Clientes
	SELECT RUCEMPRESA ID, NOMEMPRESA FROM TBM_CLIENTES
	--ComboBox Tipo Doc
	SELECT PARAMETRO COD, DESCRIPCION FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'GENTDOC' AND HABILITADO = '1' AND ESTADO = '1'
	--ComboBox Periodos
	SELECT PARAMETRO COD, DESCRIPCION FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'CICLOPREV' AND HABILITADO = '1' AND ESTADO = '1'
	--ComboBox Garantias
	SELECT PARAMETRO COD, VALOR1 DESCRIPCION FROM TBD_DATOS_GENERALES WHERE DOMINIO = 'GARANTIAS' AND HABILITADO = '1' AND ESTADO = '1'

SET NOCOUNT OFF
END
