USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_SEL_PREVENTIVOS]
(
/*=======================================================================================================
	Nombre:				Fecha:				Descripcion:
	Diego Bazalar		28.11.24		Realiza el select de los mantenimientod preventivos.
	EXEC [USP_PREV_SEL_PREVENTIVOS] @IsNumReq='', @IsNumSerie='0', @IsNumProc='0',@IsNumOrdCompra='0',@IsNumFianza='0',@IsEmpresa='0',@IsPeriodoInicio=NULL,@IsPeriodoFinal=NULL,@IsRUC= '0',@IsNomEquipo='',@IsMarca='',@IsUbigeoDestino='000000',@IsModelo=''
=======================================================================================================*/
	 @IsNumReq			BIGINT
	,@IsNumSerie		VARCHAR(100)
	,@IsNumProc			VARCHAR(15)
	,@IsNumOrdCompra	VARCHAR(200)
	,@IsNumFianza		VARCHAR(15)
	,@IsEmpresa			VARCHAR(6)
	,@IsPeriodoInicio	VARCHAR(7)
	,@IsPeriodoFinal	VARCHAR(7)
	,@IsRUC				VARCHAR(12)
	,@IsNomEquipo		VARCHAR(100)
	,@IsMarca			VARCHAR(60)
	,@IsUbigeoDestino	VARCHAR(6)
	,@IsModelo			VARCHAR(60)
	--Pendiente contrato
	--,@IsEstado			VARCHAR(5)
)
AS
BEGIN
SET NOCOUNT ON

	DECLARE @Sql NVARCHAR(MAX)

	IF OBJECT_ID('tempdb..#tmpParcial') IS NOT NULL 
		DROP TABLE #tmpParcial
	IF OBJECT_ID('tempdb..#tmpMantPrev') IS NOT NULL 
		DROP TABLE #tmpMantPrev
	IF OBJECT_ID('tempdb..#tmpProxavencer') IS NOT NULL
		DROP TABLE #tmpProxavencer

	CREATE TABLE #tmpParcial(
		ID_MANT BIGINT
		,NUMREQ BIGINT
		,SERIE VARCHAR(200)
		,FECHAINSTALACION DATETIME
		,COD_EMPRESA VARCHAR(10)
		,DIRECCION VARCHAR(150)
		,UBIGEODEST VARCHAR(6)
		,CODITEM  VARCHAR(35)
		,DESCRIPCION VARCHAR(100)
		,CODGARANTIA VARCHAR(10)
		,NUMPROCESO VARCHAR(15)
		,TIPOPROCESO VARCHAR(200)
		,ORDENCOMPRA VARCHAR(35)
		,NUMFIANZA VARCHAR(15)
		,IDCLIENTE	INT
	)
	

	CREATE TABLE #tmpMantPrev
	(
		ID_MANT BIGINT
		,TOTALPREVE INT
		,PENDIENTES INT
		,COMPLETADOS INT
	)

	;WITH CTE_1 As (
		SELECT
			COUNT(MANTDET.ID_MANT) TOTALPREVE
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT
		GROUP BY MANTDET.ID_MANT
		),
	CTE_2 AS (
		SELECT
			COUNT(MANTDET.ID_MANT) PENDIENTES
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND MANTDET.ESTADO != 'COM'
		GROUP BY MANTDET.ID_MANT
	),
	CTE_3 AS (																						----------------------------------
		SELECT
			COUNT(MANTDET.ID_MANT) COMPLETADOS
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT 
		WHERE MANTDET.ESTADO = 'COM'
		GROUP BY MANTDET.ID_MANT
	)
	INSERT INTO #tmpMantPrev(ID_MANT, TOTALPREVE, PENDIENTES, COMPLETADOS)
	SELECT
		MANT.ID_MANT
		,ISNULL(TOTALPREVE,0)  TOTALPREVE
		,ISNULL(PENDIENTES,0)  PENDIENTES
		,ISNULL(COMPLETADOS,0) COMPLETADOS
	FROM [dbo].[TBM_MANT_PREV] MANT
	LEFT JOIN CTE_1 cte1 ON cte1.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_2 cte2 ON cte2.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_3 cte3 ON cte3.ID_MANT = MANT.ID_MANT

	SELECT
			ROW_NUMBER() OVER(ORDER BY SERIE) AS CONTADOR
			,SERIE
			,FECHAINSTALACION
			,ISNULL(MIN(FECHAMANTENIMIENTO),'') PROXFECHAMANT
	INTO #tmpProxavencer
	FROM TBM_MANT_PREV MANT
	LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND ESTADO != 'COM'
	--WHERE CONVERT(VARCHAR(7),MANTDET.FECHAMANTENIMIENTO,102) BETWEEN IIF(@IsPeriodoInicio IS NULL,CONVERT(VARCHAR(7),MANTDET.FECHAMANTENIMIENTO,102),CONVERT(VARCHAR(7),@IsPeriodoInicio,102)) AND IIF(@IsPeriodoFinal IS NULL, CONVERT(VARCHAR(7),MANTDET.FECHAMANTENIMIENTO,102),CONVERT(VARCHAR(7),@IsPeriodoFinal,102))
	GROUP BY SERIE,FECHAINSTALACION


	SET @Sql = '
				SELECT 																				
					MANT.ID_MANT				   AS ID_MANT
					,INSTAL.NUMREQ				   AS NUMREQ
					,SERIE						   AS SERIE											
					,MANT.FECHAINSTALACION		   AS FECHAINSTALACION								
					,SOL.COD_EMPRESA			   AS COD_EMPRESA									
					,MANT.DIRECCION				   AS DIRECCION										
					,MANT.UBIGEODEST			   AS UBIGEODEST									
					,COTDET.CODITEM				   AS CODITEM										
					,COTDET.DESCRIPCION			   AS DESCRIPCION									
					,COTIZ.GARANTIA				   AS CODGARANTIA									
					,MANT.NUMPROCESO			   AS NUMPROCESO									
					,MANT.TIPOPROCESO			   AS TIPOPROCESO									
					,MANT.ORDENCOMPRA			   AS ORDENCOMPRA									
					,MANT.NUMFIANZA				   AS NUMFIANZA
					,SOL.IDCLIENTE				   AS IDCLIENTE
				FROM [dbo].[TBM_MANT_PREV] MANT WITH(NOLOCK)										
				LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET WITH(NOLOCK) ON MANT.ID_MANT = MANTDET.ID_MANT
				LEFT JOIN [dbo].[TBD_DESPACHO_DIST] DESP WITH(NOLOCK) ON MANT.SERIE = DESP.NUMSERIE
				LEFT JOIN [dbo].[TBD_COTIZACIONCOSTOS] COTCOST WITH(NOLOCK) ON DESP.ID_COTDETALLE = COTCOST.ID_COTDETALLE
				LEFT JOIN [dbo].[TBD_COTIZACIONVENTA] COTDET WITH(NOLOCK) ON COTDET.ID = COTCOST.ID_COTDETALLE
				LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] COTIZ WITH(NOLOCK) ON COTIZ.ID_COTIZACION = COTDET.ID_COTIZACION AND COTIZ.ESTADO = ''A''
				LEFT JOIN [dbo].[TBM_SOLICITUDVENTA] SOL WITH(NOLOCK) ON SOL.ID_SOLICITUD = COTIZ.ID_SOLICITUD
				LEFT JOIN [dbo].[TBM_INSTALACION] INSTAL WITH(NOLOCK) ON SOL.ID_SOLICITUD = INSTAL.ID_SOLICITUD
				'
	SET @sql = @sql +'WHERE 1 = 1'

	IF (@IsNumReq != '0')
	BEGIN
		SET @sql = @sql +' AND INSTAL.NUMREQ = '''+CAST(@IsNumReq AS VARCHAR)+''' '
	END
	IF (@IsNumSerie != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.SERIE = '''+CAST(@IsNumSerie AS VARCHAR)+''' '
	END
	IF (@IsNumProc != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.NUMPROCESO = '''+CAST(@IsNumProc AS VARCHAR)+''' '
	END
	IF (@IsNumOrdCompra != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.ORDENCOMPRA = '''+CAST(@IsNumOrdCompra AS VARCHAR)+''' '
	END
	IF (@IsNumFianza != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.NUMFIANZA = '''+CAST(@IsNumFianza AS VARCHAR)+''' '
	END
	IF (@IsEmpresa != '0')
	BEGIN
		SET @sql = @sql +' AND SOl.COD_EMPRESA = '''+CAST(@IsEmpresa AS VARCHAR)+''' '
	END
	IF(@IsUbigeoDestino != '')
	BEGIN
		IF @IsUbigeoDestino != '000000'
			IF SUBSTRING(@IsUbigeoDestino,3,6) != '0000'
				IF SUBSTRING(@IsUbigeoDestino,5,6) != '00'
					SET @sql = @sql + ' AND MANT.UBIGEODEST = '''+CAST(@IsUbigeoDestino AS VARCHAR(10))+''' ' 
				ELSE
					SET @sql = @sql + ' AND SUBSTRING(MANT.UBIGEODEST,1,4) = '''+CAST(SUBSTRING(@IsUbigeoDestino,1,4) AS VARCHAR(10))+''' ' 
			ELSE
				SET @sql = @sql + ' AND SUBSTRING(MANT.UBIGEODEST,1,2) = '''+CAST(SUBSTRING(@IsUbigeoDestino,1,2) AS VARCHAR(10))+''' '
	END
	IF(@IsNomEquipo != '')
	BEGIN
		SET @sql = @sql + ' AND COTDET.DESCRIPCION = '''+CAST(@IsNomEquipo AS VARCHAR)+''' '
	END


	SET @sql = @sql +'
				GROUP BY MANT.ID_MANT
					,SERIE
					,MANT.FECHAINSTALACION
					,SOL.COD_EMPRESA
					,MANT.DIRECCION
					,MANT.UBIGEODEST
					,COTDET.CODITEM
					,COTDET.DESCRIPCION
					,COTIZ.GARANTIA
					,MANT.NUMPROCESO
					,MANT.TIPOPROCESO
					,MANT.ORDENCOMPRA
					,MANT.NUMFIANZA
					,INSTAL.NUMREQ
					,SOL.IDCLIENTE'
	print(@sql)

	INSERT INTO #tmpParcial
	EXEC sp_executesql @sql
	
	SELECT
		parcial.ID_MANT
		,NUMREQ
		,parcial.SERIE
		,parcial.DESCRIPCION
		,RGA.DESC_MODELO AS MODELO
		,RGA.DESMARCA AS MARCA
		,CLI.NOMEMPRESA AS NOMEMPRESA
		,parcial.FECHAINSTALACION
		,CASE 
			WHEN ISNULL(CONVERT(VARCHAR(10),prox.PROXFECHAMANT,103),'') = '01/01/1900'
			THEN ''
		 ELSE 
			ISNULL(CONVERT(VARCHAR(10),prox.PROXFECHAMANT,103),'') END PROXFECHAMANT
		,calc.TOTALPREVE
		,calc.COMPLETADOS
		,calc.PENDIENTES
		,CONCAT(UBI.NOMDEPARTAMENTO,' / ',UBI.NOMPROVINCIA,' / ',UBI.NOMDISTRITO) AS UBIGEODEST
	FROM #tmpParcial parcial
	INNER JOIN #tmpProxavencer prox ON parcial.SERIE = prox.SERIE
	LEFT JOIN #tmpMantPrev calc ON calc.ID_MANT = parcial.ID_MANT
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] GARANT WITH(NOLOCK) ON parcial.CODGARANTIA = GARANT.COD_VALOR1 AND DOMINIO = 'GARANTIAS' AND GARANT.ESTADO = '1'
	LEFT JOIN [dbo].[TBM_UBIGEO] UBI WITH(NOLOCK) ON UBI.CODUBIGEO = parcial.UBIGEODEST
	LEFT JOIN [dbo].[TBM_CLIENTES] CLI WITH(NOLOCK) ON CLI.ID = parcial.IDCLIENTE
	LEFT JOIN (SELECT [DESMARCA],[CODIGOPRODUCTO],[DESC_MODELO] FROM OPENQUERY([AH-SRV4],'
		SELECT
			A.AR_CCODIGO CODIGOPRODUCTO,
			ISNULL(D.TG_CDESCRI,'''') DESMARCA,
			ISNULL(MO.TG_CDESCRI,'''') AS DESC_MODELO
		FROM  [RSFACCAR].[dbo].[AL0007ARTI] A WITH(NOLOCK)
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007STOC] B WITH(NOLOCK) ON A.AR_CCODIGO=B.SK_CCODIGO
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] D WITH(NOLOCK) ON D.TG_CCOD=''V7'' AND A.AR_CMARCA=D.TG_CCLAVE 
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007TABL] MO WITH(NOLOCK) ON MO.TG_CCOD = ''39'' AND A.AR_CMODELO = MO.TG_CCLAVE
		LEFT JOIN  [RSFACCAR].[dbo].[AL0007SERI] F WITH(NOLOCK) ON A.AR_CCODIGO=F.SR_CCODIGO AND B.SK_CALMA=F.SR_CALMA AND F.SR_NSKDIS<>0 
		WHERE B.SK_CALMA IN (''0001'',''0015'',''0017'') GROUP BY A.AR_CCODIGO,D.TG_CDESCRI,MO.TG_CDESCRI' )) RGA ON RGA.CODIGOPRODUCTO = parcial.CODITEM
	WHERE CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102) BETWEEN IIF(@IsPeriodoInicio IS NULL,CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102),CONVERT(VARCHAR(7),@IsPeriodoInicio,102)) AND IIF(@IsPeriodoFinal IS NULL, CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102),CONVERT(VARCHAR(7),@IsPeriodoFinal,102))
	AND CLI.RUCEMPRESA = IIF(@IsRUC = '0', CLI.RUCEMPRESA, @IsRUC)
	AND RGA.DESC_MODELO = IIF(@IsModelo IS NUll, RGA.DESC_MODELO, @IsModelo)
	AND RGA.DESMARCA = IIF(@IsMarca IS NULL, RGA.DESMARCA, @IsMarca)
	ORDER BY ID_MANT ASC

SET NOCOUNT OFF
END