USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_SEL_PREVENTIVOS]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		28.11.24		Realiza el select de los mantenimientod preventivos.
	EXEC [USP_PREV_SEL_PREVENTIVOS] @IsIdMant='', @IsNumSerie='0', @IsNumProc='0',@IsNumOrdCompra='0',@IsNumFianza='0',@IsEmpresa='0',@IsPeriodoInicio='',@IsPeriodoFinal=''
=======================================================================================================*/
	 @IsIdMant			BIGINT
	,@IsNumSerie		VARCHAR(100) 
	,@IsNumProc			VARCHAR(15)
	,@IsNumOrdCompra	VARCHAR(200)
	,@IsNumFianza		VARCHAR(15)
	,@IsEmpresa			VARCHAR(6)
	,@IsPeriodoInicio	VARCHAR(7)
	,@IsPeriodoFinal	VARCHAR(7)
	--,@IsEstado			VARCHAR(5)
)
AS
BEGIN
SET NOCOUNT ON

	DECLARE @Sql NVARCHAR(MAX)

	IF OBJECT_ID('tempdb..#tmpParcial') IS NOT NULL 
		DROP TABLE #tmpParcial
	IF OBJECT_ID('tempdb..#tmpMantPrev') IS NOT NULL 
		DROP TABLE #tmpMantPrev

	CREATE TABLE #tmpParcial(
		ID_MANT BIGINT
		,SERIE VARCHAR(200)
		,FECHAINSTALACION DATETIME
		,COD_EMPRESA VARCHAR(10)
		,DIRECCION VARCHAR(150)
		,UBIGEODEST VARCHAR(6)
		,CODITEM  VARCHAR(35)
		,DESCRIPCION VARCHAR(100)
		,CODGARANTIA VARCHAR(10)
		,NUMPROCESO VARCHAR(15)
		,TIPOPROCESO VARCHAR(200)
		,ORDENCOMPRA VARCHAR(35)
		,NUMFIANZA VARCHAR(15)
	)
	

	CREATE TABLE #tmpMantPrev
	(
		ID_MANT BIGINT
		,TOTALPREVE INT
		,PENDIENTES INT
		,COMPLETADOS INT
	)

	;WITH CTE_1 As (
		SELECT
			COUNT(MANTDET.ID_MANT) TOTALPREVE
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT
		GROUP BY MANTDET.ID_MANT
		),
	CTE_2 AS (
		SELECT
			COUNT(MANTDET.ID_MANT) PENDIENTES
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND MANTDET.ESTADO != 'COM'
		GROUP BY MANTDET.ID_MANT
	),
	CTE_3 AS (																						----------------------------------
		SELECT
			COUNT(MANTDET.ID_MANT) COMPLETADOS
			,MANTDET.ID_MANT
		FROM [dbo].[TBM_MANT_PREV] MANT
		LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT 
		WHERE MANTDET.ESTADO = 'COM'
		GROUP BY MANTDET.ID_MANT
	)
	INSERT INTO #tmpMantPrev(ID_MANT, TOTALPREVE, PENDIENTES, COMPLETADOS)
	SELECT
		MANT.ID_MANT
		,ISNULL(TOTALPREVE,0)  TOTALPREVE
		,ISNULL(PENDIENTES,0)  PENDIENTES
		,ISNULL(COMPLETADOS,0) COMPLETADOS
	FROM [dbo].[TBM_MANT_PREV] MANT
	LEFT JOIN CTE_1 cte1 ON cte1.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_2 cte2 ON cte2.ID_MANT = MANT.ID_MANT
	LEFT JOIN CTE_3 cte3 ON cte3.ID_MANT = MANT.ID_MANT

	SELECT
			ROW_NUMBER() OVER(ORDER BY SERIE) AS CONTADOR
			,SERIE
			,FECHAINSTALACION
			,MIN(FECHAMANTENIMIENTO) PROXFECHAMANT
	INTO #tmpProxavencer
	FROM TBM_MANT_PREV MANT
	LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET ON MANT.ID_MANT = MANTDET.ID_MANT AND ESTADO = 'PEND'
	GROUP BY SERIE,FECHAINSTALACION

	SET @Sql = '
				SELECT 																				
					MANT.ID_MANT				   AS ID_MANT										
					,SERIE						   AS SERIE											
					,MANT.FECHAINSTALACION		   AS FECHAINSTALACION								
					,SOL.COD_EMPRESA			   AS COD_EMPRESA									
					,MANT.DIRECCION				   AS DIRECCION										
					,MANT.UBIGEODEST			   AS UBIGEODEST									
					,COTDET.CODITEM				   AS CODITEM										
					,COTDET.DESCRIPCION			   AS DESCRIPCION									
					,COTIZ.GARANTIA				   AS CODGARANTIA									
					,MANT.NUMPROCESO			   AS NUMPROCESO									
					,MANT.TIPOPROCESO			   AS TIPOPROCESO									
					,MANT.ORDENCOMPRA			   AS ORDENCOMPRA									
					,MANT.NUMFIANZA				   AS NUMFIANZA										
				FROM [dbo].[TBM_MANT_PREV] MANT WITH(NOLOCK)										
				LEFT JOIN [dbo].[TBD_MANT_PREV] MANTDET WITH(NOLOCK) ON MANT.ID_MANT = MANTDET.ID_MANT
				LEFT JOIN [dbo].[TBD_DESPACHO_DIST] DESP WITH(NOLOCK) ON MANT.SERIE = DESP.NUMSERIE
				LEFT JOIN [dbo].[TBD_COTIZACIONCOSTOS] COTCOST WITH(NOLOCK) ON DESP.ID_COTDETALLE = COTCOST.ID_COTDETALLE
				LEFT JOIN [dbo].[TBD_COTIZACIONVENTA] COTDET WITH(NOLOCK) ON COTDET.ID = COTCOST.ID_COTDETALLE
				LEFT JOIN [dbo].[TBM_COTIZACIONVENTA] COTIZ WITH(NOLOCK) ON COTIZ.ID_COTIZACION = COTDET.ID_COTIZACION AND COTIZ.ESTADO = ''A''
				LEFT JOIN [dbo].[TBM_SOLICITUDVENTA] SOL WITH(NOLOCK) ON SOL.ID_SOLICITUD = COTIZ.ID_SOLICITUD
				WHERE 1 = 1
				'
	IF (@IsIdMant != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.ID_MANT = '''+CAST(@IsIdMant AS VARCHAR)+''' '
	END
	IF (@IsNumSerie != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.SERIE = '''+CAST(@IsNumSerie AS VARCHAR)+''' '
	END
	IF (@IsNumProc != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.NUMPROCESO = '''+CAST(@IsNumProc AS VARCHAR)+''' '
	END
	IF (@IsNumOrdCompra != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.ORDENCOMPRA = '''+CAST(@IsNumOrdCompra AS VARCHAR)+''' '
	END
	IF (@IsNumFianza != '0')
	BEGIN
		SET @sql = @sql +' AND MANT.NUMFIANZA = '''+CAST(@IsNumFianza AS VARCHAR)+''' '
	END
	IF (@IsEmpresa != '0')
	BEGIN
		SET @sql = @sql +' AND SOl.COD_EMPRESA = '''+CAST(@IsEmpresa AS VARCHAR)+''' '
	END
	--IF (@IsEstado != '')
	--BEGIN
	--	SET @sql = @sql +' AND MANT.ESTADO = '''+CAST(@IsEstado AS VARCHAR)+''' '
	--END

	SET @sql = @sql +'
				GROUP BY MANT.ID_MANT
					,SERIE
					,MANT.FECHAINSTALACION
					,SOL.COD_EMPRESA
					,MANT.DIRECCION
					,MANT.UBIGEODEST
					,COTDET.CODITEM
					,COTDET.DESCRIPCION
					,COTIZ.GARANTIA
					,MANT.NUMPROCESO
					,MANT.TIPOPROCESO
					,MANT.ORDENCOMPRA
					,MANT.NUMFIANZA'
	--print(@sql)

	INSERT INTO #tmpParcial
	EXEC sp_executesql @sql

	SELECT
		parcial.ID_MANT
		,parcial.SERIE
		,parcial.DESCRIPCION
		,parcial.FECHAINSTALACION
		,ISNULL(CONVERT(VARCHAR(10),prox.PROXFECHAMANT,103),'') PROXFECHAMANT
		,calc.TOTALPREVE
		,calc.COMPLETADOS
		,calc.PENDIENTES
		,CONCAT(UBI.NOMDEPARTAMENTO,' / ',UBI.NOMPROVINCIA,' / ',UBI.NOMDISTRITO) AS UBIGEODEST
	FROM #tmpParcial parcial
	LEFT JOIN #tmpProxavencer prox ON parcial.SERIE = prox.SERIE
	LEFT JOIN #tmpMantPrev calc ON calc.ID_MANT = parcial.ID_MANT
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] GARANT WITH(NOLOCK) ON parcial.CODGARANTIA = GARANT.COD_VALOR1 AND DOMINIO = 'GARANTIAS' AND GARANT.ESTADO = '1'
	LEFT JOIN [dbo].[TBM_UBIGEO] UBI WITH(NOLOCK) ON UBI.CODUBIGEO = parcial.UBIGEODEST
	WHERE CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102) BETWEEN IIF(@IsPeriodoInicio IS NULL,CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102),CONVERT(VARCHAR(7),@IsPeriodoInicio,102)) AND IIF(@IsPeriodoFinal IS NULL, CONVERT(VARCHAR(7),prox.PROXFECHAMANT,102),CONVERT(VARCHAR(7),@IsPeriodoFinal,102))
	ORDER BY ID_MANT ASC

SET NOCOUNT OFF
END