USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_SEL_TECNICOS]
(
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		28.11.24		Realiza el select de la los técnicos para la bandeja de preventivos.
	EXEC [USP_PREV_SEL_TECNICOS] 1
  =======================================================================================================*/
	@IsNumMant BIGINT
)
AS
BEGIN
	SELECT 
		TECNICO.ID
		,TECNICO.ID_MANT
		,TECNICO.COD_TECNICO
		,TECNICO.NOMBRES
		,TECNICO.APELLIDOPATERNO
		,TECNICO.APELLIDOMATERNO
		,TECNICO.DOCUMENTO
		,TECNICO.TIPO_DOCUMENTO
		,TECNICO.CORREO
		,TECNICO.TELEFONO
		,TECNICO.ZONA
		,CONCAT(ISNULL(ubi.[NOMDEPARTAMENTO],''),' / ',ISNULL(ubi.[NOMPROVINCIA],''),' / ',ISNULL(ubi.[NOMDISTRITO],'')) AS UBIGEO
		,TECNICO.EMPRESA
		,tipo.VALOR1 AS NOMTIPOTECNICO
		,datos.DESCRIPCION AS NOM_TIPO_DOCUMENTO
		,TECNICO.TIPOTECNICO
		,TECNICO.ESTADO
		,TECNICO.USR_REG
		,TECNICO.FEC_REG 
	FROM [dbo].[TBD_TECNICO_MANT_PREV] AS TECNICO WITH(NOLOCK)
	LEFT JOIN [dbo].[TBM_UBIGEO] AS UBI WITH(NOLOCK) ON UBI.CODUBIGEO = TECNICO.ZONA
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] datos WITH(NOLOCK) ON datos.PARAMETRO = TECNICO.TIPO_DOCUMENTO
	LEFT JOIN [dbo].[TBD_DATOS_GENERALES] tipo WITH(NOLOCK) ON tipo.COD_VALOR1 = TECNICO.TIPOTECNICO
	WHERE TECNICO.ESTADO = '1' AND ID_MANT = @IsNumMant

END