USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_SEL_INFO_SOL
/*=============================================================================
	NOMBRE:					FECHA:		DESCRIPCIÓN:
	José A. Peralta		02.12.24		Se consulta informacion de caracteristicas de solicitud
	EXEC USP_SEL_INFO_SOL 1
  =============================================================================*/
@ID_COTDETALLE BIGINT
AS
BEGIN
	SELECT A.ID_COTDETALLE,  
		CASE WHEN A.INDINFOMANUAL='S' THEN 'SI' ELSE 'NO' END INDINFOMANUAL,
		CASE WHEN A.INDCALIB='S' THEN 'SI' ELSE 'NO' END INDCALIB,
		CASE WHEN A.INDINFOVIDEO='S' THEN 'SI' ELSE 'NO' END INDINFOVIDEO,
		CASE WHEN A.INDMANTPREVENT='S' THEN 'SI' ELSE 'NO' END INDMANTPREVENT,
		CASE WHEN A.INDCAPACITACION='S' THEN 'SI' ELSE 'NO' END INDINSTA,
		'SI' INDCAPA,
		CASE WHEN A.INDREQPLACA='S' THEN 'SI' ELSE 'NO' END INDREQPLACA,
		CASE WHEN A.INDGARANADIC='S' THEN 'SI' ELSE 'NO' END INDGARANADIC,
		ISNULL(A.CODGARANADIC,'') CODGARANADIC ,
		ISNULL(B.VALOR1,'') NOMGARANTIADIC,
		ISNULL(A.OBSCLIENTE,'') OBSCLIENTE,
		ISNULL(A.OBSDESPACHO,'') OBSDESPACHO,
		ISNULL(A.DIMENSIONES,'')  DIMENSIONES
		FROM TBM_COTDET_DESPACHO A WITH(NOLOCK)
		LEFT JOIN TBD_DATOS_GENERALES B ON B.DOMINIO='GARANTIAS' AND A.CODGARANADIC=B.PARAMETRO
		WHERE A.ID_COTDETALLE = @ID_COTDETALLE

END





