USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_PREV_MANT_PEVENTIVO]
/*=======================================================================================================
	Nombre:				Fecha:			Descripcion:
	Diego Bazalar		20.11.24		Inserta Reclamo con parametros
  =======================================================================================================*/
(
	 @IsTipoEjecucion		  CHAR(1)
	,@IsID					  BIGINT
	,@IsID_MANT				  BIGINT
	,@IsID_WORKFLOW			  BIGINT
	,@IsFECHAMANTENIMIENTO	  DATETIME
	,@IsMONTOPRESTACCE		  DECIMAL(18,9)
	,@IsINDPRESTACION		  CHAR(1)
	,@IsINDREPUESTO			  CHAR(1)
	,@IsNUMFACTURA			  VARCHAR(200)
	,@IsFECHAFACTURA		  DATETIME
	,@IsESTADO				  VARCHAR(6)
	,@IsUsrEjecuta			  VARCHAR(50)
)
AS
BEGIN
	DECLARE @CODPREV BIGINT, @MSG VARCHAR(100), @FECHAPOST DATETIME
	SET NOCOUNT ON;

	IF (@IsTipoEjecucion = 'I')
		BEGIN
			INSERT INTO [dbo].[TBD_MANT_PREV](ID_MANT,ID_WORKFLOW,FECHAMANTENIMIENTO,MONTOPRESTACCE,INDPRESTACION,INDREPUESTO,NUMFACTURA,FECHAFACTURA,ESTADO,USR_REG,FEC_REG)
			VALUES (@IsID_MANT,@IsID_WORKFLOW,@IsFECHAMANTENIMIENTO,@IsMONTOPRESTACCE,@IsINDPRESTACION,@IsINDREPUESTO,@IsNUMFACTURA,@IsFECHAFACTURA,@IsESTADO,@IsUsrEjecuta,GETDATE())

			IF @@ROWCOUNT = 0
			BEGIN
				SET @CODPREV = 0;
				SET @MSG = 'ERROR EN EL REGISTRO DE LA TABLA [TBD_MANT_PREV]'
			END
			ELSE
			BEGIN
				SET @CODPREV = @@IDENTITY;
				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
			END
		END
	ELSE
	BEGIN
		IF(@IsTipoEjecucion = 'U')
			BEGIN
				IF EXISTS(SELECT FECHAMANTENIMIENTO FROM TBD_MANT_PREV WHERE ID_MANT = @IsID_MANT AND ID = @IsID + 1) --Si existe una fecha posterior a la fecha de seleccionada.
				BEGIN
					SELECT 
						@FECHAPOST = FECHAMANTENIMIENTO 
					FROM TBD_MANT_PREV 
					WHERE ID_MANT = @IsID_MANT AND ID = @IsID + 1

					IF(@FECHAPOST <= @IsFECHAMANTENIMIENTO)
					BEGIN 
						SET @CODPREV = -1;
						SET @MSG = 'INCOHERENCIA'
					END
					ELSE
					BEGIN
						UPDATE [TBD_MANT_PREV]
						SET 
							FECHAMANTENIMIENTO = @IsFECHAMANTENIMIENTO
							,MONTOPRESTACCE = @IsMONTOPRESTACCE
							,INDPRESTACION = @IsINDPRESTACION
							,INDREPUESTO = @IsINDREPUESTO
							,ESTADO		= @IsESTADO
							,USR_MOD	= @IsUsrEjecuta
							,FEC_MOD	= GETDATE()
						WHERE ID = @IsID

						IF @@ROWCOUNT = 0
						BEGIN
							SET @CODPREV = 0;
							SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA [TBD_MANT_PREV]'
						END
						ELSE
						BEGIN
							SET @CODPREV = @IsID;
							SET @MSG = 'REGISTRO REALIZADO CON EXITO'
						END
					END
				END
				ELSE
				BEGIN
				UPDATE [TBD_MANT_PREV]
						SET 
							FECHAMANTENIMIENTO = @IsFECHAMANTENIMIENTO
							,MONTOPRESTACCE = @IsMONTOPRESTACCE
							,INDPRESTACION = @IsINDPRESTACION
							,INDREPUESTO = @IsINDREPUESTO
							,ESTADO		= @IsESTADO
							,USR_MOD	= @IsUsrEjecuta
							,FEC_MOD	= GETDATE()
						WHERE ID = @IsID

						IF @@ROWCOUNT = 0
						BEGIN
							SET @CODPREV = 0;
							SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA [TBD_MANT_PREV]'
						END
						ELSE
						BEGIN
							SET @CODPREV = @IsID;
							SET @MSG = 'REGISTRO REALIZADO CON EXITO'
						END
				END
			END
		IF(@IsTipoEjecucion = 'E')
		BEGIN
			UPDATE [TBD_MANT_PREV]
			SET
				ESTADO		= @IsESTADO
				,USR_MOD	= @IsUsrEjecuta
				,FEC_MOD	= GETDATE()
			WHERE ID = @IsID
			IF @@ROWCOUNT = 0
			BEGIN
				SET @CODPREV = 0;
				SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA [TBD_MANT_PREV]'
			END
			ELSE
			BEGIN
				SET @CODPREV = @IsID;
				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
			END
		END
		IF(@IsTipoEjecucion = 'C')
		BEGIN
			UPDATE [TBD_MANT_PREV]
			SET
				NUMFACTURA		= @IsNUMFACTURA
				,FECHAFACTURA	= @IsFECHAFACTURA
				,ESTADO			= @IsESTADO
				,USR_MOD		= @IsUsrEjecuta
				,FEC_MOD		= GETDATE()
			WHERE ID = @IsID
			IF @@ROWCOUNT = 0
			BEGIN
				SET @CODPREV = 0;
				SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA [TBD_MANT_PREV]'
			END
			ELSE
			BEGIN
				SET @CODPREV = @IsID;
				SET @MSG = 'REGISTRO REALIZADO CON EXITO'
			END
		END
	END
	SELECT @CODPREV COD, @MSG MSG
	SET NOCOUNT ON;
END