USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_TECNICOS_DESPACHO
/*===================================================================================
		NOMBRE:					FECHA:		DESCRIPCIÓN:
		José A. Peralta		09.12.24		Mantenimiento de tecnicos en despacho
  ===================================================================================*/
  @TIPO CHAR(1),
  @ID BIGINT,
  @ID_SOLICITUD BIGINT,
  @COD_TECNICO INT,
  @NOMBRE VARCHAR(50),
  @APELLIDOPATERNO VARCHAR(50),
  @APELLIDOMATERNO VARCHAR(50),
  @DOCUMENTO VARCHAR(9),
  @TIPODOCUMENTO VARCHAR(12),
  @CORREO VARCHAR(100),
  @TELEFONO	VARCHAR(100),
  @ZONA	VARCHAR(6),
  @EMPRESA VARCHAR(200),
  @TIPOTECNICO CHAR(1),
  @ESTADO BIT,
  @USR_REG VARCHAR(50)
AS
BEGIN
	DECLARE @CODIGO INT , @MSG VARCHAR(100),@ID_DESPACHO BIGINT 
	SELECT @CODIGO = 0,@MSG = ''

	SELECT @ID_DESPACHO=  ID FROM TBM_DESPACHO WHERE ID_SOLICITUD=@ID_SOLICITUD AND STOCK='X' AND ID_SOLDESPACHO = @ID;

	IF(@TIPO = 'I')
	BEGIN
		IF NOT EXISTS(SELECT	1 FROM TBD_TECNICODESPACHO WHERE DOCUMENTO= @DOCUMENTO AND ESTADO=1 AND ID_DESPACHO=@ID_DESPACHO)
		BEGIN
		

			INSERT INTO TBD_TECNICODESPACHO (ID_DESPACHO,COD_TECNICO,NOMBRES,APELLIDOPATERNO,APELLIDOMATERNO,DOCUMENTO,TIPO_DOCUMENTO,
					CORREO,TELEFONO,ZONA,EMPRESA,TIPOTECNICO,ESTADO,USR_REG,FEC_REG)
					VALUES(@ID_DESPACHO,@COD_TECNICO,@NOMBRE,@APELLIDOPATERNO,@APELLIDOMATERNO,@DOCUMENTO,@TIPODOCUMENTO,
					@CORREO,@TELEFONO,@ZONA,@EMPRESA,@TIPOTECNICO,@ESTADO,@USR_REG,GETDATE())

			IF @@ROWCOUNT = 0
			BEGIN
				SELECT 
					@CODIGO = 0
					,@MSG = 'Error al realizar el registro' 
			END
			ELSE
			BEGIN
				SELECT 
					@CODIGO = @@IDENTITY
					,@MSG = 'Se registro con éxito el tecnico.' 
			END		
		END
		ELSE
		BEGIN
			SELECT @CODIGO = 0,@MSG = 'El técnico ya ha sido seleccionado.' 
		END
	END
	IF(@TIPO = 'U')
	BEGIN
		UPDATE TBD_TECNICODESPACHO
		SET 
			EMPRESA		= @EMPRESA
			,USR_MOD	= @USR_REG
			,FEC_MOD	= GETDATE()
		WHERE COD_TECNICO = @COD_TECNICO AND 
					ID_DESPACHO=@ID_DESPACHO AND
					ESTADO=1

		IF @@ROWCOUNT = 0
		BEGIN
			SET @CODIGO = 0;
			SET @MSG = 'ERROR EN LA ACTUALIZACIÓN DE LA TABLA TBD_TECNICODESPACHO'
		END
		ELSE
		BEGIN
			SET @CODIGO = @ID_DESPACHO;
			SET @MSG = 'REGISTRO REALIZADO CON EXITO'
		END
	END
	IF(@TIPO = 'D')
	BEGIN
			UPDATE TBD_TECNICODESPACHO
			SET ESTADO= 0,
					USR_MOD = @USR_REG,
					FEC_MOD = GETDATE()
			WHERE 
				ID = @ID AND
				ESTADO=1

				SELECT @CODIGO = 1,@MSG = 'Se eliminó el tecnico con éxito.' 
	END

	SELECT @CODIGO COD ,@MSG  MSG


END