USE [DB_AHSECO]
GO

CREATE OR ALTER PROCEDURE USP_MANT_TECNICOS_DESPACHO
/*===================================================================================
		NOMBRE:					FECHA:		DESCRIPCIÓN:
		José A. Peralta		09.12.24		Mantenimiento de tecnicos en despacho
  ===================================================================================*/
  @TIPO CHAR(1),
  @ID BIGINT,
  @ID_SOLICITUD BIGINT,
  @COD_TECNICO INT,
  @NOMBRE VARCHAR(50),
  @APELLIDOPATERNO VARCHAR(50),
  @APELLIDOMATERNO VARCHAR(50),
  @DOCUMENTO VARCHAR(9),
  @TIPODOCUMENTO VARCHAR(12),
  @CORREO VARCHAR(100),
  @TELEFONO	VARCHAR(100),
  @ZONA	VARCHAR(6),
  @EMPRESA VARCHAR(200),
  @TIPOTECNICO CHAR(1),
  @ESTADO BIT,
  @USR_REG VARCHAR(50)
AS
BEGIN
	DECLARE @CODIGO INT , @MSG VARCHAR(100),@ID_DESPACHO BIGINT 
	SELECT @CODIGO = 0,@MSG = ''

	SELECT @ID_DESPACHO=  MAX(ID) FROM TBM_DESPACHO WHERE ID_SOLICITUD=@ID_SOLICITUD;

	IF(@TIPO = 'I')
	BEGIN

	IF NOT EXISTS(SELECT * FROM TBD_TECNICODESPACHO WHERE DOCUMENTO= @DOCUMENTO AND ESTADO=1)
	BEGIN
		

		INSERT INTO TBD_TECNICODESPACHO (ID_DESPACHO,COD_TECNICO,NOMBRES,APELLIDOPATERNO,APELLIDOMATERNO,DOCUMENTO,TIPO_DOCUMENTO,
				CORREO,TELEFONO,ZONA,EMPRESA,TIPOTECNICO,ESTADO,USR_REG,FEC_REG)
				VALUES(@ID_DESPACHO,@COD_TECNICO,@NOMBRE,@APELLIDOPATERNO,@APELLIDOMATERNO,@DOCUMENTO,@TIPODOCUMENTO,
				@CORREO,@TELEFONO,@ZONA,@EMPRESA,@TIPOTECNICO,@ESTADO,@USR_REG,GETDATE())

			SELECT @CODIGO = 1,@MSG = 'Se registro con éxito el tecnico.' 
	END
	ELSE
	BEGIN
		SELECT @CODIGO = 0,@MSG = 'El técnico ya ha sido seleccionado.' 
	END
		

		

	END

	IF(@TIPO = 'D')
	BEGIN
			UPDATE TBD_TECNICODESPACHO
				SET ESTADO= 0,
						USR_MOD = @USR_REG,
						FEC_MOD = GETDATE()
				WHERE COD_TECNICO = @COD_TECNICO AND 
					ID_DESPACHO=@ID_DESPACHO AND
					ESTADO=1

					SELECT @CODIGO = 1,@MSG = 'Se eliminó el tecnico con éxito.' 
	END

	SELECT @CODIGO COD ,@MSG  MSG


END