USE DB_AHSECO
GO

CREATE OR ALTER PROCEDURE USP_UPD_PREV_MIGRA(
@IsNumSerie			VARCHAR(50)
,@IsNum				INT
,@IsOtm				VARCHAR(50)
,@IsConst			VARCHAR(50)
,@IsEstado			VARCHAR(20)
,@IsColaborador		VARCHAR(200)
,@IsComentarios		VARCHAR(8000)
)
AS
BEGIN
	DECLARE @ID_MANTDET BIGINT, @ID_WORKFLOW BIGINT, @MSG VARCHAR(400), @COD INT, @ID_MIG BIGINT, @PERFIL VARCHAR(100)

	BEGIN TRY
		IF(ISNULL(@IsNumSerie,'') != '')
		BEGIN
			;WITH CTE_1 AS (
					SELECT
						ROW_NUMBER() OVER( ORDER BY MANTDET.ID) AS CONTADOR
						,MANTDET.* 
					FROM [dbo].[TBD_MANT_PREV] MANTDET
					LEFT JOIN [dbo].[TBM_MANT_PREV] MANT ON MANTDET.ID_MANT = MANT.ID_MANT
					WHERE MANT.SERIE = @IsNumSerie
				), CTE_2 AS (
					SELECT
					MANTDET.ID
					,MANTDET.ID_WORKFLOW
					FROM [dbo].[TBD_MANT_PREV] AS MANTDET WITH(NOLOCK)
					INNER JOIN CTE_1 AS CTE ON CTE.ID = MANTDET.ID 
					WHERE CTE.CONTADOR = @IsNum
				)
				SELECT 
				@ID_MANTDET = ID
				,@ID_WORKFLOW = ID_WORKFLOW
				FROM CTE_2

				UPDATE [TBD_MANT_PREV]
				SET 
					VAL_OTM = @IsOtm
					,MIG_CONST = @IsConst
				WHERE ID = @ID_MANTDET

				IF ISNULL(@IsEstado,'') != '' --Solo se actualizan aquellos que sí cuenten con estado.
				BEGIN

					SELECT @PERFIL=ISNULL(C.DESCRIPCION,'') FROM TBM_SEGURIDAD_USUARIO A WITH(NOLOCK) 
					INNER JOIN TBM_SEGURIDAD_USUARIO_PERFIL B WITH(NOLOCK) ON A.ID=B.USUARIO_ID AND B.HABILITADO=1
					INNER JOIN TBM_SEGURIDAD_PERFIL C WITH(NOLOCK) ON B.PERFIL_ID=C.ID
					WHERE UPPER(A.USUARIO) =UPPER('admin') 

					UPDATE [TBD_MANT_PREV]
					SET 
						ESTADO = @IsEstado 
					WHERE ID = @ID_MANTDET


					INSERT INTO [dbo].[TBM_WORKFLOWLOG] (ID_WORKFLOW,COD_ESTADO,CARGO,AREA,AUDIT_REG_USR,AUDIT_REG_FEC)
					SELECT @ID_WORKFLOW, @IsEstado,@PERFIL,'', 'admin', GETDATE()
				END

				IF(ISNULL(@IsColaborador, '') != '')
				BEGIN
					INSERT INTO [TBD_TECNICO_MANT_PREV](ID_DETALLE,COD_TECNICO,NOMBRES,APELLIDOPATERNO,ESTADO,USR_REG,FEC_REG)
					VALUES (@ID_MANTDET, NULL, SUBSTRING(@IsColaborador,0,CHARINDEX(' ',@IsColaborador,0)), SUBSTRING(@IsColaborador, CHARINDEX(' ',@IsColaborador, 0),LEN(@IsColaborador)),1,'admin',GETDATE())
				END
				

				IF (ISNULL(@IsComentarios, '') != '')
				BEGIN
					INSERT INTO TBM_OBSERVACIONES(ID_WORKFLOW,ESTADO_INSTANCIA,OBSERVACION,NOMBRE_USUARIO,PERFIL_USUARIO,CODREF,USR_REG,FEC_REG)
					VALUES (@ID_WORKFLOW, @IsEstado, @IsComentarios,'ADMINISTRADOR_MIGRACION','ADMINISTRADOR_MIGRACION',NULL, 'admin',GETDATE())
				END
		END
	END TRY
	BEGIN CATCH
		SET @COD = 0
		SET @MSG = 'Error en el USP: Linea:'+CAST(ERROR_LINE() AS VARCHAR)+', Mensaje de error:' + CAST(ERROR_MESSAGE() AS VARCHAR(500))
		SELECT @COD COD, @MSG MSG

	END CATCH
END