USE [DB_AHSECO]
GO

CREATE TABLE TBM_SOLDESPACHO(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_SOLICITUD BIGINT NOT NULL,
	ID_COTIZACION BIGINT NOT NULL,
	ID_WORKFLOW BIGINT NOT NULL,
	TIPODESP VARCHAR(6) NULL,
	NUMORDEN VARCHAR(50) NULL,
	FECHAORDEN DATETIME NULL,
	FECHAMAX DATETIME NULL,
	NUMFACTURA VARCHAR(100) NULL,
	FECHAFACTURA DATETIME NULL,
	NUMCONTRATO VARCHAR(50) NULL,
	FEC_CONTRATO DATETIME NULL,
	CALCULO CHAR(1) NULL,
	FIANZA CHAR(1) NULL,
	PRESTPRIN CHAR(1) NULL,
	NUMFIANZAPP VARCHAR(50) NULL,
	PRESTACC CHAR(1) NULL,
	NUMFIANZAPA VARCHAR(50) NULL,
	PORCDSCTO DECIMAL (18,9) NULL,
	SUBTOTALVENTA DECIMAL(18,9) NULL,
	MONTOIGV DECIMAL(18,9) NULL,
	TOTALVENTA DECIMAL(18,9) NULL,
	ESTADO VARCHAR(6) NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME  NULL
	 CONSTRAINT [PK_TBM_SOLDESPACHO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE TBD_DESPACHO_COTIZACION(
	ID BIGINT IDENTITY(1,1) NOT NULL ,
	ID_SOLDESPACHO BIGINT NOT NULL,
	ID_COTDETALLE BIGINT NOT NULL,
	CANTIDAD INT,
	INDSTOCK CHAR(1),
	VALORUNITARIO DECIMAL(18,9),
	VALORTOTAL DECIMAL(18,9),
	MARGENADICIONAL  DECIMAL(18,9),
	VVTOTALSIGVCGAN DECIMAL(18,9),
	MONTODSCTO DECIMAL(18,9),
	VVTOTALSIGVDSCTO DECIMAL(18,9),
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
)



--select * from TBM_SOLDESPACHO
--select * from TBD_DESPACHO_COTIZACION





