USE [DB_AHSECO]
GO

/*--
DROP TABLE TBM_INSTALACION
DROP TABLE TBD_INSTALACION
DROP TABLE TBD_TECNICOINSTALACION
*/
CREATE TABLE [TBM_INSTALACION] (
	NUMREQ BIGINT IDENTITY(1,1),
	ID_WORKFLOW BIGINT NOT NULL,
	ID_SOLICITUD BIGINT NOT NULL,
	RUCEMPRESA VARCHAR(12) NULL,
	NOMEMPRESA VARCHAR(200) NULL,
	UBICACION VARCHAR(200) NULL,
	NOMBRECONTACTO VARCHAR(150) NULL,
	TELEFONOCONTACTO VARCHAR(50) NULL,
	CARGOCONTACTO VARCHAR(50) NULL,
	ESTABLECIMIENTO VARCHAR(100) NULL,
	TIPOVENTA VARCHAR(25) NULL,
	ORDENCOMPRA VARCHAR(35) NULL,
	NUMPROCESO VARCHAR(15) NULL,
	CONTRATO VARCHAR(25) NULL,
	FIANZA CHAR(1) NULL,
	NUMFIANZA VARCHAR(15) NULL,
	VENDEDOR VARCHAR(150) NULL,
	FECHAMAX DATETIME NULL,
	DESTINO VARCHAR(75) NOT NULL,
	ESTADO VARCHAR(6) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL 
	CONSTRAINT [PK_TBM_INSTALACION] PRIMARY KEY CLUSTERED 
(
	[NUMREQ] ASC
)
) ON [PRIMARY]
GO




CREATE TABLE [TBD_INSTALACION] (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	NUMREQ BIGINT NOT NULL,
	CANTIDAD INT  NULL,
	MARCA VARCHAR(150) NULL,
	MODELO VARCHAR(200) NULL,
	SERIE VARCHAR(200) NULL,
	CANTIDADMP INT NULL,
	PERIODICIDAD VARCHAR(6) NULL,
	GARANTIA VARCHAR(6) NULL,
	FECHAPROGRAMACION DATETIME NULL,
	FECHAREAL DATETIME NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_INSTALACION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE [TBD_TECNICOINSTALACION] (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_DETALLE BIGINT NOT NULL,
	COD_TECNICO INT NULL,
	NOMBRETECNICO VARCHAR(250) NULL,
	DOCUMENTO VARCHAR(12) NULL,
	CORREO VARCHAR(100) NULL,
	TELEFONO VARCHAR(100) NULL,
	ZONA VARCHAR(6) NULL,
	TIPOTECNICO CHAR(1) NULL,
	ESTADO BIT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_TECNICOINSTALACION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO
