USE [DB_AHSECO]
GO

CREATE TABLE TBM_SEDES
(
	ID_SEDE INT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE BIGINT NOT NULL,
	NOMSEDE VARCHAR(150) NULL,
	CODIGO_UNICO VARCHAR(8) NULL,
	CLASIFICACION VARCHAR(100) NULL,
	TIPO VARCHAR(6) NULL,
	UBIGEO VARCHAR(6) NULL,
	ESTADO CHAR(1) NOT NULL,
	ELIMINADO INT NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBM_SEDES] PRIMARY KEY CLUSTERED 
(
	[ID_SEDE] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE TBM_ASIG_CLIE_MANUAL
ADD ID_SEDE INT NULL
