USE [DB_AHSECO]
GO

/*--
DROP TABLE TBM_INSTALACION
DROP TABLE TBD_INSTALACION
DROP TABLE TBD_TECNICOINSTALACION
*/

CREATE TABLE [TBM_INSTALACION] (
	NUMREQ BIGINT IDENTITY(1,1),
	ID_WORKFLOW BIGINT NOT NULL,
	ID_SOLICITUD BIGINT NOT NULL,
	RUCEMPRESA VARCHAR(12) NULL,
	NOMEMPRESA VARCHAR(200) NULL,
	UBICACION VARCHAR(200) NULL,
	NOMBRECONTACTO VARCHAR(150) NULL,
	TELEFONOCONTACTO VARCHAR(50) NULL,
	CARGOCONTACTO VARCHAR(50) NULL,
	ESTABLECIMIENTO VARCHAR(100) NULL,
	TIPOVENTA VARCHAR(25) NULL,
	ORDENCOMPRA VARCHAR(35) NULL,
	NUMPROCESO VARCHAR(15) NULL,
	TIPOPROCESO VARCHAR(200) NULL,
	CONTRATO VARCHAR(25) NULL,
	CODEMPRESA VARCHAR(6) NULL,
	VENDEDOR VARCHAR(150) NULL,
	FECHAMAX DATETIME NULL,
	DESTINO VARCHAR(75) NOT NULL,
	ESTADO VARCHAR(6) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL 
	CONSTRAINT [PK_TBM_INSTALACION] PRIMARY KEY CLUSTERED 
(
	[NUMREQ] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [TBD_INSTALACION] (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	NUMREQ BIGINT NOT NULL,
	ID_DESPACHO_DIST BIGINT NOT NULL,
	CODIGOPRODUCTO VARCHAR(35) NOT NULL,
	DESCRIPCION VARCHAR(100) NULL,
	CANTIDAD INT  NULL,
	MARCA VARCHAR(150) NULL,
	MODELO VARCHAR(200) NULL,
	SERIE VARCHAR(200) NULL,
	NUMFIANZA VARCHAR(50) NULL,
	CANTIDADMP INT NULL,
	PERIODICIDAD VARCHAR(20) NULL,
	GARANTIA VARCHAR(6) NULL,
	GARANTIAADIC VARCHAR(50) NULL,
	INDLLAVEMANO CHAR(1) NULL,
	CODUBIGEODEST VARCHAR(6) NULL,
	DIRECCION VARCHAR(150) NULL,
	NROPISO INT NULL,
	DIMENSIONES VARCHAR(50) NULL,
	INDCALIBRACION CHAR(1) NULL,
	INDREQUIEREPLACA CHAR(1) NULL,
	FECLIMINSTA DATETIME NULL,
	INDFIANZA CHAR(1) NULL,
	MONTOPPRINC DECIMAL(18,9) NULL,
	MONTOPACCE DECIMAL(18,9) NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_INSTALACION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [TBD_TECNICOINSTALACION] (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_DETALLE BIGINT NOT NULL,
	COD_TECNICO INT NULL,
	NOMBRES VARCHAR(50) NULL,
	APELLIDOPATERNO VARCHAR(50) NULL,
	APELLIDOMATERNO VARCHAR(50) NULL,
	DOCUMENTO VARCHAR(12) NULL,
	TIPO_DOCUMENTO VARCHAR(9) NULL, 
	CORREO VARCHAR(100) NULL,
	TELEFONO VARCHAR(100) NULL,
	ZONA VARCHAR(6) NULL,
	EMPRESA VARCHAR(200) NULL,
	TIPOTECNICO CHAR(1) NULL,
	ESTADO BIT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_TECNICOINSTALACION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO
