USE [DB_AHSECO]
GO

CREATE TABLE TBM_INSTALACION (
	ID_INSTALACION BIGINT IDENTITY(1,1),
	ID_WORKFLOW BIGINT NOT NULL,
	ID_SOLICITUD BIGINT NOT NULL,
	COD_EMPRESA VARCHAR(10) NOT NULL,
	ID_TECNICO INT NOT NULL,
	MOTIVO VARCHAR(250) NULL,
	ESTADO VARCHAR(6) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
)

