USE [DB_AHSECO]
GO

/*
SELECT * FROM TBM_SOLICITUDVENTA
SELECT * FROM TBM_COTIZACIONVENTA
SELECT * FROM TBD_COTIZACIONVENTA
SELECT * FROM TBD_COTIZACIONCOSTOS

DROP TABLE TBM_SOLICITUDVENTA
DROP TABLE  TBM_COTIZACIONVENTA
DROP TABLE TBD_COTIZACIONVENTA
DROP TABLE TBD_COTIZACIONCOSTOS
*/


CREATE TABLE TBM_SOLICITUDVENTA
(
	ID_SOLICITUD BIGINT IDENTITY(1,1) NOT NULL,
	ID_WORKFLOW BIGINT  NOT NULL,
	ID_FLUJO INT NOT NULL,
	FECHA_SOL DATETIME NOT NULL,
	TIPO_SOL VARCHAR(6) NOT NULL,
	COD_MEDIOCONT VARCHAR(6) NOT NULL,
	IDCLIENTE INT NOT NULL,
	RUC	VARCHAR(12) NOT NULL,
	RAZONSOCIAL VARCHAR(200) NOT NULL,
	ASESORVENTA VARCHAR(200) NOT NULL,
	ESTADO VARCHAR(3) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	IP_REG VARCHAR(35) NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL,
	IP_MOD VARCHAR(35) NULL
 CONSTRAINT [PK_TBM_SOLICITUDVENTA] PRIMARY KEY CLUSTERED 
(
	[ID_SOLICITUD] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE TBM_COTIZACIONVENTA
(
	ID_COTIZACION BIGINT IDENTITY(1,1) NOT NULL,
	ID_SOLICITUD BIGINT  NOT NULL,
	FEC_COTIZACION DATETIME NOT NULL,
	NOMBRECONTACTO VARCHAR(150)  NOT NULL,
	AREACONTACTO VARCHAR(100) NOT NULL,
	TELEFONOCONTACTO VARCHAR(50) NOT NULL,
	EMAILCONTACTO VARCHAR(35) NOT NULL,
	PLAZOENTREGA VARCHAR(100) NOT NULL,
	FORMAPAGO VARCHAR(6) NOT NULL,
	MONEDA VARCHAR(5) NULL,
	VIGENCIA VARCHAR(50) NULL,
	GARANTIA VARCHAR(5) NOT NULL,
	OBSERVACION VARCHAR(200) NULL,
	ESTADO VARCHAR(1) NOT NULL, -- A: ACTIVO, I: INACTIVO
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBM_COTIZACIONVENTA] PRIMARY KEY CLUSTERED 
(
	[ID_COTIZACION] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE TBD_COTIZACIONVENTA
(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_COTIZACION BIGINT  NOT NULL,
	ITEM INT NOT NULL, --1,2,3,4,5
	TIPO VARCHAR(5) NOT NULL, --PRODUCTO, CALIBRACION, FLETE
	TIPOPRODUCTO VARCHAR(3) NULL, --PRO: PRODUCTO / ACC: ACCESORIO
	CODPRODUCTO VARCHAR(35)  NOT NULL,
	DESCRIPCION VARCHAR(100)  NOT NULL,
	STOCK INT NULL,
	UNIDAD VARCHAR(3)  NOT NULL,
	CANTIDAD INT NOT NULL,
	COSTOFOB DECIMAL(18,9) NULL,
	VVENTAUNI DECIMAL(18,9) NULL,
	VVTOTALSIGV DECIMAL(18,2) NULL,
	PORCGANANCIA DECIMAL(9,2) NOT NULL,
	VVTOTALCGAN DECIMAL(18,2) NOT NULL,
	ELIMINADO BIT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_COTIZACIONVENTA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO



CREATE TABLE TBD_COTIZACIONCOSTOS
(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_COTIZACION BIGINT  NOT NULL,
	ITEM INT NOT NULL,
	VALORVENTAPRODSD DECIMAL(18,9) NOT NULL,
	VALORVENTATOTALSD DECIMAL(18,9) NOT NULL,
	DSCTO DECIMAL(9,2) NOT NULL,
	SUBTOTALSD DECIMAL(18,9) NOT NULL,
	IGVSD DECIMAL(18,2) NOT NULL,
	TOTALVENTASD DECIMAL(18,2) NOT NULL,
	VALORVENTAPRODCD DECIMAL(18,9) NOT NULL,
	VALORVENTATOTALCD DECIMAL(18,9) NOT NULL,
	SUBTOTALCD DECIMAL(18,9) NOT NULL,
	IGVCD DECIMAL(18,2) NOT NULL,
	TOTALVENTACD DECIMAL(18,2) NOT NULL,
	TIPO VARCHAR(5) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
 CONSTRAINT [PK_TBD_COTIZACIONCOSTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO



ALTER TABLE TBD_COTIZACIONCOSTOS
ADD CONSTRAINT FK_COTIZACIONCOSTOS_CABECERA
FOREIGN KEY (ID_COTIZACION) REFERENCES TBM_COTIZACIONVENTA(ID_COTIZACION);

ALTER TABLE TBD_COTIZACIONVENTA
ADD CONSTRAINT FK_TBD_COTIZACIONVENTA_CABECERA
FOREIGN KEY (ID_COTIZACION) REFERENCES TBM_COTIZACIONVENTA(ID_COTIZACION);

ALTER TABLE TBM_COTIZACIONVENTA
ADD CONSTRAINT FK_TBM_COTIZACIONVENTA_SOL
FOREIGN KEY (ID_SOLICITUD) REFERENCES TBM_SOLICITUDVENTA(ID_SOLICITUD);