USE [DB_AHSECO]
GO

CREATE TABLE TBM_OBSERVACIONES
(
	ID_OBSERVACION BIGINT IDENTITY(1,1) NOT NULL,
	ID_WORKFLOW BIGINT  NOT NULL,
	ESTADO_INSTANCIA VARCHAR(5) NOT NULL,
	OBSERVACION VARCHAR(8000) NOT NULL,
	NOMBRE_USUARIO VARCHAR(250) NULL,
	PERFIL_USUARIO VARCHAR(100) NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL
 CONSTRAINT [PK_TBM_OBSERVACIONES] PRIMARY KEY CLUSTERED 
(
	[ID_OBSERVACION] ASC
)
) ON [PRIMARY]
GO


