USE [DB_AHSECO]
GO



CREATE TABLE TBM_FLUJOCONTROL(
	ID INT IDENTITY(1,1),
	ID_FLUJO INT NOT NULL,
	FLUJO_ESTADO VARCHAR(5) NOT NULL,
	TIPO VARCHAR(8) NULL,
	TIPOCAMPO CHAR(1) NOT NULL,
	NOMCAMPO VARCHAR(100) NOT NULL,
	STATUSCAMPO VARCHAR(35) NULL,
	ESTADO CHAR(1) NOT NULL,
	USU_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USU_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBM_FLUJOCONTROL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO
