USE [DB_AHSECO]
GO

/*
DROP TABLE [TBM_MANT_PREV]
DROP TABLE [TBD_TECNICO_MANT_PREV]
TBD_DATOS_GENERALES
*/

CREATE TABLE [TBM_MANT_PREV] (
	ID_MANT BIGINT IDENTITY(1,1),
	ID_WORKFLOW BIGINT NOT NULL,
	SERIE VARCHAR(200) NULL,
	NOMEMPRESA VARCHAR(200) NULL,
	ORDENCOMPRA VARCHAR(35) NULL,
	NUMPROCESO VARCHAR(15) NULL,
	TIPOPROCESO VARCHAR(200) NULL,
	CONTRATO VARCHAR(25) NULL,
	NUMFIANZA VARCHAR(15) NULL,
	FECHAINSTALACION DATETIME NULL,
	[CANTPREVENTIVO] INT NULL,
	[CODCICLOPREVENT] NVARCHAR(10) NULL,
	UBIGEO VARCHAR(6) NULL,
	DIRECCION VARCHAR(150) NULL,
	INDREPUESTO CHAR(1) NULL,
	INDPRESTACION CHAR(1) NULL,
	ESTADO VARCHAR(6) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL 
	CONSTRAINT [TBM_MANT_PREVENT] PRIMARY KEY CLUSTERED 
(
	[ID_MANT] ASC
)
) ON [PRIMARY]
GO



CREATE TABLE [TBD_TECNICO_MANT_PREV] (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_MANT BIGINT NOT NULL,
	COD_TECNICO INT NULL,
	NOMBRES VARCHAR(50) NULL,
	APELLIDOPATERNO VARCHAR(50) NULL,
	APELLIDOMATERNO VARCHAR(50) NULL,
	DOCUMENTO VARCHAR(12) NULL,
	TIPO_DOCUMENTO VARCHAR(9) NULL, 
	CORREO VARCHAR(100) NULL,
	TELEFONO VARCHAR(100) NULL,
	ZONA VARCHAR(6) NULL,
	EMPRESA VARCHAR(200) NULL,
	TIPOTECNICO CHAR(1) NULL,
	ESTADO BIT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_TECNICO_MANT_PREV] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO
