USE [DB_AHSECO]
GO


CREATE TABLE TBM_SOLDESPACHO(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_SOLICITUD BIGINT NOT NULL,
	ID_COTIZACION BIGINT NOT NULL,
	NUMORDEN VARCHAR(50) NULL,
	FECHAORDEN DATETIME NULL,
	FECHAMAX DATETIME NULL,
	NUMFACTURA VARCHAR(100) NULL,
	FECHAFACTURA DATETIME NULL,
	NUMCONTRATO VARCHAR(50) NULL,
	FEC_CONTRATO DATETIME NULL,
	CALCULO CHAR(1) NULL,
	FIANZA CHAR(1) NULL,
	PRESTPRIN CHAR(1) NULL,
	NUMFIANZAPP VARCHAR(50) NULL,
	PRESTACC CHAR(1) NULL,
	NUMFIANZAPA VARCHAR(50) NULL,
	TIPODESP CHAR(1) NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME  NULL
	 CONSTRAINT [PK_TBM_SOLDESPACHO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO










