USE [DB_AHSECO]
GO


CREATE TABLE [TBM_RECLAMOS] (
	ID_RECLAMO BIGINT IDENTITY(1,1),
	ID_WORKFLOW BIGINT NOT NULL,
	ID_SOLICITUD BIGINT NOT NULL,
	RUCEMPRESA VARCHAR(12) NULL,
	NOMEMPRESA VARCHAR(200) NULL,
	UBICACION VARCHAR(200) NULL,
	NOMBRECONTACTO VARCHAR(150) NULL,
	TELEFONOCONTACTO VARCHAR(50) NULL,
	CARGOCONTACTO VARCHAR(50) NULL,
	ESTABLECIMIENTO VARCHAR(100) NULL,
	TIPOVENTA VARCHAR(25) NULL,
	ORDENCOMPRA VARCHAR(35) NULL,
	NUMPROCESO VARCHAR(15) NULL,
	TIPOPROCESO VARCHAR(200) NULL,
	CONTRATO VARCHAR(25) NULL,
	CODEMPRESA VARCHAR(6) NULL,
	VENDEDOR VARCHAR(150) NULL,
	CODIGOPRODUCTO VARCHAR(35) NOT NULL,
	DESCRIPCION VARCHAR(100) NULL,
	MARCA VARCHAR(150) NULL,
	MODELO VARCHAR(200) NULL,
	SERIE VARCHAR(200) NULL,
	NUMFIANZA VARCHAR(15) NULL,
	FECHAINSTALACION DATETIME NULL,
	UBIGEO VARCHAR(6) NULL,
	DIRECCION VARCHAR(150) NULL,
	URGENCIA VARCHAR(6) NOT NULL,
	MOTIVO VARCHAR(250) NULL,
	ESTADO VARCHAR(6) NOT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL 
	CONSTRAINT [PK_TBM_RECLAMOS] PRIMARY KEY CLUSTERED 
(
	[ID_RECLAMO] ASC
)
) ON [PRIMARY]
GO



CREATE TABLE [TBD_TECNICOGARANTIA] (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_RECLAMO BIGINT NOT NULL,
	COD_TECNICO INT NULL,
	NOMBRES VARCHAR(50) NULL,
	APELLIDOPATERNO VARCHAR(50) NULL,
	APELLIDOMATERNO VARCHAR(50) NULL,
	DOCUMENTO VARCHAR(12) NULL,
	TIPO_DOCUMENTO VARCHAR(9) NULL, 
	CORREO VARCHAR(100) NULL,
	TELEFONO VARCHAR(100) NULL,
	ZONA VARCHAR(6) NULL,
	EMPRESA VARCHAR(200) NULL,
	TIPOTECNICO CHAR(1) NULL,
	ESTADO BIT NULL,
	USR_REG VARCHAR(50) NOT NULL,
	FEC_REG DATETIME NOT NULL,
	USR_MOD VARCHAR(50) NULL,
	FEC_MOD DATETIME NULL
 CONSTRAINT [PK_TBD_TECNICOGARANTIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO
