//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8937
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.sencico.gob.pe/", ClrNamespace="www.sencico.gob.pe")]

namespace www.sencico.gob.pe
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.sencico.gob.pe/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sencico.gob.pe/", ConfigurationName="sConsultaDNISoap")]
public interface sConsultaDNISoap
{
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuarioSIS del espacio de nombres http://www.sencico.gob.pe/ no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.sencico.gob.pe/Consulta", ReplyAction="*")]
    ConsultaResponse Consulta(ConsultaRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ConsultaRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta", Namespace="http://www.sencico.gob.pe/", Order=0)]
    public ConsultaRequestBody Body;
    
    public ConsultaRequest()
    {
    }
    
    public ConsultaRequest(ConsultaRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sencico.gob.pe/")]
public partial class ConsultaRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sUsuarioSIS;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string sDNIConsulta;
    
    public ConsultaRequestBody()
    {
    }
    
    public ConsultaRequestBody(string sUsuarioSIS, string sDNIConsulta)
    {
        this.sUsuarioSIS = sUsuarioSIS;
        this.sDNIConsulta = sDNIConsulta;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ConsultaResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaResponse", Namespace="http://www.sencico.gob.pe/", Order=0)]
    public ConsultaResponseBody Body;
    
    public ConsultaResponse()
    {
    }
    
    public ConsultaResponse(ConsultaResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sencico.gob.pe/")]
public partial class ConsultaResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.sencico.gob.pe.ArrayOfString ConsultaResult;
    
    public ConsultaResponseBody()
    {
    }
    
    public ConsultaResponseBody(www.sencico.gob.pe.ArrayOfString ConsultaResult)
    {
        this.ConsultaResult = ConsultaResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface sConsultaDNISoapChannel : sConsultaDNISoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class sConsultaDNISoapClient : System.ServiceModel.ClientBase<sConsultaDNISoap>, sConsultaDNISoap
{
    
    public sConsultaDNISoapClient()
    {
    }
    
    public sConsultaDNISoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public sConsultaDNISoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public sConsultaDNISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public sConsultaDNISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ConsultaResponse sConsultaDNISoap.Consulta(ConsultaRequest request)
    {
        return base.Channel.Consulta(request);
    }
    
    public www.sencico.gob.pe.ArrayOfString Consulta(string sUsuarioSIS, string sDNIConsulta)
    {
        ConsultaRequest inValue = new ConsultaRequest();
        inValue.Body = new ConsultaRequestBody();
        inValue.Body.sUsuarioSIS = sUsuarioSIS;
        inValue.Body.sDNIConsulta = sDNIConsulta;
        ConsultaResponse retVal = ((sConsultaDNISoap)(this)).Consulta(inValue);
        return retVal.Body.ConsultaResult;
    }
}
